import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { Archive, Bold, ChevronLeft, ChevronRight, FileText, Inbox, Italic, Link2, List, ListOrdered, MailOpen, Paperclip, Plus, Quote, RefreshCw, Search, Send, Smile, Star, Trash2, Underline, X } from 'lucide-react';
import { apiFetch, apiFetchEnvelope, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { Button } from '@/components/ui/Button';
import { ErrorState } from '@/components/ui/ErrorState';
import { LoadingState } from '@/components/ui/LoadingState';

type MailboxMode = 'inbox' | 'outbox';
type Folder = 'inbox' | 'outbox' | 'drafts' | 'archive' | 'starred';
type UserOption = { id: number; name: string; email: string };
type ViewerState = { starred_at?: string | null };
type Item = { id: number; subject: string; summary?: string | null; correspondence_date: string; last_message_at?: string | null; mail_unread?: boolean; recipient_names?: string[]; viewer_state?: ViewerState; sender?: UserOption | null; attachments_count?: number; latest_message?: { body: string } | null };
type MailMeta = { last_page: number; total: number; unread: number; drafts: number; starred: number };
type ComposeForm = { to: number[]; cc: number[]; bcc: number[]; subject: string; body: string };
const emptyForm: ComposeForm = { to: [], cc: [], bcc: [], subject: '', body: '' };
const emojis = ['😀','😃','😄','😁','😅','😂','🙂','😊','😍','🥰','😘','😎','🤓','🤔','😐','😕','😢','😭','😤','😡','👍','👎','👏','🙌','🙏','🤝','💪','✅','❌','⚠️','❤️','💙','💚','🎉','✨','⭐','📌','📎','📅','⏰','💡','📚','🩺','🏥','👨‍⚕️','👩‍⚕️'];
const plainText = (html?: string | null) => { if (!html) return ''; const node = document.createElement('div'); node.innerHTML = html; return node.textContent || ''; };

function RecipientPicker({ label, value, users, onChange, ar }: { label: string; value: number[]; users: UserOption[]; onChange: (ids: number[]) => void; ar: boolean }) {
  const [query, setQuery] = useState('');
  const selected = users.filter(user => value.includes(user.id));
  const results = users.filter(user => !value.includes(user.id) && `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase())).slice(0, 7);
  return <div className="relative flex min-h-11 min-w-0 items-start border-b border-slate-200 px-3 py-2 sm:px-4">
    <span className="mt-1.5 w-12 shrink-0 text-xs text-slate-500">{label}</span>
    <div className="flex min-w-0 flex-1 flex-wrap gap-1">{selected.map(user => <span key={user.id} className="inline-flex max-w-full items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-700"><span className="truncate">{user.name}</span><button type="button" onClick={() => onChange(value.filter(id => id !== user.id))} aria-label={`${ar ? 'إزالة' : 'Remove'} ${user.name}`}><X className="h-3 w-3" /></button></span>)}<input value={query} onChange={event => setQuery(event.target.value)} className="min-w-0 flex-1 border-0 bg-transparent px-1 py-1 text-sm outline-none" placeholder={selected.length ? '' : (ar ? 'اكتب اسمًا أو بريدًا' : 'Type a name or email')} /></div>
    {query && <div className="absolute inset-x-12 top-full z-30 max-h-56 overflow-y-auto rounded-b-xl border border-t-0 border-slate-200 bg-white p-1 shadow-xl">{results.length ? results.map(user => <button key={user.id} type="button" onClick={() => { onChange([...value, user.id]); setQuery(''); }} className="flex w-full items-center justify-between gap-3 rounded-lg px-3 py-2 text-start hover:bg-slate-50"><span className="truncate text-sm font-semibold text-slate-700">{user.name}</span><span className="truncate text-xs text-slate-400" dir="ltr">{user.email}</span></button>) : <p className="p-3 text-xs text-slate-400">{ar ? 'لا توجد نتائج' : 'No results'}</p>}</div>}
  </div>;
}

function MailboxMessageRow({ item, party, preview, date, selected, ar, onSelect, onStar }: {
  item: Item; party: string; preview: string; date: string; selected: boolean; ar: boolean; onSelect: () => void; onStar: () => void;
}) {
  const unread = Boolean(item.mail_unread);
  const subject = item.subject || (ar ? '(بدون موضوع)' : '(no subject)');
  return <article className={`flex min-w-0 items-start gap-2 border-b border-slate-100 px-3 py-3 transition hover:bg-teal-50/40 sm:gap-3 sm:px-4 ${unread ? 'bg-white' : 'bg-slate-50/60'}`}>
    <input type="checkbox" aria-label={`${ar ? 'تحديد' : 'Select'} ${subject}`} checked={selected} onChange={onSelect} className="mt-2.5 h-4 w-4 shrink-0 rounded border-slate-300 accent-teal-700" />
    <button type="button" onClick={onStar} aria-label={ar ? 'تمييز الرسالة' : 'Star message'} className="grid h-9 w-8 shrink-0 place-items-center rounded-lg hover:bg-white"><Star className={`h-4 w-4 ${item.viewer_state?.starred_at ? 'fill-amber-400 text-amber-400' : 'text-slate-400'}`}/></button>
    <Link to={`/correspondence/${item.id}`} className="block min-w-0 flex-1 rounded-lg py-0.5 text-start focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-600">
      <span className="flex min-w-0 items-start justify-between gap-2"><span className={`min-w-0 truncate text-xs sm:text-sm ${unread ? 'font-black text-slate-900' : 'font-semibold text-slate-700'}`}>{party}</span><time className="shrink-0 whitespace-nowrap text-[10px] text-slate-500 sm:text-xs">{date}</time></span>
      <span className={`mt-1 block truncate text-sm ${unread ? 'font-bold text-slate-900' : 'font-semibold text-slate-700'}`}>{subject}{item.attachments_count ? <Paperclip className="ms-1.5 inline h-3.5 w-3.5 text-slate-400"/> : null}</span>
      {preview && <span className="mt-0.5 block truncate text-xs font-normal text-slate-500">{preview}</span>}
    </Link>
  </article>;
}

export function CorrespondenceMailbox({ mode }: { mode: MailboxMode }) {
  const { can } = useAuth(); const { locale, t } = useI18n(); const ar = locale === 'ar'; const qc = useQueryClient();
  const [params] = useSearchParams(); const requestedFolder = params.get('folder');
  const folder: Folder = ['drafts', 'archive', 'starred'].includes(requestedFolder || '') ? requestedFolder as Folder : mode;
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [selected, setSelected] = useState<number[]>([]);
  const [composeOpen, setComposeOpen] = useState(Boolean(params.get('to'))); const [showCc, setShowCc] = useState(false); const [showBcc, setShowBcc] = useState(false); const [formatting, setFormatting] = useState(false); const [emojiOpen, setEmojiOpen] = useState(false); const [linkOpen, setLinkOpen] = useState(false); const [linkForm, setLinkForm] = useState({ text:'', url:'' });
  const [submitError, setSubmitError] = useState(''); const [files, setFiles] = useState<File[]>([]); const fileInput = useRef<HTMLInputElement>(null); const editor = useRef<HTMLDivElement>(null); const linkSelection = useRef<Range | null>(null);
  const savedDraft = (() => { try { return JSON.parse(localStorage.getItem('cdms.mail.compose') || 'null') as ComposeForm | null; } catch { return null; } })();
  const [form, setForm] = useState<ComposeForm>({ ...emptyForm, ...(savedDraft || {}), to: params.get('to') ? [Number(params.get('to'))] : (savedDraft?.to || []), bcc: savedDraft?.bcc || [] });
  useEffect(() => { if (composeOpen) localStorage.setItem('cdms.mail.compose', JSON.stringify({ ...form, body: editor.current?.innerHTML || form.body })); }, [composeOpen, form]);
  useEffect(() => { setPage(1); setSelected([]); }, [folder, search]);
  useEffect(() => { if (composeOpen && editor.current && editor.current.innerHTML !== form.body) editor.current.innerHTML = form.body || ''; }, [composeOpen]);
  const queryString = useMemo(() => { const query = new URLSearchParams({ filter: folder, page: String(page), per_page: '30', sort: 'newest' }); if (search.trim()) query.set('search', search.trim()); return query.toString(); }, [folder, page, search]);
  const mailbox = useQuery({ queryKey: ['correspondence-mailbox', queryString], queryFn: () => apiFetchEnvelope<Item[]>(`/correspondence?${queryString}`), refetchInterval: 8_000, refetchOnWindowFocus: true });
  const items = Array.isArray(mailbox.data?.data) ? mailbox.data.data : []; const meta = mailbox.data?.meta as unknown as MailMeta | undefined;
  const usersQuery = useQuery({ queryKey: ['users-lookup', 'correspondence'], queryFn: () => apiFetch<UserOption[]>('/users/lookup?purpose=correspondence'), enabled: composeOpen }); const recipients = Array.isArray(usersQuery.data) ? usersQuery.data : [];
  const clearCompose = () => { localStorage.removeItem('cdms.mail.compose'); setComposeOpen(false); setSubmitError(''); setFiles([]); setForm({ ...emptyForm }); if (fileInput.current) fileInput.current.value = ''; };
  const create = useMutation({ mutationFn: async (sendNow: boolean) => { const body = editor.current?.innerHTML.trim() || form.body; const created = await apiFetch<Item>('/correspondence', { method: 'POST', body: { to: form.to, cc: form.cc, fyi: form.bcc, subject: form.subject, body, priority: 'normal', message_type: 'message', confidentiality: 'normal', response_due_date: null, tags: [], send_now: sendNow } }); if (files.length) { const upload = new FormData(); files.forEach(file => upload.append('files[]', file)); await apiFetch(`/correspondence/${created.id}/attachments`, { method: 'POST', body: upload }); } return created; }, onSuccess: async () => { clearCompose(); await qc.invalidateQueries({ queryKey: ['correspondence-mailbox'] }); }, onError: error => setSubmitError(error instanceof ApiError ? error.message : ar ? 'تعذر حفظ الرسالة.' : 'Unable to save message.') });
  const stateMutation = useMutation({ mutationFn: ({ id, action }: { id: number; action: string }) => apiFetch(`/correspondence/${id}/mailbox/${action}`, { method: 'POST' }), onSuccess: () => qc.invalidateQueries({ queryKey: ['correspondence-mailbox'] }) });
  const runBulk = async (action: string) => { await Promise.all(selected.map(id => apiFetch(`/correspondence/${id}/mailbox/${action}`, { method: 'POST' }))); setSelected([]); await qc.invalidateQueries({ queryKey: ['correspondence-mailbox'] }); };
  const command = (name: string, value?: string) => { editor.current?.focus(); document.execCommand(name, false, value); setForm(current => ({ ...current, body: editor.current?.innerHTML || '' })); };
  const openLink = () => { const selection = window.getSelection(); const range = selection?.rangeCount ? selection.getRangeAt(0) : null; linkSelection.current = range?.cloneRange() || null; setLinkForm({ text:selection?.toString() || '', url:'' }); setLinkOpen(true); };
  const addLink = () => { let url = linkForm.url.trim(); if (!url) return; if (!/^(https?:\/\/|mailto:)/i.test(url)) url = `https://${url}`; const anchor = document.createElement('a'); anchor.href = url; anchor.target = '_blank'; anchor.rel = 'noopener noreferrer'; anchor.textContent = linkForm.text.trim() || url; const range = linkSelection.current; if (range) { range.deleteContents(); range.insertNode(anchor); range.setStartAfter(anchor); range.collapse(true); const selection = window.getSelection(); selection?.removeAllRanges(); selection?.addRange(range); } else { editor.current?.append(anchor); } editor.current?.focus(); setForm(current => ({ ...current, body:editor.current?.innerHTML || '' })); setLinkOpen(false); setLinkForm({ text:'', url:'' }); };
  if (!can('correspondence.view')) return <ErrorState title={t('state.forbidden.title')} message={t('state.forbidden.message')} />;
  if (mailbox.isLoading) return <LoadingState />; if (mailbox.isError) return <ErrorState onRetry={() => mailbox.refetch()} />;
  const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat(locale, { month: 'short', day: 'numeric', ...(new Date(value).getFullYear() !== new Date().getFullYear() ? { year: 'numeric' } : {}) }).format(new Date(value)) : '—';
  const folders = [['inbox', ar ? 'الوارد' : 'Inbox', Inbox, '/inbox', meta?.unread], ['starred', ar ? 'المميزة' : 'Starred', Star, '/inbox?folder=starred', meta?.starred], ['outbox', ar ? 'المرسل' : 'Sent', Send, '/outbox', undefined], ['drafts', ar ? 'المسودات' : 'Drafts', FileText, '/outbox?folder=drafts', meta?.drafts], ['archive', ar ? 'الأرشيف' : 'Archive', Archive, '/inbox?folder=archive', undefined]] as const;
  const allSelected = Boolean(items.length) && items.every(item => selected.includes(item.id)); const tool = 'rounded-full p-2 text-slate-500 transition hover:bg-slate-100 hover:text-slate-800 disabled:opacity-40';
  return <div className="mx-auto w-full min-w-0 max-w-[1500px] pb-4"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white lg:grid lg:min-h-[calc(100vh-150px)] lg:grid-cols-[210px_minmax(0,1fr)]">
    <aside className="min-w-0 border-b border-slate-200 bg-white p-3 lg:border-b-0 lg:border-e lg:py-4">{can('correspondence.create') && <Button className="mb-3 h-11 w-full justify-center rounded-xl shadow-sm lg:h-12" onClick={() => setComposeOpen(true)}><Plus className="me-2 h-5 w-5" />{ar ? 'إنشاء رسالة' : 'Compose'}</Button>}<nav className="grid grid-cols-3 gap-1.5 lg:flex lg:flex-col" aria-label={ar ? 'مجلدات المراسلات' : 'Mail folders'}>{folders.map(([key, label, Icon, to, count]) => <Link key={key} to={to} aria-current={folder === key ? 'page' : undefined} className={`flex min-h-11 min-w-0 items-center justify-center gap-1 rounded-xl px-1.5 py-2 text-[11px] lg:justify-start lg:gap-3 lg:px-4 lg:text-sm ${folder === key ? 'bg-teal-50 font-bold text-teal-900' : 'font-medium text-slate-600 hover:bg-slate-50'}`}><Icon className="h-4 w-4 shrink-0"/><span className="truncate lg:flex-1">{label}</span>{Boolean(count) && <span className="shrink-0 text-[10px] lg:text-xs">{count}</span>}</Link>)}</nav></aside>
    <section className="min-w-0"><div className="flex min-w-0 items-center gap-2 border-b border-slate-200 px-3 py-2.5"><input type="checkbox" aria-label={ar ? 'تحديد الكل' : 'Select all'} checked={allSelected} onChange={() => setSelected(allSelected ? [] : items.map(item => item.id))} className="h-4 w-4 shrink-0 rounded border-slate-300 accent-teal-700"/>{selected.length ? <><button className={tool} onClick={() => runBulk('archive')} aria-label={ar ? 'أرشفة المحدد' : 'Archive selected'}><Archive className="h-4 w-4"/></button><button className={tool} onClick={() => runBulk('star')} aria-label={ar ? 'تمييز المحدد' : 'Star selected'}><Star className="h-4 w-4"/></button><button className={tool} onClick={() => runBulk('unread')} aria-label={ar ? 'تحديد كغير مقروء' : 'Mark selected unread'}><MailOpen className="h-4 w-4"/></button></> : <button className={tool} onClick={() => mailbox.refetch()} aria-label={ar ? 'تحديث المراسلات' : 'Refresh messages'}><RefreshCw className="h-4 w-4"/></button>}<label className="relative ms-1 min-w-0 max-w-3xl flex-1"><Search className="absolute start-3.5 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={event => setSearch(event.target.value)} className="h-10 w-full min-w-0 rounded-xl bg-slate-100 ps-10 pe-3 text-sm outline-none focus:bg-white focus:ring-2 focus:ring-teal-100" placeholder={ar ? 'ابحث في المراسلات' : 'Search messages'}/></label></div>
    {!items.length ? <div className="border-b border-slate-100 px-6 py-16 text-center"><Inbox className="mx-auto h-10 w-10 text-slate-300"/><p className="mt-3 text-sm font-semibold text-slate-600">{ar ? 'لا توجد رسائل هنا' : 'No messages here'}</p></div> : <div className="border-b border-slate-200">{items.map(item => { const party = folder === 'outbox' || folder === 'drafts' ? item.recipient_names?.join('، ') : item.sender?.name; return <MailboxMessageRow key={item.id} item={item} party={party || (ar ? 'مسودة' : 'Draft')} preview={plainText(item.latest_message?.body || item.summary)} date={formatDate(item.last_message_at || item.correspondence_date)} selected={selected.includes(item.id)} ar={ar} onSelect={() => setSelected(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])} onStar={() => stateMutation.mutate({ id: item.id, action: item.viewer_state?.starred_at ? 'unstar' : 'star' })}/>; })}</div>}
    {(meta?.last_page || 1) > 1 && <div className="flex items-center justify-end gap-2 px-4 py-3 text-xs text-slate-500"><span>{meta?.total} {ar ? 'رسالة' : 'messages'} · {page}/{meta?.last_page}</span><button className={tool} disabled={page <= 1} onClick={() => setPage(value => value - 1)}>{ar ? <ChevronRight className="h-4 w-4"/> : <ChevronLeft className="h-4 w-4"/>}</button><button className={tool} disabled={page >= (meta?.last_page || 1)} onClick={() => setPage(value => value + 1)}>{ar ? <ChevronLeft className="h-4 w-4"/> : <ChevronRight className="h-4 w-4"/>}</button></div>}</section></div>
    {composeOpen && <form onSubmit={(event: FormEvent) => { event.preventDefault(); setSubmitError(''); create.mutate(true); }} className="fixed inset-0 z-50 flex h-[100dvh] min-w-0 flex-col overflow-y-auto bg-white shadow-[0_0_30px_rgba(15,23,42,.22)] sm:inset-x-auto sm:inset-y-auto sm:bottom-6 sm:end-6 sm:h-auto sm:max-h-[92vh] sm:w-[650px] sm:rounded-2xl sm:border sm:border-slate-200"><div className="sticky top-0 z-20 flex min-h-12 shrink-0 items-center justify-between border-b border-teal-100 bg-teal-50 px-4 text-teal-950"><strong className="text-sm">{ar ? 'رسالة جديدة' : 'New message'}</strong><button type="button" onClick={() => setComposeOpen(false)} className="grid h-9 w-9 place-items-center rounded-full hover:bg-teal-100" aria-label={ar ? 'إغلاق نافذة الرسالة' : 'Close message composer'}><X className="h-4 w-4"/></button></div><div><RecipientPicker label={ar ? 'إلى' : 'To'} value={form.to} users={recipients} onChange={to => setForm({ ...form, to })} ar={ar}/>{(!showCc || !showBcc) && <div className="flex justify-end gap-3 border-b border-slate-100 px-4 py-1 text-xs font-bold text-teal-700">{!showCc && <button type="button" onClick={() => setShowCc(true)}>CC</button>}{!showBcc && <button type="button" onClick={() => setShowBcc(true)}>BCC</button>}</div>}</div>{showCc && <RecipientPicker label="CC" value={form.cc} users={recipients} onChange={cc => setForm({ ...form, cc })} ar={ar}/>} {showBcc && <RecipientPicker label="BCC" value={form.bcc} users={recipients} onChange={bcc => setForm({ ...form, bcc })} ar={ar}/>}<input required value={form.subject} onChange={event => setForm({ ...form, subject: event.target.value })} className="h-11 shrink-0 border-b border-slate-200 px-4 text-sm outline-none" placeholder={ar ? 'الموضوع' : 'Subject'}/><div ref={editor} contentEditable role="textbox" aria-label={ar ? 'نص الرسالة' : 'Message body'} aria-multiline="true" suppressContentEditableWarning onInput={event => { const body = event.currentTarget.innerHTML; setForm(current => ({ ...current, body })); }} className="min-h-40 flex-1 overflow-y-auto px-4 py-3 text-sm leading-7 outline-none sm:min-h-72 [&_a]:font-medium [&_a]:text-blue-600 [&_a]:underline" />
    {files.length > 0 && <div className="flex flex-wrap gap-2 border-t border-slate-100 px-4 py-2">{files.map((file, index) => <span key={`${file.name}-${index}`} className="inline-flex max-w-48 items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600"><Paperclip className="h-3 w-3"/><span className="truncate">{file.name}</span><button type="button" onClick={() => setFiles(current => current.filter((_, i) => i !== index))}><X className="h-3 w-3"/></button></span>)}</div>}{submitError && <p className="mx-4 rounded-lg bg-red-50 p-2 text-xs text-red-700">{submitError}</p>}
    {formatting && <div className="flex items-center gap-1 overflow-x-auto border-t border-slate-100 px-3 py-1.5 sm:px-4">{[[Bold, 'bold'], [Italic, 'italic'], [Underline, 'underline'], [ListOrdered, 'insertOrderedList'], [List, 'insertUnorderedList'], [Quote, 'formatBlock']].map(([Icon, name]) => { const Tool = Icon as typeof Bold; return <button key={name as string} type="button" className={`${tool} shrink-0`} onClick={() => command(name as string, name === 'formatBlock' ? 'blockquote' : undefined)}><Tool className="h-4 w-4"/></button>})}<button type="button" className={tool} onClick={openLink}><Link2 className="h-4 w-4"/></button></div>}
    <div className="flex items-center gap-1 border-t border-slate-200 px-4 py-2"><Button type="submit" className="rounded-full px-6" disabled={!form.to.length || !form.subject.trim()} isLoading={create.isPending}><Send className="me-2 h-4 w-4"/>{ar ? 'إرسال' : 'Send'}</Button><button type="button" className={tool} onClick={() => setFormatting(value => !value)}><Bold className="h-4 w-4"/></button><input ref={fileInput} multiple type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.png,.jpg,.jpeg" onChange={event => setFiles(Array.from(event.target.files || []))}/><button type="button" className={tool} onClick={() => fileInput.current?.click()}><Paperclip className="h-4 w-4"/></button><button type="button" className={tool} onClick={openLink}><Link2 className="h-4 w-4"/></button><div className="relative"><button type="button" className={tool} onClick={() => setEmojiOpen(value => !value)}><Smile className="h-4 w-4"/></button>{emojiOpen && <div className="absolute bottom-full start-0 mb-2 grid w-72 grid-cols-8 gap-1 rounded-xl border border-slate-200 bg-white p-2 shadow-xl">{emojis.map((emoji, index) => <button key={`${emoji}-${index}`} type="button" className="rounded p-1.5 text-xl hover:bg-teal-50" onClick={() => { command('insertText', emoji); setEmojiOpen(false); }}>{emoji}</button>)}</div>}</div><button type="button" className={`${tool} ms-auto`} onClick={clearCompose}><Trash2 className="h-4 w-4"/></button></div>{linkOpen && <div className="absolute inset-x-4 bottom-14 z-40 rounded-xl border border-slate-200 bg-white p-4 shadow-2xl"><div className="mb-3 flex items-center justify-between"><strong className="text-sm text-slate-800">{ar ? 'إضافة رابط' : 'Insert link'}</strong><button type="button" onClick={() => setLinkOpen(false)}><X className="h-4 w-4 text-slate-400"/></button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">{ar ? 'النص الظاهر' : 'Text to display'}<input autoFocus value={linkForm.text} onChange={event => setLinkForm({ ...linkForm, text:event.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-teal-400"/></label><label className="text-xs text-slate-500">{ar ? 'عنوان الرابط' : 'Web address'}<input dir="ltr" value={linkForm.url} onChange={event => setLinkForm({ ...linkForm, url:event.target.value })} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); addLink(); } }} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-start text-sm outline-none focus:border-teal-400" placeholder="https://example.com"/></label></div><div className="mt-3 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setLinkOpen(false)}>{ar ? 'إلغاء' : 'Cancel'}</Button><Button type="button" disabled={!linkForm.url.trim()} onClick={addLink}>{ar ? 'إضافة' : 'Insert'}</Button></div></div>}</form>}
  </div>;
}
