<?php

namespace App\Console\Commands;

use App\Models\AcademicYear;
use App\Models\AttendanceRecord;
use App\Models\AttendanceWarningNotification;
use App\Models\ClinicalSession;
use App\Models\Course;
use App\Models\Rotation;
use App\Models\RotationBlock;
use App\Models\Student;
use Illuminate\Console\Command;
use Illuminate\Database\QueryException;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class PrepareAttendanceWarningTest extends Command
{
    private const COURSE_CODE = 'QA-ATT-WARNING';

    private const DATA_SOURCE = 'attendance_warning_test_fixture';

    private const SESSION_PREFIX = '[QA Attendance Warning]';

    protected $signature = 'cdms:attendance-warning-test
        {university_number=22210466 : Student university number}
        {--threshold=20 : Warning threshold to exceed (10 or 20)}
        {--cleanup : Remove the generated attendance-warning fixture}
        {--force : Skip the production confirmation prompt}';

    protected $description = 'Prepare or remove an isolated attendance-warning fixture for staging verification.';

    public function handle(): int
    {
        $universityNumber = trim((string) $this->argument('university_number'));
        if (! preg_match('/^[A-Za-z0-9_-]{4,30}$/', $universityNumber)) {
            $this->error('The university number format is invalid.');

            return self::FAILURE;
        }

        if (! $this->option('force') && ! $this->confirm(
            'This command changes test data in the current database. Confirm that this is the OLD STAGING SERVER and continue?',
        )) {
            return self::SUCCESS;
        }

        if ($this->option('cleanup')) {
            return $this->cleanup($universityNumber);
        }

        $threshold = (int) $this->option('threshold');
        if (! in_array($threshold, [10, 20], true)) {
            $this->error('The --threshold option must be 10 or 20.');

            return self::FAILURE;
        }

        $academicYear = AcademicYear::query()->current()->first()
            ?? AcademicYear::query()->active()->latest('start_date')->first();
        if (! $academicYear) {
            $this->error('No active academic year exists. Create/activate an academic year first.');

            return self::FAILURE;
        }

        $existingStudent = Student::query()->where('university_number', $universityNumber)->first();
        if ($existingStudent && $existingStudent->academic_level !== 'fourth') {
            $this->error('The existing student is not assigned to the fourth-year cohort; no student data was modified.');

            return self::FAILURE;
        }

        $result = DB::transaction(function () use ($academicYear, $threshold, $universityNumber) {
            $student = Student::query()->where('university_number', $universityNumber)->first();
            $student ??= Student::create([
                'university_number' => $universityNumber,
                'full_name_ar' => 'طالب فحص إنذار الغياب',
                'full_name_en' => 'Attendance Warning Test Student',
                'university_email' => $universityNumber.'@'.config('group_registration.student_email_domain', 'students.hebron.edu'),
                'academic_level' => 'fourth',
                'academic_year_id' => $academicYear->id,
                'registration_status' => 'active',
                'academic_registration_status' => 'registered',
                'data_source' => self::DATA_SOURCE,
                'notes' => 'Staging-only attendance warning verification record.',
            ]);

            $course = Course::query()->updateOrCreate(
                ['code' => self::COURSE_CODE],
                [
                    'name_ar' => 'مساق فحص إنذارات الغياب',
                    'name_en' => 'Attendance Warning QA Course',
                    'credit_hours' => 2,
                    'academic_level' => 'fourth',
                    'is_active' => true,
                    'description' => 'Staging-only course generated by cdms:attendance-warning-test.',
                ],
            );

            $rotation = Rotation::query()->updateOrCreate(
                ['academic_year_id' => $academicYear->id, 'course_id' => $course->id],
                [
                    'code' => 'QA-ATT-'.$academicYear->id,
                    'name' => 'Attendance Warning QA Rotation',
                    'academic_level' => 'fourth',
                    'duration_weeks' => 2,
                    'start_date' => Carbon::today()->subWeeks(2),
                    'end_date' => Carbon::today(),
                    'status' => 'active',
                ],
            );

            $block = RotationBlock::query()->firstOrCreate(
                ['rotation_id' => $rotation->id, 'block_code' => 'QA-ATT'],
                ['from_week' => 1, 'to_week' => 2, 'department_id' => null],
            );

            $requiredDays = (int) $course->credit_hours * 5;
            $absentDays = (int) floor($requiredDays * ($threshold / 100)) + 1;

            $testSessionIds = ClinicalSession::query()
                ->where('rotation_block_id', $block->id)
                ->where('title', 'like', self::SESSION_PREFIX.'%')
                ->pluck('id');
            AttendanceRecord::query()
                ->where('student_id', $student->id)
                ->whereIn('clinical_session_id', $testSessionIds)
                ->delete();
            AttendanceWarningNotification::query()
                ->where('student_id', $student->id)
                ->where('rotation_id', $rotation->id)
                ->delete();

            for ($day = 1; $day <= $absentDays; $day++) {
                $date = Carbon::today()->subDays($day)->toDateString();
                $session = ClinicalSession::query()->firstOrCreate(
                    [
                        'rotation_block_id' => $block->id,
                        'session_date' => $date,
                        'title' => self::SESSION_PREFIX.' Day '.$day,
                    ],
                    ['training_site_id' => null],
                );
                AttendanceRecord::query()->updateOrCreate(
                    ['clinical_session_id' => $session->id, 'student_id' => $student->id],
                    ['status' => 'absent', 'excuse_note' => null, 'recorded_by_user_id' => null],
                );
            }

            return [
                'student' => $student,
                'course' => $course,
                'rotation' => $rotation,
                'required_days' => $requiredDays,
                'absent_days' => $absentDays,
                'percentage' => round(($absentDays / $requiredDays) * 100, 2),
            ];
        });

        $this->newLine();
        $this->info('Attendance warning test fixture is ready.');
        $this->table(
            ['Student', 'Email', 'Course', 'Absent / Required', 'Absence rate'],
            [[
                $result['student']->university_number,
                $result['student']->university_number.'@'.config('group_registration.student_email_domain', 'students.hebron.edu'),
                $result['course']->code,
                $result['absent_days'].' / '.$result['required_days'],
                $result['percentage'].'%',
            ]],
        );
        $this->line('Open /attendance with a user who has attendance.view; the send button also requires attendance.notify.');
        $this->warn('Run with --cleanup --force after testing to remove the generated QA attendance data.');

        return self::SUCCESS;
    }

    private function cleanup(string $universityNumber): int
    {
        $student = Student::query()->where('university_number', $universityNumber)->first();
        $course = Course::query()->where('code', self::COURSE_CODE)->first();

        DB::transaction(function () use ($course, $student) {
            $rotations = $course ? Rotation::query()->where('course_id', $course->id)->get() : collect();
            $rotationIds = $rotations->pluck('id');
            $blockIds = RotationBlock::query()->whereIn('rotation_id', $rotationIds)->pluck('id');
            $sessionIds = ClinicalSession::query()
                ->whereIn('rotation_block_id', $blockIds)
                ->where('title', 'like', self::SESSION_PREFIX.'%')
                ->pluck('id');

            if ($student) {
                AttendanceWarningNotification::query()
                    ->where('student_id', $student->id)
                    ->whereIn('rotation_id', $rotationIds)
                    ->delete();
                AttendanceRecord::query()
                    ->where('student_id', $student->id)
                    ->whereIn('clinical_session_id', $sessionIds)
                    ->delete();
            }

            ClinicalSession::query()->whereIn('id', $sessionIds)->delete();
            RotationBlock::query()->whereIn('id', $blockIds)->delete();
            Rotation::query()->whereIn('id', $rotationIds)->delete();
            $course?->delete();
        });

        if ($student?->data_source === self::DATA_SOURCE) {
            try {
                $student->delete();
                $this->info('The generated test student was also removed.');
            } catch (QueryException) {
                $this->warn('The test student now has other linked records, so it was preserved; generated QA attendance data was removed.');
            }
        }

        $this->info('Attendance warning test fixture cleaned successfully.');

        return self::SUCCESS;
    }
}
