import { useEffect, useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, Pencil, Play, Plus, Search, ShieldCheck } from 'lucide-react';
import { apiFetch, apiFetchEnvelope, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { EmptyState } from '@/components/ui/EmptyState';
import { Button } from '@/components/ui/Button';
import { Modal } from '@/components/ui/Modal';
import { QualitySectionGuide } from '@/components/quality/QualitySectionGuide';
import { dateOnly, localDate } from './dateOnly';

type Plan = { id: number; academic_year?: string; source: string; reference?: string; observation: string; root_cause?: string; improvement_action: string; desired_outcome?: string; responsible: string; owner_user_id?: number|null; quality_kpi_id?: number|null; quality_survey_id?: number|null; data_source?: string; owner?: { name:string }; start_date?: string; due_date: string; priority: string; progress_percent:number; status: string; closure_evidence?: string; verification_result?: string };
const initialForm = { observation: '', root_cause:'', improvement_action: '', desired_outcome:'', priority: 'normal', progress_percent:0, due_date: '', start_date: '', responsible: '', owner_user_id:'', quality_kpi_id:'', quality_survey_id:'', quality_finding_id:'', academic_year: '', source: 'ملاحظة داخلية', reference: '', data_source: '' };
const inputClass = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-100';
const statusMap: Record<string, { ar: string; en: string }> = { open: { ar: 'مفتوحة', en: 'Open' }, in_progress: { ar: 'قيد التنفيذ', en: 'In progress' }, under_review: { ar: 'قيد التحقق', en: 'Under review' }, closed: { ar: 'مغلقة', en: 'Closed' } };
const priorityMap: Record<string, { ar: string; en: string }> = { high: { ar: 'عالية', en: 'High' }, normal: { ar: 'متوسطة', en: 'Medium' }, low: { ar: 'منخفضة', en: 'Low' } };

export function ImprovementPlansPage() {
  const { can } = useAuth(); const { locale } = useI18n(); const isAr = locale === 'ar'; const client = useQueryClient();
  const [createOpen, setCreateOpen] = useState(false); const [editingPlan, setEditingPlan] = useState<Plan | null>(null); const [actionPlan, setActionPlan] = useState<Plan | null>(null);
  const [form, setForm] = useState(initialForm); const [search, setSearch] = useState(''); const [debouncedSearch, setDebouncedSearch] = useState(''); const [status, setStatus] = useState('all'); const [page, setPage] = useState(1);
  const [actionForm, setActionForm] = useState({ status: 'in_progress', reason: '', closure_evidence: '', verification_result: '' });
  useEffect(() => { const timer = window.setTimeout(() => setDebouncedSearch(search.trim()), 300); return () => window.clearTimeout(timer); }, [search]);
  const params = new URLSearchParams({ per_page: '20', page: String(page) });
  if (debouncedSearch) params.set('search', debouncedSearch);
  if (status !== 'all') params.set('status', status);
  const query = useQuery({ queryKey: ['quality-plans', page, status, debouncedSearch], queryFn: () => apiFetchEnvelope<Plan[]>(`/quality-improvement-plans?${params}`), enabled: can('quality.view') });
  const options = useQuery({ queryKey: ['quality-options'], queryFn: () => apiFetch<{academic_years:Array<{code:string;is_current:boolean}>;owners:Array<{id:number;name:string}>;kpis:Array<{id:number;code:string;name:string}>;surveys:Array<{id:number;code:string;title:string}>;findings:Array<{id:number;reference:string;title:string;description:string}>}>('/quality-options'), enabled: can('quality.manage') });
  const create = useMutation({ mutationFn: () => apiFetch(editingPlan ? `/quality-improvement-plans/${editingPlan.id}` : '/quality-improvement-plans', { method: editingPlan ? 'PUT' : 'POST', body: {...form,owner_user_id:form.owner_user_id?Number(form.owner_user_id):null,quality_kpi_id:form.quality_kpi_id?Number(form.quality_kpi_id):null,quality_survey_id:form.quality_survey_id?Number(form.quality_survey_id):null,quality_finding_id:!editingPlan&&form.quality_finding_id?Number(form.quality_finding_id):null} }), onSuccess: async () => { await refresh(); await client.invalidateQueries({queryKey:['quality-operations']}); await client.invalidateQueries({queryKey:['quality-options']}); setCreateOpen(false); setEditingPlan(null); setForm(initialForm); } });
  const transition = useMutation({ mutationFn: () => apiFetch(`/quality-improvement-plans/${actionPlan!.id}/transition`, { method: 'POST', body: actionForm }), onSuccess: async () => { await refresh(); setActionPlan(null); } });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ['quality-plans'] }), client.invalidateQueries({ queryKey: ['quality-overview'] })]); };

  const items = query.data?.data || []; const total = Number(query.data?.meta.total || 0); const lastPage = Math.max(1, Math.ceil(total / 20));
  const today = localDate();
  const openAction = (plan: Plan, next: string) => { setActionPlan(plan); setActionForm({ status: next, reason: '', closure_evidence: '', verification_result: '' }); };
  const openCreate = () => { setEditingPlan(null); setForm({...initialForm,academic_year:options.data?.academic_years.find(year=>year.is_current)?.code||''}); setCreateOpen(true); };
  const openEdit = (plan:Plan) => { setEditingPlan(plan); setForm({observation:plan.observation,root_cause:plan.root_cause||'',improvement_action:plan.improvement_action,desired_outcome:plan.desired_outcome||'',priority:plan.priority,progress_percent:plan.progress_percent||0,due_date:dateOnly(plan.due_date),start_date:dateOnly(plan.start_date),responsible:plan.responsible,owner_user_id:String(plan.owner_user_id||''),quality_kpi_id:String(plan.quality_kpi_id||''),quality_survey_id:String(plan.quality_survey_id||''),quality_finding_id:'',academic_year:plan.academic_year||'',source:plan.source,reference:plan.reference||'',data_source:plan.data_source||''}); setCreateOpen(true); };
  const closeEditor = () => { setCreateOpen(false); setEditingPlan(null); create.reset(); };
  const error = create.error || transition.error; const errorMessage = error instanceof ApiError ? error.message : (isAr ? 'تعذر حفظ الإجراء.' : 'Unable to save the action.');
  if (!can('quality.view')) return <ErrorState title={isAr ? 'غير مصرح' : 'Access denied'} />;
  if (query.isLoading) return <LoadingState />;
  if (query.isError) return <ErrorState onRetry={() => query.refetch()} />;

  return <div className="mx-auto max-w-7xl space-y-5 pb-14">
    <PageHeader title={isAr ? 'خطط التحسين والمتابعة' : 'Improvement Plans'} description={isAr ? 'حوّل الملاحظات والنتائج إلى إجراءات محددة بمسؤول وموعد، ثم تحقق من أثرها قبل الإغلاق.' : 'Turn findings into owned, dated actions and verify their impact before closure.'}>
      {can('quality.manage') && <Button onClick={openCreate}><Plus className="ml-2 h-4 w-4" />{isAr ? 'خطة تحسين جديدة' : 'New plan'}</Button>}
    </PageHeader>
    <QualitySectionGuide titleAr="كيف تعمل خطط التحسين؟" titleEn="How improvement plans work" stepsAr={['ابدأ من ملاحظة أو نتيجة استبيان أو مؤشر غير متحقق.','وثّق السبب الجذري والنتيجة المطلوبة وحدد المسؤول والموعد.','تابع التنفيذ ونسبة الإنجاز، ثم أرسل الخطة للتحقق المستقل.','لا تغلق الخطة إلا بدليل تنفيذ ونتيجة واضحة لقياس الأثر.']} stepsEn={['Start from a finding, survey result, or unmet indicator.','Document root cause, desired outcome, owner, and deadline.','Track execution then submit for independent verification.','Close only with implementation evidence and an impact result.']}/>

    <section className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_14rem]">
      <label className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3"><Search className="h-4 w-4 text-slate-400" /><input aria-label={isAr ? 'بحث في الخطط' : 'Search plans'} value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} className="h-11 w-full bg-transparent text-sm outline-none" placeholder={isAr ? 'الملاحظة أو الإجراء أو المسؤول' : 'Observation, action, or owner'} /></label>
      <select aria-label={isAr ? 'حالة الخطة' : 'Plan status'} value={status} onChange={e => { setStatus(e.target.value); setPage(1); }} className={inputClass}><option value="all">{isAr ? 'جميع الحالات' : 'All statuses'}</option>{Object.entries(statusMap).map(([key, value]) => <option key={key} value={key}>{isAr ? value.ar : value.en}</option>)}</select>
    </section>

    {!items.length ? <EmptyState message={isAr ? 'لا توجد خطط مطابقة.' : 'No matching plans.'} /> : <section className="space-y-3">{items.map(plan => {
      const overdue = plan.status !== 'closed' && plan.due_date && dateOnly(plan.due_date) < today;
      return <article key={plan.id} className={`overflow-hidden rounded-3xl border bg-white shadow-sm ${overdue ? 'border-amber-200' : 'border-slate-200'}`}>
        <div className="p-4 sm:p-5">
          <div className="flex flex-wrap items-center gap-2"><span className="rounded-lg bg-teal-50 px-2 py-1 text-[10px] font-black text-teal-700">{isAr ? statusMap[plan.status]?.ar : statusMap[plan.status]?.en}</span><span className="text-[10px] font-bold text-slate-500">{isAr ? priorityMap[plan.priority]?.ar : priorityMap[plan.priority]?.en}</span>{overdue && <span className="inline-flex items-center gap-1 rounded-lg bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-700"><AlertTriangle className="h-3 w-3"/>{isAr ? 'متأخرة' : 'Overdue'}</span>}</div>
          <h2 className="mt-3 break-words text-sm font-black text-slate-900">{plan.observation}</h2>
          <p className="mt-2 text-sm leading-6 text-slate-600">{plan.improvement_action}</p>
          <div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-slate-500"><span>{isAr ? 'المسؤول' : 'Owner'}: <strong className="text-slate-700">{plan.responsible}</strong></span><span>{isAr ? 'الموعد' : 'Due'}: <strong className={overdue ? 'text-amber-700' : 'text-slate-700'}>{dateOnly(plan.due_date) || '—'}</strong></span>{plan.status !== 'closed' && plan.progress_percent > 0 && <span>{isAr ? 'الإنجاز' : 'Progress'}: {plan.progress_percent}%</span>}</div>
          {(plan.root_cause || plan.desired_outcome) && <details className="mt-3 text-xs text-slate-600"><summary className="cursor-pointer font-bold text-teal-700">{isAr ? 'التحليل والنتيجة المطلوبة' : 'Analysis and desired outcome'}</summary><div className="mt-2 space-y-1 rounded-lg bg-slate-50 p-3">{plan.root_cause && <p>{isAr ? 'السبب الجذري' : 'Root cause'}: {plan.root_cause}</p>}{plan.desired_outcome && <p>{isAr ? 'النتيجة' : 'Outcome'}: {plan.desired_outcome}</p>}</div></details>}
        {can('quality.manage') && plan.status !== 'closed' && <div className="mt-4 flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-3"><Button size="sm" variant="outline" onClick={() => openEdit(plan)}><Pencil className="ml-1 h-4 w-4" />{isAr ? 'تحديث الخطة' : 'Edit plan'}</Button>{plan.status === 'open' && <Button size="sm" variant="outline" onClick={() => openAction(plan, 'in_progress')}><Play className="ml-1 h-4 w-4" />{isAr ? 'بدء التنفيذ' : 'Start'}</Button>}{['open','in_progress'].includes(plan.status) && <Button size="sm" variant="outline" onClick={() => openAction(plan, 'under_review')}><ShieldCheck className="ml-1 h-4 w-4" />{isAr ? 'إرسال للتحقق' : 'Send for review'}</Button>}{plan.status === 'under_review' && <Button size="sm" onClick={() => openAction(plan, 'closed')}><CheckCircle2 className="ml-1 h-4 w-4" />{isAr ? 'إغلاق بدليل' : 'Close with evidence'}</Button>}</div>}
        {plan.status === 'closed' && <div className="mt-4 grid gap-3 border-t border-slate-100 pt-3 sm:grid-cols-2"><div><p className="text-[10px] font-black text-slate-400">{isAr ? 'دليل الإغلاق' : 'Closure evidence'}</p><p className="mt-1 text-xs text-slate-600">{plan.closure_evidence || '—'}</p></div><div><p className="text-[10px] font-black text-slate-400">{isAr ? 'نتيجة التحقق' : 'Verification result'}</p><p className="mt-1 text-xs text-slate-600">{plan.verification_result || '—'}</p></div></div>}
        </div>
      </article>})}</section>}
    {lastPage > 1 && <nav aria-label={isAr ? 'صفحات الخطط' : 'Plan pages'} className="flex items-center justify-center gap-3"><Button variant="outline" disabled={page <= 1} onClick={() => setPage(value => value - 1)}>{isAr ? 'السابق' : 'Previous'}</Button><span className="text-xs text-slate-600">{page} / {lastPage}</span><Button variant="outline" disabled={page >= lastPage} onClick={() => setPage(value => value + 1)}>{isAr ? 'التالي' : 'Next'}</Button></nav>}

    <Modal isOpen={createOpen} onClose={closeEditor} title={editingPlan ? (isAr ? 'تحديث خطة التحسين' : 'Edit improvement plan') : (isAr ? 'خطة تحسين جديدة' : 'New improvement plan')} maxWidth="2xl">
      <form onSubmit={(event: FormEvent) => { event.preventDefault(); create.mutate(); }} className="space-y-4">
        {!editingPlan && <label><span className="mb-1 block text-xs font-bold">{isAr ? 'الملاحظة المرتبطة (اختياري)' : 'Related finding (optional)'}</span><select value={form.quality_finding_id} onChange={event => { const finding=options.data?.findings.find(item=>String(item.id)===event.target.value); setForm({...form,quality_finding_id:event.target.value,observation:form.observation||finding?.title||'',reference:form.reference||finding?.reference||''}); }} className={inputClass}><option value="">{isAr ? 'خطة مستقلة' : 'Standalone plan'}</option>{options.data?.findings.map(item=><option key={item.id} value={item.id}>{item.reference} · {item.title}</option>)}</select></label>}
        <div className="grid gap-3 sm:grid-cols-2">
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'مصدر الملاحظة' : 'Finding source'}</span><select value={form.source} onChange={event => setForm({...form, source:event.target.value})} className={inputClass}><option value="ملاحظة داخلية">{isAr ? 'ملاحظة داخلية' : 'Internal finding'}</option><option value="نتائج استبيان">{isAr ? 'نتائج استبيان' : 'Survey result'}</option><option value="مؤشر جودة">{isAr ? 'مؤشر جودة' : 'Indicator'}</option><option value="تدقيق أو اعتماد">{isAr ? 'تدقيق أو اعتماد' : 'Audit or accreditation'}</option><option value="قرار مجلس الكلية">{isAr ? 'قرار مجلس الكلية' : 'Faculty Council decision'}</option></select></label>
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'العام الأكاديمي' : 'Academic year'}</span><select value={form.academic_year} onChange={event => setForm({...form,academic_year:event.target.value})} className={inputClass}><option value="">{isAr ? 'غير محدد' : 'Not specified'}</option>{options.data?.academic_years.map(year => <option key={year.code} value={year.code}>{year.code}{year.is_current ? (isAr ? ' — الحالي' : ' — Current') : ''}</option>)}</select></label>
        </div>
        <label><span className="mb-1 block text-xs font-bold">{isAr ? 'فجوة الجودة أو الملاحظة' : 'Quality gap or finding'}</span><textarea required rows={2} value={form.observation} onChange={event => setForm({...form,observation:event.target.value})} className={inputClass}/></label>
        <div className="grid gap-3 sm:grid-cols-2">
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'السبب الجذري' : 'Root cause'}</span><textarea rows={2} value={form.root_cause} onChange={event => setForm({...form,root_cause:event.target.value})} className={inputClass}/></label>
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'النتيجة المنشودة' : 'Desired outcome'}</span><textarea rows={2} value={form.desired_outcome} onChange={event => setForm({...form,desired_outcome:event.target.value})} className={inputClass}/></label>
        </div>
        <label><span className="mb-1 block text-xs font-bold">{isAr ? 'إجراء التحسين' : 'Improvement action'}</span><textarea required rows={2} value={form.improvement_action} onChange={event => setForm({...form,improvement_action:event.target.value})} className={inputClass}/></label>
        <div className="grid gap-3 sm:grid-cols-2">
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'المسؤول' : 'Owner'}</span><input required value={form.responsible} onChange={event => setForm({...form,responsible:event.target.value})} className={inputClass}/></label>
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'الموعد النهائي' : 'Due date'}</span><input required type="date" min={form.start_date||undefined} value={form.due_date} onChange={event => setForm({...form,due_date:event.target.value})} className={inputClass}/></label>
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'تاريخ البدء' : 'Start date'}</span><input type="date" value={form.start_date} onChange={event => setForm({...form,start_date:event.target.value})} className={inputClass}/></label>
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'الأولوية' : 'Priority'}</span><select value={form.priority} onChange={event => setForm({...form,priority:event.target.value})} className={inputClass}><option value="low">{isAr ? 'منخفضة' : 'Low'}</option><option value="normal">{isAr ? 'متوسطة' : 'Medium'}</option><option value="high">{isAr ? 'عالية' : 'High'}</option></select></label>
          {editingPlan && <label><span className="mb-1 block text-xs font-bold">{isAr ? 'نسبة الإنجاز' : 'Progress'}</span><input type="number" min="0" max="100" value={form.progress_percent} onChange={event => setForm({...form,progress_percent:Number(event.target.value)})} className={inputClass}/></label>}
        </div>
        <details className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer text-xs font-bold text-teal-700">{isAr ? 'ربط الخطة بمصدر وبيانات إضافية' : 'Link the plan to a source'}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'استبيان مرتبط' : 'Related survey'}</span><select value={form.quality_survey_id} onChange={event => setForm({...form,quality_survey_id:event.target.value})} className={inputClass}><option value="">—</option>{options.data?.surveys.map(survey => <option key={survey.id} value={survey.id}>{survey.code} · {survey.title}</option>)}</select></label>
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'مؤشر مرتبط' : 'Related indicator'}</span><select value={form.quality_kpi_id} onChange={event => setForm({...form,quality_kpi_id:event.target.value})} className={inputClass}><option value="">—</option>{options.data?.kpis.map(kpi => <option key={kpi.id} value={kpi.id}>{kpi.code} · {kpi.name}</option>)}</select></label>
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'مرجع إضافي' : 'Reference'}</span><input value={form.reference} onChange={event => setForm({...form,reference:event.target.value})} className={inputClass}/></label>
          <label><span className="mb-1 block text-xs font-bold">{isAr ? 'مصدر بيانات التحقق' : 'Verification data source'}</span><input value={form.data_source} onChange={event => setForm({...form,data_source:event.target.value})} className={inputClass}/></label>
        </div></details>
        {create.isError && <p role="alert" className="text-sm font-bold text-red-600">{errorMessage}</p>}
        <div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={closeEditor}>{isAr ? 'إلغاء' : 'Cancel'}</Button><Button type="submit" isLoading={create.isPending}>{isAr ? 'حفظ الخطة' : 'Save plan'}</Button></div>
      </form>
    </Modal>

    <Modal isOpen={Boolean(actionPlan)} onClose={() => setActionPlan(null)} title={actionForm.status === 'closed' ? (isAr ? 'التحقق وإغلاق الخطة' : 'Verify and close plan') : (isAr ? 'تحديث سير الخطة' : 'Update plan workflow')}><form onSubmit={(e:FormEvent) => { e.preventDefault(); transition.mutate(); }} className="space-y-4">{actionForm.status === 'closed' && <><label><span className="mb-1 block text-xs font-bold">{isAr ? 'دليل تنفيذ الإجراء' : 'Implementation evidence'}</span><textarea required rows={4} value={actionForm.closure_evidence} onChange={e => setActionForm({...actionForm, closure_evidence:e.target.value})} className={inputClass} placeholder={isAr ? 'صف الوثيقة، المحضر، النتيجة أو الرابط الذي يثبت التنفيذ...' : 'Describe the document, result, or link proving implementation...'} /></label><label><span className="mb-1 block text-xs font-bold">{isAr ? 'نتيجة التحقق من الأثر' : 'Impact verification result'}</span><textarea rows={3} value={actionForm.verification_result} onChange={e => setActionForm({...actionForm, verification_result:e.target.value})} className={inputClass} /></label></>}<label><span className="mb-1 block text-xs font-bold">{isAr ? 'ملاحظة الحركة' : 'Workflow note'}</span><textarea rows={2} value={actionForm.reason} onChange={e => setActionForm({...actionForm, reason:e.target.value})} className={inputClass} /></label>{transition.isError && <p className="text-sm font-bold text-red-600">{errorMessage}</p>}<div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={() => setActionPlan(null)}>{isAr ? 'إلغاء' : 'Cancel'}</Button><Button type="submit" isLoading={transition.isPending}>{isAr ? 'اعتماد الحركة' : 'Confirm'}</Button></div></form></Modal>
  </div>;
}
