import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BarChart3, Calendar, CheckCircle2, Plus, RotateCcw, Ruler, ShieldCheck, Target } from 'lucide-react';
import { apiFetch, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { EmptyState } from '@/components/ui/EmptyState';
import { Button } from '@/components/ui/Button';
import { Modal } from '@/components/ui/Modal';

type Measurement={id:number;measured_at:string;display_value:string;achievement_status:string;review_status:string};
type Kpi={id:number;code:string;name:string;category?:string;target_value?:string;measurement_frequency?:string;responsible?:string;latest_measurement?:Measurement|null};
const field='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-100';
const achievement:Record<string,[string,string]>={achieved:['متحقق','Achieved'],partially_achieved:['متحقق جزئيًا','Partially achieved'],not_achieved:['غير متحقق','Not achieved'],not_assessed:['غير مقاس','Not assessed']};
const reviewText:Record<string,[string,string]>={draft:['مسودة','Draft'],submitted:['بانتظار المراجعة','Pending review'],approved:['معتمد','Approved'],returned:['معاد للتعديل','Returned']};
const emptyKpi={code:'',name:'',category:'',target_value:'',target_numeric:'',warning_numeric:'',comparison_operator:'gte',value_type:'percentage',measurement_frequency:'',responsible:'',weight:'',measurement_method:'',data_source:'',is_active:true};
const newMeasurement=()=>({academic_year:'',measured_at:new Date().toISOString().slice(0,10),numeric_value:'',display_value:'',evidence:'',notes:'',submit_for_review:true});

export function KpiPage(){
 const{can}=useAuth();const{locale}=useI18n();const ar=locale==='ar';const client=useQueryClient();
 const[createOpen,setCreateOpen]=useState(false),[measuring,setMeasuring]=useState<Kpi|null>(null),[category,setCategory]=useState('all');
 const[form,setForm]=useState(emptyKpi),[measurement,setMeasurement]=useState(newMeasurement());
 const query=useQuery({queryKey:['quality-kpis'],queryFn:()=>apiFetch<Kpi[]>('/quality-kpis?per_page=100')});
 const refresh=async()=>{await Promise.all([client.invalidateQueries({queryKey:['quality-kpis']}),client.invalidateQueries({queryKey:['quality-overview']})]);};
 const create=useMutation({mutationFn:()=>apiFetch('/quality-kpis',{method:'POST',body:{...form,weight:form.weight?Number(form.weight):null,target_numeric:Number(form.target_numeric),warning_numeric:form.warning_numeric===''?null:Number(form.warning_numeric)}}),onSuccess:async()=>{await refresh();setCreateOpen(false);setForm(emptyKpi);}});
 const record=useMutation({mutationFn:()=>apiFetch(`/quality-kpis/${measuring!.id}/measurements`,{method:'POST',body:{...measurement,numeric_value:Number(measurement.numeric_value)}}),onSuccess:async()=>{await refresh();setMeasuring(null);setMeasurement(newMeasurement());}});
 const review=useMutation({mutationFn:({id,decision}:{id:number;decision:string})=>apiFetch(`/quality-kpi-measurements/${id}/review`,{method:'POST',body:{decision}}),onSuccess:refresh});
 const items=query.data||[],categories=useMemo(()=>[...new Set(items.map(x=>x.category).filter(Boolean))] as string[],[items]),filtered=category==='all'?items:items.filter(x=>x.category===category);
 const err=create.error||record.error||review.error,error=err instanceof ApiError?err.message:(ar?'تعذر حفظ البيانات.':'Unable to save data.');
 if(!can('quality.view'))return <ErrorState title={ar?'غير مصرح':'Access denied'}/>;if(query.isLoading)return <LoadingState/>;if(query.isError)return <ErrorState onRetry={()=>query.refetch()}/>;
 return <div className="mx-auto max-w-7xl space-y-5 pb-14">
  <PageHeader title={ar?'سجل مؤشرات الجودة':'Quality Indicator Register'} description={ar?'مؤشرات قابلة للقياس مع احتساب آلي للإنجاز ومراجعة مستقلة قبل الاعتماد.':'Measurable indicators with automatic achievement calculation and independent review.'}>{can('kpi.manage')&&<Button onClick={()=>setCreateOpen(true)}><Plus className="ml-2 h-4 w-4"/>{ar?'مؤشر جديد':'New indicator'}</Button>}</PageHeader>
  <section className="flex flex-col gap-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><BarChart3 className="h-5 w-5"/></span><div><p className="text-sm font-black">{items.length} {ar?'مؤشرًا معرفًا':'defined indicators'}</p><p className="text-xs text-slate-500">{items.filter(x=>x.latest_measurement?.review_status==='submitted').length} {ar?'قياسات تنتظر المراجعة':'measurements await review'}</p></div></div><select value={category} onChange={e=>setCategory(e.target.value)} className={`${field} sm:w-60`}><option value="all">{ar?'جميع المحاور':'All categories'}</option>{categories.map(x=><option key={x}>{x}</option>)}</select></section>
  {!filtered.length?<EmptyState message={ar?'لا توجد مؤشرات جودة بعد.':'No quality indicators yet.'}/>:<section className="grid gap-4 lg:grid-cols-2">{filtered.map(kpi=><KpiCard key={kpi.id} kpi={kpi} ar={ar} manage={can('kpi.manage')} measuring={()=>setMeasuring(kpi)} review={(decision)=>kpi.latest_measurement&&review.mutate({id:kpi.latest_measurement.id,decision})}/>)}</section>}
  <Modal isOpen={createOpen} onClose={()=>setCreateOpen(false)} title={ar?'تعريف مؤشر جودة':'Define quality indicator'} maxWidth="2xl"><form onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate();}} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Label text={ar?'رمز المؤشر':'Code'}><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className={field}/></Label><Label text={ar?'المحور':'Category'}><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className={field}/></Label></div><Label text={ar?'اسم المؤشر':'Indicator name'}><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={field}/></Label><div className="grid gap-3 sm:grid-cols-2"><Label text={ar?'عرض المستهدف':'Target display'}><input required value={form.target_value} onChange={e=>setForm({...form,target_value:e.target.value})} className={field} placeholder="≥ 80%"/></Label><Label text={ar?'القيمة الرقمية المستهدفة':'Numeric target'}><input required type="number" step="0.01" value={form.target_numeric} onChange={e=>setForm({...form,target_numeric:e.target.value})} className={field}/></Label><Label text={ar?'اتجاه النجاح':'Success direction'}><select value={form.comparison_operator} onChange={e=>setForm({...form,comparison_operator:e.target.value})} className={field}><option value="gte">{ar?'أعلى أو يساوي المستهدف':'At least target'}</option><option value="lte">{ar?'أقل أو يساوي المستهدف':'At most target'}</option></select></Label><Label text={ar?'دورية القياس':'Frequency'}><input required value={form.measurement_frequency} onChange={e=>setForm({...form,measurement_frequency:e.target.value})} className={field}/></Label><Label text={ar?'المسؤول':'Owner'}><input required value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value})} className={field}/></Label><Label text={ar?'مصدر البيانات':'Data source'}><input value={form.data_source} onChange={e=>setForm({...form,data_source:e.target.value})} className={field}/></Label></div><Label text={ar?'طريقة القياس':'Measurement method'}><textarea rows={3} value={form.measurement_method} onChange={e=>setForm({...form,measurement_method:e.target.value})} className={field}/></Label>{create.isError&&<p className="text-sm font-bold text-red-600">{error}</p>}<Actions ar={ar} loading={create.isPending} close={()=>setCreateOpen(false)}/></form></Modal>
  <Modal isOpen={Boolean(measuring)} onClose={()=>setMeasuring(null)} title={`${ar?'تسجيل قياس':'Record measurement'} — ${measuring?.code||''}`}><form onSubmit={(e:FormEvent)=>{e.preventDefault();record.mutate();}} className="space-y-4"><div className="rounded-2xl bg-teal-50 p-3 text-xs text-teal-800"><strong>{ar?'المستهدف:':'Target:'}</strong> {measuring?.target_value}</div><div className="grid gap-3 sm:grid-cols-2"><Label text={ar?'تاريخ القياس':'Measurement date'}><input required type="date" value={measurement.measured_at} onChange={e=>setMeasurement({...measurement,measured_at:e.target.value})} className={field}/></Label><Label text={ar?'العام الأكاديمي':'Academic year'}><input required value={measurement.academic_year} onChange={e=>setMeasurement({...measurement,academic_year:e.target.value})} className={field} placeholder="2026/2027"/></Label><Label text={ar?'النتيجة الرقمية':'Numeric result'}><input required type="number" step="0.01" value={measurement.numeric_value} onChange={e=>setMeasurement({...measurement,numeric_value:e.target.value})} className={field}/></Label><Label text={ar?'النتيجة المعروضة':'Display result'}><input required value={measurement.display_value} onChange={e=>setMeasurement({...measurement,display_value:e.target.value})} className={field} placeholder="84%"/></Label></div><p className="rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-700">{ar?'يحتسب النظام حالة الإنجاز تلقائيًا ويرسل القياس للمراجعة.':'Achievement is calculated automatically and submitted for review.'}</p><Label text={ar?'الدليل أو مرجع البيانات':'Evidence'}><textarea required rows={3} value={measurement.evidence} onChange={e=>setMeasurement({...measurement,evidence:e.target.value})} className={field}/></Label>{record.isError&&<p className="text-sm font-bold text-red-600">{error}</p>}<Actions ar={ar} loading={record.isPending} close={()=>setMeasuring(null)}/></form></Modal>
 </div>;
}

function KpiCard({kpi,ar,manage,measuring,review}:{kpi:Kpi;ar:boolean;manage:boolean;measuring:()=>void;review:(decision:string)=>void}){const latest=kpi.latest_measurement,status=latest?.achievement_status||'not_assessed';return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><div className="flex gap-2"><span className="rounded-lg bg-teal-50 px-2 py-1 text-[10px] font-black text-teal-700">{kpi.code}</span>{kpi.category&&<span className="text-[10px] font-bold text-slate-400">{kpi.category}</span>}</div><h2 className="mt-2 text-sm font-black">{kpi.name}</h2></div><span className="rounded-xl bg-slate-50 px-3 py-2 text-xs font-black">{achievement[status]?.[ar?0:1]}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Mini icon={<Target className="h-3.5 w-3.5"/>} label={ar?'المستهدف':'Target'} value={kpi.target_value||'—'}/><Mini teal icon={<Ruler className="h-3.5 w-3.5"/>} label={ar?'آخر نتيجة':'Latest'} value={latest?.display_value||(ar?'غير مقاس':'Not measured')}/></div><div className="mt-3 flex flex-wrap gap-3 text-[10px] text-slate-400">{latest?.measured_at&&<span className="flex gap-1"><Calendar className="h-3 w-3"/>{latest.measured_at}</span>}<span>{ar?'المسؤول':'Owner'}: {kpi.responsible||'—'}</span>{latest&&<span className="rounded bg-slate-100 px-2 py-1 font-bold">{reviewText[latest.review_status]?.[ar?0:1]}</span>}</div>{manage&&<div className="mt-4 flex flex-wrap justify-end gap-2 border-t pt-3">{latest?.review_status==='submitted'&&<><Button size="sm" variant="outline" onClick={()=>review('returned')}><RotateCcw className="ml-1 h-4 w-4"/>{ar?'إعادة':'Return'}</Button><Button size="sm" onClick={()=>review('approved')}><ShieldCheck className="ml-1 h-4 w-4"/>{ar?'اعتماد':'Approve'}</Button></>}<Button size="sm" variant="outline" onClick={measuring}><CheckCircle2 className="ml-1 h-4 w-4"/>{ar?'تسجيل قياس':'Record'}</Button></div>}</article>}
function Mini({icon,label,value,teal=false}:{icon:ReactNode;label:string;value:string;teal?:boolean}){return <div className={`rounded-2xl p-3 ${teal?'bg-teal-50/70':'bg-slate-50'}`}><p className={`flex items-center gap-1 text-[10px] font-bold ${teal?'text-teal-600':'text-slate-400'}`}>{icon}{label}</p><p className={`mt-1 text-sm font-black ${teal?'text-teal-800':''}`}>{value}</p></div>}
function Label({text,children}:{text:string;children:ReactNode}){return <label><span className="mb-1 block text-xs font-bold">{text}</span>{children}</label>}
function Actions({ar,loading,close}:{ar:boolean;loading:boolean;close:()=>void}){return <div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={close}>{ar?'إلغاء':'Cancel'}</Button><Button type="submit" isLoading={loading}>{ar?'حفظ':'Save'}</Button></div>}
