import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ExternalLink, FileCheck2, Plus, Search } from 'lucide-react';
import { apiFetch, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { EmptyState } from '@/components/ui/EmptyState';
import { Button } from '@/components/ui/Button';
import { Modal } from '@/components/ui/Modal';

type Finding={id:number;reference:string;academic_year?:string;source:string;category?:string;title:string;description:string;severity:string;status:string;is_recurring:boolean;due_date?:string;owner?:{name:string};root_cause?:string;recommended_action?:string;evidence_reference?:string};
type Evidence={id:number;code:string;title:string;category?:string;description?:string;reference_url?:string;document_version?:string;issued_at?:string;expires_at?:string;status:string;owner?:{name:string}};
type Options={owners:Array<{id:number;name:string;email:string}>};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-100';
const emptyFinding={academic_year:'',source:'تدقيق داخلي',category:'',title:'',description:'',severity:'medium',is_recurring:false,owner_user_id:'',due_date:'',root_cause:'',recommended_action:'',evidence_reference:''};
const emptyEvidence={code:'',title:'',category:'',description:'',reference_url:'',document_version:'1.0',issued_at:'',expires_at:'',status:'draft',owner_user_id:''};
const severity:Record<string,[string,string]>={low:['منخفضة','Low'],medium:['متوسطة','Medium'],high:['عالية','High'],critical:['حرجة','Critical']};
const findingStatus:Record<string,[string,string]>={open:['مفتوحة','Open'],analyzing:['تحليل السبب','Analyzing'],action_required:['تحتاج إجراء','Action required'],linked_to_plan:['مرتبطة بخطة','Linked to plan'],closed:['مغلقة','Closed']};

export function QualityOperationsPage(){
 const{can}=useAuth();const{locale}=useI18n();const ar=locale==='ar',client=useQueryClient();const[tab,setTab]=useState<'findings'|'evidence'>('findings'),[search,setSearch]=useState(''),[modal,setModal]=useState<'finding'|'evidence'|null>(null),[finding,setFinding]=useState(emptyFinding),[evidence,setEvidence]=useState(emptyEvidence);
 const query=useQuery({queryKey:['quality-operations'],queryFn:()=>apiFetch<{findings:Finding[];evidence:Evidence[]}>('/quality-operations')});const options=useQuery({queryKey:['quality-options'],queryFn:()=>apiFetch<Options>('/quality-options')});
 const refresh=async()=>{await Promise.all([client.invalidateQueries({queryKey:['quality-operations']}),client.invalidateQueries({queryKey:['quality-overview']})]);};
 const addFinding=useMutation({mutationFn:()=>apiFetch('/quality-findings',{method:'POST',body:{...finding,owner_user_id:finding.owner_user_id?Number(finding.owner_user_id):null}}),onSuccess:async()=>{await refresh();setModal(null);setFinding(emptyFinding);}});
 const addEvidence=useMutation({mutationFn:()=>apiFetch('/quality-evidence',{method:'POST',body:{...evidence,owner_user_id:evidence.owner_user_id?Number(evidence.owner_user_id):null}}),onSuccess:async()=>{await refresh();setModal(null);setEvidence(emptyEvidence);}});
 const findings=useMemo(()=>(query.data?.findings||[]).filter(x=>`${x.reference} ${x.title} ${x.description}`.toLowerCase().includes(search.toLowerCase())),[query.data,search]);const evidences=useMemo(()=>(query.data?.evidence||[]).filter(x=>`${x.code} ${x.title} ${x.category}`.toLowerCase().includes(search.toLowerCase())),[query.data,search]);
 const mutation=modal==='finding'?addFinding:addEvidence,err=mutation.error,error=err instanceof ApiError?err.message:(ar?'تعذر حفظ السجل.':'Unable to save record.');
 if(!can('quality.view'))return <ErrorState title={ar?'غير مصرح':'Access denied'}/>;if(query.isLoading)return <LoadingState/>;if(query.isError)return <ErrorState onRetry={()=>query.refetch()}/>;
 return <div className="mx-auto max-w-7xl space-y-5 pb-14"><PageHeader title={ar?'الملاحظات والأدلة':'Findings & Evidence'} description={ar?'سجل موحد لعدم المطابقة وفرص التحسين ووثائق الاعتماد.':'A unified register for findings, improvement opportunities, and accreditation evidence.'}>{can('quality.manage')&&<div className="flex gap-2"><Button variant="outline" onClick={()=>setModal('evidence')}><FileCheck2 className="ml-1 h-4 w-4"/>{ar?'دليل جديد':'New evidence'}</Button><Button onClick={()=>setModal('finding')}><Plus className="ml-1 h-4 w-4"/>{ar?'ملاحظة جديدة':'New finding'}</Button></div>}</PageHeader>
 <section className="flex flex-col gap-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center"><div className="flex rounded-xl bg-slate-100 p-1"><button onClick={()=>setTab('findings')} className={`rounded-lg px-4 py-2 text-xs font-black ${tab==='findings'?'bg-white text-teal-700 shadow-sm':'text-slate-500'}`}>{ar?'الملاحظات وعدم المطابقة':'Findings'} ({query.data?.findings.length||0})</button><button onClick={()=>setTab('evidence')} className={`rounded-lg px-4 py-2 text-xs font-black ${tab==='evidence'?'bg-white text-teal-700 shadow-sm':'text-slate-500'}`}>{ar?'مركز الأدلة':'Evidence'} ({query.data?.evidence.length||0})</button></div><label className="flex flex-1 items-center gap-2 rounded-xl border bg-slate-50 px-3"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="h-10 w-full bg-transparent text-sm outline-none" placeholder={ar?'بحث في السجل...':'Search register...'}/></label></section>
 {tab==='findings'?(!findings.length?<EmptyState message={ar?'لا توجد ملاحظات جودة بعد.':'No quality findings yet.'}/>:<section className="space-y-3">{findings.map(x=><article key={x.id} className={`rounded-3xl border bg-white p-5 shadow-sm ${x.severity==='critical'?'border-red-200':x.severity==='high'?'border-amber-200':'border-slate-200'}`}><div className="flex flex-col justify-between gap-3 md:flex-row"><div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-lg bg-teal-50 px-2 py-1 text-[10px] font-black text-teal-700">{x.reference}</span><span className="rounded-lg bg-slate-100 px-2 py-1 text-[10px] font-bold">{findingStatus[x.status]?.[ar?0:1]}</span><span className="rounded-lg bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">{severity[x.severity]?.[ar?0:1]}</span>{x.is_recurring&&<span className="rounded-lg bg-red-50 px-2 py-1 text-[10px] font-bold text-red-700">{ar?'متكررة':'Recurring'}</span>}</div><h2 className="mt-3 font-black text-slate-900">{x.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{x.description}</p></div><aside className="shrink-0 rounded-2xl bg-slate-50 p-3 text-xs md:w-56"><p className="text-slate-400">{ar?'المسؤول':'Owner'}</p><p className="mt-1 font-bold">{x.owner?.name||'—'}</p><p className="mt-3 text-slate-400">{ar?'الموعد':'Due'}</p><p className="mt-1 font-bold">{x.due_date||'—'}</p></aside></div></article>)}</section>):(!evidences.length?<EmptyState message={ar?'لا توجد أدلة مسجلة بعد.':'No evidence registered yet.'}/>:<section className="grid gap-4 lg:grid-cols-2">{evidences.map(x=><article key={x.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><span className="rounded-lg bg-teal-50 px-2 py-1 text-[10px] font-black text-teal-700">{x.code}</span><h2 className="mt-3 font-black">{x.title}</h2><p className="mt-1 text-xs text-slate-500">{x.category||'—'} · v{x.document_version||'—'}</p></div><FileCheck2 className="h-5 w-5 text-teal-600"/></div><div className="mt-4 flex items-center justify-between border-t pt-3 text-xs"><span>{ar?'ينتهي:':'Expires:'} {x.expires_at||'—'}</span>{x.reference_url&&<a href={x.reference_url} target="_blank" rel="noreferrer" className="flex items-center gap-1 font-bold text-teal-700"><ExternalLink className="h-3.5 w-3.5"/>{ar?'فتح الدليل':'Open'}</a>}</div></article>)}</section>)}
 <Modal isOpen={modal==='finding'} onClose={()=>setModal(null)} title={ar?'تسجيل ملاحظة أو عدم مطابقة':'Register quality finding'} maxWidth="2xl"><form onSubmit={(e:FormEvent)=>{e.preventDefault();addFinding.mutate();}} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Select label={ar?'المصدر':'Source'} value={finding.source} set={v=>setFinding({...finding,source:v})} items={['تدقيق داخلي','نتائج استبيان','مؤشر جودة','شكوى','زيارة اعتماد','تقرير مساق','اجتماع لجنة']}/><Field label={ar?'العام الأكاديمي':'Academic year'}><input value={finding.academic_year} onChange={e=>setFinding({...finding,academic_year:e.target.value})} className={input} placeholder="2026/2027"/></Field><Field label={ar?'العنوان':'Title'}><input required value={finding.title} onChange={e=>setFinding({...finding,title:e.target.value})} className={input}/></Field><Select label={ar?'الخطورة':'Severity'} value={finding.severity} set={v=>setFinding({...finding,severity:v})} items={['low','medium','high','critical']} labels={severity}/></div><Field label={ar?'وصف الملاحظة':'Description'}><textarea required rows={3} value={finding.description} onChange={e=>setFinding({...finding,description:e.target.value})} className={input}/></Field><Field label={ar?'تحليل السبب الجذري':'Root cause'}><textarea rows={2} value={finding.root_cause} onChange={e=>setFinding({...finding,root_cause:e.target.value})} className={input}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label={ar?'المسؤول':'Owner'}><select value={finding.owner_user_id} onChange={e=>setFinding({...finding,owner_user_id:e.target.value})} className={input}><option value="">—</option>{options.data?.owners.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label={ar?'الموعد':'Due date'}><input type="date" value={finding.due_date} onChange={e=>setFinding({...finding,due_date:e.target.value})} className={input}/></Field></div>{addFinding.isError&&<p className="text-sm font-bold text-red-600">{error}</p>}<Actions ar={ar} loading={addFinding.isPending} close={()=>setModal(null)}/></form></Modal>
 <Modal isOpen={modal==='evidence'} onClose={()=>setModal(null)} title={ar?'إضافة دليل جودة':'Add quality evidence'} maxWidth="2xl"><form onSubmit={(e:FormEvent)=>{e.preventDefault();addEvidence.mutate();}} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label={ar?'رمز الدليل':'Evidence code'}><input required value={evidence.code} onChange={e=>setEvidence({...evidence,code:e.target.value})} className={input}/></Field><Field label={ar?'العنوان':'Title'}><input required value={evidence.title} onChange={e=>setEvidence({...evidence,title:e.target.value})} className={input}/></Field><Field label={ar?'التصنيف':'Category'}><input value={evidence.category} onChange={e=>setEvidence({...evidence,category:e.target.value})} className={input}/></Field><Field label={ar?'الإصدار':'Version'}><input value={evidence.document_version} onChange={e=>setEvidence({...evidence,document_version:e.target.value})} className={input}/></Field><Field label={ar?'رابط الوثيقة':'Document URL'}><input type="url" value={evidence.reference_url} onChange={e=>setEvidence({...evidence,reference_url:e.target.value})} className={input}/></Field><Field label={ar?'تاريخ الانتهاء':'Expiry date'}><input type="date" value={evidence.expires_at} onChange={e=>setEvidence({...evidence,expires_at:e.target.value})} className={input}/></Field></div><Field label={ar?'الوصف':'Description'}><textarea rows={3} value={evidence.description} onChange={e=>setEvidence({...evidence,description:e.target.value})} className={input}/></Field>{addEvidence.isError&&<p className="text-sm font-bold text-red-600">{error}</p>}<Actions ar={ar} loading={addEvidence.isPending} close={()=>setModal(null)}/></form></Modal>
 </div>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label><span className="mb-1 block text-xs font-bold">{label}</span>{children}</label>}
function Select({label,value,set,items,labels}:{label:string;value:string;set:(v:string)=>void;items:string[];labels?:Record<string,[string,string]>}){return <Field label={label}><select value={value} onChange={e=>set(e.target.value)} className={input}>{items.map(x=><option key={x} value={x}>{labels?.[x]?.[0]||x}</option>)}</select></Field>}
function Actions({ar,loading,close}:{ar:boolean;loading:boolean;close:()=>void}){return <div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={close}>{ar?'إلغاء':'Cancel'}</Button><Button type="submit" isLoading={loading}>{ar?'حفظ':'Save'}</Button></div>}
