import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { Download, Search } from 'lucide-react';
import ExcelJS from 'exceljs';
import { apiFetch } from '@/api/client';
import { useI18n } from '@/i18n/I18nContext';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { EmptyState } from '@/components/ui/EmptyState';
import { Button } from '@/components/ui/Button';

type Question={id:number;question_text:string;question_type:string};
type Submission={submission_id:string;responded_at:string;respondent_identifier?:string|null;answers:Record<string,string|number|null>};
type Matrix={survey:{code:string;title:string;is_anonymous:boolean};questions:Question[];submissions:Submission[]};

export function SurveyResponsesPage(){
 const{id}=useParams();const{locale}=useI18n();const ar=locale==='ar';const[search,setSearch]=useState('');const[exporting,setExporting]=useState(false);const[exportError,setExportError]=useState(false);
 const query=useQuery({queryKey:['quality-survey-matrix',id],queryFn:()=>apiFetch<Matrix>(`/quality-surveys/${id}/response-matrix`)});
 const rows=useMemo(()=>query.data?.submissions.filter(s=>!search||`${s.respondent_identifier||''} ${Object.values(s.answers).join(' ')}`.toLowerCase().includes(search.toLowerCase()))||[],[query.data,search]);
 if(query.isLoading)return <LoadingState/>;if(query.isError||!query.data)return <ErrorState onRetry={()=>query.refetch()}/>;const data=query.data;
 const exportExcel=async()=>{setExporting(true);setExportError(false);try{const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet(ar?'الردود':'Responses',{views:[{rightToLeft:ar}]});ws.columns=[{header:'#',key:'n',width:8},{header:ar?'وقت الإرسال':'Submitted',key:'date',width:22},...(!data.survey.is_anonymous?[{header:ar?'المجيب':'Respondent',key:'person',width:22}]:[]),...data.questions.map(q=>({header:q.question_text,key:`q${q.id}`,width:30}))];rows.forEach((s,i)=>ws.addRow({n:i+1,date:new Date(s.responded_at).toLocaleString(ar?'ar-PS':'en-GB'),person:s.respondent_identifier||'',...Object.fromEntries(data.questions.map(q=>[`q${q.id}`,s.answers[q.id]??'']))}));ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0F766E'}};ws.views=[{state:'frozen',ySplit:1,rightToLeft:ar}];const buffer=await wb.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([buffer]));const a=document.createElement('a');a.href=url;a.download=`${data.survey.code}-responses.xlsx`;a.click();URL.revokeObjectURL(url)}catch{setExportError(true)}finally{setExporting(false)}};
 return <div className="mx-auto max-w-[1500px] space-y-4 pb-16 sm:space-y-5 sm:px-2">
  <header className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><Link to={`/quality/surveys/${id}`} className="text-xs font-bold text-teal-700">← {ar?'الاستبيان':'Survey'}</Link><div className="mt-3 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div className="min-w-0"><h1 className="break-words text-xl font-black sm:text-2xl">{ar?'ردود: ':'Responses: '}{data.survey.title}</h1><p className="mt-1 text-xs text-slate-500">{rows.length} {ar?'رد معروض من':'shown of'} {data.submissions.length} {ar?'رد مكتمل':'completed responses'}</p></div><Button onClick={exportExcel} isLoading={exporting} disabled={!rows.length} className="w-full md:w-auto"><Download className="ml-1 h-4 w-4"/>{ar?'تصدير المعروض إلى Excel':'Export shown rows'}</Button></div></header>
  {exportError&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{ar?'تعذر إنشاء ملف Excel. حاول مرة أخرى.':'Unable to create the Excel file. Please try again.'}</p>}
  <label className="flex h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 shadow-sm"><Search className="h-4 w-4 shrink-0 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder={ar?'بحث في الردود...':'Search responses...'}/></label>
  {!rows.length?<EmptyState message={search?(ar?'لا توجد ردود مطابقة للبحث.':'No matching responses.'):(ar?'لا توجد ردود حتى الآن.':'No responses yet.')}/>:<><section className="space-y-3 md:hidden">{rows.map((s,i)=><MobileResponse key={s.submission_id} item={s} index={i} questions={data.questions} anonymous={data.survey.is_anonymous} ar={ar}/>)}</section><section className="hidden overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm md:block"><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-3 text-start">#</th><th className="whitespace-nowrap p-3 text-start">{ar?'وقت الإرسال':'Submitted'}</th>{!data.survey.is_anonymous&&<th className="p-3 text-start">{ar?'المجيب':'Respondent'}</th>}{data.questions.map(q=><th key={q.id} className="min-w-56 p-3 text-start">{q.question_text}</th>)}</tr></thead><tbody className="divide-y">{rows.map((s,i)=><tr key={s.submission_id} className="hover:bg-teal-50/30"><td className="p-3 font-black">{i+1}</td><td className="whitespace-nowrap p-3 text-slate-500">{date(s.responded_at,ar)}</td>{!data.survey.is_anonymous&&<td className="p-3">{s.respondent_identifier||'—'}</td>}{data.questions.map(q=><td key={q.id} className="max-w-sm whitespace-pre-wrap p-3 leading-5">{s.answers[q.id]??'—'}</td>)}</tr>)}</tbody></table></div></section></>}
 </div>;
}
function MobileResponse({item,index,questions,anonymous,ar}:{item:Submission;index:number;questions:Question[];anonymous:boolean;ar:boolean}){return <details className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-2 bg-slate-50 px-4 py-3 [&::-webkit-details-marker]:hidden"><b className="text-sm">{ar?'الاستجابة':'Response'} #{index+1}</b><span className="text-[10px] text-slate-500">{date(item.responded_at,ar)}</span></summary><div className="divide-y divide-slate-100">{!anonymous&&<Pair label={ar?'المجيب':'Respondent'} value={item.respondent_identifier||'—'}/>} {questions.map(q=><Pair key={q.id} label={q.question_text} value={item.answers[q.id]??'—'}/>)}</div></details>}
function Pair({label,value}:{label:string;value:string|number}){return <div className="px-4 py-3"><p className="text-[11px] font-bold leading-5 text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm font-semibold leading-6 text-slate-700">{value}</p></div>}
function date(value:string,ar:boolean){return new Date(value).toLocaleString(ar?'ar-PS':'en-GB')}
