import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { Download, Search } from 'lucide-react';
import ExcelJS from 'exceljs';
import { apiFetch } from '@/api/client';
import { useI18n } from '@/i18n/I18nContext';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { EmptyState } from '@/components/ui/EmptyState';
import { Button } from '@/components/ui/Button';

type Question={id:number;question_text:string;question_type:string;options?:string|null};
type Submission={submission_id:string;responded_at:string;respondent_identifier?:string|null;answers:Record<string,string|number|null>};
type Matrix={survey:{code:string;title:string;is_anonymous:boolean};questions:Question[];submissions:Submission[]};

export function SurveyResponsesPage({surveyId,embedded=false}:{surveyId?:string;embedded?:boolean}={}){
 const{id:routeId}=useParams();const id=surveyId||routeId;const{locale}=useI18n();const ar=locale==='ar';const[search,setSearch]=useState('');const[exporting,setExporting]=useState(false);const[exportError,setExportError]=useState(false);
 const query=useQuery({queryKey:['quality-survey-matrix',id],queryFn:()=>apiFetch<Matrix>(`/quality-surveys/${id}/response-matrix`)});
 const rows=useMemo(()=>query.data?.submissions.filter(s=>!search||`${s.respondent_identifier||''} ${Object.values(s.answers).join(' ')}`.toLowerCase().includes(search.toLowerCase()))||[],[query.data,search]);
 if(query.isLoading)return <LoadingState/>;if(query.isError||!query.data)return <ErrorState onRetry={()=>query.refetch()}/>;const data=query.data;
 const scored=data.questions.filter(q=>q.question_type==='rating'||q.question_type==='number').map(q=>{const values=rows.map(s=>s.answers[q.id]).filter(value=>value!==null&&value!==undefined&&value!=='').map(Number).filter(Number.isFinite);return {question:q,average:values.length?values.reduce((sum,n)=>sum+n,0)/values.length:null,count:values.length}});
 const choices=data.questions.filter(q=>['single_choice','multiple_choice'].includes(q.question_type)&&q.options).map(question=>{const options=(question.options||'').split(/[,\n]/).map(value=>value.trim()).filter(Boolean);const answers=rows.map(submission=>String(submission.answers[question.id]??'').trim()).filter(Boolean);return {question,total:answers.length,options:options.map(option=>({label:option,count:answers.filter(answer=>(question.question_type==='multiple_choice'?answer.split('\n').map(value=>value.trim()):[answer]).includes(option)).length}))}});
 const exportExcel=async()=>{setExporting(true);setExportError(false);try{const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet(ar?'الردود':'Responses',{views:[{rightToLeft:ar}]});ws.columns=[{header:'#',key:'n',width:8},{header:ar?'وقت الإرسال':'Submitted',key:'date',width:22},...(!data.survey.is_anonymous?[{header:ar?'المجيب':'Respondent',key:'person',width:22}]:[]),...data.questions.map(q=>({header:q.question_text,key:`q${q.id}`,width:30}))];rows.forEach((s,i)=>ws.addRow({n:i+1,date:new Date(s.responded_at).toLocaleString(ar?'ar-PS':'en-GB'),person:s.respondent_identifier||'',...Object.fromEntries(data.questions.map(q=>[`q${q.id}`,s.answers[q.id]??'']))}));ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0F766E'}};ws.views=[{state:'frozen',ySplit:1,rightToLeft:ar}];const buffer=await wb.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([buffer]));const a=document.createElement('a');a.href=url;a.download=`${data.survey.code}-responses.xlsx`;a.click();URL.revokeObjectURL(url)}catch{setExportError(true)}finally{setExporting(false)}};
 return <main className={`${embedded?'':'mx-auto max-w-6xl pb-16'} space-y-5`}>
  <section className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 px-4 py-5 sm:flex-row sm:items-end sm:justify-between sm:px-6">{!embedded&&<Link to={`/quality/surveys/${id}`} className="text-xs font-bold text-teal-700">← {ar?'الاستبيان':'Survey'}</Link>}<div className="min-w-0 flex-1"><p className="text-[11px] font-black text-teal-800">{ar?'تحليل الاستبيان':'SURVEY ANALYSIS'}</p><h2 className="mt-1 text-lg font-black text-slate-900 sm:text-xl">{ar?'النتائج والردود':'Results & responses'}</h2><p className="mt-1 text-xs text-slate-500">{rows.length} {ar?'رد معروض من':'shown of'} {data.submissions.length} {ar?'رد مكتمل':'completed responses'}</p></div><Button onClick={exportExcel} isLoading={exporting} disabled={!rows.length} className="w-full sm:w-auto"><Download className="me-2 h-4 w-4"/>{ar?'تصدير المعروض إلى Excel':'Export shown rows'}</Button></div><div className="border-t border-slate-100 bg-slate-50/60 px-4 py-3 sm:px-6"><label className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 focus-within:border-teal-500"><Search className="h-4 w-4 shrink-0 text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder={ar?'ابحث في الردود':'Search responses'} /></label></div></section>
  {exportError&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{ar?'تعذر إنشاء ملف Excel. حاول مرة أخرى.':'Unable to create the Excel file. Please try again.'}</p>}
  {!!rows.length&&!!scored.length&&<section aria-label={ar?'ملخص العلامات':'Score summary'} className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 px-4 py-3 sm:px-6"><h3 className="text-sm font-black">{ar?'المتوسطات':'Averages'}</h3></div><div className="grid sm:grid-cols-2">{scored.map(({question,average,count})=><article key={question.id} className="border-b border-slate-100 p-4 sm:p-5"><p className="line-clamp-2 text-xs font-bold leading-5 text-slate-600">{question.question_text}</p><div className="mt-3 flex items-end justify-between gap-3"><strong className="text-2xl font-black text-[#155c61]">{average===null?'—':average.toFixed(1)}</strong><span className="text-[11px] text-slate-500">{count} {ar?'إجابة رقمية':'numeric answers'}</span></div>{question.question_type==='rating'&&<div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600" style={{width:`${Math.min(100,Math.max(0,(average||0)/5*100))}%`}}/></div>}</article>)}</div></section>}
  {!!rows.length&&!!choices.length&&<section aria-label={ar?'توزيع الإجابات':'Choice distribution'} className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 px-4 py-3 sm:px-6"><h3 className="text-sm font-black">{ar?'توزيع الاختيارات':'Choice distribution'}</h3></div><div className="grid lg:grid-cols-2">{choices.map(({question,total,options})=><article key={question.id} className="border-b border-slate-100 p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><h4 className="text-sm font-black leading-6 text-slate-900">{question.question_text}</h4><span className="shrink-0 text-[11px] text-slate-500">{total} {ar?'إجابة':'answers'}</span></div><div className="mt-4 space-y-3">{options.map(option=><div key={option.label}><div className="mb-1 flex justify-between gap-2 text-xs"><span className="min-w-0 break-words font-semibold text-slate-700">{option.label}</span><span className="shrink-0 font-black text-teal-800">{option.count} · {total?Math.round(option.count/total*100):0}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600" style={{width:`${total?option.count/total*100:0}%`}}/></div></div>)}</div></article>)}</div></section>}
  {!rows.length?<EmptyState message={search?(ar?'لا توجد ردود مطابقة للبحث.':'No matching responses.'):(ar?'لا توجد ردود حتى الآن.':'No responses yet.')}/>:<section aria-label={ar?'الردود الفردية':'Individual responses'} className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 px-4 py-3 sm:px-6"><h3 className="text-sm font-black">{ar?'الردود الفردية':'Individual responses'}</h3></div><div className="divide-y divide-slate-100 md:hidden">{rows.map((item,index)=><MobileResponse key={item.submission_id} item={item} index={index} questions={data.questions} anonymous={data.survey.is_anonymous} ar={ar}/>)}</div><div className="hidden overflow-x-auto md:block"><table className="min-w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-3 text-start">#</th><th className="whitespace-nowrap p-3 text-start">{ar?'وقت الإرسال':'Submitted'}</th>{!data.survey.is_anonymous&&<th className="p-3 text-start">{ar?'المجيب':'Respondent'}</th>}{data.questions.map(question=><th key={question.id} className="min-w-56 p-3 text-start">{question.question_text}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((item,index)=><tr key={item.submission_id} className="hover:bg-teal-50/30"><td className="p-3 font-black">{index+1}</td><td className="whitespace-nowrap p-3 text-slate-500">{date(item.responded_at,ar)}</td>{!data.survey.is_anonymous&&<td className="p-3">{item.respondent_identifier||'—'}</td>}{data.questions.map(question=><td key={question.id} className="max-w-sm whitespace-pre-wrap p-3 leading-5">{item.answers[question.id]??'—'}</td>)}</tr>)}</tbody></table></div></section>}
 </main>;
}
function MobileResponse({item,index,questions,anonymous,ar}:{item:Submission;index:number;questions:Question[];anonymous:boolean;ar:boolean}){return <details><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-2 px-4 py-3 [&::-webkit-details-marker]:hidden"><b className="text-sm">{ar?'الاستجابة':'Response'} #{index+1}</b><span className="text-[10px] text-slate-500">{date(item.responded_at,ar)}</span></summary><div className="divide-y divide-slate-100 bg-slate-50/60">{!anonymous&&<Pair label={ar?'المجيب':'Respondent'} value={item.respondent_identifier||'—'}/>} {questions.map(q=><Pair key={q.id} label={q.question_text} value={item.answers[q.id]??'—'}/>)}</div></details>}
function Pair({label,value}:{label:string;value:string|number}){return <div className="px-4 py-3"><p className="text-[11px] font-bold leading-5 text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm font-semibold leading-6 text-slate-700">{value}</p></div>}
function date(value:string,ar:boolean){return new Date(value).toLocaleString(ar?'ar-PS':'en-GB')}
