import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { BarChart3, Download, Inbox, Search } from 'lucide-react';
import ExcelJS from 'exceljs';
import { apiFetch } from '@/api/client';
import { useI18n } from '@/i18n/I18nContext';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { EmptyState } from '@/components/ui/EmptyState';
import { Button } from '@/components/ui/Button';

type Question={id:number;question_number:number;question_text:string;question_type:string};
type Submission={submission_id:string;responded_at:string;respondent_identifier?:string|null;answers:Record<string,string|number|null>};
type Matrix={survey:{id:number;code:string;title:string;status:string;is_anonymous:boolean};questions:Question[];submissions:Submission[]};

export function SurveyResponsesPage(){
 const{id}=useParams();const{locale}=useI18n();const ar=locale==='ar';const[search,setSearch]=useState('');const[exporting,setExporting]=useState(false);
 const query=useQuery({queryKey:['quality-survey-matrix',id],queryFn:()=>apiFetch<Matrix>(`/quality-surveys/${id}/response-matrix`)});
 const rows=useMemo(()=>query.data?.submissions.filter(s=>!search||`${s.respondent_identifier||''} ${Object.values(s.answers).join(' ')}`.toLowerCase().includes(search.toLowerCase()))||[],[query.data,search]);
 if(query.isLoading)return <LoadingState/>;if(query.isError||!query.data)return <ErrorState onRetry={()=>query.refetch()}/>;const data=query.data;
 const exportExcel=async()=>{setExporting(true);try{const wb=new ExcelJS.Workbook();wb.creator='CDMS Quality';const ws=wb.addWorksheet(ar?'الردود':'Responses',{views:[{rightToLeft:ar}]});ws.columns=[{header:ar?'رقم الاستجابة':'Submission ID',key:'id',width:38},{header:ar?'وقت الإرسال':'Submitted at',key:'date',width:23},...(!data.survey.is_anonymous?[{header:ar?'المجيب':'Respondent',key:'respondent',width:24}]:[]),...data.questions.map(q=>({header:q.question_text,key:`q${q.id}`,width:28}))];for(const s of data.submissions)ws.addRow({id:s.submission_id,date:new Date(s.responded_at).toLocaleString(ar?'ar-PS':'en-GB'),respondent:s.respondent_identifier||'',...Object.fromEntries(data.questions.map(q=>[`q${q.id}`,s.answers[q.id]??'']))});ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0F766E'}};ws.autoFilter={from:{row:1,column:1},to:{row:1,column:ws.columnCount}};ws.views=[{state:'frozen',ySplit:1,rightToLeft:ar}];const buffer=await wb.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([buffer]));const a=document.createElement('a');a.href=url;a.download=`${data.survey.code}-responses.xlsx`;a.click();URL.revokeObjectURL(url)}finally{setExporting(false)}};
 return <div className="mx-auto max-w-[1500px] space-y-5 pb-14"><header className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><Link to={`/quality/surveys/${id}`} className="text-xs font-bold text-teal-700">{ar?'← الرجوع لمحرر الاستبيان':'← Back to survey editor'}</Link><div className="mt-3 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><h1 className="text-2xl font-black">{ar?'ردود: ':'Responses: '}{data.survey.title}</h1><p className="mt-1 text-sm text-slate-500">{data.submissions.length} {ar?'استجابة مكتملة؛ كل صف يمثل نموذجًا واحدًا.':'completed submissions; each row is one form.'}</p></div><Button onClick={exportExcel} isLoading={exporting} disabled={!data.submissions.length}><Download className="ml-1 h-4 w-4"/>{ar?'تصدير Excel':'Export Excel'}</Button></div></header>
 <section className="grid gap-3 sm:grid-cols-3"><Stat icon={<Inbox/>} value={data.submissions.length} label={ar?'إجمالي الردود':'Total responses'}/><Stat icon={<BarChart3/>} value={data.questions.length} label={ar?'عدد الأسئلة':'Questions'}/><Stat icon={<BarChart3/>} value={average(data)} label={ar?'متوسط التقييمات':'Rating average'}/></section>
 <label className="flex h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full text-sm outline-none" placeholder={ar?'بحث داخل جميع الردود...':'Search all responses...'}/></label>
 {!rows.length?<EmptyState message={ar?'لا توجد ردود حتى الآن.':'No responses yet.'}/>:<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="bg-slate-50"><tr><th className="whitespace-nowrap p-3 text-right">#</th><th className="whitespace-nowrap p-3 text-right">{ar?'وقت الإرسال':'Submitted'}</th>{!data.survey.is_anonymous&&<th className="p-3 text-right">{ar?'المجيب':'Respondent'}</th>}{data.questions.map(q=><th key={q.id} className="min-w-56 p-3 text-right">{q.question_text}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((s,i)=><tr key={s.submission_id} className="hover:bg-teal-50/30"><td className="p-3 font-black">{i+1}</td><td className="whitespace-nowrap p-3 text-slate-500">{new Date(s.responded_at).toLocaleString(ar?'ar-PS':'en-GB')}</td>{!data.survey.is_anonymous&&<td className="p-3">{s.respondent_identifier||'—'}</td>}{data.questions.map(q=><td key={q.id} className="max-w-sm whitespace-pre-wrap p-3 leading-5">{s.answers[q.id]??'—'}</td>)}</tr>)}</tbody></table></div></section>}</div>;
}
function average(data:Matrix){const ratingIds=new Set(data.questions.filter(q=>['rating','number'].includes(q.question_type)).map(q=>q.id));const values=data.submissions.flatMap(s=>Object.entries(s.answers).filter(([id,v])=>ratingIds.has(Number(id))&&typeof v==='number').map(([,v])=>Number(v)));return values.length?(values.reduce((a,b)=>a+b,0)/values.length).toFixed(1):'—'}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string|number;label:string}){return <div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4"><span className="rounded-xl bg-teal-50 p-2 text-teal-700 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><p className="text-xl font-black">{value}</p><p className="text-xs text-slate-400">{label}</p></div></div>}
