<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Http\Controllers\Concerns\HasSafePagination; use App\Http\Responses\ApiResponse; use App\Models\QualitySurvey; use App\Models\QualitySurveyQuestion; use App\Models\QualitySurveyResponse; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class QualitySurveyController extends Controller {
 use HasSafePagination;
 public function index(Request $request): JsonResponse { $items=QualitySurvey::withCount('questions')->orderBy('code')->paginate($this->perPage($request,25,100)); return ApiResponse::success($items->items(),null,['current_page'=>$items->currentPage(),'last_page'=>$items->lastPage(),'total'=>$items->total()]); }
 public function store(Request $request): JsonResponse { $data=$request->validate(['code'=>['required','string','max:100','unique:quality_surveys,code'],'title'=>['required','string','max:500'],'target_group'=>['required','string','max:255'],'purpose'=>['nullable','string','max:3000'],'frequency'=>['nullable','string','max:100'],'responsible'=>['nullable','string','max:255'],'form_url'=>['nullable','url','max:2000'],'is_mandatory'=>['boolean'],'notes'=>['nullable','string','max:3000']]); return ApiResponse::success(QualitySurvey::create($data),'Quality survey created.',[],201); }
 public function show(QualitySurvey $qualitySurvey): JsonResponse { return ApiResponse::success($qualitySurvey->load(['questions'=>fn($q)=>$q->orderBy('version')->orderBy('question_number')])); }
 public function responses(Request $request, QualitySurvey $qualitySurvey): JsonResponse { $responses=QualitySurveyResponse::with('question:id,question_text')->where('quality_survey_id',$qualitySurvey->id)->latest('responded_at')->paginate($this->perPage($request,50,100)); $summary=QualitySurveyResponse::query()->leftJoin('quality_survey_questions','quality_survey_questions.id','=','quality_survey_responses.quality_survey_question_id')->where('quality_survey_responses.quality_survey_id',$qualitySurvey->id)->groupBy('quality_survey_responses.quality_survey_question_id','quality_survey_questions.question_text')->get(['quality_survey_responses.quality_survey_question_id as question_id','quality_survey_questions.question_text',DB::raw('COUNT(*) as response_count'),DB::raw('AVG(quality_survey_responses.numeric_answer) as numeric_average')]); return ApiResponse::success(['responses'=>$responses->items(),'summary'=>$summary],null,['current_page'=>$responses->currentPage(),'last_page'=>$responses->lastPage(),'total'=>$responses->total()]); }
 public function storeQuestion(Request $request, QualitySurvey $qualitySurvey): JsonResponse { $data=$request->validate(['version'=>['required','string','max:50'],'question_number'=>['required','integer','min:1'],'question_text'=>['required','string','max:3000'],'question_type'=>['required','string','max:100'],'options'=>['nullable','string','max:3000'],'is_required'=>['boolean'],'weight'=>['nullable','numeric','min:0'],'axis'=>['nullable','string','max:255'],'active_from'=>['nullable','date'],'active_until'=>['nullable','date']]); $data['quality_survey_id']=$qualitySurvey->id; return ApiResponse::success(QualitySurveyQuestion::create($data),'Survey question created.',[],201); }
 public function storeResponse(Request $request, QualitySurvey $qualitySurvey): JsonResponse { $data=$request->validate(['quality_survey_question_id'=>['required','exists:quality_survey_questions,id'],'version'=>['required','string','max:50'],'respondent_identifier'=>['nullable','string','max:255'],'target_group'=>['nullable','string','max:255'],'course_id'=>['nullable','exists:courses,id'],'department_id'=>['nullable','exists:departments,id'],'training_site_id'=>['nullable','exists:training_sites,id'],'supervisor_person_id'=>['nullable','exists:people,id'],'numeric_answer'=>['nullable','numeric'],'text_answer'=>['nullable','string','max:5000']]); if(!QualitySurveyQuestion::where('id',$data['quality_survey_question_id'])->where('quality_survey_id',$qualitySurvey->id)->exists()) return ApiResponse::error('The question does not belong to this survey.',[],[],422); $data['quality_survey_id']=$qualitySurvey->id; $data['responded_at']=now(); return ApiResponse::success(QualitySurveyResponse::create($data),'Survey response recorded.',[],201); }
}
