<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;
use App\Http\Responses\ApiResponse;
use App\Models\QualityEvidence;
use App\Models\QualityFinding;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class QualityOperationsController extends Controller {
 public function index(Request $request): JsonResponse { $year=$request->string('academic_year')->toString(); return ApiResponse::success(['findings'=>QualityFinding::with(['owner:id,name,email','plan:id,observation,status'])->when($year,fn($q)=>$q->where('academic_year',$year))->latest()->get(),'evidence'=>QualityEvidence::with('owner:id,name,email')->latest()->get()]); }
 public function storeFinding(Request $request): JsonResponse { $data=$request->validate(['academic_year'=>['nullable','string','max:100'],'source'=>['required','string','max:255'],'category'=>['nullable','string','max:255'],'title'=>['required','string','max:500'],'description'=>['required','string','max:5000'],'severity'=>['required',Rule::in(['low','medium','high','critical'])],'is_recurring'=>['boolean'],'owner_user_id'=>['nullable','exists:users,id'],'due_date'=>['nullable','date'],'root_cause'=>['nullable','string','max:5000'],'recommended_action'=>['nullable','string','max:5000'],'evidence_reference'=>['nullable','string','max:5000']]); $data['reference']='QF-'.now()->format('Ymd').'-'.str_pad((string)(QualityFinding::max('id')+1),4,'0',STR_PAD_LEFT); $data['created_by']=$request->user()?->id; return ApiResponse::success(QualityFinding::create($data),'تم تسجيل ملاحظة الجودة.',[],201); }
 public function updateFinding(Request $request, QualityFinding $finding): JsonResponse { $data=$request->validate(['status'=>['required',Rule::in(['open','analyzing','action_required','linked_to_plan','closed'])],'owner_user_id'=>['nullable','exists:users,id'],'due_date'=>['nullable','date'],'root_cause'=>['nullable','string','max:5000'],'recommended_action'=>['nullable','string','max:5000'],'evidence_reference'=>['nullable','string','max:5000']]); if($data['status']==='closed' && blank($data['evidence_reference']??$finding->evidence_reference)) return ApiResponse::error('دليل المعالجة مطلوب قبل إغلاق الملاحظة.',[],[],422); if($data['status']==='closed'){ $data['closed_by']=$request->user()?->id;$data['closed_at']=now(); } $finding->update($data); return ApiResponse::success($finding->fresh()->load('owner:id,name,email'),'تم تحديث ملاحظة الجودة.'); }
 public function storeEvidence(Request $request): JsonResponse { $data=$request->validate(['code'=>['required','string','max:100','unique:quality_evidence,code'],'title'=>['required','string','max:500'],'category'=>['nullable','string','max:255'],'description'=>['nullable','string','max:5000'],'reference_url'=>['nullable','url','max:2000'],'document_version'=>['nullable','string','max:100'],'issued_at'=>['nullable','date'],'expires_at'=>['nullable','date','after_or_equal:issued_at'],'status'=>['required',Rule::in(['draft','approved','expired','archived'])],'owner_user_id'=>['nullable','exists:users,id']]); $data['created_by']=$request->user()?->id; return ApiResponse::success(QualityEvidence::create($data),'تم تسجيل دليل الجودة.',[],201); }
 public function updateEvidence(Request $request, QualityEvidence $evidence): JsonResponse { $data=$request->validate(['title'=>['required','string','max:500'],'category'=>['nullable','string','max:255'],'description'=>['nullable','string','max:5000'],'reference_url'=>['nullable','url','max:2000'],'document_version'=>['nullable','string','max:100'],'issued_at'=>['nullable','date'],'expires_at'=>['nullable','date','after_or_equal:issued_at'],'status'=>['required',Rule::in(['draft','approved','expired','archived'])],'owner_user_id'=>['nullable','exists:users,id']]); $evidence->update($data); return ApiResponse::success($evidence->fresh()->load('owner:id,name,email'),'تم تحديث دليل الجودة.'); }
}
