import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { CheckCircle2, Clock3, ExternalLink, GitBranch, RotateCcw, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { apiFetch } from '@/api/client';
import { useI18n } from '@/i18n/I18nContext';

type Step={id:number;step_order:number;name_ar:string;name_en:string;role_codes:string[]};
type Item={id:number;public_id:string;title_ar:string;title_en:string;source_url?:string;status:string;current_step_order:number;requested_at:string;workflow:{name_ar:string;name_en:string;steps:Step[]};requester?:{name:string};actions:{id:number;action:string;comment?:string;acted_at:string;actor?:{name:string};step?:Step}[]};

export function ApprovalsPage(){const {locale}=useI18n();const ar=locale==='ar';const [scope,setScope]=useState<'queue'|'mine'>('queue');const query=useQuery({queryKey:['approvals',scope],queryFn:()=>apiFetch<Item[]>(`/approvals${scope==='mine'?'?scope=mine':''}`)});const items=query.data??[];
return <div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-black text-slate-900"><GitBranch className="h-6 w-6 text-teal-700"/>{ar?'مركز الاعتمادات':'Approval Center'}</h1><p className="mt-1 text-sm text-slate-500">{ar?'جميع الطلبات التي تنتظر قرارك مع المرحلة والجهة المطلوبة.':'All requests awaiting your decision, with their current stage and owner.'}</p></div><div className="flex rounded-2xl border border-slate-200 bg-white p-1 text-xs font-bold"><button onClick={()=>setScope('queue')} className={`rounded-xl px-4 py-2 ${scope==='queue'?'bg-teal-700 text-white':'text-slate-600'}`}>{ar?'بانتظار قراري':'Awaiting my decision'}</button><button onClick={()=>setScope('mine')} className={`rounded-xl px-4 py-2 ${scope==='mine'?'bg-teal-700 text-white':'text-slate-600'}`}>{ar?'طلباتي':'My requests'}</button></div></header>
{query.isLoading?<p className="p-8 text-center text-sm text-slate-500">{ar?'جارٍ تحميل الطلبات...':'Loading requests...'}</p>:items.length===0?<div className="rounded-3xl border border-slate-200 bg-white p-12 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-500"/><h2 className="mt-3 font-black">{ar?'لا توجد طلبات معلقة':'No pending requests'}</h2><p className="mt-1 text-sm text-slate-500">{ar?'كل الاعتمادات المطلوبة منك منجزة حالياً.':'All approvals assigned to you are currently complete.'}</p></div>:<div className="space-y-3">{items.map(item=>{const step=item.workflow.steps.find(s=>s.step_order===item.current_step_order);return <article key={item.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex flex-wrap items-center gap-2"><span className={`rounded-lg px-2.5 py-1 text-[10px] font-black ${item.status==='pending'?'bg-amber-50 text-amber-700':item.status==='approved'?'bg-emerald-50 text-emerald-700':item.status==='returned'?'bg-red-50 text-red-700':'bg-slate-100 text-slate-600'}`}>{status(item.status,ar)}</span><span className="text-xs font-bold text-teal-700">{ar?item.workflow.name_ar:item.workflow.name_en}</span></div><h2 className="font-black text-slate-900">{ar?item.title_ar:item.title_en}</h2><div className="mt-2 flex flex-wrap gap-4 text-[11px] text-slate-500"><span className="flex items-center gap-1"><UserRound className="h-3.5 w-3.5"/>{ar?'مقدم الطلب:':'Requester:'} {item.requester?.name??'—'}</span><span className="flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>{new Intl.DateTimeFormat(ar?'ar-PS':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.requested_at))}</span></div></div><div className="flex items-center gap-3"><div className="rounded-2xl bg-slate-50 px-4 py-3"><p className="text-[10px] font-bold text-slate-400">{ar?'المرحلة الحالية':'Current stage'}</p><p className="mt-1 text-xs font-black text-slate-800">{step?(ar?step.name_ar:step.name_en):'—'}</p></div>{item.source_url&&<Link to={item.source_url} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-xs font-black text-white hover:bg-teal-800">{ar?'فتح المعاملة':'Open record'}<ExternalLink className="h-4 w-4"/></Link>}</div></div>
{item.actions.length>1&&<details className="mt-4 border-t border-slate-100 pt-3"><summary className="cursor-pointer text-xs font-bold text-slate-500">{ar?'عرض سجل الإجراءات':'View action history'}</summary><div className="mt-3 space-y-2">{item.actions.map(a=><div key={a.id} className="flex flex-wrap items-center gap-2 text-[11px] text-slate-600">{a.action==='returned'?<RotateCcw className="h-3.5 w-3.5 text-red-500"/>:<CheckCircle2 className="h-3.5 w-3.5 text-teal-600"/>}<b>{a.actor?.name}</b><span>{action(a.action,ar)}</span>{a.step&&<span>— {ar?a.step.name_ar:a.step.name_en}</span>}{a.comment&&<span className="text-slate-500">({a.comment})</span>}</div>)}</div></details>}</article>})}</div>}</div>}
const status=(s:string,ar:boolean)=>({pending:ar?'قيد الاعتماد':'Pending',approved:ar?'معتمد':'Approved',returned:ar?'معاد للتعديل':'Returned',cancelled:ar?'ملغي':'Cancelled'}[s]??s);
const action=(s:string,ar:boolean)=>({submitted:ar?'أرسل الطلب':'submitted the request',approved:ar?'اعتمد المرحلة':'approved the stage',returned:ar?'أعاد الطلب':'returned the request',cancelled:ar?'ألغي بسبب تعديل المحتوى':'cancelled after content changed'}[s]??s);
