import { useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, ArrowLeft, ArrowRight, Download, Forward, ListChecks, MailOpen, Paperclip, Printer, Reply, Send, Star, Trash2, X } from 'lucide-react';
import { apiFetch, apiUrl, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { Button } from '@/components/ui/Button';
import { ErrorState } from '@/components/ui/ErrorState';
import { LoadingState } from '@/components/ui/LoadingState';

type UserOption = { id: number; name: string; email: string; person?: { full_name_ar?: string; full_name_en?: string } };
type Participant = { id: number; user_id: number; participant_role: string; starred_at?: string|null; archived_at?: string|null; user?: UserOption };
type Attachment = { id: number; uploaded_by?: number|null; original_name: string; file_size: number; mime_type?: string; uploader?: UserOption|null };
type Message = { id: number; sender_id: number; body: string; created_at: string; sender?: UserOption|null };
type Activity = { id: number; action: string; created_at: string; user?: UserOption|null; changes?: Record<string,unknown> };
type Item = { id:number; reference_number:string; subject:string; summary?:string|null; priority:string; message_type:string; confidentiality:string; tags?:string[]|null; status:string; submitted_at?:string|null; response_due_date?:string|null; sender_id:number; sender?:UserOption|null; participants:Participant[]; attachments:Attachment[]; messages:Message[]; activity?:Activity[] };
const fieldClass='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-100';

function DraftEditor({item,users,ar,onDone}:{item:Item;users:UserOption[];ar:boolean;onDone:()=>Promise<void>}){
 const current=(role:string)=>item.participants.filter(p=>p.participant_role===role).map(p=>p.user_id);const [form,setForm]=useState({subject:item.subject,body:item.summary||'',to:current('to'),cc:current('cc'),fyi:current('fyi')});const [error,setError]=useState('');
 const request=useMutation({mutationFn:(send:boolean)=>apiFetch(`/correspondence/${item.id}${send?'/submit':''}`,{method:send?'POST':'PUT',body:{...form,message_type:'message',priority:'normal',confidentiality:'normal',response_due_date:null}}),onSuccess:onDone,onError:value=>setError(value instanceof ApiError?value.message:(ar?'تعذر حفظ المسودة.':'Unable to save draft.'))});
 const values=(event:ChangeEvent<HTMLSelectElement>)=>Array.from(event.target.selectedOptions).map(option=>Number(option.value));
 return <form onSubmit={e=>{e.preventDefault();request.mutate(true)}} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-800 px-5 py-3 text-sm font-bold text-white">{ar?'تعديل المسودة':'Edit draft'}</div><div className="space-y-3 p-5"><label className="block text-xs text-slate-500">{ar?'إلى':'To'}<select multiple value={form.to.map(String)} onChange={e=>setForm({...form,to:values(e)})} className={`${fieldClass} mt-1 h-24`}>{users.map(u=><option key={u.id} value={u.id}>{u.name} — {u.email}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">CC<select multiple value={form.cc.map(String)} onChange={e=>setForm({...form,cc:values(e)})} className={`${fieldClass} mt-1 h-20`}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="text-xs text-slate-500">BCC<select multiple value={form.fyi.map(String)} onChange={e=>setForm({...form,fyi:values(e)})} className={`${fieldClass} mt-1 h-20`}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label></div><input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} className={fieldClass} placeholder={ar?'الموضوع':'Subject'}/><textarea rows={9} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} className={fieldClass} placeholder={ar?'اكتب رسالتك...':'Write your message...'}/>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>request.mutate(false)} isLoading={request.isPending}>{ar?'حفظ':'Save'}</Button><Button type="submit" disabled={!form.to.length} isLoading={request.isPending}><Send className="me-2 h-4 w-4"/>{ar?'إرسال':'Send'}</Button></div></div></form>;
}

export function CorrespondenceDetailsPage(){
 const {id}=useParams();const navigate=useNavigate();const qc=useQueryClient();const {user,can}=useAuth();const {locale,t}=useI18n();const ar=locale==='ar';
 const [reply,setReply]=useState('');const [error,setError]=useState('');const [files,setFiles]=useState<File[]>([]);const fileInput=useRef<HTMLInputElement>(null);const [forwardOpen,setForwardOpen]=useState(false);const [forwardTo,setForwardTo]=useState('');const [forwardBody,setForwardBody]=useState('');const [taskOpen,setTaskOpen]=useState(false);const [task,setTask]=useState({title:'',description:'',assigned_to:'',due_date:'',priority:'normal'});
 const itemQuery=useQuery({queryKey:['correspondence',id],queryFn:()=>apiFetch<Item>(`/correspondence/${id}`),enabled:Boolean(id)});const usersQuery=useQuery({queryKey:['users-lookup','correspondence'],queryFn:()=>apiFetch<UserOption[]>('/users/lookup?purpose=correspondence'),enabled:Boolean(itemQuery.data)});const item=itemQuery.data;const users=Array.isArray(usersQuery.data)?usersQuery.data:[];
 const refresh=async()=>{await qc.invalidateQueries({queryKey:['correspondence',id]});await qc.invalidateQueries({queryKey:['correspondence-mailbox']})};const fail=(fallback:string)=>(value:unknown)=>setError(value instanceof ApiError?value.message:fallback);
 const replyMutation=useMutation({mutationFn:()=>apiFetch(`/correspondence/${id}/messages`,{method:'POST',body:{body:reply.trim()}}),onSuccess:async()=>{setReply('');setError('');await uploadSelected();await refresh()},onError:fail(ar?'تعذر إرسال الرد.':'Unable to send reply.')});
 const uploadMutation=useMutation({mutationFn:(selected:File[])=>{const body=new FormData();selected.forEach(file=>body.append('files[]',file));return apiFetch(`/correspondence/${id}/attachments`,{method:'POST',body})},onSuccess:async()=>{setFiles([]);if(fileInput.current)fileInput.current.value='';await refresh()},onError:fail(ar?'تعذر رفع المرفقات.':'Unable to upload attachments.')});
 const uploadSelected=async()=>{if(files.length)await uploadMutation.mutateAsync(files)};
 const stateMutation=useMutation({mutationFn:(action:string)=>apiFetch(`/correspondence/${id}/mailbox/${action}`,{method:'POST'}),onSuccess:refresh,onError:fail(ar?'تعذر تحديث الرسالة.':'Unable to update message.')});
 const removeAttachment=useMutation({mutationFn:(attachmentId:number)=>apiFetch(`/correspondence/${id}/attachments/${attachmentId}`,{method:'DELETE'}),onSuccess:refresh,onError:fail(ar?'تعذر حذف المرفق.':'Unable to delete attachment.')});
 const forwardMutation=useMutation({mutationFn:()=>apiFetch(`/correspondence/${id}/forward`,{method:'POST',body:{to:[Number(forwardTo)],body:forwardBody}}),onSuccess:async()=>{setForwardOpen(false);setForwardTo('');setForwardBody('');await refresh()},onError:fail(ar?'تعذرت إعادة التوجيه.':'Unable to forward.')});
 const createTask=useMutation({mutationFn:()=>apiFetch(`/correspondence/${id}/tasks`,{method:'POST',body:{...task,assigned_to:Number(task.assigned_to),due_date:task.due_date||null}}),onSuccess:async()=>{setTaskOpen(false);await qc.invalidateQueries({queryKey:['operational-tasks']})},onError:fail(ar?'تعذر إنشاء المهمة.':'Unable to create task.')});
 if(!can('correspondence.view'))return <ErrorState title={t('state.forbidden.title')} message={t('state.forbidden.message')}/>;if(itemQuery.isLoading)return <LoadingState/>;if(itemQuery.isError||!item)return <ErrorState onRetry={()=>itemQuery.refetch()}/>;
 const nameOf=(value?:UserOption|null)=>(ar?value?.person?.full_name_ar:value?.person?.full_name_en)||value?.name||value?.email||'—';const formatDate=(value?:string|null,withTime=false)=>value?new Intl.DateTimeFormat(locale,{year:'numeric',month:'short',day:'numeric',...(withTime?{hour:'numeric',minute:'2-digit'}:{})}).format(new Date(value)):'—';
 const me=item.participants.find(p=>p.user_id===user?.id);const recipients=(role:string)=>item.participants.filter(p=>p.participant_role===role).map(p=>nameOf(p.user)).join('، ');const conversation=[{id:0,sender_id:item.sender_id,body:item.summary||'',created_at:item.submitted_at||'',sender:item.sender},...(item.messages||[])];
 if(item.status==='draft')return <div className="mx-auto max-w-[900px] space-y-4 pb-8"><button onClick={()=>navigate(-1)} className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-teal-50">{ar?<ArrowRight className="h-4 w-4"/>:<ArrowLeft className="h-4 w-4"/>}{ar?'العودة للمسودات':'Back to drafts'}</button><DraftEditor item={item} users={users} ar={ar} onDone={refresh}/></div>;
 return <div className="mx-auto max-w-[1100px] space-y-4 pb-8"><div className="flex flex-wrap items-center justify-between gap-2"><button onClick={()=>navigate(-1)} className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-teal-50">{ar?<ArrowRight className="h-4 w-4"/>:<ArrowLeft className="h-4 w-4"/>}{ar?'العودة للبريد':'Back to mail'}</button><div className="flex gap-1"><button title={ar?'تمييز':'Star'} onClick={()=>stateMutation.mutate(me?.starred_at?'unstar':'star')} className="rounded-lg p-2 hover:bg-amber-50"><Star className={`h-5 w-5 ${me?.starred_at?'fill-amber-400 text-amber-400':'text-slate-400'}`}/></button><button title={ar?'كغير مقروءة':'Mark unread'} onClick={()=>stateMutation.mutate('unread')} className="rounded-lg p-2 text-slate-500 hover:bg-teal-50"><MailOpen className="h-5 w-5"/></button><a title={ar?'طباعة PDF':'Print PDF'} href={apiUrl(`/correspondence/${item.id}/print`)} className="rounded-lg p-2 text-slate-500 hover:bg-teal-50"><Printer className="h-5 w-5"/></a><button title={me?.archived_at?(ar?'إعادة للوارد':'Restore'):(ar?'أرشفة':'Archive')} onClick={()=>stateMutation.mutate(me?.archived_at?'restore':'archive')} className="rounded-lg p-2 text-slate-500 hover:bg-teal-50"><Archive className="h-5 w-5"/></button></div></div>
 <article className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><h1 className="text-xl font-bold text-slate-950 sm:text-2xl">{item.subject}</h1><span className="text-xs font-semibold text-slate-400" dir="ltr">{item.reference_number}</span></div><div className="mt-4 grid gap-1 text-xs text-slate-500 sm:grid-cols-[60px_1fr]"><strong>{ar?'من':'From'}</strong><span>{nameOf(item.sender)} · {item.sender?.email}</span><strong>{ar?'إلى':'To'}</strong><span>{recipients('to')||'—'}</span>{recipients('cc')&&<><strong>CC</strong><span>{recipients('cc')}</span></>}{recipients('fyi')&&<><strong>BCC</strong><span>{recipients('fyi')}</span></>}</div></header>
 <div className="divide-y divide-slate-100">{conversation.map((message,index)=><section key={`${index}-${message.id}`} className="p-5 sm:p-6"><div className="mb-3 flex items-center justify-between gap-2"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-teal-50 text-xs font-bold text-teal-700">{nameOf(message.sender).slice(0,1)}</span><strong className="text-sm text-slate-800">{nameOf(message.sender)}</strong></div><time className="text-xs text-slate-400">{formatDate(message.created_at,true)}</time></div><div className="whitespace-pre-wrap text-sm leading-8 text-slate-700" dangerouslySetInnerHTML={{__html:message.body||(ar?'بدون نص.':'No content.')}} /></section>)}</div>
 <form onSubmit={(event:FormEvent)=>{event.preventDefault();replyMutation.mutate()}} className="border-t border-slate-100 bg-slate-50/50 p-5"><div className="mb-2 flex items-center gap-2 font-bold text-slate-800"><Reply className="h-4 w-4 text-teal-600"/>{ar?'الرد على الجميع':'Reply all'}</div><textarea required rows={4} value={reply} onChange={e=>setReply(e.target.value)} className={fieldClass} placeholder={ar?'اكتب ردك...':'Write a reply...'}/><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><div><input ref={fileInput} multiple type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.png,.jpg,.jpeg" onChange={e=>setFiles(Array.from(e.target.files||[]))}/><Button type="button" variant="outline" onClick={()=>fileInput.current?.click()}><Paperclip className="me-2 h-4 w-4"/>{files.length?(ar?`${files.length} مرفقات`:`${files.length} attachments`):(ar?'إرفاق ملفات':'Attach files')}</Button></div><div className="flex gap-2"><Button type="button" variant="outline" onClick={()=>setForwardOpen(true)}><Forward className="me-2 h-4 w-4"/>{ar?'إعادة توجيه':'Forward'}</Button><Button type="submit" disabled={!reply.trim()} isLoading={replyMutation.isPending}><Send className="me-2 h-4 w-4"/>{ar?'إرسال':'Send'}</Button></div></div></form></article>
 {error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-800">{ar?'المرفقات':'Attachments'}</h2>{files.length>0&&<Button size="sm" onClick={uploadSelected} isLoading={uploadMutation.isPending}>{ar?'رفع الآن':'Upload now'}</Button>}</div>{item.attachments?.length?<div className="mt-3 divide-y divide-slate-100">{item.attachments.map(file=><div key={file.id} className="flex items-center justify-between gap-2 py-3"><div className="min-w-0"><div className="truncate text-sm font-semibold text-slate-700">{file.original_name}</div><div className="text-xs text-slate-400">{Math.max(1,Math.round(file.file_size/1024))} KB</div></div><div className="flex"><a href={apiUrl(`/correspondence/${item.id}/attachments/${file.id}/download`)} className="rounded-lg p-2 text-teal-700 hover:bg-teal-50"><Download className="h-4 w-4"/></a>{(file.uploaded_by===user?.id||item.sender_id===user?.id)&&<button onClick={()=>removeAttachment.mutate(file.id)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4"/></button>}</div></div>)}</div>:<p className="mt-3 text-sm text-slate-400">{ar?'لا توجد مرفقات.':'No attachments.'}</p>}</section>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-800">{ar?'سجل الرسالة':'Message activity'}</h2>{can('tasks.manage')&&<Button size="sm" variant="outline" onClick={()=>{setTaskOpen(true);setTask({...task,title:item.subject})}}><ListChecks className="me-2 h-4 w-4"/>{ar?'إنشاء مهمة':'Create task'}</Button>}</div><div className="mt-3 max-h-44 space-y-2 overflow-y-auto">{item.activity?.length?item.activity.map(entry=><div key={entry.id} className="flex items-start gap-2 text-xs"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-teal-500"/><div><strong className="text-slate-700">{nameOf(entry.user)}</strong><span className="mx-1 text-slate-500">{({ 'correspondence.sent':ar?'أرسل الرسالة':'sent the message','correspondence.replied':ar?'أضاف رداً':'replied','correspondence.forwarded':ar?'أعاد التوجيه':'forwarded','correspondence.archive':ar?'أرشف الرسالة':'archived','correspondence.restore':ar?'أعاد الرسالة للوارد':'restored','correspondence.star':ar?'ميّز الرسالة':'starred','correspondence.unstar':ar?'أزال التمييز':'unstarred','correspondence.unread':ar?'علّمها كغير مقروءة':'marked unread','correspondence.attachments_added':ar?'أضاف مرفقات':'added attachments' } as Record<string,string>)[entry.action]||entry.action}</span><span className="text-slate-400">· {formatDate(entry.created_at,true)}</span></div></div>):<p className="text-sm text-slate-400">{ar?'لا توجد حركات مسجلة.':'No activity recorded.'}</p>}</div>{item.tags?.length?<div className="mt-3 flex flex-wrap gap-1">{item.tags.map(tag=><span key={tag} className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">#{tag}</span>)}</div>:null}</section></div>
 {forwardOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-4"><form onSubmit={e=>{e.preventDefault();forwardMutation.mutate()}} className="w-full max-w-lg space-y-3 rounded-2xl bg-white p-5 shadow-xl"><div className="flex justify-between"><h2 className="font-bold">{ar?'إعادة توجيه الرسالة':'Forward message'}</h2><button type="button" onClick={()=>setForwardOpen(false)}><X className="h-5 w-5"/></button></div><select required value={forwardTo} onChange={e=>setForwardTo(e.target.value)} className={fieldClass}><option value="">{ar?'اختر المستلم...':'Choose recipient...'}</option>{users.filter(u=>!item.participants.some(p=>p.user_id===u.id)).map(u=><option key={u.id} value={u.id}>{u.name} — {u.email}</option>)}</select><textarea rows={3} value={forwardBody} onChange={e=>setForwardBody(e.target.value)} className={fieldClass} placeholder={ar?'ملاحظة اختيارية':'Optional note'}/><div className="flex justify-end"><Button type="submit" disabled={!forwardTo} isLoading={forwardMutation.isPending}>{ar?'إعادة توجيه':'Forward'}</Button></div></form></div>}
 {taskOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-4"><form onSubmit={e=>{e.preventDefault();createTask.mutate()}} className="w-full max-w-xl space-y-3 rounded-2xl bg-white p-5 shadow-xl"><h2 className="font-bold">{ar?'مهمة متابعة':'Follow-up task'}</h2><input required value={task.title} onChange={e=>setTask({...task,title:e.target.value})} className={fieldClass}/><textarea rows={3} value={task.description} onChange={e=>setTask({...task,description:e.target.value})} className={fieldClass}/><select required value={task.assigned_to} onChange={e=>setTask({...task,assigned_to:e.target.value})} className={fieldClass}><option value="">{ar?'اختر المكلف...':'Choose assignee...'}</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><input type="date" value={task.due_date} onChange={e=>setTask({...task,due_date:e.target.value})} className={fieldClass}/><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setTaskOpen(false)}>{ar?'إلغاء':'Cancel'}</Button><Button type="submit" isLoading={createTask.isPending}>{ar?'إنشاء':'Create'}</Button></div></form></div>}</div>;
}
