import { useRef, useState, type FormEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, ArrowLeft, ArrowRight, CheckCircle2, ChevronDown, ChevronUp, Download, Forward, ListChecks, Paperclip, Reply, RotateCcw, Send, Trash2 } from 'lucide-react';
import { apiFetch, apiUrl, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { Button } from '@/components/ui/Button';
import { ErrorState } from '@/components/ui/ErrorState';
import { LoadingState } from '@/components/ui/LoadingState';

type UserOption = { id: number; name: string; email: string; person?: { full_name_ar?: string; full_name_en?: string } };
type Transition = { id: number; from_state?: string | null; to_state: string; reason?: string | null; created_at: string; user?: UserOption | null };
type Attachment = { id: number; uploaded_by?: number | null; original_name: string; file_size: number; created_at: string; uploader?: UserOption | null };
type Message = { id: number; sender_id: number; body: string; created_at: string; sender?: UserOption | null };
type Item = { id: number; reference_number: string; subject: string; summary?: string | null; priority: string; status: string; correspondence_date: string; response_due_date?: string | null; sender_id: number; assigned_to?: number | null; sender?: UserOption | null; assignee?: UserOption | null; transitions?: Transition[]; attachments?: Attachment[]; messages?: Message[] };
const fieldClass = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-100';

export function CorrespondenceDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const qc = useQueryClient();
  const { user, can } = useAuth(); const { locale, t } = useI18n(); const ar = locale === 'ar';
  const fileInput = useRef<HTMLInputElement>(null);
  const [reply, setReply] = useState(''); const [assignee, setAssignee] = useState(''); const [notes, setNotes] = useState('');
  const [error, setError] = useState(''); const [advanced, setAdvanced] = useState(false); const [attachment, setAttachment] = useState<File | null>(null); const [taskOpen, setTaskOpen] = useState(false);
  const [task, setTask] = useState({ title: '', description: '', assigned_to: '', due_date: '', priority: 'normal' });
  const { data: item, isLoading, isError, refetch } = useQuery({ queryKey: ['correspondence', id], queryFn: () => apiFetch<Item>(`/correspondence/${id}`), enabled: Boolean(id) });
  const { data: users = [] } = useQuery({ queryKey: ['users-lookup', 'correspondence'], queryFn: () => apiFetch<UserOption[]>('/users/lookup?purpose=correspondence'), enabled: Boolean(item) });
  const recipientOptions = Array.isArray(users) ? users : [];
  const refresh = async () => { await qc.invalidateQueries({ queryKey: ['correspondence', id] }); await qc.invalidateQueries({ queryKey: ['correspondence-mailbox'] }); };
  const fail = (fallback: string) => (value: unknown) => setError(value instanceof ApiError ? value.message : fallback);
  const action = useMutation({ mutationFn: ({ name, body }: { name: string; body?: object }) => apiFetch(`/correspondence/${id}/${name}`, { method: 'POST', body }), onSuccess: async () => { setError(''); setNotes(''); setAssignee(''); await refresh(); }, onError: fail(ar ? 'تعذر تنفيذ الإجراء.' : 'Action failed.') });
  const sendReply = useMutation({ mutationFn: () => apiFetch(`/correspondence/${id}/messages`, { method: 'POST', body: { body: reply.trim() } }), onSuccess: async () => { setReply(''); setError(''); await refresh(); }, onError: fail(ar ? 'تعذر إرسال الرد.' : 'Unable to send reply.') });
  const upload = useMutation({ mutationFn: () => { const body = new FormData(); if (attachment) body.append('file', attachment); return apiFetch(`/correspondence/${id}/attachments`, { method: 'POST', body }); }, onSuccess: async () => { setAttachment(null); if (fileInput.current) fileInput.current.value = ''; await refresh(); }, onError: fail(ar ? 'تعذر رفع المرفق.' : 'Unable to upload attachment.') });
  const removeAttachment = useMutation({ mutationFn: (attachmentId: number) => apiFetch(`/correspondence/${id}/attachments/${attachmentId}`, { method: 'DELETE' }), onSuccess: refresh, onError: fail(ar ? 'تعذر حذف المرفق.' : 'Unable to delete attachment.') });
  const createTask = useMutation({ mutationFn: () => apiFetch(`/correspondence/${id}/tasks`, { method: 'POST', body: { ...task, assigned_to: Number(task.assigned_to), due_date: task.due_date || null } }), onSuccess: async () => { setTaskOpen(false); await qc.invalidateQueries({ queryKey: ['operational-tasks'] }); }, onError: fail(ar ? 'تعذر إنشاء المهمة.' : 'Unable to create task.') });

  if (!can('correspondence.view')) return <ErrorState title={t('state.forbidden.title')} message={t('state.forbidden.message')} />;
  if (isLoading) return <LoadingState />;
  if (isError || !item) return <ErrorState onRetry={() => refetch()} />;

  const isSender = item.sender_id === user?.id; const isAssignee = item.assigned_to === user?.id; const active = ['submitted', 'under_review'].includes(item.status);
  const nameOf = (value?: UserOption | null) => (ar ? value?.person?.full_name_ar : value?.person?.full_name_en) || value?.name || value?.email || '—';
  const initials = (value?: UserOption | null) => nameOf(value).split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase();
  const formatDate = (value?: string | null, withTime = false) => value ? new Intl.DateTimeFormat(locale, { year: 'numeric', month: 'short', day: 'numeric', ...(withTime ? { hour: 'numeric', minute: '2-digit' } : {}) }).format(new Date(value)) : '—';
  const statusLabel = ({ draft: ar ? 'مسودة' : 'Draft', submitted: ar ? 'مرسلة' : 'Sent', under_review: ar ? 'قيد المتابعة' : 'In progress', returned: ar ? 'معادة' : 'Returned', approved: ar ? 'مكتملة' : 'Completed', closed: ar ? 'مؤرشفة' : 'Archived' } as Record<string, string>)[item.status] || item.status;
  const run = (name: string, body?: object) => { setError(''); action.mutate({ name, body }); };
  const conversation = [{ id: 0, sender_id: item.sender_id, body: item.summary || '', created_at: item.correspondence_date, sender: item.sender }, ...(Array.isArray(item.messages) ? item.messages : [])];

  return <div className="mx-auto max-w-[1050px] space-y-4 pb-10">
    <div className="flex items-center justify-between gap-3"><button onClick={() => navigate(-1)} className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-teal-50 hover:text-teal-700">{ar ? <ArrowRight className="h-4 w-4" /> : <ArrowLeft className="h-4 w-4" />}{ar ? 'العودة للبريد' : 'Back to mail'}</button><span className="text-xs font-semibold text-slate-400">{item.reference_number}</span></div>

    <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <header className="border-b border-slate-100 p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h1 className="text-xl font-bold text-slate-900 sm:text-2xl">{item.subject}</h1><div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="rounded-full bg-teal-50 px-2.5 py-1 font-semibold text-teal-700">{statusLabel}</span>{['urgent', 'critical'].includes(item.priority) && <span className="rounded-full bg-teal-50 px-2.5 py-1 font-semibold text-teal-700">{ar ? 'عاجل' : 'Urgent'}</span>}<span>{formatDate(item.correspondence_date)}</span>{item.response_due_date && <span>{ar ? 'الرد قبل:' : 'Reply by:'} {formatDate(item.response_due_date)}</span>}</div></div></div></header>
      <div className="divide-y divide-slate-100">{conversation.map((message, index) => <section key={message.id} className="p-5 sm:p-7"><div className="mb-4 flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-teal-50 text-xs font-bold text-teal-700">{initials(message.sender)}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="font-bold text-slate-800">{nameOf(message.sender)}</span>{index === 0 && <div className="mt-0.5 text-xs text-slate-400">{ar ? 'إلى' : 'to'} {nameOf(item.assignee)}</div>}</div><time className="text-xs text-slate-400">{formatDate(message.created_at, index > 0)}</time></div></div></div><p className="whitespace-pre-wrap text-sm leading-8 text-slate-700">{message.body || (ar ? 'لا يوجد نص.' : 'No message body.')}</p></section>)}</div>

      {item.status !== 'closed' && item.status !== 'draft' && <form onSubmit={(event: FormEvent) => { event.preventDefault(); sendReply.mutate(); }} className="border-t border-slate-100 bg-slate-50/40 p-5 sm:p-7"><div className="mb-2 flex items-center gap-2 font-bold text-slate-800"><Reply className="h-4 w-4 text-teal-600" />{ar ? 'رد' : 'Reply'}</div><textarea required rows={4} value={reply} onChange={event => setReply(event.target.value)} className={fieldClass} placeholder={ar ? 'اكتب ردك...' : 'Write a reply...'} /><div className="mt-3 flex justify-end"><Button type="submit" disabled={!reply.trim()} isLoading={sendReply.isPending}><Send className="me-2 h-4 w-4" />{ar ? 'إرسال الرد' : 'Send reply'}</Button></div></form>}
    </article>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-slate-800">{ar ? 'المرفقات' : 'Attachments'}</h2><p className="mt-1 text-xs text-slate-400">{ar ? 'PDF أو Word أو Excel أو صورة، بحد أقصى 10MB.' : 'PDF, Word, Excel, or image up to 10MB.'}</p></div>{item.status !== 'closed' && <><input ref={fileInput} type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg" onChange={event => setAttachment(event.target.files?.[0] || null)} /><Button type="button" variant="outline" onClick={() => fileInput.current?.click()}><Paperclip className="me-2 h-4 w-4" />{attachment?.name || (ar ? 'اختيار ملف' : 'Choose file')}</Button></>}</div>{attachment && <div className="mt-3 flex justify-end"><Button size="sm" onClick={() => upload.mutate()} isLoading={upload.isPending}>{ar ? 'رفع المرفق' : 'Upload'}</Button></div>}{item.attachments?.length ? <div className="mt-4 divide-y divide-slate-100">{item.attachments.map(file => <div key={file.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><div className="truncate text-sm font-semibold text-slate-700">{file.original_name}</div><div className="mt-1 text-xs text-slate-400">{Math.max(1, Math.round(file.file_size / 1024))} KB · {nameOf(file.uploader)}</div></div><div className="flex"><a href={apiUrl(`/correspondence/${item.id}/attachments/${file.id}/download`)} className="rounded-lg p-2 text-teal-700 hover:bg-teal-50" title={ar ? 'تنزيل' : 'Download'}><Download className="h-4 w-4" /></a>{(file.uploaded_by === user?.id || can('correspondence.close')) && <button onClick={() => removeAttachment.mutate(file.id)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button>}</div></div>)}</div> : <p className="mt-4 text-sm text-slate-400">{ar ? 'لا توجد مرفقات.' : 'No attachments.'}</p>}</section>

    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><button onClick={() => setAdvanced(!advanced)} className="flex w-full items-center justify-between p-5 text-start"><div><h2 className="font-bold text-slate-800">{ar ? 'خيارات المتابعة الإدارية' : 'Administrative options'}</h2><p className="mt-1 text-xs text-slate-400">{ar ? 'التحويل والاعتماد والأرشفة وسجل الحركة.' : 'Forwarding, approval, archiving, and activity history.'}</p></div>{advanced ? <ChevronUp className="h-5 w-5 text-teal-600" /> : <ChevronDown className="h-5 w-5 text-teal-600" />}</button>{advanced && <div className="space-y-5 border-t border-slate-100 p-5">
      {error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      {(active || item.status === 'draft' || item.status === 'returned' || item.status === 'approved') && <div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select value={assignee} onChange={event => setAssignee(event.target.value)} className={fieldClass}><option value="">{ar ? 'اختر مستلمًا أو شخصًا للتحويل...' : 'Choose recipient...'}</option>{recipientOptions.filter(option => option.id !== user?.id).map(option => <option key={option.id} value={option.id}>{nameOf(option)} — {option.email}</option>)}</select><input value={notes} onChange={event => setNotes(event.target.value)} className={fieldClass} placeholder={ar ? 'ملاحظة اختيارية...' : 'Optional note...'} /><div className="flex flex-wrap gap-2">{['draft', 'returned'].includes(item.status) && isSender && can('correspondence.submit') && <Button disabled={!assignee} onClick={() => run('submit', { assigned_to: Number(assignee), notes })}><Send className="me-1 h-4 w-4" />{ar ? 'إرسال' : 'Send'}</Button>}{active && (isAssignee || can('correspondence.approve')) && can('correspondence.forward') && <Button disabled={!assignee} onClick={() => run('forward', { assigned_to: Number(assignee), notes })}><Forward className="me-1 h-4 w-4" />{ar ? 'تحويل' : 'Forward'}</Button>}{active && (isAssignee || can('correspondence.approve')) && <Button variant="outline" disabled={!notes.trim()} onClick={() => run('return', { reason: notes })}><RotateCcw className="me-1 h-4 w-4" />{ar ? 'إعادة للمرسل' : 'Return'}</Button>}{active && can('correspondence.approve') && <Button onClick={() => run('approve')}><CheckCircle2 className="me-1 h-4 w-4" />{ar ? 'إكمال' : 'Complete'}</Button>}{['approved', 'submitted', 'under_review'].includes(item.status) && can('correspondence.close') && <Button variant="outline" onClick={() => run('close', { notes })}><Archive className="me-1 h-4 w-4" />{ar ? 'أرشفة' : 'Archive'}</Button>}</div></div>}
      {can('tasks.manage') && <Button variant="secondary" onClick={() => { setTaskOpen(true); setTask({ ...task, title: item.subject }); }}><ListChecks className="me-2 h-4 w-4" />{ar ? 'إنشاء مهمة من الرسالة' : 'Create task from message'}</Button>}
      <div><h3 className="mb-3 text-sm font-bold text-slate-700">{ar ? 'سجل الحركة' : 'Activity'}</h3>{!item.transitions?.length ? <p className="text-sm text-slate-400">{ar ? 'لا توجد حركات.' : 'No activity.'}</p> : <ol className="space-y-3">{item.transitions.map(transition => <li key={transition.id} className="flex gap-3 text-xs"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-teal-500" /><div><div className="font-semibold text-slate-700">{nameOf(transition.user)} · {formatDate(transition.created_at, true)}</div>{transition.reason && <p className="mt-1 text-slate-500">{transition.reason}</p>}</div></li>)}</ol>}</div>
    </div>}</section>

    {taskOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/25 p-4 backdrop-blur-sm"><form onSubmit={(event: FormEvent) => { event.preventDefault(); createTask.mutate(); }} className="w-full max-w-xl space-y-4 rounded-2xl bg-white p-5 shadow-xl"><h2 className="font-bold text-slate-800">{ar ? 'مهمة متابعة' : 'Follow-up task'}</h2><input required value={task.title} onChange={event => setTask({ ...task, title: event.target.value })} className={fieldClass} placeholder={ar ? 'عنوان المهمة' : 'Task title'} /><textarea rows={3} value={task.description} onChange={event => setTask({ ...task, description: event.target.value })} className={fieldClass} placeholder={ar ? 'التفاصيل' : 'Details'} /><select required value={task.assigned_to} onChange={event => setTask({ ...task, assigned_to: event.target.value })} className={fieldClass}><option value="">{ar ? 'اختر المكلف...' : 'Choose assignee...'}</option>{recipientOptions.map(option => <option key={option.id} value={option.id}>{nameOf(option)}</option>)}</select><input type="date" value={task.due_date} onChange={event => setTask({ ...task, due_date: event.target.value })} className={fieldClass} /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setTaskOpen(false)}>{ar ? 'إلغاء' : 'Cancel'}</Button><Button type="submit" isLoading={createTask.isPending}>{ar ? 'إنشاء' : 'Create'}</Button></div></form></div>}
  </div>;
}
