import { useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, ArrowLeft, ArrowRight, ChevronDown, Download, Forward, MailOpen, Paperclip, Printer, Reply, Send, Star, Trash2, X } from 'lucide-react';
import { apiFetch, apiUrl, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { Button } from '@/components/ui/Button';
import { ErrorState } from '@/components/ui/ErrorState';
import { LoadingState } from '@/components/ui/LoadingState';

type UserOption = { id: number; name: string; email: string; person?: { full_name_ar?: string; full_name_en?: string } };
type Participant = { id: number; user_id: number; participant_role: string; starred_at?: string|null; archived_at?: string|null; user?: UserOption };
type Attachment = { id: number; uploaded_by?: number|null; original_name: string; file_size: number };
type Message = { id: number; sender_id: number; body: string; created_at: string; sender?: UserOption|null };
type Item = { id:number; reference_number:string; subject:string; summary?:string|null; status:string; submitted_at?:string|null; sender_id:number; sender?:UserOption|null; participants:Participant[]; attachments:Attachment[]; messages:Message[] };
const fieldClass = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-teal-400 focus:ring-2 focus:ring-teal-100';

function DraftEditor({ item, users, ar, onDone }: { item:Item; users:UserOption[]; ar:boolean; onDone:()=>Promise<void> }) {
  const current = (role:string) => item.participants.filter(participant => participant.participant_role === role).map(participant => participant.user_id);
  const [form, setForm] = useState({ subject:item.subject, body:item.summary || '', to:current('to'), cc:current('cc'), fyi:current('fyi') });
  const [error, setError] = useState('');
  const request = useMutation({ mutationFn:(send:boolean) => apiFetch(`/correspondence/${item.id}${send ? '/submit' : ''}`, { method:send ? 'POST' : 'PUT', body:{ ...form, message_type:'message', priority:'normal', confidentiality:'normal', response_due_date:null } }), onSuccess:onDone, onError:value => setError(value instanceof ApiError ? value.message : (ar ? 'تعذر حفظ المسودة.' : 'Unable to save draft.')) });
  const values = (event:ChangeEvent<HTMLSelectElement>) => Array.from(event.target.selectedOptions).map(option => Number(option.value));
  return <form onSubmit={event => { event.preventDefault(); request.mutate(true); }} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
    <div className="border-b border-teal-100 bg-teal-50 px-5 py-3 text-sm font-bold text-teal-950">{ar ? 'تعديل المسودة' : 'Edit draft'}</div>
    <div className="space-y-3 p-5"><label className="block text-xs text-slate-500">{ar ? 'إلى' : 'To'}<select multiple value={form.to.map(String)} onChange={event => setForm({ ...form, to:values(event) })} className={`${fieldClass} mt-1 h-24`}>{users.map(user => <option key={user.id} value={user.id}>{user.name} — {user.email}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">CC<select multiple value={form.cc.map(String)} onChange={event => setForm({ ...form, cc:values(event) })} className={`${fieldClass} mt-1 h-20`}>{users.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label className="text-xs text-slate-500">BCC<select multiple value={form.fyi.map(String)} onChange={event => setForm({ ...form, fyi:values(event) })} className={`${fieldClass} mt-1 h-20`}>{users.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label></div><input required value={form.subject} onChange={event => setForm({ ...form, subject:event.target.value })} className={fieldClass} placeholder={ar ? 'الموضوع' : 'Subject'}/><textarea rows={10} value={form.body} onChange={event => setForm({ ...form, body:event.target.value })} className={fieldClass} placeholder={ar ? 'اكتب رسالتك...' : 'Write your message...'}/>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => request.mutate(false)} isLoading={request.isPending}>{ar ? 'حفظ' : 'Save'}</Button><Button type="submit" disabled={!form.to.length} isLoading={request.isPending}><Send className="me-2 h-4 w-4"/>{ar ? 'إرسال' : 'Send'}</Button></div></div>
  </form>;
}

export function CorrespondenceDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const qc = useQueryClient(); const { user, can } = useAuth(); const { locale, t } = useI18n(); const ar = locale === 'ar';
  const [reply, setReply] = useState(''); const [error, setError] = useState(''); const [files, setFiles] = useState<File[]>([]); const fileInput = useRef<HTMLInputElement>(null); const [forwardOpen, setForwardOpen] = useState(false); const [forwardTo, setForwardTo] = useState(''); const [forwardBody, setForwardBody] = useState('');
  const itemQuery = useQuery({ queryKey:['correspondence', id], queryFn:() => apiFetch<Item>(`/correspondence/${id}`), enabled:Boolean(id), refetchInterval:8_000, refetchOnWindowFocus:true });
  const usersQuery = useQuery({ queryKey:['users-lookup','correspondence'], queryFn:() => apiFetch<UserOption[]>('/users/lookup?purpose=correspondence'), enabled:Boolean(itemQuery.data) });
  const item = itemQuery.data; const users = Array.isArray(usersQuery.data) ? usersQuery.data : [];
  const refresh = async () => { await qc.invalidateQueries({ queryKey:['correspondence', id] }); await qc.invalidateQueries({ queryKey:['correspondence-mailbox'] }); };
  const fail = (fallback:string) => (value:unknown) => setError(value instanceof ApiError ? value.message : fallback);
  const uploadMutation = useMutation({ mutationFn:(selected:File[]) => { const body = new FormData(); selected.forEach(file => body.append('files[]', file)); return apiFetch(`/correspondence/${id}/attachments`, { method:'POST', body }); }, onSuccess:async () => { setFiles([]); if (fileInput.current) fileInput.current.value = ''; await refresh(); }, onError:fail(ar ? 'تعذر رفع المرفقات.' : 'Unable to upload attachments.') });
  const uploadSelected = async () => { if (files.length) await uploadMutation.mutateAsync(files); };
  const replyMutation = useMutation({ mutationFn:() => apiFetch(`/correspondence/${id}/messages`, { method:'POST', body:{ body:reply.trim() } }), onSuccess:async () => { setReply(''); setError(''); await uploadSelected(); await refresh(); }, onError:fail(ar ? 'تعذر إرسال الرد.' : 'Unable to send reply.') });
  const stateMutation = useMutation({ mutationFn:(action:string) => apiFetch(`/correspondence/${id}/mailbox/${action}`, { method:'POST' }), onSuccess:refresh, onError:fail(ar ? 'تعذر تحديث الرسالة.' : 'Unable to update message.') });
  const removeAttachment = useMutation({ mutationFn:(attachmentId:number) => apiFetch(`/correspondence/${id}/attachments/${attachmentId}`, { method:'DELETE' }), onSuccess:refresh, onError:fail(ar ? 'تعذر حذف المرفق.' : 'Unable to delete attachment.') });
  const forwardMutation = useMutation({ mutationFn:() => apiFetch(`/correspondence/${id}/forward`, { method:'POST', body:{ to:[Number(forwardTo)], body:forwardBody } }), onSuccess:async () => { setForwardOpen(false); setForwardTo(''); setForwardBody(''); await refresh(); }, onError:fail(ar ? 'تعذرت إعادة التوجيه.' : 'Unable to forward.') });
  if (!can('correspondence.view')) return <ErrorState title={t('state.forbidden.title')} message={t('state.forbidden.message')}/>;
  if (itemQuery.isLoading) return <LoadingState/>; if (itemQuery.isError || !item) return <ErrorState onRetry={() => itemQuery.refetch()}/>;
  const nameOf = (value?:UserOption|null) => (ar ? value?.person?.full_name_ar : value?.person?.full_name_en) || value?.name || value?.email || '—';
  const formatDate = (value?:string|null) => value ? new Intl.DateTimeFormat(locale, { year:'numeric', month:'short', day:'numeric', hour:'numeric', minute:'2-digit' }).format(new Date(value)) : '—';
  const me = item.participants.find(participant => participant.user_id === user?.id);
  const recipients = (role:string) => item.participants.filter(participant => participant.participant_role === role).map(participant => nameOf(participant.user)).join('، ');
  const conversation = [{ id:0, body:item.summary || '', created_at:item.submitted_at || '', sender:item.sender }, ...(item.messages || [])];
  const iconButton = 'rounded-full p-2 text-slate-500 transition hover:bg-slate-100 hover:text-slate-800';
  if (item.status === 'draft') return <div className="mx-auto max-w-[900px] space-y-4 pb-8"><button onClick={() => navigate(-1)} className="inline-flex items-center gap-2 px-2 py-2 text-sm font-semibold text-slate-600">{ar ? <ArrowRight className="h-4 w-4"/> : <ArrowLeft className="h-4 w-4"/>}{ar ? 'العودة للمسودات' : 'Back to drafts'}</button><DraftEditor item={item} users={users} ar={ar} onDone={refresh}/></div>;
  return <div className="mx-auto max-w-[1080px] pb-8">
    <div className="mb-3 flex items-center gap-1 border-b border-slate-200 pb-3"><button onClick={() => navigate(-1)} className={iconButton} title={ar ? 'العودة' : 'Back'}>{ar ? <ArrowRight className="h-5 w-5"/> : <ArrowLeft className="h-5 w-5"/>}</button><span className="mx-1 h-6 w-px bg-slate-200"/><button className={iconButton} onClick={() => stateMutation.mutate(me?.archived_at ? 'restore' : 'archive')} title={ar ? 'أرشفة' : 'Archive'}><Archive className="h-5 w-5"/></button><button className={iconButton} onClick={() => stateMutation.mutate('unread')} title={ar ? 'كغير مقروءة' : 'Mark unread'}><MailOpen className="h-5 w-5"/></button><button className={iconButton} onClick={() => stateMutation.mutate(me?.starred_at ? 'unstar' : 'star')} title={ar ? 'تمييز' : 'Star'}><Star className={`h-5 w-5 ${me?.starred_at ? 'fill-amber-400 text-amber-400' : ''}`}/></button><a className={iconButton} href={apiUrl(`/correspondence/${item.id}/print?locale=${locale}`)} title={ar ? 'طباعة PDF' : 'Print PDF'}><Printer className="h-5 w-5"/></a><span className="ms-auto text-xs text-slate-400" dir="ltr">{item.reference_number}</span></div>
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
      <div className="flex items-start gap-3 border-b border-slate-100 px-5 py-5"><h1 className="min-w-0 flex-1 text-xl font-bold text-slate-950 sm:text-2xl">{item.subject}</h1></div>
      <div className="divide-y divide-slate-100">{conversation.map((message, index) => <article key={`${message.id}-${index}`} className="px-5 py-5 sm:px-7"><div className="mb-4 flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-teal-100 text-sm font-bold text-teal-800">{nameOf(message.sender).slice(0,1)}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><strong className="text-sm text-slate-900">{nameOf(message.sender)}</strong><span className="ms-2 text-xs text-slate-400" dir="ltr">&lt;{message.sender?.email}&gt;</span></div><time className="text-xs text-slate-400">{formatDate(message.created_at)}</time></div>{index === 0 && <details className="mt-1 text-xs text-slate-500"><summary className="inline-flex cursor-pointer list-none items-center gap-1">{ar ? 'إلى المستلمين' : 'to recipients'}<ChevronDown className="h-3 w-3"/></summary><div className="mt-2 grid max-w-2xl grid-cols-[45px_1fr] gap-1 rounded-lg bg-slate-50 p-3"><strong>{ar ? 'إلى' : 'To'}</strong><span>{recipients('to') || '—'}</span>{recipients('cc') && <><strong>CC</strong><span>{recipients('cc')}</span></>}{recipients('fyi') && <><strong>BCC</strong><span>{recipients('fyi')}</span></>}</div></details>}</div></div><div className="text-sm leading-8 text-slate-700 [&_a]:font-medium [&_a]:text-blue-600 [&_a]:underline [&_a]:underline-offset-2" dangerouslySetInnerHTML={{ __html:message.body || (ar ? 'بدون محتوى.' : 'No content.') }}/></article>)}</div>
      {item.attachments?.length > 0 && <div className="border-t border-slate-100 px-5 py-4 sm:px-7"><div className="mb-2 flex items-center gap-2 text-sm font-bold text-slate-700"><Paperclip className="h-4 w-4"/>{ar ? 'المرفقات' : 'Attachments'} ({item.attachments.length})</div><div className="flex flex-wrap gap-2">{item.attachments.map(file => <div key={file.id} className="flex max-w-full items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2"><div className="min-w-0"><div className="max-w-56 truncate text-xs font-semibold text-slate-700">{file.original_name}</div><div className="text-[10px] text-slate-400">{Math.max(1, Math.round(file.file_size / 1024))} KB</div></div><a href={apiUrl(`/correspondence/${item.id}/attachments/${file.id}/download`)} className={iconButton}><Download className="h-4 w-4"/></a>{(file.uploaded_by === user?.id || item.sender_id === user?.id) && <button onClick={() => removeAttachment.mutate(file.id)} className={`${iconButton} hover:text-red-600`}><Trash2 className="h-4 w-4"/></button>}</div>)}</div></div>}
      <form onSubmit={(event:FormEvent) => { event.preventDefault(); replyMutation.mutate(); }} className="border-t border-slate-200 p-5 sm:px-7"><div className="rounded-xl border border-slate-200 focus-within:border-teal-400 focus-within:ring-2 focus-within:ring-teal-100"><div className="flex items-center gap-2 border-b border-slate-100 px-4 py-2 text-sm font-semibold text-slate-700"><Reply className="h-4 w-4 text-teal-600"/>{ar ? 'الرد على الجميع' : 'Reply all'}</div><textarea required rows={4} value={reply} onChange={event => setReply(event.target.value)} className="w-full resize-y border-0 px-4 py-3 text-sm outline-none" placeholder={ar ? 'اكتب ردك...' : 'Write a reply...'}/><div className="flex items-center gap-2 border-t border-slate-100 px-3 py-2"><Button type="submit" disabled={!reply.trim()} isLoading={replyMutation.isPending}><Send className="me-2 h-4 w-4"/>{ar ? 'إرسال' : 'Send'}</Button><input ref={fileInput} multiple type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.png,.jpg,.jpeg" onChange={event => setFiles(Array.from(event.target.files || []))}/><button type="button" className={iconButton} onClick={() => fileInput.current?.click()} title={ar ? 'إرفاق ملفات' : 'Attach files'}><Paperclip className="h-4 w-4"/></button>{files.length > 0 && <span className="text-xs text-teal-700">{ar ? `${files.length} ملفات` : `${files.length} files`}</span>}<button type="button" className={`${iconButton} ms-auto`} onClick={() => setForwardOpen(true)} title={ar ? 'إعادة توجيه' : 'Forward'}><Forward className="h-4 w-4"/></button></div></div></form>
    </div>{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {forwardOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-4"><form onSubmit={event => { event.preventDefault(); forwardMutation.mutate(); }} className="w-full max-w-lg overflow-hidden rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-teal-100 bg-teal-50 px-5 py-3"><h2 className="font-bold text-teal-950">{ar ? 'إعادة توجيه الرسالة' : 'Forward message'}</h2><button type="button" onClick={() => setForwardOpen(false)}><X className="h-5 w-5"/></button></div><div className="space-y-3 p-5"><select required value={forwardTo} onChange={event => setForwardTo(event.target.value)} className={fieldClass}><option value="">{ar ? 'اختر المستلم...' : 'Choose recipient...'}</option>{users.filter(option => !item.participants.some(participant => participant.user_id === option.id)).map(option => <option key={option.id} value={option.id}>{option.name} — {option.email}</option>)}</select><textarea rows={4} value={forwardBody} onChange={event => setForwardBody(event.target.value)} className={fieldClass} placeholder={ar ? 'ملاحظة اختيارية' : 'Optional note'}/><div className="flex justify-end"><Button type="submit" disabled={!forwardTo} isLoading={forwardMutation.isPending}>{ar ? 'إعادة توجيه' : 'Forward'}</Button></div></div></form></div>}
  </div>;
}
