import { useEffect, useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, Clock3, FileCheck2, History, ListChecks, MapPin, Pencil, Plus, Printer, RotateCcw, Trash2, UserRound, Users } from 'lucide-react';
import { apiFetch, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { Button } from '@/components/ui/Button';
import { ConfirmDialog, Modal } from '@/components/ui/Modal';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { LoadingState } from '@/components/ui/LoadingState';

type UserOption={id:number;name:string;email:string;person?:{full_name_ar?:string;full_name_en?:string}};
type ActionItem={id:number;item_type:'decision'|'recommendation'|'task';description:string;responsible?:string|null;assigned_to?:number|null;assignee?:UserOption|null;executing_entity?:string|null;priority:string;due_date?:string|null;status:string;notes?:string|null;completion_evidence?:string|null;operational_task_id?:number|null};
type Transition={id:number;from_state:string;to_state:string;reason?:string|null;created_at:string;user?:UserOption|null};
type Meeting={id:number;minutes_number:string;meeting_type:string;status:string;meeting_date:string;meeting_time?:string|null;location?:string|null;chairperson?:string|null;attendees?:string|null;absentees?:string|null;agenda?:string|null;discussion_summary?:string|null;decisions_summary?:string|null;implementation_owner?:string|null;approved_at?:string|null;approver?:UserOption|null;action_items:ActionItem[];transitions?:Transition[]};
type Tab='minutes'|'outputs'|'history';
const input='w-full rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-bold text-slate-800 outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100';
const blankAction={item_type:'task' as ActionItem['item_type'],description:'',assigned_to:'',responsible:'',executing_entity:'',priority:'normal',due_date:'',notes:''};
const steps=['draft','scheduled','held','minutes_draft','approved'];

export function MeetingDetailsPage(){
  const {id}=useParams();const {can}=useAuth();const {locale,t}=useI18n();const ar=locale==='ar';const qc=useQueryClient();
  const [tab,setTab]=useState<Tab>('minutes');const [editOpen,setEditOpen]=useState(false);const [actionOpen,setActionOpen]=useState(false);const [editingAction,setEditingAction]=useState<ActionItem|null>(null);const [deleteId,setDeleteId]=useState<number|null>(null);const [cancelOpen,setCancelOpen]=useState(false);const [error,setError]=useState('');
  const [editForm,setEditForm]=useState({meeting_type:'',meeting_date:'',meeting_time:'',location:'',chairperson:'',attendees:'',absentees:'',agenda:'',discussion_summary:'',decisions_summary:'',implementation_owner:''});
  const [actionForm,setActionForm]=useState(blankAction);
  const query=useQuery({queryKey:['meeting',id],queryFn:()=>apiFetch<Meeting>(`/meetings/${id}`),enabled:Boolean(id)});
  const users=useQuery({queryKey:['users-lookup'],queryFn:()=>apiFetch<UserOption[]>('/users/lookup'),enabled:actionOpen});
  useEffect(()=>{const m=query.data;if(m)setEditForm({meeting_type:m.meeting_type,meeting_date:m.meeting_date?.slice(0,10)||'',meeting_time:m.meeting_time?.slice(0,5)||'',location:m.location||'',chairperson:m.chairperson||'',attendees:m.attendees||'',absentees:m.absentees||'',agenda:m.agenda||'',discussion_summary:m.discussion_summary||'',decisions_summary:m.decisions_summary||'',implementation_owner:m.implementation_owner||''})},[query.data]);
  const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['meeting',id]}),qc.invalidateQueries({queryKey:['meetings']}),qc.invalidateQueries({queryKey:['operational-tasks']})])};
  const fail=(e:unknown)=>setError(e instanceof ApiError?e.message:(ar?'تعذر تنفيذ الإجراء.':'Action failed.'));
  const update=useMutation({mutationFn:()=>apiFetch(`/meetings/${id}`,{method:'PUT',body:{...editForm,meeting_time:editForm.meeting_time||null,location:editForm.location||null,chairperson:editForm.chairperson||null}}),onSuccess:async()=>{setEditOpen(false);setError('');await refresh()},onError:fail});
  const statusChange=useMutation({mutationFn:(status:string)=>apiFetch(`/meetings/${id}/status`,{method:'POST',body:{status}}),onSuccess:refresh,onError:fail});
  const approval=useMutation({mutationFn:(action:'approve'|'reopen')=>apiFetch(`/meetings/${id}/${action}`,{method:'POST'}),onSuccess:refresh,onError:fail});
  const saveAction=useMutation({mutationFn:()=>apiFetch(`/meetings/${id}/actions${editingAction?`/${editingAction.id}`:''}`,{method:editingAction?'PUT':'POST',body:{...actionForm,assigned_to:actionForm.assigned_to?Number(actionForm.assigned_to):null,due_date:actionForm.due_date||null}}),onSuccess:async()=>{setActionOpen(false);setEditingAction(null);setActionForm(blankAction);setError('');await refresh()},onError:fail});
  const removeAction=useMutation({mutationFn:(actionId:number)=>apiFetch(`/meetings/${id}/actions/${actionId}`,{method:'DELETE'}),onSuccess:async()=>{setDeleteId(null);await refresh()},onError:fail});
  if(!can('meetings.manage'))return <ErrorState title={t('state.forbidden.title')} message={t('state.forbidden.message')}/>;if(query.isLoading)return <LoadingState/>;if(query.isError||!query.data)return <ErrorState onRetry={()=>query.refetch()}/>;
  const m=query.data;const locked=m.status==='approved';const nameOf=(u?:UserOption|null)=>(ar?u?.person?.full_name_ar:u?.person?.full_name_en)||u?.name||u?.email||'—';
  const state=(v:string)=>({draft:ar?'مسودة':'Draft',scheduled:ar?'مجدول':'Scheduled',held:ar?'تم الانعقاد':'Held',minutes_draft:ar?'المحضر قيد الإعداد':'Minutes draft',approved:ar?'محضر معتمد':'Approved',cancelled:ar?'ملغي':'Cancelled'}[v]||v);
  const type=(v:string)=>({task:ar?'مهمة':'Task',decision:ar?'قرار':'Decision',recommendation:ar?'توصية':'Recommendation'}[v]||v);
  const priority=(v:string)=>({low:ar?'منخفضة':'Low',normal:ar?'عادية':'Normal',high:ar?'عالية':'High'}[v]||v);
  const taskState=(v:string)=>({open:ar?'مفتوحة':'Open',in_progress:ar?'قيد التنفيذ':'In progress',completed:ar?'منجزة':'Completed',cancelled:ar?'ملغاة':'Cancelled'}[v]||v);
  const openAction=(item?:ActionItem)=>{setEditingAction(item||null);setActionForm(item?{item_type:item.item_type,description:item.description,assigned_to:item.assigned_to?String(item.assigned_to):'',responsible:item.responsible||'',executing_entity:item.executing_entity||'',priority:item.priority,due_date:item.due_date?.slice(0,10)||'',notes:item.notes||''}:blankAction);setActionOpen(true)};
  const nextButton=()=>{if(m.status==='draft')return <Button isLoading={statusChange.isPending} onClick={()=>statusChange.mutate('scheduled')}>{ar?'جدولة الاجتماع':'Schedule meeting'}</Button>;if(m.status==='scheduled')return <Button isLoading={statusChange.isPending} onClick={()=>statusChange.mutate('held')}>{ar?'تأكيد انعقاد الاجتماع':'Mark as held'}</Button>;if(m.status==='held')return <Button isLoading={statusChange.isPending} onClick={()=>statusChange.mutate('minutes_draft')}>{ar?'إرسال المحضر للاعتماد':'Send minutes for approval'}</Button>;if(m.status==='minutes_draft'&&can('meetings.approve_minutes'))return <Button isLoading={approval.isPending} onClick={()=>approval.mutate('approve')}><FileCheck2 className="me-2 h-4 w-4"/>{ar?'اعتماد المحضر':'Approve minutes'}</Button>;return null};
  const activeStep=Math.max(0,steps.indexOf(m.status));const openCount=m.action_items.filter(x=>!['completed','cancelled'].includes(x.status)).length;
  return <div className="mx-auto max-w-7xl space-y-4 pb-14 print:max-w-none">
    <header className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><Link to="/meetings" className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-500 hover:text-teal-700">{ar?<ArrowRight className="h-4 w-4"/>:<ArrowLeft className="h-4 w-4"/>}{ar?'العودة للاجتماعات':'Back to meetings'}</Link><div className="mt-3 flex flex-wrap items-center gap-2"><h1 className="text-lg font-black text-slate-950 sm:text-xl">{m.meeting_type}</h1><span className="rounded-full bg-teal-50 px-2.5 py-1 text-[10px] font-black text-teal-700">{state(m.status)}</span></div><p className="mt-1 font-mono text-[10px] font-bold text-slate-400">{m.minutes_number}</p></div><div className="flex flex-wrap gap-2 print:hidden"><Button variant="outline" onClick={()=>window.print()}><Printer className="me-2 h-4 w-4"/>{ar?'طباعة':'Print'}</Button>{!locked&&m.status!=='cancelled'&&<Button variant="outline" onClick={()=>setEditOpen(true)}><Pencil className="me-2 h-4 w-4"/>{ar?'تحرير':'Edit'}</Button>}{['draft','scheduled'].includes(m.status)&&<Button variant="danger" onClick={()=>setCancelOpen(true)}>{ar?'إلغاء الاجتماع':'Cancel'}</Button>}{m.status==='cancelled'&&<Button variant="outline" isLoading={statusChange.isPending} onClick={()=>statusChange.mutate('draft')}><RotateCcw className="me-2 h-4 w-4"/>{ar?'إعادة فتح كمسودة':'Restore draft'}</Button>}{locked&&can('meetings.approve_minutes')&&<Button variant="outline" isLoading={approval.isPending} onClick={()=>approval.mutate('reopen')}><RotateCcw className="me-2 h-4 w-4"/>{ar?'إعادة فتح':'Reopen'}</Button>}{nextButton()}</div></div>
      {m.status!=='cancelled'&&<div className="mt-5 grid grid-cols-5 gap-1 border-t border-slate-100 pt-4">{steps.map((s,i)=><div key={s} className="text-center"><div className={`mx-auto h-1.5 rounded-full ${i<=activeStep?'bg-teal-600':'bg-slate-200'}`}/><span className={`mt-2 hidden text-[9px] font-bold sm:block ${i<=activeStep?'text-teal-700':'text-slate-400'}`}>{state(s)}</span></div>)}</div>}
    </header>
    {error&&<p className="rounded-2xl border border-rose-100 bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}
    <section className="flex flex-wrap items-center gap-x-6 gap-y-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-[11px] font-bold text-slate-600 shadow-sm"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-teal-600"/>{m.meeting_date.slice(0,10)}{m.meeting_time?` · ${m.meeting_time.slice(0,5)}`:''}</span><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-teal-600"/>{m.location||'—'}</span><span className="flex items-center gap-2"><UserRound className="h-4 w-4 text-teal-600"/>{m.chairperson||'—'}</span><span className="ms-auto rounded-lg bg-amber-50 px-2.5 py-1 text-amber-700">{openCount} {ar?'مخرج قيد المتابعة':'open outputs'}</span></section>
    <nav className="flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm print:hidden">{([{id:'minutes',label:ar?'المحضر':'Minutes',icon:FileCheck2},{id:'outputs',label:`${ar?'القرارات والتكليفات':'Outputs'} (${m.action_items.length})`,icon:ListChecks},{id:'history',label:ar?'سجل الإجراءات':'Activity',icon:History}] as const).map(x=><button key={x.id} onClick={()=>setTab(x.id)} className={`flex min-w-fit flex-1 items-center justify-center gap-2 rounded-xl px-3 py-2.5 text-xs font-black transition ${tab===x.id?'bg-teal-600 text-white shadow-sm':'text-slate-500 hover:bg-slate-50'}`}><x.icon className="h-4 w-4"/>{x.label}</button>)}</nav>
    {tab==='minutes'&&<section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="grid gap-4 lg:grid-cols-2"><Text title={ar?'جدول الأعمال':'Agenda'} value={m.agenda}/><Text title={ar?'ملخص النقاش':'Discussion summary'} value={m.discussion_summary}/><Text title={ar?'الحضور':'Attendees'} value={m.attendees}/><Text title={ar?'المعتذرون والغائبون':'Absentees'} value={m.absentees}/><Text title={ar?'خلاصة القرارات':'Decisions summary'} value={m.decisions_summary}/><Text title={ar?'مسؤول المتابعة العام':'Implementation owner'} value={m.implementation_owner}/></div>{m.approved_at&&<div className="mt-5 flex items-center gap-3 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-xs font-bold text-emerald-800"><CheckCircle2 className="h-5 w-5"/>{ar?'اعتمد المحضر بواسطة':'Approved by'} {nameOf(m.approver)} · {new Date(m.approved_at).toLocaleDateString(ar?'ar-PS':'en-GB')}</div>}</section>}
    {tab==='outputs'&&<section className="space-y-3"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-black text-slate-900">{ar?'مخرجات الاجتماع':'Meeting outputs'}</h2><p className="mt-1 text-[11px] font-bold text-slate-500">{ar?'المهمة المسندة لمستخدم تظهر تلقائيًا في شاشة مهامه.':'Assigned tasks appear automatically in the assignee workspace.'}</p></div>{!locked&&<Button onClick={()=>openAction()}><Plus className="me-2 h-4 w-4"/>{ar?'إضافة مخرج':'Add output'}</Button>}</div>{!m.action_items.length?<EmptyState message={ar?'لم تسجل قرارات أو تكليفات بعد.':'No outputs yet.'}/>:<div className="grid gap-3 lg:grid-cols-2">{m.action_items.map(item=><article key={item.id} className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-1.5"><Badge value={type(item.item_type)} tone="teal"/><Badge value={priority(item.priority)} tone={item.priority==='high'?'red':'slate'}/><Badge value={taskState(item.status)} tone={item.status==='completed'?'green':'amber'}/></div>{!locked&&<div className="flex gap-1"><button onClick={()=>openAction(item)} className="rounded-lg p-2 text-slate-400 hover:bg-teal-50 hover:text-teal-700"><Pencil className="h-4 w-4"/></button><button onClick={()=>setDeleteId(item.id)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></div>}</div><p className="mt-3 text-sm font-black leading-6 text-slate-800">{item.description}</p><div className="mt-3 space-y-1.5 border-t border-slate-100 pt-3 text-[11px] font-bold text-slate-500">{item.assigned_to&&<p><Users className="me-1 inline h-3.5 w-3.5 text-teal-600"/>{ar?'المكلف:':'Assignee:'} {nameOf(item.assignee)}</p>}{item.responsible&&<p>{ar?'المسؤول:':'Owner:'} {item.responsible}</p>}{item.executing_entity&&<p>{ar?'الجهة المنفذة:':'Entity:'} {item.executing_entity}</p>}{item.due_date&&<p className={item.status!=='completed'&&item.due_date.slice(0,10)<new Date().toISOString().slice(0,10)?'text-rose-600':''}><Clock3 className="me-1 inline h-3.5 w-3.5"/>{ar?'الموعد:':'Due:'} {item.due_date.slice(0,10)}</p>}{item.notes&&<p className="rounded-xl bg-slate-50 p-2 font-medium leading-5">{item.notes}</p>}</div></article>)}</div>}</section>}
    {tab==='history'&&<section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6">{!m.transitions?.length?<EmptyState message={ar?'لا توجد إجراءات مسجلة بعد.':'No activity yet.'}/>:<div className="space-y-0">{m.transitions.map((x,i)=><div key={x.id} className="flex gap-3"><div className="flex flex-col items-center"><span className="mt-1 h-2.5 w-2.5 rounded-full bg-teal-600 ring-4 ring-teal-50"/>{i<m.transitions!.length-1&&<span className="h-full w-px bg-slate-200"/>}</div><div className="pb-6"><p className="text-xs font-black text-slate-800">{state(x.from_state)} ← {state(x.to_state)}</p><p className="mt-1 text-[10px] font-bold text-slate-400">{nameOf(x.user)} · {new Date(x.created_at).toLocaleString(ar?'ar-PS':'en-GB')}</p>{x.reason&&<p className="mt-2 text-xs text-slate-600">{x.reason}</p>}</div></div>)}</div>}</section>}
    <Modal isOpen={editOpen} onClose={()=>setEditOpen(false)} title={ar?'تحرير بيانات ومحضر الاجتماع':'Edit meeting and minutes'} maxWidth="2xl"><form onSubmit={(e:FormEvent)=>{e.preventDefault();update.mutate()}} className="grid gap-3 sm:grid-cols-2"><Field label={ar?'نوع الاجتماع':'Meeting type'}><input required value={editForm.meeting_type} onChange={e=>setEditForm({...editForm,meeting_type:e.target.value})} className={input}/></Field><Field label={ar?'التاريخ':'Date'}><input required type="date" value={editForm.meeting_date} onChange={e=>setEditForm({...editForm,meeting_date:e.target.value})} className={input}/></Field><Field label={ar?'الوقت':'Time'}><input type="time" value={editForm.meeting_time} onChange={e=>setEditForm({...editForm,meeting_time:e.target.value})} className={input}/></Field><Field label={ar?'المكان':'Location'}><input value={editForm.location} onChange={e=>setEditForm({...editForm,location:e.target.value})} className={input}/></Field><Field label={ar?'رئيس الجلسة':'Chairperson'}><input value={editForm.chairperson} onChange={e=>setEditForm({...editForm,chairperson:e.target.value})} className={input}/></Field><Field label={ar?'مسؤول المتابعة':'Implementation owner'}><input value={editForm.implementation_owner} onChange={e=>setEditForm({...editForm,implementation_owner:e.target.value})} className={input}/></Field>{(['agenda','discussion_summary','attendees','absentees','decisions_summary'] as const).map(k=><Field key={k} label={({agenda:ar?'جدول الأعمال':'Agenda',discussion_summary:ar?'ملخص النقاش':'Discussion',attendees:ar?'الحضور':'Attendees',absentees:ar?'المعتذرون والغائبون':'Absentees',decisions_summary:ar?'خلاصة القرارات':'Decision summary'} as Record<string,string>)[k]}><textarea rows={4} value={editForm[k]} onChange={e=>setEditForm({...editForm,[k]:e.target.value})} className={input}/></Field>)}<div className="flex justify-end gap-2 border-t border-slate-100 pt-4 sm:col-span-2"><Button type="button" variant="outline" onClick={()=>setEditOpen(false)}>{ar?'إلغاء':'Cancel'}</Button><Button type="submit" isLoading={update.isPending}>{ar?'حفظ المحضر':'Save minutes'}</Button></div></form></Modal>
    <Modal isOpen={actionOpen} onClose={()=>setActionOpen(false)} title={editingAction?(ar?'تعديل مخرج الاجتماع':'Edit output'):(ar?'إضافة قرار أو تكليف':'Add decision or task')} maxWidth="2xl"><form onSubmit={(e:FormEvent)=>{e.preventDefault();saveAction.mutate()}} className="grid gap-3 sm:grid-cols-2"><Field label={ar?'نوع المخرج':'Output type'}><select value={actionForm.item_type} onChange={e=>setActionForm({...actionForm,item_type:e.target.value as ActionItem['item_type']})} className={input}><option value="task">{type('task')}</option><option value="decision">{type('decision')}</option><option value="recommendation">{type('recommendation')}</option></select></Field><Field label={ar?'الأولوية':'Priority'}><select value={actionForm.priority} onChange={e=>setActionForm({...actionForm,priority:e.target.value})} className={input}><option value="low">{priority('low')}</option><option value="normal">{priority('normal')}</option><option value="high">{priority('high')}</option></select></Field><label className="sm:col-span-2"><span className="mb-1 block text-xs font-black text-slate-600">{ar?'نص القرار أو التكليف':'Output description'}</span><textarea required rows={4} value={actionForm.description} onChange={e=>setActionForm({...actionForm,description:e.target.value})} className={input}/></label>{actionForm.item_type==='task'&&<Field label={ar?'المكلف من مستخدمي النظام':'System assignee'}><select value={actionForm.assigned_to} onChange={e=>setActionForm({...actionForm,assigned_to:e.target.value})} className={input}><option value="">{ar?'بدون تكليف مستخدم':'No system assignee'}</option>{(users.data??[]).map(u=><option key={u.id} value={u.id}>{nameOf(u)}</option>)}</select></Field>}<Field label={ar?'الموعد النهائي':'Due date'}><input type="date" value={actionForm.due_date} onChange={e=>setActionForm({...actionForm,due_date:e.target.value})} className={input}/></Field><Field label={ar?'الجهة المنفذة':'Executing entity'}><input value={actionForm.executing_entity} onChange={e=>setActionForm({...actionForm,executing_entity:e.target.value})} className={input}/></Field><Field label={ar?'مسؤول إضافي خارج النظام':'Additional owner'}><input value={actionForm.responsible} onChange={e=>setActionForm({...actionForm,responsible:e.target.value})} className={input}/></Field><label className="sm:col-span-2"><span className="mb-1 block text-xs font-black text-slate-600">{ar?'ملاحظات التنفيذ':'Execution notes'}</span><textarea rows={3} value={actionForm.notes} onChange={e=>setActionForm({...actionForm,notes:e.target.value})} className={input}/></label><div className="flex justify-end gap-2 border-t border-slate-100 pt-4 sm:col-span-2"><Button type="button" variant="outline" onClick={()=>setActionOpen(false)}>{ar?'إلغاء':'Cancel'}</Button><Button type="submit" isLoading={saveAction.isPending}>{ar?'حفظ وربط':'Save and link'}</Button></div></form></Modal>
    <ConfirmDialog isOpen={deleteId!==null} onClose={()=>setDeleteId(null)} onConfirm={()=>deleteId&&removeAction.mutate(deleteId)} isDanger isConfirming={removeAction.isPending} title={ar?'حذف المخرج':'Delete output'} message={ar?'سيُحذف المخرج والمهمة المرتبطة به. لا يمكن التراجع عن ذلك.':'The output and linked task will be deleted.'}/>
    <ConfirmDialog isOpen={cancelOpen} onClose={()=>setCancelOpen(false)} onConfirm={()=>{setCancelOpen(false);statusChange.mutate('cancelled')}} isDanger isConfirming={statusChange.isPending} title={ar?'إلغاء الاجتماع':'Cancel meeting'} message={ar?'سيظهر الاجتماع كملغي ويمكن إعادته لاحقًا إلى مسودة عند الحاجة.':'The meeting will be marked as cancelled and can later be restored as a draft.'}/>
  </div>
}

function Text({title,value}:{title:string;value?:string|null}){return <article className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><h3 className="text-xs font-black text-slate-600">{title}</h3><p className="mt-2 whitespace-pre-wrap text-xs font-medium leading-6 text-slate-700">{value||'—'}</p></article>}
function Badge({value,tone}:{value:string;tone:'teal'|'red'|'slate'|'green'|'amber'}){const styles={teal:'bg-teal-50 text-teal-700',red:'bg-rose-50 text-rose-700',slate:'bg-slate-100 text-slate-600',green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700'};return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${styles[tone]}`}>{value}</span>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1 block text-xs font-black text-slate-600">{label}</span>{children}</label>}
