import { useMemo, useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { CalendarClock, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleDot, ClipboardList, MapPin, Plus, Search, Users } from 'lucide-react';
import { apiFetch, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { LoadingState } from '@/components/ui/LoadingState';
import { Modal } from '@/components/ui/Modal';
import { PageHeader } from '@/components/ui/PageHeader';

type Meeting = { id:number; minutes_number:string; meeting_type:string; status:string; meeting_date:string; meeting_time?:string|null; location?:string|null; chairperson?:string|null; action_items_count:number; open_actions_count:number };
const initialForm = { meeting_type:'مجلس الدائرة السريرية', status:'scheduled', meeting_date:new Date().toISOString().slice(0,10), meeting_time:'', location:'', chairperson:'', agenda:'' };
const field = 'h-11 w-full rounded-2xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-800 outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-100';
const stateStyles:Record<string,string> = { draft:'bg-slate-100 text-slate-600', scheduled:'bg-blue-50 text-blue-700', held:'bg-amber-50 text-amber-700', minutes_draft:'bg-violet-50 text-violet-700', approved:'bg-emerald-50 text-emerald-700', cancelled:'bg-rose-50 text-rose-700' };

export function MeetingsPage(){
  const {can}=useAuth(); const {locale,t}=useI18n(); const ar=locale==='ar'; const qc=useQueryClient();
  const [createOpen,setCreateOpen]=useState(false); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [form,setForm]=useState(initialForm); const [error,setError]=useState('');
  const params=useMemo(()=>{const p=new URLSearchParams({per_page:'100'});if(search.trim())p.set('search',search.trim());if(status)p.set('status',status);return p.toString()},[search,status]);
  const query=useQuery({queryKey:['meetings',params],queryFn:()=>apiFetch<Meeting[]>(`/meetings?${params}`)});
  const create=useMutation({mutationFn:()=>apiFetch<Meeting>('/meetings',{method:'POST',body:{...form,meeting_time:form.meeting_time||null,location:form.location||null,chairperson:form.chairperson||null,agenda:form.agenda||null}}),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['meetings']});setCreateOpen(false);setForm(initialForm);setError('')},onError:e=>setError(e instanceof ApiError?e.message:(ar?'تعذر إنشاء الاجتماع.':'Unable to create meeting.'))});
  if(!can('meetings.manage'))return <ErrorState title={t('state.forbidden.title')} message={t('state.forbidden.message')}/>;
  if(query.isLoading)return <LoadingState/>; if(query.isError)return <ErrorState onRetry={()=>query.refetch()}/>;
  const meetings=query.data??[];
  const stateLabel=(v:string)=>({draft:ar?'مسودة':'Draft',scheduled:ar?'مجدول':'Scheduled',held:ar?'تم الانعقاد':'Held',minutes_draft:ar?'المحضر قيد الإعداد':'Minutes draft',approved:ar?'محضر معتمد':'Approved',cancelled:ar?'ملغي':'Cancelled'}[v]||v);
  const today=new Date().toISOString().slice(0,10);
  const stats=[
    {label:ar?'اجتماعات قادمة':'Upcoming',value:meetings.filter(m=>m.meeting_date>=today&&!['cancelled','approved'].includes(m.status)).length,icon:CalendarClock,color:'text-blue-700 bg-blue-50'},
    {label:ar?'بانتظار إعداد المحضر':'Minutes to prepare',value:meetings.filter(m=>['held','minutes_draft'].includes(m.status)).length,icon:ClipboardList,color:'text-violet-700 bg-violet-50'},
    {label:ar?'مهام مفتوحة':'Open actions',value:meetings.reduce((n,m)=>n+(m.open_actions_count||0),0),icon:CircleDot,color:'text-amber-700 bg-amber-50'},
    {label:ar?'محاضر معتمدة':'Approved minutes',value:meetings.filter(m=>m.status==='approved').length,icon:CheckCircle2,color:'text-emerald-700 bg-emerald-50'},
  ];
  return <div className="mx-auto max-w-7xl space-y-4 pb-14">
    <PageHeader title={ar?'الاجتماعات ومحاضر الجلسات':'Meetings and minutes'} description={ar?'مساحة واحدة لتخطيط الاجتماع، توثيق المحضر، وتحويل القرارات إلى مهام قابلة للمتابعة.':'Plan meetings, document minutes, and track decisions as actionable tasks.'}><Button onClick={()=>setCreateOpen(true)}><Plus className="me-2 h-4 w-4"/>{ar?'اجتماع جديد':'New meeting'}</Button></PageHeader>
    <section className="grid grid-cols-2 gap-2 lg:grid-cols-4">{stats.map(s=><article key={s.label} className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><div className="flex items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${s.color}`}><s.icon className="h-4 w-4"/></span><div><strong className="block text-xl font-black text-slate-900">{s.value}</strong><span className="text-[10px] font-bold text-slate-500 sm:text-xs">{s.label}</span></div></div></article>)}</section>
    <section className="rounded-3xl border border-slate-200 bg-white p-3 shadow-sm"><div className="grid gap-2 sm:grid-cols-[1fr_230px]"><label className="relative"><Search className="absolute right-3.5 top-3.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className={`${field} pr-10`} placeholder={ar?'بحث برقم المحضر أو نوع الاجتماع أو جدول الأعمال...':'Search meetings...'}/></label><select value={status} onChange={e=>setStatus(e.target.value)} className={field}><option value="">{ar?'كل حالات الاجتماعات':'All statuses'}</option>{['scheduled','held','minutes_draft','approved','draft','cancelled'].map(x=><option key={x} value={x}>{stateLabel(x)}</option>)}</select></div></section>
    {!meetings.length?<EmptyState message={ar?'لا توجد اجتماعات مطابقة. ابدأ بإنشاء اجتماع جديد.':'No matching meetings.'}/>:<section className="grid gap-3 md:grid-cols-2">{meetings.map(m=>{const overdue=m.open_actions_count>0&&m.meeting_date<today;return <Link key={m.id} to={`/meetings/${m.id}`} className="group rounded-3xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-teal-200 hover:shadow-md sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><span className="font-mono text-[10px] font-bold text-teal-700">{m.minutes_number}</span><h2 className="mt-1 truncate text-sm font-black text-slate-900 sm:text-base">{m.meeting_type}</h2></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-black ${stateStyles[m.status]||stateStyles.draft}`}>{stateLabel(m.status)}</span></div><div className="mt-4 grid gap-2 text-[11px] font-bold text-slate-500 sm:grid-cols-2"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-teal-600"/>{m.meeting_date}{m.meeting_time?` · ${m.meeting_time.slice(0,5)}`:''}</span><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-teal-600"/>{m.location||(ar?'لم يحدد المكان':'No location')}</span><span className="flex items-center gap-2"><Users className="h-4 w-4 text-teal-600"/>{m.chairperson||(ar?'لم يحدد رئيس الجلسة':'No chair')}</span><span className={`flex items-center gap-2 ${overdue?'text-rose-600':''}`}><CircleDot className="h-4 w-4"/>{m.open_actions_count||0} {ar?'مخرج قيد المتابعة':'open actions'}</span></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-[10px] font-bold text-slate-400">{m.action_items_count||0} {ar?'قرار وتكليف':'outputs'}</span><span className="flex items-center gap-1 text-xs font-black text-teal-700">{ar?'فتح ملف الاجتماع':'Open meeting'}{ar?<ChevronLeft className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</span></div></Link>})}</section>}
    <Modal isOpen={createOpen} onClose={()=>setCreateOpen(false)} title={ar?'إنشاء اجتماع جديد':'Create a new meeting'} maxWidth="2xl"><form onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate()}} className="space-y-5"><div className="rounded-2xl bg-teal-50 p-3 text-xs font-bold leading-5 text-teal-800">{ar?'سيُنشئ النظام رقم المحضر تلقائيًا. أدخل بيانات التحضير الآن، ثم وثّق الحضور والنقاش والقرارات بعد انعقاد الاجتماع.':'The minutes number is generated automatically. Add planning details now and complete the minutes after the meeting.'}</div><div className="grid gap-3 sm:grid-cols-2"><Field label={ar?'نوع الاجتماع':'Meeting type'}><select required value={form.meeting_type} onChange={e=>setForm({...form,meeting_type:e.target.value})} className={field}>{['مجلس الدائرة السريرية','اجتماع رؤساء الأقسام','لجنة الجودة والاعتماد','لجنة التدريب السريري','لجنة أكاديمية','اجتماع طارئ'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label={ar?'حالة الإنشاء':'Initial status'}><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className={field}><option value="scheduled">{ar?'مجدول':'Scheduled'}</option><option value="draft">{ar?'مسودة':'Draft'}</option></select></Field><Field label={ar?'تاريخ الاجتماع':'Meeting date'}><input required type="date" value={form.meeting_date} onChange={e=>setForm({...form,meeting_date:e.target.value})} className={field}/></Field><Field label={ar?'وقت الاجتماع':'Meeting time'}><input type="time" value={form.meeting_time} onChange={e=>setForm({...form,meeting_time:e.target.value})} className={field}/></Field><Field label={ar?'المكان أو رابط الاجتماع':'Location or link'}><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className={field}/></Field><Field label={ar?'رئيس الجلسة':'Chairperson'}><input value={form.chairperson} onChange={e=>setForm({...form,chairperson:e.target.value})} className={field}/></Field></div><Field label={ar?'جدول الأعمال المبدئي':'Initial agenda'}><textarea rows={5} value={form.agenda} onChange={e=>setForm({...form,agenda:e.target.value})} className={`${field} h-auto py-3`} placeholder={ar?'اكتب كل بند في سطر مستقل...':'Write each item on a separate line...'}/></Field>{error&&<p className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}<div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><Button type="button" variant="outline" onClick={()=>setCreateOpen(false)}>{ar?'إلغاء':'Cancel'}</Button><Button type="submit" isLoading={create.isPending}>{ar?'إنشاء الاجتماع':'Create meeting'}</Button></div></form></Modal>
  </div>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-black text-slate-600">{label}</span>{children}</label>}
