import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { useParams } from 'react-router-dom';
import { apiFetch, ApiError } from '@/api/client';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { CheckCircle2, GraduationCap, Lock, Mail, ShieldCheck } from 'lucide-react';

type CycleInfo = { public_id:string; academic_level:string; academic_year:string; status:'open'|'closed' };
type Options = { student:{name:string;university_number:string;academic_level:string}; main_group:string; subgroups:Array<{id:number;name:string;capacity:number;occupied:number;available:number;is_full:boolean;is_selected:boolean}> };
const levelName:Record<string,string>={fourth:'السنة الرابعة',fifth:'السنة الخامسة',sixth:'السنة السادسة'};

export function PublicStudentRegistrationPage() {
  const { publicId } = useParams();
  const [cycle,setCycle]=useState<CycleInfo|null>(null), [number,setNumber]=useState(''), [challenge,setChallenge]=useState(''), [otp,setOtp]=useState(''), [emailHint,setEmailHint]=useState(''), [accessToken,setAccessToken]=useState('');
  const [options,setOptions]=useState<Options|null>(null), [busy,setBusy]=useState(false), [error,setError]=useState(''), [message,setMessage]=useState('');
  useEffect(()=>{ if(!publicId){setError('رابط التسجيل غير مكتمل. يرجى استخدام الرابط الصادر عن إدارة الدائرة السريرية.');return;} apiFetch<CycleInfo>(`/public/group-registration/${publicId}`).then(setCycle).catch(()=>setError('رابط التسجيل غير صالح أو لم يعد متاحاً.')); },[publicId]);
  const fail=(e:unknown)=>setError(e instanceof ApiError?e.message:'تعذر إتمام العملية. يرجى المحاولة لاحقاً.');
  const requestOtp=async(e:FormEvent)=>{e.preventDefault();if(!publicId)return;setBusy(true);setError('');setMessage('');try{const r=await apiFetch<{challenge_token:string;email_hint:string}>(`/public/group-registration/${publicId}/request-otp`,{method:'POST',body:{university_number:number.trim()}});setChallenge(r.challenge_token);setEmailHint(r.email_hint);setMessage('تم إرسال رمز التحقق إلى بريدك الجامعي.');}catch(e){fail(e)}finally{setBusy(false)}};
  const verify=async(e:FormEvent)=>{e.preventDefault();if(!publicId)return;setBusy(true);setError('');try{const r=await apiFetch<{access_token:string}>(`/public/group-registration/${publicId}/verify-otp`,{method:'POST',body:{challenge_token:challenge,otp}});setAccessToken(r.access_token);const data=await apiFetch<Options>(`/public/group-registration/${publicId}/options`,{method:'POST',body:{access_token:r.access_token}});setOptions(data);setMessage('تم التحقق من هويتك بنجاح.');}catch(e){fail(e)}finally{setBusy(false)}};
  const refresh=async()=>{if(publicId&&accessToken)setOptions(await apiFetch<Options>(`/public/group-registration/${publicId}/options`,{method:'POST',body:{access_token:accessToken}}));};
  const select=async(id:number)=>{if(!publicId)return;setBusy(true);setError('');try{await apiFetch(`/public/group-registration/${publicId}/select`,{method:'POST',body:{access_token:accessToken,subgroup_id:id}});await refresh();setMessage('تم حجز مقعدك بنجاح.');}catch(e){fail(e)}finally{setBusy(false)}};
  const withdraw=async()=>{if(!publicId||!confirm('هل أنت متأكد من الانسحاب من المجموعة؟'))return;setBusy(true);setError('');try{await apiFetch(`/public/group-registration/${publicId}/withdraw`,{method:'POST',body:{access_token:accessToken}});await refresh();setMessage('تم الانسحاب وأصبح المقعد متاحاً.');}catch(e){fail(e)}finally{setBusy(false)}};
  return <main dir="rtl" className="min-h-screen bg-slate-50 p-4 sm:p-8 text-slate-900"><div className="mx-auto max-w-3xl space-y-5">
    <header className="rounded-3xl border bg-white p-6 text-center shadow-sm"><div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-2xl bg-teal-600 text-white"><GraduationCap/></div><div className="mb-2 inline-flex items-center gap-1 rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-700"><ShieldCheck className="h-4 w-4"/>بوابة آمنة للتحقق عبر البريد الجامعي</div><h1 className="text-2xl font-black">اختيار المجموعة السريرية</h1>{cycle&&<p className="mt-2 text-sm text-slate-500">{levelName[cycle.academic_level]} · {cycle.academic_year}</p>}</header>
    {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{message&&<div className="flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700"><CheckCircle2 className="h-5 w-5"/>{message}</div>}
    {cycle?.status==='closed'&&<Card className="p-8 text-center"><Lock className="mx-auto mb-3 text-amber-600"/><h2 className="font-bold">فترة التسجيل مغلقة حالياً</h2><p className="mt-2 text-sm text-slate-500">يرجى التواصل مع إدارة الدائرة السريرية.</p></Card>}
    {cycle?.status==='open'&&!challenge&&<Card className="p-6"><form onSubmit={requestOtp} className="space-y-4"><label className="block text-sm font-bold">الرقم الجامعي</label><input required inputMode="numeric" pattern="[0-9]+" value={number} onChange={e=>setNumber(e.target.value)} className="w-full rounded-xl border p-3 font-mono" placeholder="مثال: 22210466"/><Button className="w-full" isLoading={busy}>إرسال رمز التحقق</Button></form></Card>}
    {challenge&&!accessToken&&<Card className="p-6"><form onSubmit={verify} className="space-y-4"><div className="flex items-center gap-2 text-sm text-slate-600"><Mail className="h-5 w-5 text-teal-600"/>أرسلنا رمزاً من 6 أرقام إلى {emailHint}</div><input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value)} className="w-full rounded-xl border p-3 text-center font-mono text-2xl tracking-[.4em]"/><Button className="w-full" isLoading={busy}>التحقق والمتابعة</Button></form></Card>}
    {options&&<section className="space-y-4"><Card className="p-5"><p className="font-bold">{options.student.name}</p><p className="mt-1 text-sm text-slate-500">{options.student.university_number} · المجموعة الرئيسية <b>{options.main_group}</b></p></Card><div className="grid gap-4 sm:grid-cols-2">{options.subgroups.map(s=><Card key={s.id} className={`p-5 ${s.is_selected?'border-2 border-teal-500 bg-teal-50':''}`}><div className="flex items-center justify-between"><h3 className="text-lg font-black">{s.name}</h3><span className={`rounded-full px-2 py-1 text-xs font-bold ${s.is_full?'bg-red-100 text-red-700':'bg-emerald-100 text-emerald-700'}`}>{s.occupied}/{s.capacity}</span></div><p className="my-4 text-sm text-slate-500">{s.is_full?'المجموعة مكتملة':'المقاعد المتاحة: '+s.available}</p>{s.is_selected?<Button variant="danger" className="w-full" disabled={busy} onClick={withdraw}>الانسحاب من المجموعة</Button>:<Button className="w-full" disabled={busy||s.is_full} onClick={()=>select(s.id)}>{s.is_full?'مكتملة':'حجز المقعد'}</Button>}</Card>)}</div></section>}
  </div></main>;
}
