import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { apiFetch, apiUrl, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { PageHeader } from '@/components/ui/PageHeader';
import { Copy, Download, ExternalLink, Link2, Plus, Save, Sparkles, Trash2, UserRound, Users } from 'lucide-react';

type RegisteredStudent={id:number;name:string;university_number:string;registered_at?:string};
type Subgroup={id:number;name:string;capacity:number;max_size:number;is_active:boolean;current_students_count:number;registered_students:RegisteredStudent[]};
type Group={id:number;name:string;roster_count:number;registered_roster_count:number;recommended_subgroups_count:number;recommended_capacity_plan:number[];current_active_capacity:number;subgroups:Subgroup[]};
type RosterStudent={id:number;name:string;university_number:string;academic_registration_status:string;main_group_id:number;main_group:string;student_subgroup_id:number|null;student_subgroup:string|null};
type Cycle={id:number;public_id:string;academic_year_id:number;academic_year?:{code:string;name?:string};academic_level:string;status:string;default_capacity:number;rosters_count:number;registered_rosters_count:number;public_url:string;groups:Group[];roster_students:RosterStudent[]};
type Year={id:number;code:string;name?:string;is_current?:boolean};
type YearsResponse=Year[]|{data?:Year[]};
const levels={fourth:'السنة الرابعة — L, M, N',fifth:'السنة الخامسة — A, B, C',sixth:'السنة السادسة'};

export function StudentGroupsPage(){
  const {can}=useAuth(), qc=useQueryClient();
  const [yearId,setYearId]=useState(''),[level,setLevel]=useState('fourth'),[capacity,setCapacity]=useState(6),[selectedId,setSelectedId]=useState<number|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [assignmentDrafts,setAssignmentDrafts]=useState<Record<number,string>>({}),[reasonDrafts,setReasonDrafts]=useState<Record<number,string>>({});
  const {data:cycles=[],refetch}=useQuery({queryKey:['group-registration-cycles'],queryFn:()=>apiFetch<Cycle[]>('/group-registration-cycles')});
  const {data:yearsResponse,isLoading:yearsLoading,isError:yearsError}=useQuery({queryKey:['academic-years'],queryFn:()=>apiFetch<YearsResponse>('/academic-years?per_page=100')});
  const years=useMemo(()=>Array.isArray(yearsResponse)?yearsResponse:(yearsResponse?.data??[]),[yearsResponse]);
  useEffect(()=>{if(!yearId&&years.length){setYearId(String(years.find(y=>y.is_current)?.id??years[0].id));}},[yearId,years]);
  const selected=useMemo(()=>cycles.find(c=>c.id===selectedId)||cycles[0],[cycles,selectedId]);
  const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await fn();await qc.invalidateQueries({queryKey:['group-registration-cycles']});await refetch();return true;}catch(e){setError(e instanceof ApiError?e.message:'تعذر تنفيذ العملية.');return false;}finally{setBusy(false)}};
  const create=(e:FormEvent)=>{e.preventDefault();run(()=>apiFetch('/group-registration-cycles',{method:'POST',body:{academic_year_id:Number(yearId),academic_level:level,default_capacity:capacity}}));};
  const updateCycle=(status:string)=>selected&&run(()=>apiFetch(`/group-registration-cycles/${selected.id}`,{method:'PUT',body:{status}}));
  const addSub=(group:Group)=>{const next=group.subgroups.length+1;const name=prompt('اسم المجموعة الفرعية',`${group.name}${next}`);if(name&&selected)run(()=>apiFetch(`/group-registration-cycles/${selected.id}/groups/${group.id}/subgroups`,{method:'POST',body:{name,capacity:selected.default_capacity}}));};
  const generateSubgroups=()=>{if(!selected||selected.rosters_count===0)return;if(!confirm('سيحسب النظام عدد طلبة كل مجموعة رئيسية وينشئ أو يستكمل مجموعات فرعية بسعة 5 أو 6. لن يحذف أي مجموعة ولن يغيّر سعة مجموعة يوجد فيها طلبة. هل تريد المتابعة؟'))return;run(()=>apiFetch(`/group-registration-cycles/${selected.id}/generate-subgroups`,{method:'POST'})).then(saved=>{if(saved)setNotice('تم تجهيز المجموعات الفرعية الفارغة حسب عدد طلبة كل مجموعة رئيسية.');});};
  const editSub=(s:Subgroup)=>{if(!selected)return;const name=prompt('اسم المجموعة الفرعية',s.name);if(!name)return;const cap=Number(prompt('السعة 5 أو 6',String(s.capacity||s.max_size||6)));if(![5,6].includes(cap))return;run(()=>apiFetch(`/group-registration-cycles/${selected.id}/subgroups/${s.id}`,{method:'PUT',body:{name,capacity:cap,is_active:s.is_active}}));};
  const removeSub=(s:Subgroup)=>selected&&confirm(`حذف المجموعة ${s.name} نهائيًا؟ لا يمكن حذفها قبل تفريغ جميع الطلبة منها.`)&&run(()=>apiFetch(`/group-registration-cycles/${selected.id}/subgroups/${s.id}`,{method:'DELETE'}));
  const copyLink=()=>selected&&navigator.clipboard.writeText(`${location.origin}${selected.public_url}`);
  const overrideStudent=(student:RosterStudent)=>{if(!selected)return;const subgroupValue=assignmentDrafts[student.id]??String(student.student_subgroup_id??'');const reason=(reasonDrafts[student.id]??'').trim();if(reason.length<3){setError('يجب كتابة سبب إداري واضح قبل حفظ تعديل الطالب.');return;}const subgroupId=subgroupValue?Number(subgroupValue):null;const target=selected.groups.flatMap(group=>group.subgroups).find(subgroup=>subgroup.id===subgroupId);const overCapacity=Boolean(target&&target.id!==student.student_subgroup_id&&target.current_students_count>=target.capacity);if(overCapacity&&!confirm(`المجموعة ${target?.name} مكتملة. هل تريد تجاوز السعة إداريًا؟`))return;run(()=>apiFetch(`/group-registration-cycles/${selected.id}/students/${student.id}/assignment`,{method:'PUT',body:{student_subgroup_id:subgroupId,reason,allow_over_capacity:overCapacity}})).then(saved=>{if(saved)setReasonDrafts(current=>({...current,[student.id]:''}));});};
  const exportResults=async()=>{if(!selected||busy)return;setBusy(true);setError('');try{const response=await fetch(apiUrl(`/group-registration-cycles/${selected.id}/export`),{credentials:'include',headers:{Accept:'text/csv'}});if(!response.ok)throw new Error('export');const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`group-registration-${selected.academic_year?.code??selected.academic_year_id}-${selected.academic_level}.csv`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);}catch{setError('تعذر تصدير نتائج التسجيل. تأكد من الصلاحية ثم حاول مجددًا.');}finally{setBusy(false);}};
  return <div dir="rtl" className="mx-auto max-w-[1500px] space-y-5 pb-14">
    <PageHeader title="إدارة التسجيل الذاتي للمجموعات" description="إنشاء دورات التسجيل، إدارة المجموعات والسعات، ومتابعة تسجيل الطلبة من مكان واحد.">
      <Link to="/directory" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700"><Users className="h-4 w-4 text-teal-600"/>دليل الطلاب</Link>
    </PageHeader>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
    {notice&&<div className="rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm font-bold text-teal-800">{notice}</div>}
    {can('group_registration.manage_groups')&&<Card className="space-y-3 rounded-3xl border border-slate-100 p-4 sm:p-5"><div><h2 className="text-sm font-black text-slate-800">إنشاء دورة تسجيل جديدة</h2><p className="mt-1 text-[11px] text-slate-500">سيُنشئ النظام المجموعات الرئيسية المناسبة للسنة المختارة، وبعد ربط الطلبة يمكنك توليد المجموعات الفرعية حسب العدد الفعلي.</p></div><form onSubmit={create} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><select required disabled={yearsLoading||years.length===0} value={yearId} onChange={e=>setYearId(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold"><option value="">{yearsLoading?'جاري تحميل الأعوام...':'العام الأكاديمي'}</option>{years.map(y=><option key={y.id} value={y.id}>{y.name||y.code}{y.is_current?' — الحالي':''}</option>)}</select><select value={level} onChange={e=>setLevel(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold">{Object.entries(levels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={capacity} onChange={e=>setCapacity(Number(e.target.value))} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold"><option value={6}>السعة الافتراضية 6</option><option value={5}>السعة الافتراضية 5</option></select><Button className="h-11 bg-teal-600 hover:bg-teal-700" disabled={!yearId||yearsError||years.length===0} isLoading={busy}><Plus className="ml-2 h-4 w-4"/>إنشاء دورة والمجموعات الرئيسية</Button></form>{yearsError&&<p className="text-xs font-bold text-red-700">تعذر تحميل السنوات الأكاديمية. يرجى تحديث الصفحة أو التواصل مع مدير النظام.</p>}{!yearsLoading&&!yearsError&&years.length===0&&<p className="text-xs font-bold text-slate-700">لا توجد سنة أكاديمية معرفة في النظام. يجب إضافتها قبل إنشاء دورة التسجيل.</p>}</Card>}
    <div className="flex gap-2 overflow-x-auto">{cycles.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`whitespace-nowrap rounded-xl border px-4 py-2 text-sm font-bold ${(selected?.id===c.id)?'bg-teal-600 text-white':'bg-white'}`}>{levels[c.academic_level as keyof typeof levels]} · {c.academic_year?.code} · {c.status}</button>)}</div>
    {selected&&<>
      <Card className="rounded-3xl border border-slate-100 p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-slate-800">{levels[selected.academic_level as keyof typeof levels]} · {selected.academic_year?.code}</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${selected.status==='open'?'bg-teal-100 text-teal-700':'bg-slate-100 text-slate-800'}`}>{selected.status==='open'?'التسجيل مفتوح':'التسجيل مغلق'}</span></div><p className="mt-1 text-xs text-slate-500">القائمة: {selected.rosters_count} · المسجلون أكاديمياً: {selected.registered_rosters_count}</p></div><div className="flex flex-wrap gap-2">{can('group_registration.export')&&<Button variant="outline" onClick={exportResults} disabled={busy}><Download className="ml-1 h-4 w-4"/>تصدير النتائج</Button>}<Button variant="outline" onClick={copyLink}><Copy className="ml-1 h-4 w-4"/>نسخ الرابط</Button><Button variant="outline" onClick={()=>window.open(selected.public_url,'_blank','noopener,noreferrer')}><ExternalLink className="ml-1 h-4 w-4"/>فتح</Button>{can('group_registration.open_close')&&<Button variant={selected.status==='open'?'danger':'primary'} onClick={()=>updateCycle(selected.status==='open'?'closed':'open')} isLoading={busy}>{selected.status==='open'?'إغلاق التسجيل':'فتح التسجيل'}</Button>}</div></div><div className="mt-3 flex items-center gap-2 overflow-hidden rounded-xl border border-slate-100 bg-slate-50 p-3 font-mono text-[11px]"><Link2 className="h-4 w-4 shrink-0 text-teal-600"/><span dir="ltr" className="truncate">{location.origin}{selected.public_url}</span></div></Card>
      <Card className="flex flex-wrap items-center justify-between gap-3 border-teal-100 bg-teal-50/40 p-4"><div><h3 className="font-bold text-teal-800">قائمة الطلبة وحالتهم الأكاديمية</h3><p className="mt-1 text-xs text-teal-800">تُدار مركزيًا من دليل الطلاب، ثم تُربط بهذه الدورة والمجموعات الرئيسية أثناء الاستيراد.</p></div><Link to="/directory" className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2 text-xs font-bold text-white"><Users className="h-4 w-4"/>فتح دليل الطلاب</Link></Card>
      <Card className="rounded-3xl border-teal-100 p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-teal-600"/><h3 className="font-black text-slate-800">التخطيط الذكي للمجموعات الفرعية</h3></div><p className="mt-1 text-xs text-slate-500">يعتمد على جميع طلبة القائمة حتى تبقى المقاعد كافية للطلبة غير المسجلين أكاديميًا عند تغير حالتهم لاحقًا.</p></div>{can('group_registration.manage_groups')&&<Button onClick={generateSubgroups} disabled={busy||selected.rosters_count===0} isLoading={busy}><Sparkles className="ml-2 h-4 w-4"/>إنشاء أو استكمال المجموعات تلقائيًا</Button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-3">{selected.groups.map(g=><div key={g.id} className="rounded-2xl border border-slate-200 bg-slate-50/60 p-4"><div className="flex items-center justify-between gap-2"><span className="font-black text-slate-800">المجموعة {g.name}</span><span className="rounded-full bg-teal-50 px-2 py-1 text-[11px] font-bold text-teal-700">{g.roster_count} طالب</span></div><p className="mt-2 text-xs text-slate-600">{g.roster_count===0?'بانتظار ربط الطلبة':<>المقترح: <strong>{g.recommended_subgroups_count}</strong> مجموعات · السعات {g.recommended_capacity_plan.join(' + ')}</>}</p><p className="mt-1 text-[11px] text-slate-400">المسجلون أكاديميًا: {g.registered_roster_count} · السعة الحالية: {g.current_active_capacity}</p></div>)}</div></Card>
      <div className="grid gap-5 xl:grid-cols-3">{selected.groups.map(g=><Card key={g.id} className="overflow-hidden border-slate-200"><div className="flex items-center justify-between border-b bg-slate-50 px-5 py-4"><div><h3 className="text-xl font-black text-slate-800">المجموعة {g.name}</h3><p className="mt-0.5 text-xs text-slate-500">{g.roster_count} طالب في القائمة · {g.subgroups.reduce((n,s)=>n+s.current_students_count,0)} اختاروا مجموعة</p></div>{can('group_registration.manage_groups')&&<button onClick={()=>addSub(g)} className="rounded-xl bg-teal-600 p-2.5 text-white shadow-sm" title="إضافة مجموعة فرعية"><Plus className="h-4 w-4"/></button>}</div><div className="space-y-3 p-4">{g.subgroups.length===0&&<p className="rounded-xl border border-dashed p-5 text-center text-xs text-slate-400">لم تُنشأ مجموعات فرعية بعد</p>}{g.subgroups.map(s=>{const cap=s.capacity||s.max_size;const count=s.current_students_count||0;const full=count>=cap;return <div key={s.id} className={`rounded-2xl border p-4 ${!s.is_active?'opacity-50':full?'border-slate-200 bg-slate-50/40':'border-slate-200 bg-white'}`}><div className="flex items-start justify-between gap-3"><div><button onClick={()=>can('group_registration.manage_groups')&&editSub(s)} className="text-lg font-black text-slate-800">{s.name}</button><div className="mt-1 flex items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${full?'bg-slate-100 text-slate-800':'bg-teal-100 text-teal-700'}`}>{full?'مكتملة':`${cap-count} مقعد متاح`}</span><span className="text-xs font-bold text-slate-500">{count}/{cap}</span></div></div>{can('group_registration.manage_groups')&&<button onClick={()=>removeSub(s)} className="rounded-lg p-2 text-red-500 hover:bg-red-50" title="حذف المجموعة نهائيًا"><Trash2 className="h-4 w-4"/></button>}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${full?'bg-slate-500':'bg-teal-500'}`} style={{width:`${Math.min(100,(count/cap)*100)}%`}}/></div><div className="mt-3 space-y-1.5">{s.registered_students?.length?s.registered_students.map(student=><div key={student.id} className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-teal-100 text-teal-700"><UserRound className="h-3.5 w-3.5"/></div><div className="min-w-0"><p className="truncate text-xs font-bold text-slate-800">{student.name}</p><p className="font-mono text-[10px] text-slate-500">{student.university_number}</p></div></div>):<p className="rounded-xl border border-dashed p-3 text-center text-xs text-slate-400">لم يسجل أي طالب بعد</p>}</div></div>})}</div></Card>)}</div>
      {can('group_registration.override')&&<Card className="overflow-hidden rounded-3xl border-slate-200"><div className="border-b bg-slate-50 px-5 py-4"><h3 className="font-black text-slate-800">التحكم الإداري بتسجيل الطلبة</h3><p className="mt-1 text-xs text-slate-500">انقل الطالب أو أخرجه من المجموعة مع توثيق سبب العملية. خيار «بدون مجموعة» يعني إخراج الطالب.</p></div><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-right text-xs"><thead className="bg-white text-slate-500"><tr><th className="p-3">الطالب</th><th className="p-3">الحالة</th><th className="p-3">الرئيسية</th><th className="p-3">المجموعة الفرعية</th><th className="p-3">سبب التعديل</th><th className="p-3">الإجراء</th></tr></thead><tbody className="divide-y divide-slate-100">{selected.roster_students.map(student=>{const group=selected.groups.find(item=>item.id===student.main_group_id);const value=assignmentDrafts[student.id]??String(student.student_subgroup_id??'');return <tr key={student.id} className="align-middle"><td className="p-3"><p className="font-bold text-slate-800">{student.name}</p><p className="font-mono text-[10px] text-slate-500">{student.university_number}</p></td><td className="p-3"><span className={`rounded-full px-2 py-1 font-bold ${student.academic_registration_status==='registered'?'bg-teal-50 text-teal-700':'bg-amber-50 text-amber-700'}`}>{student.academic_registration_status==='registered'?'مسجل':'غير مسجل'}</span></td><td className="p-3 font-black">{student.main_group}</td><td className="p-3"><select value={value} onChange={event=>setAssignmentDrafts(current=>({...current,[student.id]:event.target.value}))} className="h-10 min-w-36 rounded-xl border border-slate-200 bg-white px-3"><option value="">بدون مجموعة</option>{group?.subgroups.filter(subgroup=>subgroup.is_active).map(subgroup=><option key={subgroup.id} value={subgroup.id}>{subgroup.name} — {subgroup.current_students_count}/{subgroup.capacity}</option>)}</select></td><td className="p-3"><input value={reasonDrafts[student.id]??''} onChange={event=>setReasonDrafts(current=>({...current,[student.id]:event.target.value}))} className="h-10 w-full min-w-56 rounded-xl border border-slate-200 px-3" placeholder="سبب النقل أو الإخراج..."/></td><td className="p-3"><Button size="sm" onClick={()=>overrideStudent(student)} disabled={busy||value===String(student.student_subgroup_id??'')}><Save className="ml-1 h-4 w-4"/>حفظ</Button></td></tr>})}</tbody></table></div>{selected.roster_students.length===0&&<p className="p-6 text-center text-sm text-slate-400">لا يوجد طلبة مرتبطون بهذه الدورة.</p>}</Card>}
    </>}
  </div>;
}
