import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { apiFetch, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Copy, Link2, Plus, Trash2, UserRound, Users } from 'lucide-react';

type RegisteredStudent={id:number;name:string;university_number:string;registered_at?:string};
type Subgroup={id:number;name:string;capacity:number;max_size:number;is_active:boolean;current_students_count:number;registered_students:RegisteredStudent[]};
type Group={id:number;name:string;subgroups:Subgroup[]};
type Cycle={id:number;public_id:string;academic_year_id:number;academic_year?:{code:string;name?:string};academic_level:string;status:string;default_capacity:number;rosters_count:number;registered_rosters_count:number;public_url:string;groups:Group[]};
type Year={id:number;code:string;name?:string;is_current?:boolean};
type YearsResponse=Year[]|{data?:Year[]};
const levels={fourth:'السنة الرابعة — L, M, N',fifth:'السنة الخامسة — A, B, C',sixth:'السنة السادسة'};

export function StudentGroupsPage(){
  const {can}=useAuth(), qc=useQueryClient();
  const [yearId,setYearId]=useState(''),[level,setLevel]=useState('fourth'),[capacity,setCapacity]=useState(6),[selectedId,setSelectedId]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const {data:cycles=[],refetch}=useQuery({queryKey:['group-registration-cycles'],queryFn:()=>apiFetch<Cycle[]>('/group-registration-cycles')});
  const {data:yearsResponse,isLoading:yearsLoading,isError:yearsError}=useQuery({queryKey:['academic-years'],queryFn:()=>apiFetch<YearsResponse>('/academic-years?per_page=100')});
  const years=useMemo(()=>Array.isArray(yearsResponse)?yearsResponse:(yearsResponse?.data??[]),[yearsResponse]);
  useEffect(()=>{if(!yearId&&years.length){setYearId(String(years.find(y=>y.is_current)?.id??years[0].id));}},[yearId,years]);
  const selected=useMemo(()=>cycles.find(c=>c.id===selectedId)||cycles[0],[cycles,selectedId]);
  const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await qc.invalidateQueries({queryKey:['group-registration-cycles']});await refetch();}catch(e){setError(e instanceof ApiError?e.message:'تعذر تنفيذ العملية.')}finally{setBusy(false)}};
  const create=(e:FormEvent)=>{e.preventDefault();run(()=>apiFetch('/group-registration-cycles',{method:'POST',body:{academic_year_id:Number(yearId),academic_level:level,default_capacity:capacity}}));};
  const updateCycle=(status:string)=>selected&&run(()=>apiFetch(`/group-registration-cycles/${selected.id}`,{method:'PUT',body:{status}}));
  const addSub=(group:Group)=>{const next=group.subgroups.length+1;const name=prompt('اسم المجموعة الفرعية',`${group.name}${next}`);if(name&&selected)run(()=>apiFetch(`/group-registration-cycles/${selected.id}/groups/${group.id}/subgroups`,{method:'POST',body:{name,capacity:selected.default_capacity}}));};
  const editSub=(s:Subgroup)=>{if(!selected)return;const name=prompt('اسم المجموعة الفرعية',s.name);if(!name)return;const cap=Number(prompt('السعة 5 أو 6',String(s.capacity||s.max_size||6)));if(![5,6].includes(cap))return;run(()=>apiFetch(`/group-registration-cycles/${selected.id}/subgroups/${s.id}`,{method:'PUT',body:{name,capacity:cap,is_active:s.is_active}}));};
  const removeSub=(s:Subgroup)=>selected&&confirm(`حذف/أرشفة ${s.name}؟`)&&run(()=>apiFetch(`/group-registration-cycles/${selected.id}/subgroups/${s.id}`,{method:'DELETE'}));
  const copyLink=()=>selected&&navigator.clipboard.writeText(`${location.origin}${selected.public_url}`);
  return <div dir="rtl" className="space-y-6">
    <div><h1 className="text-2xl font-black text-slate-900">إدارة التسجيل الذاتي للمجموعات</h1><p className="mt-1 text-sm text-slate-500">إنشاء الدورات، إدارة الشعب والسعات، متابعة تسجيل الطلبة، وفتح الرابط العام الآمن.</p></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
    {can('group_registration.manage_groups')&&<Card className="p-5 space-y-3"><form onSubmit={create} className="grid gap-3 md:grid-cols-4"><select required disabled={yearsLoading||years.length===0} value={yearId} onChange={e=>setYearId(e.target.value)} className="rounded-xl border p-2"><option value="">{yearsLoading?'جاري تحميل الأعوام...':'العام الأكاديمي'}</option>{years.map(y=><option key={y.id} value={y.id}>{y.name||y.code}{y.is_current?' — الحالي':''}</option>)}</select><select value={level} onChange={e=>setLevel(e.target.value)} className="rounded-xl border p-2">{Object.entries(levels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={capacity} onChange={e=>setCapacity(Number(e.target.value))} className="rounded-xl border p-2"><option value={6}>السعة 6</option><option value={5}>السعة 5</option></select><Button disabled={!yearId||yearsError||years.length===0} isLoading={busy}><Plus className="ml-2 h-4 w-4"/>إنشاء دورة ومجموعات فارغة</Button></form>{yearsError&&<p className="text-xs font-bold text-red-700">تعذر تحميل السنوات الأكاديمية. يرجى تحديث الصفحة أو التواصل مع مدير النظام.</p>}{!yearsLoading&&!yearsError&&years.length===0&&<p className="text-xs font-bold text-amber-700">لا توجد سنة أكاديمية معرفة في النظام. يجب إضافتها قبل إنشاء دورة التسجيل.</p>}</Card>}
    <div className="flex gap-2 overflow-x-auto">{cycles.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`whitespace-nowrap rounded-xl border px-4 py-2 text-sm font-bold ${(selected?.id===c.id)?'bg-teal-600 text-white':'bg-white'}`}>{levels[c.academic_level as keyof typeof levels]} · {c.academic_year?.code} · {c.status}</button>)}</div>
    {selected&&<>
      <Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">{levels[selected.academic_level as keyof typeof levels]} · {selected.academic_year?.code}</h2><p className="mt-1 text-sm text-slate-500">القائمة: {selected.rosters_count} · المسجلون أكاديمياً: {selected.registered_rosters_count}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={copyLink}><Copy className="ml-1 h-4 w-4"/>نسخ الرابط</Button>{can('group_registration.open_close')&&<Button variant={selected.status==='open'?'danger':'primary'} onClick={()=>updateCycle(selected.status==='open'?'closed':'open')} isLoading={busy}>{selected.status==='open'?'إغلاق التسجيل':'فتح التسجيل'}</Button>}</div></div><div className="mt-3 flex items-center gap-2 rounded-xl bg-slate-50 p-3 font-mono text-xs"><Link2 className="h-4 w-4"/>{location.origin}{selected.public_url}</div></Card>
      <Card className="flex flex-wrap items-center justify-between gap-3 border-teal-100 bg-teal-50/40 p-4"><div><h3 className="font-bold text-teal-950">قائمة الطلبة وحالتهم الأكاديمية</h3><p className="mt-1 text-xs text-teal-800">تُدار مركزيًا من دليل الطلاب، ثم تُربط بهذه الدورة والمجموعات الرئيسية أثناء الاستيراد.</p></div><Link to="/directory" className="inline-flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2 text-xs font-bold text-white"><Users className="h-4 w-4"/>فتح دليل الطلاب</Link></Card>
      <div className="grid gap-5 xl:grid-cols-3">{selected.groups.map(g=><Card key={g.id} className="overflow-hidden border-slate-200"><div className="flex items-center justify-between border-b bg-slate-50 px-5 py-4"><div><h3 className="text-xl font-black text-slate-900">المجموعة {g.name}</h3><p className="mt-0.5 text-xs text-slate-500">{g.subgroups.reduce((n,s)=>n+s.current_students_count,0)} طالب مسجل</p></div>{can('group_registration.manage_groups')&&<button onClick={()=>addSub(g)} className="rounded-xl bg-teal-600 p-2.5 text-white shadow-sm" title="إضافة مجموعة فرعية"><Plus className="h-4 w-4"/></button>}</div><div className="space-y-3 p-4">{g.subgroups.map(s=>{const cap=s.capacity||s.max_size;const count=s.current_students_count||0;const full=count>=cap;return <div key={s.id} className={`rounded-2xl border p-4 ${!s.is_active?'opacity-50':full?'border-amber-200 bg-amber-50/40':'border-slate-200 bg-white'}`}><div className="flex items-start justify-between gap-3"><div><button onClick={()=>can('group_registration.manage_groups')&&editSub(s)} className="text-lg font-black text-slate-900">{s.name}</button><div className="mt-1 flex items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${full?'bg-amber-100 text-amber-800':'bg-emerald-100 text-emerald-700'}`}>{full?'مكتملة':`${cap-count} مقعد متاح`}</span><span className="text-xs font-bold text-slate-500">{count}/{cap}</span></div></div>{can('group_registration.manage_groups')&&<button onClick={()=>removeSub(s)} className="rounded-lg p-2 text-red-500 hover:bg-red-50" title="حذف أو أرشفة"><Trash2 className="h-4 w-4"/></button>}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${full?'bg-amber-500':'bg-teal-500'}`} style={{width:`${Math.min(100,(count/cap)*100)}%`}}/></div><div className="mt-3 space-y-1.5">{s.registered_students?.length?s.registered_students.map(student=><div key={student.id} className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-teal-100 text-teal-700"><UserRound className="h-3.5 w-3.5"/></div><div className="min-w-0"><p className="truncate text-xs font-bold text-slate-800">{student.name}</p><p className="font-mono text-[10px] text-slate-500">{student.university_number}</p></div></div>):<p className="rounded-xl border border-dashed p-3 text-center text-xs text-slate-400">لم يسجل أي طالب بعد</p>}</div></div>})}</div></Card>)}</div>
    </>}
  </div>;
}
