import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowRight, BookOpenCheck, CheckCircle2, Download, ExternalLink, FileUp, Search, Send, Trash2, XCircle } from 'lucide-react';
import * as XLSX from 'xlsx';
import { bulkRecordPaperReceipt, closePolicyCampaign, deletePolicyCampaign, downloadPrivateFile, getPolicyCampaign, publishPolicyCampaign, recordPaperReceipt, recordPolicyExport, uploadPolicyScan, type PolicyAssignment } from '@/api/studentPolicies';
import { useAuth } from '@/auth/AuthContext';
import { LoadingState } from '@/components/ui/LoadingState';
import { Modal } from '@/components/ui/Modal';

const levelLabel: Record<string,string> = { fourth: 'الرابعة', fifth: 'الخامسة', sixth: 'السادسة' };
const milestone = (row: PolicyAssignment) => row.scan_attached ? 'نسخة مرفوعة' : row.paper_received_at ? 'مستلم ورقيًا' : row.acknowledged_at ? 'أقرّ بالقراءة' : row.opened_at ? 'فتح الوثيقة' : 'لم يفتح';

export function StudentPolicyCampaignPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const { can } = useAuth(); const manage = can('student_policies.manage'); const qc = useQueryClient();
  const [search, setSearch] = useState(''); const [level, setLevel] = useState(''); const [status, setStatus] = useState(''); const [selected, setSelected] = useState<number[]>([]); const [notice, setNotice] = useState(''); const [deleteOpen,setDeleteOpen]=useState(false); const [deleteConfirmation,setDeleteConfirmation]=useState('');
  const queryString = useMemo(() => { const p = new URLSearchParams({ per_page: '2000' }); if(search)p.set('search',search); if(level)p.set('level',level); if(status)p.set('milestone',status); return `?${p}`; }, [search,level,status]);
  const details = useQuery({ queryKey: ['student-policy', id, queryString], queryFn: () => getPolicyCampaign(id, queryString) });
  const refresh = () => qc.invalidateQueries({ queryKey: ['student-policy', id] });
  const action = useMutation({ mutationFn: async (fn:()=>Promise<unknown>) => fn(), onSuccess: () => { setNotice('تم حفظ التحديث بنجاح.'); refresh(); }, onError: (e:Error)=>setNotice(e.message) });
  const remove = useMutation({ mutationFn: () => deletePolicyCampaign(Number(id), deleteConfirmation), onSuccess: () => navigate('/student-policies', { replace: true }), onError: (e:Error) => setNotice(e.message) });
  if (details.isLoading) return <LoadingState />;
  if (!details.data) return <p className="p-8 text-center text-red-700">تعذر تحميل الحملة.</p>;
  const { campaign } = details.data; const rows = details.data.assignments.data ?? [];
  const exportRows = async () => { await recordPolicyExport(campaign.id); const data = rows.map(r=>({ 'الرقم الجامعي':r.student.university_number,'اسم الطالب':r.student.full_name_ar,'السنة':levelLabel[r.student.academic_level]??r.student.academic_level,'فتح الوثيقة':r.opened_at?'نعم':'لا','أقر بالقراءة':r.acknowledged_at?'نعم':'لا','استلام الورقة':r.paper_received_at?'نعم':'لا','النسخة الموقعة':r.scan_attached?'مرفوعة':'غير مرفوعة' })); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'المتابعة'); XLSX.writeFile(wb,`code-of-conduct-${campaign.document.version_label}.xlsx`); };

  return <div className="space-y-4" dir="rtl">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><Link to="/student-policies" className="mb-2 inline-flex items-center gap-1 text-sm font-bold text-teal-700"><ArrowRight className="h-4 w-4"/>كل الحملات</Link><h1 className="text-xl font-black text-slate-900">{campaign.document.title_ar}</h1><p className="mt-1 text-sm text-slate-500">الإصدار {campaign.document.version_label} · {campaign.academic_year?.code} · آخر موعد {campaign.deadline}</p></div><div className="flex flex-wrap gap-2"><a target="_blank" href={`/api/v1/student-policies/campaigns/${campaign.id}/document?language=ar`} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold"><BookOpenCheck className="ml-2 inline h-4 w-4"/>النسخة العربية</a>{campaign.document.has_english_document&&<a target="_blank" href={`/api/v1/student-policies/campaigns/${campaign.id}/document?language=en`} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold"><BookOpenCheck className="ml-2 inline h-4 w-4"/>English version</a>}<button onClick={exportRows} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold"><Download className="ml-2 inline h-4 w-4"/>تصدير Excel</button>{campaign.status==='published'&&<a target="_blank" href={`/portal/student-policies/${campaign.public_id}`} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold"><ExternalLink className="ml-2 inline h-4 w-4"/>الرابط العام</a>}{manage&&campaign.status==='draft'&&<button onClick={()=>action.mutate(()=>publishPolicyCampaign(campaign.id))} className="rounded-xl bg-teal-700 px-4 py-2 text-sm font-bold text-white"><Send className="ml-2 inline h-4 w-4"/>نشر الحملة</button>}{manage&&campaign.status==='published'&&<button onClick={()=>confirm('إغلاق الحملة ومنع الإقرارات الجديدة؟')&&action.mutate(()=>closePolicyCampaign(campaign.id))} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-bold text-red-700"><XCircle className="ml-2 inline h-4 w-4"/>إغلاق</button>}{manage&&<button onClick={()=>{setDeleteConfirmation('');setDeleteOpen(true)}} className="rounded-xl border border-red-200 bg-red-50 px-4 py-2 text-sm font-bold text-red-700"><Trash2 className="ml-2 inline h-4 w-4"/>حذف الحملة نهائيًا</button>}</div></div>
    {notice&&<div className="rounded-xl bg-teal-50 p-3 text-sm font-bold text-teal-800">{notice}</div>}
    <div className="grid grid-cols-2 gap-2 lg:grid-cols-5">{[['الإجمالي','total'],['لم يفتح','not_opened'],['أقرّ بالقراءة','acknowledged'],['مستلم ورقيًا','paper_received'],['نسخة مرفوعة','scan_attached']].map(([label,key])=><div key={key} className="rounded-xl border bg-white p-3"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-xl font-black">{campaign.counts?.[key]??0}</p></div>)}</div>
    <div className="flex flex-col gap-2 rounded-2xl border bg-white p-3 md:flex-row"><label className="relative flex-1"><Search className="absolute right-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث باسم الطالب أو رقمه" className="w-full rounded-xl border py-2.5 pr-9 pl-3 text-sm"/></label><select value={level} onChange={e=>setLevel(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">كل السنوات</option>{Object.entries(levelLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">كل الحالات</option><option value="not_opened">لم يفتح</option><option value="opened">فتح ولم يقر</option><option value="acknowledged">أقر بالقراءة</option><option value="paper_received">مستلم ورقيًا</option><option value="scan_attached">نسخة مرفوعة</option></select>{manage&&selected.length>0&&<button onClick={()=>confirm(`تسجيل استلام ${selected.length} نسخة ورقية؟`)&&action.mutate(async()=>{await bulkRecordPaperReceipt(selected);setSelected([])})} className="rounded-xl bg-teal-700 px-4 py-2 text-sm font-bold text-white">تسجيل استلام ({selected.length})</button>}</div>
    <div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{manage&&<th className="p-3"><input aria-label="تحديد الجميع" type="checkbox" checked={rows.length>0&&selected.length===rows.length} onChange={e=>setSelected(e.target.checked?rows.map(r=>r.id):[])}/></th>}<th className="p-3 text-right">الطالب</th><th className="p-3 text-right">السنة</th><th className="p-3 text-right">الحالة الحالية</th><th className="p-3 text-right">الإقرار الإلكتروني</th><th className="p-3 text-right">النسخة الورقية</th><th className="p-3 text-right">المرفق الخاص</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100">{manage&&<td className="p-3"><input aria-label={`تحديد ${r.student.full_name_ar}`} type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(x=>x!==r.id))}/></td>}<td className="p-3"><b>{r.student.full_name_ar}</b><span className="block text-xs text-slate-500">{r.student.university_number}</span></td><td className="p-3">{levelLabel[r.student.academic_level]}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{milestone(r)}</span></td><td className="p-3">{r.acknowledged_at?<span className="text-emerald-700"><CheckCircle2 className="ml-1 inline h-4 w-4"/>موثق</span>:'—'}</td><td className="p-3">{r.paper_received_at?'تم الاستلام':manage?<button onClick={()=>action.mutate(()=>recordPaperReceipt(r.id))} className="font-bold text-teal-700">تسجيل الاستلام</button>:'غير مستلمة'}</td><td className="p-3">{r.scan_attached?<button onClick={()=>downloadPrivateFile(`/student-policies/assignments/${r.id}/scan`,r.scan_name||'signed.pdf')} className="font-bold text-teal-700">تنزيل النسخة</button>:manage?<label className="inline-flex cursor-pointer items-center gap-1 font-bold text-teal-700"><FileUp className="h-4 w-4"/>رفع نسخة<input className="hidden" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)action.mutate(()=>uploadPolicyScan(r.id,f))}}/></label>:'—'}</td></tr>)}</tbody></table></div>{rows.length===0&&<p className="p-10 text-center text-slate-500">لا توجد نتائج مطابقة.</p>}</div>
    <Modal isOpen={deleteOpen} onClose={()=>!remove.isPending&&setDeleteOpen(false)} title="حذف الحملة نهائيًا" maxWidth="sm" backdropTone="light"><div className="space-y-4"><p className="text-sm leading-6 text-slate-600">سيحذف النظام الحملة وملفاتها نهائيًا. لا يمكن حذف حملة بدأ أي طالب بالتفاعل معها.</p><label className="block text-sm font-bold text-slate-700">اكتب «حذف الحملة» للتأكيد<input autoFocus value={deleteConfirmation} onChange={e=>setDeleteConfirmation(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label>{remove.isError&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{(remove.error as Error).message}</p>}<div className="flex gap-2"><button type="button" disabled={deleteConfirmation!=='حذف الحملة'||remove.isPending} onClick={()=>remove.mutate()} className="rounded-xl bg-red-700 px-4 py-2.5 text-sm font-bold text-white disabled:bg-slate-300">{remove.isPending?'جارٍ الحذف...':'تأكيد الحذف النهائي'}</button><button type="button" disabled={remove.isPending} onClick={()=>setDeleteOpen(false)} className="rounded-xl border px-4 py-2.5 text-sm font-bold">إلغاء</button></div></div></Modal>
  </div>;
}
