import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, CalendarClock, Check, CheckCircle2, ChevronLeft, ChevronRight, CircleDot, ExternalLink, MessageSquare, Pencil, Plus, RefreshCw, Search, Send, Trash2, UserRound, X } from 'lucide-react';
import { apiFetch, apiFetchEnvelope, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { LoadingState } from '@/components/ui/LoadingState';
import { PageHeader } from '@/components/ui/PageHeader';

type UserOption = { id: number; name: string; email: string; person?: { full_name_ar?: string; full_name_en?: string } };
type TaskStatus = 'open' | 'in_progress' | 'completed' | 'cancelled';
type TaskPriority = 'low' | 'normal' | 'high';
type TaskComment = { id: number; body: string; created_at: string; user?: UserOption };
type Activity = { id: number; action: string; created_at: string; user?: UserOption };
type Task = { id:number; title:string; description?:string|null; due_date?:string|null; priority:TaskPriority; status:TaskStatus; created_by:number; assigned_to:number|null; can_execute?:boolean; can_manage?:boolean; can_delete?:boolean; comments_count?:number; creator?:UserOption|null; assignee?:UserOption|null; source_type?:string|null; source_id?:number|null; completion_notes?:string|null; comments?:TaskComment[]; activity?:Activity[]; meeting_action_item?:{meeting?:{id:number;minutes_number:string}}|null };
type Summary = { mine:number; assigned:number; created:number; overdue:number; completed:number };
type ViewKey = keyof Summary;
type UpdateMutation = { mutate:(value:{id:number;body:object})=>void; isPending:boolean };
type CommentMutation = { mutate:(value:{id:number;body:string})=>void; isPending:boolean };
type DeleteMutation = { mutate:(id:number)=>void };
const blank = { title:'', description:'', assigned_to:'', due_date:'', priority:'normal' as TaskPriority };
const fieldClass = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-100';

export function TasksPage() {
  const { can } = useAuth();
  const { locale, t } = useI18n();
  const ar = locale === 'ar';
  const qc = useQueryClient();
  const [urlParams,setUrlParams] = useSearchParams();
  const [view,setView] = useState<ViewKey>('mine');
  const [search,setSearch] = useState('');
  const [status,setStatus] = useState('');
  const [due,setDue] = useState('');
  const [page,setPage] = useState(1);
  const [createOpen,setCreateOpen] = useState(false);
  const [form,setForm] = useState(blank);
  const [editTask,setEditTask] = useState<Task|null>(null);
  const [comment,setComment] = useState('');
  const [completion,setCompletion] = useState('');
  const [error,setError] = useState('');
  const selectedId = Number(urlParams.get('task')) || null;
  const qs = useMemo(()=>{const p=new URLSearchParams({per_page:'25',page:String(page),view});if(search.trim())p.set('search',search.trim());if(status)p.set('status',status);if(due)p.set('due',due);return p.toString();},[due,page,search,status,view]);
  useEffect(()=>setPage(1),[due,search,status,view]);
  const tasksQuery=useQuery({queryKey:['operational-tasks',qs],queryFn:()=>apiFetchEnvelope<Task[]>(`/operational-tasks?${qs}`),refetchInterval:15000});
  const detailQuery=useQuery({queryKey:['operational-task',selectedId],queryFn:()=>apiFetch<Task>(`/operational-tasks/${selectedId}`),enabled:selectedId!==null,refetchInterval:selectedId?15000:false});
  const {data:users=[]}=useQuery({queryKey:['users-lookup','tasks'],queryFn:()=>apiFetch<UserOption[]>('/users/lookup'),enabled:(createOpen||Boolean(editTask))&&can('tasks.manage')});
  const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['operational-tasks']}),qc.invalidateQueries({queryKey:['operational-task']}),qc.invalidateQueries({queryKey:['notifications']})]);};
  const fail=(e:unknown)=>setError(e instanceof ApiError?e.message:(ar?'تعذر تنفيذ الإجراء.':'Action failed.'));
  const setTaskInUrl=(id:number)=>{const next=new URLSearchParams(urlParams);next.set('task',String(id));setUrlParams(next);};
  const closeTask=()=>{const next=new URLSearchParams(urlParams);next.delete('task');setUrlParams(next);};
  const create=useMutation({mutationFn:()=>apiFetch<Task>('/operational-tasks',{method:'POST',body:{...form,assigned_to:Number(form.assigned_to),due_date:form.due_date||null}}),onSuccess:async task=>{setCreateOpen(false);setForm(blank);setError('');setTaskInUrl(task.id);await refresh();},onError:fail});
  const update=useMutation({mutationFn:({id,body}:{id:number;body:object})=>apiFetch<Task>(`/operational-tasks/${id}`,{method:'PUT',body}),onSuccess:async()=>{setCompletion('');setEditTask(null);setError('');await refresh();},onError:fail});
  const addComment=useMutation({mutationFn:({id,body}:{id:number;body:string})=>apiFetch(`/operational-tasks/${id}/comments`,{method:'POST',body:{body}}),onSuccess:async()=>{setComment('');setError('');await refresh();},onError:fail});
  const remove=useMutation({mutationFn:(id:number)=>apiFetch(`/operational-tasks/${id}`,{method:'DELETE'}),onSuccess:async()=>{closeTask();await refresh();},onError:fail});
  if(!can('tasks.view'))return <ErrorState title={t('state.forbidden.title')} message={t('state.forbidden.message')}/>;
  if(tasksQuery.isLoading)return <LoadingState/>;
  if(tasksQuery.isError)return <ErrorState onRetry={()=>tasksQuery.refetch()}/>;
  const tasks=tasksQuery.data?.data??[]; const meta=tasksQuery.data?.meta??{};
  const summary=(meta.summary??{mine:0,assigned:0,created:0,overdue:0,completed:0}) as Summary;
  const currentPage=Number(meta.current_page??1),lastPage=Number(meta.last_page??1);
  const label=(v:string)=>({open:ar?'مفتوحة':'Open',in_progress:ar?'قيد التنفيذ':'In progress',completed:ar?'مكتملة':'Completed',cancelled:ar?'ملغاة':'Cancelled'}[v]??v);
  const priorityLabel=(v:string)=>({high:ar?'عالية':'High',normal:ar?'عادية':'Normal',low:ar?'منخفضة':'Low'}[v]??v);
  const nameOf=(u?:UserOption|null)=>(ar?u?.person?.full_name_ar:u?.person?.full_name_en)||u?.name||u?.email||'—';
  const dateOnly=(v?:string|null)=>v?new Intl.DateTimeFormat(locale,{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v)):'—';
  const dateTime=(v?:string|null)=>v?new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
  const overdue=(task:Task)=>Boolean(task.due_date&&!['completed','cancelled'].includes(task.status)&&task.due_date.slice(0,10)<new Date().toISOString().slice(0,10));
  const allTabs:{key:ViewKey;ar:string;en:string}[]=[{key:'mine',ar:'الكل',en:'All'},{key:'assigned',ar:'مكلّف بها',en:'Assigned'},{key:'created',ar:'أنشأتها',en:'Created'},{key:'overdue',ar:'متأخرة',en:'Overdue'},{key:'completed',ar:'مكتملة',en:'Completed'}];
  const tabs=allTabs.filter(tab=>tab.key!=='created'||can('tasks.manage'));
  return <div className="mx-auto max-w-[1320px] space-y-4 pb-10">
    <PageHeader title={ar?'المهام':'Tasks'} description={ar?'مساحة عملية لمتابعة التكليفات والإنجاز دون تعقيد.':'A focused workspace for assignments and delivery.'}><div className="flex gap-2"><Button variant="outline" onClick={()=>void refresh()} aria-label={ar?'تحديث':'Refresh'}><RefreshCw className="h-4 w-4"/></Button>{can('tasks.manage')&&<Button onClick={()=>setCreateOpen(true)}><Plus className="me-2 h-4 w-4"/>{ar?'مهمة جديدة':'New task'}</Button>}</div></PageHeader>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="flex gap-1 overflow-x-auto border-b border-slate-200 px-3 pt-2">{tabs.map(tab=><button key={tab.key} onClick={()=>setView(tab.key)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-semibold transition ${view===tab.key?'border-teal-600 text-teal-700':'border-transparent text-slate-500 hover:text-slate-800'}`}>{ar?tab.ar:tab.en}<span className={`ms-2 rounded-full px-2 py-0.5 text-[11px] ${view===tab.key?'bg-teal-50':'bg-slate-100'}`}>{summary[tab.key]}</span></button>)}</div>
      <div className="grid gap-2 border-b border-slate-200 bg-slate-50/60 p-3 md:grid-cols-[1fr_180px_180px]"><label className="relative"><Search className="absolute start-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className={`${fieldClass} ps-10`} placeholder={ar?'ابحث بالعنوان أو التفاصيل':'Search title or details'}/></label><select value={status} onChange={e=>setStatus(e.target.value)} className={fieldClass}><option value="">{ar?'كل الحالات':'All statuses'}</option>{['open','in_progress','completed','cancelled'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select value={due} onChange={e=>setDue(e.target.value)} className={fieldClass}><option value="">{ar?'كل المواعيد':'All due dates'}</option><option value="today">{ar?'اليوم':'Today'}</option><option value="week">{ar?'خلال 7 أيام':'Next 7 days'}</option><option value="overdue">{ar?'متأخرة':'Overdue'}</option><option value="none">{ar?'دون موعد':'No due date'}</option></select></div>
      {error&&<p className="m-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}
      {!tasks.length?<div className="p-8"><EmptyState message={ar?'لا توجد مهام مطابقة.':'No matching tasks.'}/></div>:<><div className="hidden grid-cols-[minmax(260px,1fr)_200px_135px_120px_48px] gap-3 border-b border-slate-200 px-4 py-2.5 text-xs font-semibold text-slate-500 md:grid"><span>{ar?'المهمة':'Task'}</span><span>{ar?'المكلّف':'Assignee'}</span><span>{ar?'الموعد':'Due date'}</span><span>{ar?'الحالة':'Status'}</span><span/></div><div className="divide-y divide-slate-100">{tasks.map(task=><button key={task.id} onClick={()=>setTaskInUrl(task.id)} className={`grid w-full gap-3 px-4 py-3 text-start transition hover:bg-slate-50 md:grid-cols-[minmax(260px,1fr)_200px_135px_120px_48px] md:items-center ${selectedId===task.id?'bg-teal-50/60':''}`}><span className="min-w-0"><span className="flex items-center gap-2"><span className={`h-2 w-2 shrink-0 rounded-full ${task.status==='completed'?'bg-emerald-500':overdue(task)?'bg-red-500':task.status==='in_progress'?'bg-amber-500':'bg-teal-500'}`}/><span className={`truncate text-sm font-semibold text-slate-800 ${task.status==='completed'?'line-through opacity-60':''}`}>{task.title}</span>{task.comments_count?<span className="inline-flex items-center gap-1 text-[11px] text-slate-400"><MessageSquare className="h-3 w-3"/>{task.comments_count}</span>:null}</span><span className="mt-1 block truncate ps-4 text-xs text-slate-400">{task.description||(ar?'بدون تفاصيل إضافية':'No additional details')}</span></span><span className="flex items-center gap-2 text-xs text-slate-600"><UserRound className="h-4 w-4 shrink-0 text-slate-400"/><span className="truncate">{nameOf(task.assignee)}</span></span><span className={`flex items-center gap-1 text-xs ${overdue(task)?'font-bold text-red-600':'text-slate-600'}`}><CalendarClock className="h-4 w-4"/>{dateOnly(task.due_date)}</span><span><StatusBadge status={task.status} text={label(task.status)}/></span><span className="hidden justify-end md:flex">{ar?<ChevronLeft className="h-4 w-4 text-slate-400"/>:<ChevronRight className="h-4 w-4 text-slate-400"/>}</span></button>)}</div>{lastPage>1&&<div className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-xs text-slate-500"><span>{ar?`صفحة ${currentPage} من ${lastPage}`:`Page ${currentPage} of ${lastPage}`}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={currentPage<=1} onClick={()=>setPage(p=>p-1)}>{ar?<ChevronRight className="h-4 w-4"/>:<ChevronLeft className="h-4 w-4"/>}</Button><Button size="sm" variant="outline" disabled={currentPage>=lastPage} onClick={()=>setPage(p=>p+1)}>{ar?<ChevronLeft className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</Button></div></div>}</>}
    </section>
    {createOpen&&<Modal title={ar?'مهمة جديدة':'New task'} onClose={()=>setCreateOpen(false)}><form onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate();}} className="space-y-3"><input autoFocus required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={fieldClass} placeholder={ar?'عنوان واضح للمهمة':'Clear task title'}/><select required value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})} className={fieldClass}><option value="">{ar?'اختر المكلّف':'Choose assignee'}</option>{users.map(u=><option key={u.id} value={u.id}>{nameOf(u)} — {u.email}</option>)}</select><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className={fieldClass} placeholder={ar?'النتيجة المطلوبة أو تعليمات التنفيذ (اختياري)':'Expected outcome or instructions (optional)'}/><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-xs text-slate-500"><span>{ar?'موعد الإنجاز':'Due date'}</span><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})} className={fieldClass}/></label><label className="space-y-1 text-xs text-slate-500"><span>{ar?'الأولوية':'Priority'}</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as TaskPriority})} className={fieldClass}><option value="low">{priorityLabel('low')}</option><option value="normal">{priorityLabel('normal')}</option><option value="high">{priorityLabel('high')}</option></select></label></div><div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><Button type="button" variant="outline" onClick={()=>setCreateOpen(false)}>{ar?'إلغاء':'Cancel'}</Button><Button type="submit" isLoading={create.isPending}>{ar?'إنشاء وتكليف':'Create and assign'}</Button></div></form></Modal>}
    {editTask&&<Modal title={ar?'تعديل المهمة':'Edit task'} onClose={()=>setEditTask(null)}><form onSubmit={(e:FormEvent)=>{e.preventDefault();update.mutate({id:editTask.id,body:{title:editTask.title,description:editTask.description||null,assigned_to:Number(editTask.assigned_to),due_date:editTask.due_date?.slice(0,10)||null,priority:editTask.priority}});}} className="space-y-3"><input required value={editTask.title} onChange={e=>setEditTask({...editTask,title:e.target.value})} className={fieldClass}/><select required value={editTask.assigned_to??''} onChange={e=>setEditTask({...editTask,assigned_to:Number(e.target.value)})} className={fieldClass}><option value="">{ar?'اختر المكلّف':'Choose assignee'}</option>{users.map(u=><option key={u.id} value={u.id}>{nameOf(u)} — {u.email}</option>)}</select><textarea rows={4} value={editTask.description||''} onChange={e=>setEditTask({...editTask,description:e.target.value})} className={fieldClass}/><div className="grid gap-3 sm:grid-cols-2"><input type="date" value={editTask.due_date?.slice(0,10)||''} onChange={e=>setEditTask({...editTask,due_date:e.target.value})} className={fieldClass}/><select value={editTask.priority} onChange={e=>setEditTask({...editTask,priority:e.target.value as TaskPriority})} className={fieldClass}><option value="low">{priorityLabel('low')}</option><option value="normal">{priorityLabel('normal')}</option><option value="high">{priorityLabel('high')}</option></select></div><div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><Button type="button" variant="outline" onClick={()=>setEditTask(null)}>{ar?'إلغاء':'Cancel'}</Button><Button type="submit" isLoading={update.isPending}>{ar?'حفظ التعديلات':'Save changes'}</Button></div></form></Modal>}
    {selectedId&&<TaskDrawer task={detailQuery.data} loading={detailQuery.isLoading} error={detailQuery.isError} ar={ar} onClose={closeTask} onEdit={setEditTask} nameOf={nameOf} dateOnly={dateOnly} dateTime={dateTime} label={label} priorityLabel={priorityLabel} completion={completion} setCompletion={setCompletion} comment={comment} setComment={setComment} update={update as UpdateMutation} addComment={addComment as CommentMutation} remove={remove as DeleteMutation}/>}
  </div>;
}

function TaskDrawer({task,loading,error,ar,onClose,onEdit,nameOf,dateOnly,dateTime,label,priorityLabel,completion,setCompletion,comment,setComment,update,addComment,remove}:{task?:Task;loading:boolean;error:boolean;ar:boolean;onClose:()=>void;onEdit:(task:Task)=>void;nameOf:(u?:UserOption|null)=>string;dateOnly:(v?:string|null)=>string;dateTime:(v?:string|null)=>string;label:(v:string)=>string;priorityLabel:(v:string)=>string;completion:string;setCompletion:(v:string)=>void;comment:string;setComment:(v:string)=>void;update:UpdateMutation;addComment:CommentMutation;remove:DeleteMutation}){
  const activities:Record<string,string>={'task.created':ar?'أنشأ المهمة':'Created the task','task.updated':ar?'حدّث المهمة':'Updated the task','task.comment_added':ar?'أضاف تعليقًا':'Added a comment'};
  return <div className="fixed inset-0 z-50 bg-slate-900/25 backdrop-blur-[1px]" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><aside dir={ar?'rtl':'ltr'} className={`absolute inset-y-0 w-full max-w-xl overflow-y-auto bg-white shadow-2xl ${ar?'left-0':'right-0'}`}><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white/95 px-5 py-4 backdrop-blur"><div className="flex items-center gap-2"><button onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100">{ar?<ArrowLeft className="h-5 w-5"/>:<ArrowRight className="h-5 w-5"/>}</button><span className="text-sm font-bold text-slate-700">{ar?'تفاصيل المهمة':'Task details'}</span></div>{task&&<StatusBadge status={task.status} text={label(task.status)}/>}</div>{loading&&<LoadingState/>}{error&&<div className="p-6"><ErrorState/></div>}{task&&<div className="space-y-6 p-5"><div><h2 className="text-xl font-bold leading-8 text-slate-900">{task.title}</h2>{task.description&&<p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-600">{task.description}</p>}</div><div className="grid grid-cols-2 gap-4 rounded-xl bg-slate-50 p-4 text-xs"><Info label={ar?'المكلّف':'Assignee'} value={nameOf(task.assignee)}/><Info label={ar?'أنشأها':'Created by'} value={nameOf(task.creator)}/><Info label={ar?'موعد الإنجاز':'Due date'} value={dateOnly(task.due_date)}/><Info label={ar?'الأولوية':'Priority'} value={priorityLabel(task.priority)}/></div>
    {(task.meeting_action_item?.meeting||(task.source_type?.includes('Correspondence')&&task.source_id))&&<div className="flex flex-wrap gap-2">{task.meeting_action_item?.meeting&&<Link to={`/meetings/${task.meeting_action_item.meeting.id}`} className="inline-flex items-center gap-1 rounded-lg bg-slate-50 px-3 py-2 text-xs font-semibold text-teal-700"><ExternalLink className="h-3.5 w-3.5"/>{task.meeting_action_item.meeting.minutes_number}</Link>}{task.source_type?.includes('Correspondence')&&task.source_id&&<Link to={`/correspondence/${task.source_id}`} className="inline-flex items-center gap-1 rounded-lg bg-slate-50 px-3 py-2 text-xs font-semibold text-teal-700"><ExternalLink className="h-3.5 w-3.5"/>{ar?'فتح المراسلة المصدر':'Open source message'}</Link>}</div>}
    <section className="rounded-xl border border-slate-200 p-4"><h3 className="mb-3 text-sm font-bold text-slate-800">{ar?'الإجراء':'Action'}</h3><div className="flex flex-wrap gap-2">{task.can_manage&&<Button size="sm" variant="outline" onClick={()=>onEdit(task)}><Pencil className="me-1 h-4 w-4"/>{ar?'تعديل':'Edit'}</Button>}{task.can_execute&&task.status==='open'&&<Button size="sm" onClick={()=>update.mutate({id:task.id,body:{status:'in_progress'}})}><CircleDot className="me-1 h-4 w-4"/>{ar?'بدء التنفيذ':'Start'}</Button>}{task.can_manage&&!['completed','cancelled'].includes(task.status)&&<Button size="sm" variant="outline" onClick={()=>update.mutate({id:task.id,body:{status:'cancelled'}})}>{ar?'إلغاء المهمة':'Cancel task'}</Button>}{task.can_manage&&['completed','cancelled'].includes(task.status)&&<Button size="sm" variant="outline" onClick={()=>update.mutate({id:task.id,body:{status:'open'}})}>{ar?'إعادة فتح':'Reopen'}</Button>}{task.can_delete&&<Button size="sm" variant="outline" onClick={()=>remove.mutate(task.id)}><Trash2 className="me-1 h-4 w-4"/>{ar?'حذف':'Delete'}</Button>}</div>{task.can_execute&&!['completed','cancelled'].includes(task.status)&&<form onSubmit={e=>{e.preventDefault();update.mutate({id:task.id,body:{status:'completed',completion_notes:completion}});}} className="mt-3 flex gap-2"><input required value={completion} onChange={e=>setCompletion(e.target.value)} className={fieldClass} placeholder={ar?'ملخص الإنجاز أو رابط الدليل':'Completion summary or evidence link'}/><Button type="submit" isLoading={update.isPending}><Check className="me-1 h-4 w-4"/>{ar?'إنجاز':'Complete'}</Button></form>}{task.completion_notes&&<p className="mt-3 rounded-lg bg-emerald-50 p-3 text-xs leading-6 text-emerald-800"><CheckCircle2 className="me-1 inline h-4 w-4"/>{task.completion_notes}</p>}</section>
    <section><h3 className="mb-3 flex items-center gap-2 text-sm font-bold text-slate-800"><MessageSquare className="h-4 w-4 text-teal-600"/>{ar?'التعليقات':'Comments'} <span className="text-xs font-normal text-slate-400">({task.comments?.length??0})</span></h3><div className="space-y-2">{task.comments?.map(item=><div key={item.id} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-3 text-xs"><strong className="text-slate-700">{nameOf(item.user)}</strong><span className="text-slate-400">{dateTime(item.created_at)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.body}</p></div>)}{!task.comments?.length&&<p className="text-xs text-slate-400">{ar?'لا توجد تعليقات بعد.':'No comments yet.'}</p>}</div><form onSubmit={e=>{e.preventDefault();if(comment.trim())addComment.mutate({id:task.id,body:comment.trim()});}} className="mt-3 flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} className={fieldClass} placeholder={ar?'اكتب تحديثًا أو استفسارًا...':'Write an update or question...'}/><Button type="submit" disabled={!comment.trim()} isLoading={addComment.isPending}><Send className="h-4 w-4"/></Button></form></section>
    <section className="border-t border-slate-200 pt-5"><h3 className="mb-3 text-sm font-bold text-slate-800">{ar?'سجل النشاط':'Activity'}</h3><div className="space-y-3">{task.activity?.map(item=><div key={item.id} className="flex gap-3 text-xs"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-teal-500"/><div><p className="text-slate-600"><strong>{nameOf(item.user)}</strong> {activities[item.action]??item.action}</p><p className="mt-0.5 text-slate-400">{dateTime(item.created_at)}</p></div></div>)}</div></section></div>}</aside></div>;
}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="w-full max-w-xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="font-bold text-slate-800">{title}</h2><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="h-5 w-5"/></button></div><div className="p-5">{children}</div></div></div>}
function StatusBadge({status,text}:{status:TaskStatus;text:string}){const cls={open:'bg-slate-100 text-slate-700',in_progress:'bg-amber-50 text-amber-700',completed:'bg-emerald-50 text-emerald-700',cancelled:'bg-red-50 text-red-700'}[status];return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${cls}`}>{text}</span>}
function Info({label,value}:{label:string;value:string}){return <div><span className="block text-slate-400">{label}</span><strong className="mt-1 block text-slate-700">{value}</strong></div>}
