import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, Save, Settings2, Trash2 } from 'lucide-react';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Button } from '@/components/ui/Button';
import type { AssessmentTemplate } from './supervisorWorkspace';

type Course={id:number;code:string;name_ar:string;name_en?:string|null;academic_level?:number};
type CriteriaResponse={templates:AssessmentTemplate[];courses:Course[];batch_years:number[]};
type Draft={name_ar:string;name_en:string;criteria:Array<{name_ar:string;name_en:string;max_score:string}>};
const blank=():Draft=>({name_ar:'نموذج التقييم السريري الأسبوعي',name_en:'Weekly Clinical Assessment',criteria:[{name_ar:'',name_en:'',max_score:'2'}]});

export function AssessmentCriteriaPage(){
 const {can}=useAuth();const {locale}=useI18n();const ar=locale==='ar';const tr=(a:string,e:string)=>ar?a:e;const queryClient=useQueryClient();const [scope,setScope]=useState('global');const [batch,setBatch]=useState('all');const [draft,setDraft]=useState<Draft>(blank());const [done,setDone]=useState(false);
 const query=useQuery({queryKey:['clinical-assessment-templates'],queryFn:()=>apiFetch<CriteriaResponse>('/clinical-assessment-templates'),enabled:can('assessment.criteria.manage')});
 const current=query.data?.templates.find(item=>item.is_active!==false&&(scope==='global'?!item.course_id:item.course_id===Number(scope))&&(batch==='all'?!item.batch_year:item.batch_year===Number(batch)));
 useEffect(()=>{if(current)setDraft({name_ar:current.name_ar,name_en:current.name_en??'',criteria:current.criteria.map(item=>({name_ar:item.name_ar,name_en:item.name_en??'',max_score:String(item.max_score)}))});else setDraft(blank());setDone(false);},[scope,batch,current?.id]);
 const total=draft.criteria.reduce((sum,item)=>sum+(Number(item.max_score)||0),0);
 const save=useMutation({mutationFn:()=>apiFetch('/clinical-assessment-templates',{method:'POST',body:{name_ar:draft.name_ar,name_en:draft.name_en||null,course_id:scope==='global'?null:Number(scope),batch_year:batch==='all'?null:Number(batch),criteria:draft.criteria.map((item,index)=>({...item,code:`criterion_${index+1}`,max_score:Number(item.max_score)}))}}),onSuccess:async()=>{setDone(true);await queryClient.invalidateQueries({queryKey:['clinical-assessment-templates']});}});
 if(!can('assessment.criteria.manage'))return <ErrorState title={tr('الصلاحية غير مفعلة','Permission is disabled')}/>;if(query.isLoading)return <LoadingState/>;if(query.isError||!query.data)return <ErrorState onRetry={()=>query.refetch()}/>;
 return <div className="mx-auto max-w-5xl space-y-5 pb-16"><PageHeader title={tr('إعداد نموذج التقييم الأسبوعي','Weekly assessment template')} description={tr('أنشئ إصداراً معتمداً من 10 درجات. تبقى الإصدارات القديمة محفوظة مع تقييماتها.','Publish a 10-point template version. Previous versions remain attached to historical assessments.')}/>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="grid gap-4 lg:grid-cols-[1fr_220px_1fr]"><label className="text-xs font-bold text-slate-600"><span className="mb-2 block">{tr('المساق','Course')}</span><select value={scope} onChange={e=>setScope(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="global">{tr('نموذج عام لكل المساقات','Global template for all courses')}</option>{query.data.courses.map(course=><option key={course.id} value={course.id}>{course.code} — {ar?course.name_ar:course.name_en||course.name_ar}</option>)}</select></label><label className="text-xs font-bold text-slate-600"><span className="mb-2 block">{tr('دفعة القبول','Admission cohort')}</span><select value={batch} onChange={e=>setBatch(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="all">{tr('كل الدفعات','All cohorts')}</option>{query.data.batch_years.map(year=><option key={year} value={year}>{tr(`دفعة ${year}`,`Cohort ${year}`)}</option>)}</select></label><div className="rounded-2xl bg-teal-50 p-3 text-xs text-teal-800"><p className="font-black">{current?tr(`الإصدار الحالي: ${current.version}`,`Current version: ${current.version}`):tr('لا يوجد إصدار لهذا النطاق بعد','No version exists for this scope')}</p><p className="mt-1">{tr('النموذج الخاص بالمساق والدفعة له الأولوية، والحفظ لا يغير التقييمات السابقة.','The course-and-cohort template takes priority, and saving does not alter previous assessments.')}</p></div></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={draft.name_ar} onChange={e=>setDraft(d=>({...d,name_ar:e.target.value}))} placeholder="اسم النموذج بالعربية" className="rounded-xl border border-slate-200 px-3 py-2.5"/><input dir="ltr" value={draft.name_en} onChange={e=>setDraft(d=>({...d,name_en:e.target.value}))} placeholder="English template name" className="rounded-xl border border-slate-200 px-3 py-2.5"/></div>
  <div className="mt-6 flex items-center justify-between"><h2 className="flex items-center gap-2 font-black text-slate-900"><Settings2 className="h-5 w-5 text-teal-700"/>{tr('معايير التقييم','Assessment criteria')}</h2><span className={`rounded-xl px-3 py-1.5 text-sm font-black ${Math.abs(total-10)<.001?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{total.toFixed(2)} / 10</span></div>
  <div className="mt-3 space-y-3">{draft.criteria.map((item,index)=><div key={index} className="grid gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-3 md:grid-cols-[1fr_1fr_130px_40px]"><input value={item.name_ar} onChange={e=>setDraft(d=>({...d,criteria:d.criteria.map((row,i)=>i===index?{...row,name_ar:e.target.value}:row)}))} placeholder={tr('اسم المعيار بالعربية','Arabic criterion name')} className="rounded-lg border border-slate-200 bg-white px-3 py-2"/><input dir="ltr" value={item.name_en} onChange={e=>setDraft(d=>({...d,criteria:d.criteria.map((row,i)=>i===index?{...row,name_en:e.target.value}:row)}))} placeholder="English name" className="rounded-lg border border-slate-200 bg-white px-3 py-2"/><input type="number" min="0.25" max="10" step="0.25" value={item.max_score} onChange={e=>setDraft(d=>({...d,criteria:d.criteria.map((row,i)=>i===index?{...row,max_score:e.target.value}:row)}))} className="rounded-lg border border-slate-200 bg-white px-3 py-2 font-black"/><button type="button" disabled={draft.criteria.length===1} onClick={()=>setDraft(d=>({...d,criteria:d.criteria.filter((_,i)=>i!==index)}))} className="flex items-center justify-center rounded-lg text-red-600 hover:bg-red-50 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}</div>
  <div className="mt-5 flex flex-wrap items-center gap-3"><Button variant="outline" onClick={()=>setDraft(d=>({...d,criteria:[...d.criteria,{name_ar:'',name_en:'',max_score:'1'}]}))}><Plus className="h-4 w-4"/>{tr('إضافة معيار','Add criterion')}</Button><Button disabled={Math.abs(total-10)>.001||!draft.name_ar||draft.criteria.some(item=>!item.name_ar)} isLoading={save.isPending} onClick={()=>save.mutate()}><Save className="h-4 w-4"/>{tr('اعتماد إصدار جديد','Publish new version')}</Button>{done&&<span className="text-xs font-bold text-emerald-700">{tr('تم اعتماد النموذج بنجاح.','Template published successfully.')}</span>}</div>{save.isError&&<p className="mt-3 text-sm font-bold text-red-700">{tr('تعذر حفظ النموذج. تحقق من الحقول وأن المجموع 10.','Unable to save. Check fields and ensure the total is 10.')}</p>}
 </section></div>;
}
