import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, Save, XCircle } from 'lucide-react';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Button } from '@/components/ui/Button';
import { SupervisorStudentNotesButton } from '@/components/clinical/SupervisorStudentNotesButton';
import { formatDate, groupName, groupSupervisorAssignments, preferredDate, studentName, supervisorErrorMessage, workspaceQueryKey, type AttendanceStatus, type SupervisorGroup, type Workspace } from './supervisorWorkspace';

const statuses: { value: AttendanceStatus; ar: string; en: string; icon: typeof CheckCircle2 }[] = [
  { value: 'present', ar: 'حاضر', en: 'Present', icon: CheckCircle2 }, { value: 'absent', ar: 'غائب', en: 'Absent', icon: XCircle },
  { value: 'late', ar: 'متأخر', en: 'Late', icon: Clock3 }, { value: 'excused', ar: 'بعذر', en: 'Excused', icon: CalendarDays },
];

export function SupervisorAttendancePage(){
  const {user,can}=useAuth(); const {locale}=useI18n(); const ar=locale==='ar'; const tr=(a:string,e:string)=>ar?a:e; const queryClient=useQueryClient(); const [params]=useSearchParams();
  const isSupervisor=(user?.roles??[]).some(role=>String(role).toUpperCase()==='CLINICAL_SUPERVISOR');
  const workspace=useQuery({queryKey:workspaceQueryKey,queryFn:()=>apiFetch<Workspace>('/operational/my-supervisor-workspace'),enabled:isSupervisor&&can('supervisor.workspace.view')&&can('attendance.record')});
  const groups=useMemo(()=>groupSupervisorAssignments(workspace.data?.assignments??[]),[workspace.data?.assignments]);
  const dates=useMemo(()=>[...new Set(groups.flatMap(group=>group.scheduledDates))].sort(),[groups]);
  const [selectedDate,setSelectedDate]=useState(''); const [selectedGroup,setSelectedGroup]=useState(params.get('group')??''); const [values,setValues]=useState<Record<string,AttendanceStatus>>({}); const [notes,setNotes]=useState<Record<string,string>>({}); const [saved,setSaved]=useState('');
  useEffect(()=>{const requested=params.get('group');if(requested)setSelectedGroup(requested);},[params]);
  useEffect(()=>{if(!dates.length)return;const requested=params.get('date');setSelectedDate(current=>requested&&dates.includes(requested)?requested:dates.includes(current)?current:preferredDate(dates));},[dates,params]);
  const scheduledGroups=useMemo(()=>groups.filter(group=>group.scheduledDates.includes(selectedDate)),[groups,selectedDate]);
  useEffect(()=>{if(selectedGroup&&!scheduledGroups.some(group=>group.key===selectedGroup))setSelectedGroup('');},[scheduledGroups,selectedGroup]);
  const visibleGroups=useMemo(()=>selectedGroup?scheduledGroups.filter(group=>group.key===selectedGroup):scheduledGroups,[scheduledGroups,selectedGroup]);
  useEffect(()=>{if(!workspace.data||!selectedDate)return; setValues(current=>{const next={...current};visibleGroups.forEach(group=>group.students.forEach(student=>{const key=`${group.key}:${selectedDate}:${student.id}`;const record=workspace.data!.attendance_records.find(item=>item.student_id===student.id&&item.session?.rotation_block_id===group.rotationBlockId&&String(item.session?.session_date).slice(0,10)===selectedDate);if(!next[key])next[key]=record?.status??'present';}));return next;});setNotes(current=>{const next={...current};visibleGroups.forEach(group=>group.students.forEach(student=>{const key=`${group.key}:${selectedDate}:${student.id}`;const record=workspace.data!.attendance_records.find(item=>item.student_id===student.id&&item.session?.rotation_block_id===group.rotationBlockId&&String(item.session?.session_date).slice(0,10)===selectedDate);if(next[key]===undefined)next[key]=record?.excuse_note??'';}));return next;});},[visibleGroups,selectedDate,workspace.data]);
  const save=useMutation({mutationFn:(group:SupervisorGroup)=>apiFetch('/operational/my-supervisor-attendance',{method:'POST',body:{assignment_id:group.assignmentId,session_date:selectedDate,records:group.students.map(student=>({student_id:student.id,status:values[`${group.key}:${selectedDate}:${student.id}`]??'present',excuse_note:notes[`${group.key}:${selectedDate}:${student.id}`]||null}))}}),onSuccess:async(_,group)=>{setSaved(group.key);await queryClient.invalidateQueries({queryKey:workspaceQueryKey});}});
  if(!isSupervisor)return <ErrorState title={tr('سجل حضور المشرف','Supervisor attendance')} message={tr('هذه الشاشة مخصصة للمشرف السريري.','This page is for clinical supervisors.')} />;
  if(!can('supervisor.workspace.view')||!can('attendance.record'))return <ErrorState title={tr('صلاحية الحضور غير مفعلة','Attendance permission is disabled')} />;
  if(workspace.isLoading)return <LoadingState/>; if(workspace.isError||!workspace.data)return <ErrorState onRetry={()=>workspace.refetch()}/>;
  return <div className="mx-auto max-w-7xl space-y-5 pb-16">
    <Link to="/supervisor/portal" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold"><ArrowRight className="h-4 w-4"/>{tr('الرجوع للوحة المشرف','Back to dashboard')}</Link>
    <PageHeader title={tr('الحضور والغياب','Attendance')} description={tr('اختر جلسة فعلية من جدولك؛ تظهر فقط المجموعات المجدولة في ذلك اليوم.','Choose an actual scheduled session; only groups scheduled that day appear.')}/>
    {!dates.length?<ErrorState title={tr('لا توجد جلسات مجدولة','No scheduled sessions')} message={tr('يجب نشر الجدول وتحديد أيام عملك في الموقع التدريبي أولاً.','The schedule and your work days at the training site must be configured first.')}/>:<>
      <section className="flex flex-col gap-3 rounded-2xl border border-teal-100 bg-teal-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black text-teal-900">{tr('الجلسة السريرية','Clinical session')}</p><p className="mt-1 text-[11px] text-teal-700">{selectedDate&&formatDate(selectedDate,ar)} · {scheduledGroups.length} {tr('مجموعات مجدولة','scheduled groups')}</p></div><div className="grid gap-2 sm:grid-cols-2"><select value={selectedDate} onChange={e=>setSelectedDate(e.target.value)} className="rounded-xl border border-teal-200 bg-white px-4 py-2.5 text-sm font-bold">{dates.map(date=><option key={date} value={date}>{formatDate(date,ar)}</option>)}</select><select value={selectedGroup} onChange={e=>setSelectedGroup(e.target.value)} className="rounded-xl border border-teal-200 bg-white px-4 py-2.5 text-sm font-bold"><option value="">{tr('كل مجموعات هذه الجلسة','All groups in this session')}</option>{scheduledGroups.map(group=><option key={group.key} value={group.key}>{groupName(group,ar)}</option>)}</select></div></section>
      <div className="space-y-4">{visibleGroups.map(group=><section key={group.key} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-col gap-3 border-b border-slate-200 bg-slate-50 px-4 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black text-slate-900">{groupName(group,ar)}</h2><p className="mt-1 text-[11px] text-slate-500">{ar?group.siteAr:group.siteEn} · {group.students.length} {tr('طالب','students')}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setValues(current=>({...current,...Object.fromEntries(group.students.map(student=>[`${group.key}:${selectedDate}:${student.id}`,'present']))}))}>{tr('الكل حاضر','All present')}</Button><Button size="sm" isLoading={save.isPending&&save.variables?.key===group.key} onClick={()=>save.mutate(group)}><Save className="h-4 w-4"/>{tr('حفظ السجل','Save register')}</Button></div>{saved===group.key&&<span className="text-xs font-bold text-emerald-700">{tr('تم الحفظ','Saved')}</span>}</header>
        <div className="divide-y divide-slate-100">{group.students.map((student,index)=>{const key=`${group.key}:${selectedDate}:${student.id}`;const selected=values[key]??'present';return <article key={student.id} className="grid gap-3 p-4 lg:grid-cols-[36px_1.4fr_2fr_1.4fr] lg:items-center"><span className="hidden text-slate-400 lg:block">{index+1}</span><div><div className="flex flex-wrap items-center gap-2"><span className="font-black text-slate-800">{studentName(student,ar)}</span><SupervisorStudentNotesButton student={student} group={group} notes={workspace.data.student_notes??[]}/></div><p dir="ltr" className="mt-1 text-right font-mono text-[11px] text-slate-400">{student.university_number}</p></div><div className="flex flex-wrap gap-1.5">{statuses.map(option=><button key={option.value} type="button" onClick={()=>setValues(current=>({...current,[key]:option.value}))} className={`inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs font-bold ${selected===option.value?(option.value==='absent'?'border-red-300 bg-red-50 text-red-700':'border-teal-400 bg-teal-50 text-teal-800'):'border-slate-200 text-slate-500'}`}><option.icon className="h-3.5 w-3.5"/>{ar?option.ar:option.en}</button>)}</div><input value={notes[key]??''} onChange={e=>setNotes(current=>({...current,[key]:e.target.value}))} placeholder={tr('ملاحظة أو سبب العذر (اختياري)','Optional note or excuse reason')} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-xs focus:border-teal-400 focus:outline-none"/></article>})}</div>
      </section>)}</div></>}
    {save.isError&&<p className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{supervisorErrorMessage(save.error,ar,tr('تعذر حفظ الحضور.','Unable to save attendance.'))}</p>}
  </div>;
}
