import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, CheckCircle2, Clock3, Save, XCircle } from 'lucide-react';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Button } from '@/components/ui/Button';
import { clampDate, defaultGroupDate, groupName, groupSupervisorAssignments, isDateValue, studentName, supervisorErrorMessage, workspaceQueryKey, type AttendanceStatus, type SupervisorGroup, type Workspace } from './supervisorWorkspace';

const statuses: { value: AttendanceStatus; ar: string; en: string; icon: typeof CheckCircle2 }[] = [
  { value: 'present', ar: 'حاضر', en: 'Present', icon: CheckCircle2 },
  { value: 'absent', ar: 'غائب', en: 'Absent', icon: XCircle },
  { value: 'late', ar: 'متأخر', en: 'Late', icon: Clock3 },
  { value: 'excused', ar: 'بعذر', en: 'Excused', icon: CalendarDays },
];

export function SupervisorAttendancePage() {
  const { user, can } = useAuth(); const { locale } = useI18n(); const ar = locale === 'ar'; const tr = (a: string, e: string) => ar ? a : e;
  const [params] = useSearchParams(); const queryClient = useQueryClient();
  const isSupervisor = (user?.roles ?? []).some(role => String(role).toUpperCase() === 'CLINICAL_SUPERVISOR');
  const workspace = useQuery({ queryKey: workspaceQueryKey, queryFn: () => apiFetch<Workspace>('/operational/my-supervisor-workspace'), enabled: isSupervisor && can('supervisor.workspace.view') && can('attendance.record') });
  const groups = useMemo(() => { const items = groupSupervisorAssignments(workspace.data?.assignments ?? []); const target = params.get('group'); return target ? [...items].sort((a, b) => Number(b.key === target) - Number(a.key === target)) : items; }, [workspace.data?.assignments, params]);
  const [dates, setDates] = useState<Record<string, string>>({});
  const [values, setValues] = useState<Record<string, AttendanceStatus>>({});
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [saved, setSaved] = useState('');
  useEffect(() => { setDates(current => { const next = { ...current }; let changed=false; groups.forEach(group => { if (!isDateValue(next[group.key]??'')) { next[group.key] = defaultGroupDate(group); changed=true; } }); return changed?next:current; }); }, [groups]);
  useEffect(() => { if (!workspace.data) return; setValues(current => { const next = { ...current }; groups.forEach(group => { const date = dates[group.key]; if (!date) return; group.students.forEach(student => { const key = `${group.key}:${date}:${student.id}`; if (next[key]) return; const record = workspace.data!.attendance_records.find(item => item.student_id === student.id && item.session?.rotation_block_id === group.rotationBlockId && String(item.session?.session_date).slice(0, 10) === date); next[key] = record?.status ?? 'present'; }); }); return next; }); }, [groups, dates, workspace.data]);
  useEffect(() => { if (!workspace.data) return; setNotes(current => { const next = { ...current }; groups.forEach(group => { const date = dates[group.key]; if (!date) return; group.students.forEach(student => { const key = `${group.key}:${date}:${student.id}`; if (next[key] !== undefined) return; const record = workspace.data!.attendance_records.find(item => item.student_id === student.id && item.session?.rotation_block_id === group.rotationBlockId && String(item.session?.session_date).slice(0, 10) === date); next[key] = record?.excuse_note ?? ''; }); }); return next; }); }, [groups, dates, workspace.data]);
  const save = useMutation({ mutationFn: ({ group, date }: { group: SupervisorGroup; date: string }) => apiFetch('/operational/my-supervisor-attendance', { method: 'POST', body: { assignment_id: group.assignmentId, session_date: date, records: group.students.map(student => ({ student_id: student.id, status: values[`${group.key}:${date}:${student.id}`] ?? 'present', excuse_note: notes[`${group.key}:${date}:${student.id}`] || null })) } }), onSuccess: async (_, variables) => { setSaved(variables.group.key); await queryClient.invalidateQueries({ queryKey: workspaceQueryKey }); } });
  if (!isSupervisor) return <ErrorState title={tr('سجل حضور المشرف', 'Supervisor attendance')} message={tr('هذه الشاشة مخصصة للمشرف السريري.', 'This page is for clinical supervisors.')} />;
  if (!can('supervisor.workspace.view')) return <ErrorState title={tr('صلاحية مساحة المشرف غير مفعلة', 'Supervisor workspace permission is disabled')} />;
  if (!can('attendance.record')) return <ErrorState title={tr('صلاحية رصد الحضور غير مفعلة', 'Attendance permission is disabled')} />;
  if (workspace.isLoading) return <LoadingState />;
  if (workspace.isError || !workspace.data) return <ErrorState onRetry={() => workspace.refetch()} />;
  return <div className="mx-auto max-w-7xl space-y-5 pb-16"><PageHeader title={tr('الحضور والغياب', 'Attendance')} description={tr('سجل يومي موحّد لجميع طلبتك، مصنف حسب المجموعة والتكليف السريري.', 'A unified daily register for all assigned students, grouped by clinical assignment.')} />
    {!groups.length ? <ErrorState title={tr('لا توجد مجموعات حالية', 'No current groups')} message={tr('تظهر المجموعات بعد نشر الجدول وإسنادها لك.', 'Groups appear after the schedule is published and assigned to you.')} /> :
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-right text-xs"><thead><tr className="border-b border-slate-200 bg-slate-50 text-slate-500"><th className="px-4 py-4 w-14">#</th><th className="px-4 py-4">{tr('الطالب', 'Student')}</th><th className="px-4 py-4">{tr('الرقم الجامعي', 'Student ID')}</th><th className="px-4 py-4">{tr('حالة الحضور', 'Attendance status')}</th><th className="px-4 py-4">{tr('ملاحظة أو سبب العذر', 'Note or excuse reason')}</th></tr></thead>
      {groups.map(group => { const date = isDateValue(dates[group.key]??'')?dates[group.key]:defaultGroupDate(group); return <tbody key={group.key} className="border-b-8 border-slate-50 last:border-b-0"><tr className="bg-teal-50/80"><td colSpan={5} className="px-4 py-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black text-teal-900">{groupName(group, ar)}</h2><p className="mt-1 text-[10px] text-teal-700">{ar ? group.periodAr : group.periodEn} · {ar ? group.siteAr : group.siteEn} · {group.students.length} {tr('طالب', 'students')}</p></div><div className="flex items-center gap-2"><input required type="date" value={date} min={group.startDate || undefined} max={group.endDate || undefined} onChange={event => setDates(current => ({ ...current, [group.key]: event.target.value?clampDate(group,event.target.value):defaultGroupDate(group) }))} className="rounded-xl border border-teal-200 bg-white px-3 py-2 font-bold" /><Button size="sm" variant="outline" onClick={() => setValues(current => ({ ...current, ...Object.fromEntries(group.students.map(student => [`${group.key}:${date}:${student.id}`, 'present'])) }))}>{tr('الكل حاضر', 'All present')}</Button><Button size="sm" disabled={!isDateValue(date)} isLoading={save.isPending && save.variables?.group.key === group.key} onClick={() => save.mutate({ group, date })}><Save className="ml-1 h-4 w-4" />{tr('حفظ المجموعة', 'Save group')}</Button></div></div>{saved === group.key && <p className="mt-2 text-[10px] font-bold text-emerald-700">{tr('تم حفظ سجل المجموعة بنجاح.', 'Group attendance saved successfully.')}</p>}</td></tr>
        {group.students.map((student, index) => { const key = `${group.key}:${date}:${student.id}`; const selected = values[key] ?? 'present'; return <tr key={student.id} className="border-t border-slate-100 hover:bg-slate-50/60"><td className="px-4 py-3 text-slate-400">{index + 1}</td><td className="px-4 py-3 font-black text-slate-800">{studentName(student, ar)}</td><td dir="ltr" className="px-4 py-3 text-right font-mono text-slate-500">{student.university_number}</td><td className="px-4 py-3"><div className="flex gap-1.5">{statuses.map(option => <button key={option.value} type="button" onClick={() => setValues(current => ({ ...current, [key]: option.value }))} className={`inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 font-bold transition ${selected === option.value ? option.value === 'absent' ? 'border-red-300 bg-red-50 text-red-700' : 'border-teal-400 bg-teal-50 text-teal-800' : 'border-slate-200 bg-white text-slate-500'}`}><option.icon className="h-3.5 w-3.5" />{ar ? option.ar : option.en}</button>)}</div></td><td className="px-4 py-3"><input value={notes[key] ?? ''} onChange={event => setNotes(current => ({ ...current, [key]: event.target.value }))} placeholder={selected === 'excused' ? tr('اكتب سبب العذر...', 'Enter excuse reason...') : tr('اختياري...', 'Optional...')} className="w-full rounded-xl border border-slate-200 px-3 py-2 focus:border-teal-400 focus:outline-none" /></td></tr>; })}</tbody>; })}</table></div></section>}
    {save.isError && <p className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{supervisorErrorMessage(save.error,ar,tr('تعذر حفظ الحضور. تحقق من التاريخ والتكليف ثم أعد المحاولة.','Unable to save attendance. Check the date and assignment, then retry.'))}</p>}
  </div>;
}
