import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, CheckCircle2, ChevronLeft, ChevronRight, Clock3, FileCheck2, Save, XCircle } from 'lucide-react';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Button } from '@/components/ui/Button';
import { SupervisorStudentNotesButton } from '@/components/clinical/SupervisorStudentNotesButton';
import { SupervisorStudentPhoto } from '@/components/clinical/SupervisorStudentPhoto';
import { formatDate, formatWeekday, groupName, groupSupervisorAssignments, preferredDate, studentName, supervisorErrorMessage, workspaceQueryKey, type AttendanceStatus, type SupervisorGroup, type Workspace } from './supervisorWorkspace';

const statuses: { value: AttendanceStatus; ar: string; en: string; icon: typeof CheckCircle2 }[] = [
  { value: 'present', ar: 'حاضر', en: 'Present', icon: CheckCircle2 }, { value: 'absent', ar: 'غائب', en: 'Absent', icon: XCircle },
  { value: 'late', ar: 'متأخر', en: 'Late', icon: Clock3 }, { value: 'excused', ar: 'بعذر', en: 'Excused', icon: FileCheck2 },
];

export function SupervisorAttendancePage(){
  const {user,can}=useAuth(); const {locale}=useI18n(); const ar=locale==='ar'; const tr=(a:string,e:string)=>ar?a:e; const queryClient=useQueryClient(); const [params]=useSearchParams();
  const isSupervisor=(user?.roles??[]).some(role=>String(role).toUpperCase()==='CLINICAL_SUPERVISOR');
  const workspace=useQuery({queryKey:workspaceQueryKey,queryFn:()=>apiFetch<Workspace>('/operational/my-supervisor-workspace'),enabled:isSupervisor&&can('supervisor.workspace.view')&&can('attendance.record')});
  const groups=useMemo(()=>groupSupervisorAssignments(workspace.data?.assignments??[]),[workspace.data?.assignments]);
  const dates=useMemo(()=>[...new Set(groups.flatMap(group=>group.scheduledDates))].sort(),[groups]);
  const [selectedDate,setSelectedDate]=useState(''); const [selectedGroup,setSelectedGroup]=useState(params.get('group')??''); const [values,setValues]=useState<Record<string,AttendanceStatus>>({}); const [notes,setNotes]=useState<Record<string,string>>({}); const [saved,setSaved]=useState('');
  useEffect(()=>{const requested=params.get('group');if(requested)setSelectedGroup(requested);},[params]);
  useEffect(()=>{if(!dates.length)return;const requested=params.get('date');setSelectedDate(current=>requested&&dates.includes(requested)?requested:dates.includes(current)?current:preferredDate(dates));},[dates,params]);
  const scheduledGroups=useMemo(()=>groups.filter(group=>group.scheduledDates.includes(selectedDate)),[groups,selectedDate]);
  const selectedDateIndex=dates.indexOf(selectedDate);
  const moveDate=(step:number)=>{const next=dates[selectedDateIndex+step];if(next){setSelectedDate(next);setSaved('');}};
  useEffect(()=>{if(selectedGroup&&!scheduledGroups.some(group=>group.key===selectedGroup))setSelectedGroup('');},[scheduledGroups,selectedGroup]);
  const visibleGroups=useMemo(()=>selectedGroup?scheduledGroups.filter(group=>group.key===selectedGroup):scheduledGroups,[scheduledGroups,selectedGroup]);
  useEffect(()=>{if(!workspace.data||!selectedDate)return; setValues(current=>{const next={...current};visibleGroups.forEach(group=>group.students.forEach(student=>{const key=`${group.key}:${selectedDate}:${student.id}`;const record=workspace.data!.attendance_records.find(item=>item.student_id===student.id&&item.session?.rotation_block_id===group.rotationBlockId&&String(item.session?.session_date).slice(0,10)===selectedDate);if(!next[key])next[key]=record?.status??'present';}));return next;});setNotes(current=>{const next={...current};visibleGroups.forEach(group=>group.students.forEach(student=>{const key=`${group.key}:${selectedDate}:${student.id}`;const record=workspace.data!.attendance_records.find(item=>item.student_id===student.id&&item.session?.rotation_block_id===group.rotationBlockId&&String(item.session?.session_date).slice(0,10)===selectedDate);if(next[key]===undefined)next[key]=record?.excuse_note??'';}));return next;});},[visibleGroups,selectedDate,workspace.data]);
  const save=useMutation({mutationFn:(group:SupervisorGroup)=>apiFetch('/operational/my-supervisor-attendance',{method:'POST',body:{assignment_id:group.assignmentId,session_date:selectedDate,records:group.students.map(student=>({student_id:student.id,status:values[`${group.key}:${selectedDate}:${student.id}`]??'present',excuse_note:notes[`${group.key}:${selectedDate}:${student.id}`]||null}))}}),onSuccess:async(_,group)=>{setSaved(group.key);await queryClient.invalidateQueries({queryKey:workspaceQueryKey});}});
  if(!isSupervisor)return <ErrorState title={tr('سجل حضور المشرف','Supervisor attendance')} message={tr('هذه الشاشة مخصصة للمشرف السريري.','This page is for clinical supervisors.')} />;
  if(!can('supervisor.workspace.view')||!can('attendance.record'))return <ErrorState title={tr('صلاحية الحضور غير مفعلة','Attendance permission is disabled')} />;
  if(workspace.isLoading)return <LoadingState/>; if(workspace.isError||!workspace.data)return <ErrorState onRetry={()=>workspace.refetch()}/>;
  return <div className="mx-auto max-w-7xl space-y-5 pb-16">
    <Link to="/supervisor/portal" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold"><ArrowRight className="h-4 w-4"/>{tr('الرجوع للوحة المشرف','Back to dashboard')}</Link>
    <PageHeader title={tr('الحضور والغياب','Attendance')} description={tr('اختر يوم التدريب، ثم سجّل حالة كل طالب واحفظ المجموعة.','Choose the training day, record each student status, then save the group.')}/>
    {!dates.length?<ErrorState title={tr('لا توجد جلسات مجدولة','No scheduled sessions')} message={tr('يجب نشر الجدول وتحديد أيام عملك في الموقع التدريبي أولاً.','The schedule and your work days at the training site must be configured first.')}/>:<>
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
        <div className="grid gap-4 lg:grid-cols-[minmax(280px,1fr)_minmax(260px,1fr)] lg:items-end">
          <div><label className="mb-1.5 block text-[11px] font-black text-slate-500">{tr('يوم التدريب','Training day')}</label><div className="flex gap-2"><button type="button" disabled={selectedDateIndex<=0} onClick={()=>moveDate(-1)} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-slate-200 text-slate-500 disabled:opacity-30" title={tr('الجلسة السابقة','Previous session')}>{ar?<ChevronRight className="h-4 w-4"/>:<ChevronLeft className="h-4 w-4"/>}</button><select dir={ar?'rtl':'ltr'} value={selectedDate} onChange={e=>{setSelectedDate(e.target.value);setSaved('');}} className="h-10 min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold outline-none focus:border-teal-500">{dates.map(date=><option key={date} value={date}>{`${formatWeekday(date,ar)} — \u200E${formatDate(date,ar)}\u200E`}</option>)}</select><button type="button" disabled={selectedDateIndex<0||selectedDateIndex>=dates.length-1} onClick={()=>moveDate(1)} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-slate-200 text-slate-500 disabled:opacity-30" title={tr('الجلسة التالية','Next session')}>{ar?<ChevronLeft className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</button></div></div>
          <div><label className="mb-1.5 block text-[11px] font-black text-slate-500">{tr('المجموعة','Group')}</label><select value={selectedGroup} onChange={e=>setSelectedGroup(e.target.value)} className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold outline-none focus:border-teal-500"><option value="">{tr('جميع مجموعات هذا اليوم','All groups on this day')}</option>{scheduledGroups.map(group=><option key={group.key} value={group.key}>{groupName(group,ar)}</option>)}</select></div>
        </div>
        <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-3 text-[11px]"><span className="rounded-lg bg-teal-50 px-2.5 py-1.5 font-black text-teal-800">{selectedDate&&formatWeekday(selectedDate,ar)}</span><span dir="ltr" className="rounded-lg bg-slate-100 px-2.5 py-1.5 font-bold text-slate-700">{selectedDate&&formatDate(selectedDate,ar)}</span><span className="text-slate-500">{scheduledGroups.length} {tr('مجموعات','groups')} · {scheduledGroups.reduce((total,group)=>total+group.students.length,0)} {tr('طالب','students')}</span></div>
      </section>
      <div className="space-y-4">{visibleGroups.map(group=><section key={group.key} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-col gap-3 border-b border-slate-200 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-black text-slate-900">{groupName(group,ar)}</h2><p className="mt-1 text-[10px] text-slate-500">{ar?group.siteAr:group.siteEn} · {group.students.length} {tr('طالب','students')}</p></div><div className="flex flex-wrap items-center gap-2">{saved===group.key&&<span className="text-[11px] font-bold text-emerald-700">{tr('تم الحفظ','Saved')}</span>}<Button size="sm" variant="outline" onClick={()=>{setValues(current=>({...current,...Object.fromEntries(group.students.map(student=>[`${group.key}:${selectedDate}:${student.id}`,'present']))}));setSaved('');}}>{tr('تحديد الكل حاضر','Mark all present')}</Button><Button size="sm" isLoading={save.isPending&&save.variables?.key===group.key} onClick={()=>save.mutate(group)}><Save className="h-3.5 w-3.5"/>{tr('حفظ المجموعة','Save group')}</Button></div></header>
        <div className="hidden grid-cols-[36px_minmax(190px,1.25fr)_minmax(270px,1.6fr)_minmax(220px,1.2fr)_110px] border-b border-slate-100 bg-slate-50 px-4 py-2.5 text-[10px] font-black text-slate-500 lg:grid"><span>#</span><span>{tr('الطالب','Student')}</span><span>{tr('حالة الحضور','Attendance status')}</span><span>{tr('ملاحظة السجل','Register note')}</span><span>{tr('ملاحظاتي','My notes')}</span></div>
        <div className="divide-y divide-slate-100">{group.students.map((student,index)=>{const key=`${group.key}:${selectedDate}:${student.id}`;const selected=values[key]??'present';return <article key={student.id} className="grid gap-3 px-4 py-3 text-xs lg:grid-cols-[36px_minmax(190px,1.25fr)_minmax(270px,1.6fr)_minmax(220px,1.2fr)_110px] lg:items-center"><span className="hidden text-[10px] text-slate-400 lg:block">{index+1}</span><div className="flex items-center gap-2.5"><SupervisorStudentPhoto student={student} ar={ar}/><div className="min-w-0"><span className="block truncate font-black text-slate-800">{studentName(student,ar)}</span><p dir="ltr" className="mt-1 text-right font-mono text-[10px] text-slate-400">{student.university_number}</p></div></div><div className="flex flex-wrap gap-1">{statuses.map(option=>{const active=selected===option.value;const activeStyle=option.value==='absent'?'border-red-300 bg-red-50 text-red-700':option.value==='late'?'border-amber-300 bg-amber-50 text-amber-800':option.value==='excused'?'border-blue-300 bg-blue-50 text-blue-700':'border-teal-300 bg-teal-50 text-teal-800';return <button key={option.value} type="button" onClick={()=>{setValues(current=>({...current,[key]:option.value}));setSaved('');}} className={`inline-flex items-center gap-1 rounded-lg border px-2 py-1.5 text-[11px] font-bold transition ${active?activeStyle:'border-slate-200 bg-white text-slate-500 hover:bg-slate-50'}`}><option.icon className="h-3.5 w-3.5"/>{ar?option.ar:option.en}</button>})}</div><input value={notes[key]??''} onChange={e=>{setNotes(current=>({...current,[key]:e.target.value}));setSaved('');}} placeholder={selected==='excused'?tr('سبب العذر','Excuse reason'):tr('اختياري','Optional')} className="h-9 w-full rounded-lg border border-slate-200 px-2.5 text-[11px] outline-none focus:border-teal-400"/><div><SupervisorStudentNotesButton student={student} group={group} notes={workspace.data.student_notes??[]}/></div></article>})}</div>
      </section>)}</div></>}
    {save.isError&&<p className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{supervisorErrorMessage(save.error,ar,tr('تعذر حفظ الحضور.','Unable to save attendance.'))}</p>}
  </div>;
}
