import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, Save, Send, Users } from 'lucide-react';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Button } from '@/components/ui/Button';
import { clampDate, defaultGroupDate, groupName, groupSupervisorAssignments, isDateValue, studentName, supervisorErrorMessage, workspaceQueryKey, type Assessment, type SupervisorGroup, type Workspace } from './supervisorWorkspace';

const statusText: Record<string, { ar: string; en: string }> = { draft: { ar: 'مسودة', en: 'Draft' }, submitted: { ar: 'مرسل للاعتماد', en: 'Submitted' }, approved: { ar: 'معتمد', en: 'Approved' }, returned: { ar: 'معاد للتعديل', en: 'Returned' } };
export function SupervisorAssessmentsPage() {
  const { user, can } = useAuth(); const { locale } = useI18n(); const ar = locale === 'ar'; const tr = (a: string, e: string) => ar ? a : e;
  const [params] = useSearchParams(); const queryClient = useQueryClient();
  const isSupervisor = (user?.roles ?? []).some(role => String(role).toUpperCase() === 'CLINICAL_SUPERVISOR');
  const workspace = useQuery({ queryKey: workspaceQueryKey, queryFn: () => apiFetch<Workspace>('/operational/my-supervisor-workspace'), enabled: isSupervisor && can('supervisor.workspace.view') && can('assessment.create') });
  const groups = useMemo(() => { const items = groupSupervisorAssignments(workspace.data?.assignments ?? []); const target = params.get('group'); return target ? [...items].sort((a, b) => Number(b.key === target) - Number(a.key === target)) : items; }, [workspace.data?.assignments, params]);
  const [dates, setDates] = useState<Record<string, string>>({}); const [scores, setScores] = useState<Record<string, string>>({}); const [notes, setNotes] = useState<Record<string, string>>({}); const [saved, setSaved] = useState(''); const [bulkNotice, setBulkNotice] = useState('');
  useEffect(() => { setDates(current => { const next = { ...current }; let changed=false; groups.forEach(group => { if (!isDateValue(next[group.key]??'')) { next[group.key] = defaultGroupDate(group); changed=true; } }); return changed?next:current; }); }, [groups]);
  const assessmentFor = (group: SupervisorGroup, studentId: number, date: string): Assessment | undefined => workspace.data?.assessments.find(item => item.student_id === studentId && item.session?.rotation_block_id === group.rotationBlockId && String(item.session?.session_date).slice(0, 10) === date);
  const pendingTargetsFor = (group: SupervisorGroup, date: string) => group.students.flatMap(student => { const key = `${group.key}:${date}:${student.id}`; const existing = assessmentFor(group, student.id, date); const value = Number(scores[key]); return !['submitted', 'approved'].includes(existing?.status ?? '') && scores[key] !== '' && scores[key] !== undefined && value >= 0 && value <= 20 ? [{ group, date, studentId: student.id, assessmentId: existing?.id }] : []; });
  useEffect(() => { if (!workspace.data) return; setScores(current => { const next = { ...current }; groups.forEach(group => { const date = dates[group.key]; if (!date) return; group.students.forEach(student => { const key = `${group.key}:${date}:${student.id}`, item = assessmentFor(group, student.id, date); if (next[key] === undefined) next[key] = item?.score == null ? '' : String(item.score); }); }); return next; }); setNotes(current => { const next = { ...current }; groups.forEach(group => { const date = dates[group.key]; if (!date) return; group.students.forEach(student => { const key = `${group.key}:${date}:${student.id}`, item = assessmentFor(group, student.id, date); if (next[key] === undefined) next[key] = item?.notes ?? ''; }); }); return next; }); }, [groups, dates, workspace.data]);
  const submit = useMutation({ mutationFn: ({ group, date, studentId, assessmentId }: { group: SupervisorGroup; date: string; studentId: number; assessmentId?: number }) => apiFetch('/operational/my-supervisor-assessments', { method: 'POST', body: { assessment_id: assessmentId ?? null, assignment_id: group.assignmentId, student_id: studentId, session_date: date, score: Number(scores[`${group.key}:${date}:${studentId}`]), notes: notes[`${group.key}:${date}:${studentId}`] || null } }), onSuccess: async (_, variables) => { setSaved(`${variables.group.key}:${variables.date}:${variables.studentId}`); await queryClient.invalidateQueries({ queryKey: workspaceQueryKey }); } });
  const bulkSubmit = useMutation({ mutationFn: async (targets: Array<{ group: SupervisorGroup; date: string; studentId: number; assessmentId?: number }>) => { for (const target of targets) await apiFetch('/operational/my-supervisor-assessments', { method: 'POST', body: { assessment_id: target.assessmentId ?? null, assignment_id: target.group.assignmentId, student_id: target.studentId, session_date: target.date, score: Number(scores[`${target.group.key}:${target.date}:${target.studentId}`]), notes: notes[`${target.group.key}:${target.date}:${target.studentId}`] || null } }); return targets.length; }, onSuccess: async count => { setBulkNotice(tr(`تم حفظ وإرسال ${count} تقييم بنجاح.`, `${count} assessments saved and submitted successfully.`)); await queryClient.invalidateQueries({ queryKey: workspaceQueryKey }); } });
  if (!isSupervisor) return <ErrorState title={tr('تقييمات المشرف', 'Supervisor assessments')} message={tr('هذه الشاشة مخصصة للمشرف السريري.', 'This page is for clinical supervisors.')} />;
  if (!can('supervisor.workspace.view')) return <ErrorState title={tr('صلاحية مساحة المشرف غير مفعلة', 'Supervisor workspace permission is disabled')} />;
  if (!can('assessment.create')) return <ErrorState title={tr('صلاحية التقييم غير مفعلة', 'Assessment permission is disabled')} />;
  if (workspace.isLoading) return <LoadingState />; if (workspace.isError || !workspace.data) return <ErrorState onRetry={() => workspace.refetch()} />;
  const allTargets = groups.flatMap(group => { const date = isDateValue(dates[group.key] ?? '') ? dates[group.key] : defaultGroupDate(group); return pendingTargetsFor(group, date); });
  return <div className="mx-auto max-w-7xl space-y-5 pb-16"><div className="flex flex-wrap items-center justify-between gap-3"><Link to="/supervisor/portal" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700 shadow-sm transition hover:border-teal-200 hover:text-teal-700"><ArrowRight className="h-4 w-4" />{tr('الرجوع للوحة المشرف', 'Back to supervisor dashboard')}</Link><Button disabled={!allTargets.length || submit.isPending || bulkSubmit.isPending} isLoading={bulkSubmit.isPending} onClick={() => bulkSubmit.mutate(allTargets)} className="!whitespace-nowrap"><Users className="ml-2 h-4 w-4" />{tr(`حفظ جميع المجموعات (${allTargets.length})`, `Save all groups (${allTargets.length})`)}</Button></div><PageHeader title={tr('تقييمات الطلبة السريرية', 'Clinical student assessments')} description={tr('قيّم طالبًا منفردًا أو احفظ المجموعة الحالية أو جميع المجموعات دفعة واحدة.', 'Assess one student, the current group, or all groups in one workflow.')} />
    {bulkNotice && <p className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-800">{bulkNotice}</p>}
    {!groups.length ? <ErrorState title={tr('لا توجد مجموعات حالية', 'No current groups')} /> : <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-right text-xs"><thead><tr className="border-b border-slate-200 bg-slate-50 text-slate-500"><th className="w-14 px-4 py-4">#</th><th className="px-4 py-4">{tr('الطالب', 'Student')}</th><th className="px-4 py-4">{tr('الرقم الجامعي', 'Student ID')}</th><th className="w-36 px-4 py-4">{tr('العلامة من 20', 'Score / 20')}</th><th className="px-4 py-4">{tr('ملاحظة للمراجع', 'Reviewer note')}</th><th className="w-36 px-4 py-4">{tr('الحالة', 'Status')}</th><th className="w-32 px-4 py-4">{tr('الحفظ', 'Save')}</th></tr></thead>
      {groups.map(group => { const date = isDateValue(dates[group.key]??'')?dates[group.key]:defaultGroupDate(group); const groupTargets = pendingTargetsFor(group, date); return <tbody key={group.key} className="border-b-8 border-slate-50 last:border-b-0"><tr className="bg-teal-50/80"><td colSpan={7} className="px-4 py-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black text-teal-900">{groupName(group, ar)}</h2><p className="mt-1 text-[10px] text-teal-700">{ar ? group.periodAr : group.periodEn} · {ar ? group.siteAr : group.siteEn} · {group.students.length} {tr('طالب', 'students')}</p></div><div className="flex flex-wrap items-center gap-2"><input required type="date" value={date} min={group.startDate || undefined} max={group.endDate || undefined} onChange={event => setDates(current => ({ ...current, [group.key]: event.target.value?clampDate(group,event.target.value):defaultGroupDate(group) }))} className="rounded-xl border border-teal-200 bg-white px-3 py-2 font-bold" /><Button size="sm" variant="outline" disabled={!groupTargets.length || submit.isPending || bulkSubmit.isPending} isLoading={bulkSubmit.isPending} onClick={() => bulkSubmit.mutate(groupTargets)} className="!whitespace-nowrap"><Save className="ml-1 h-4 w-4" />{tr(`حفظ المجموعة (${groupTargets.length})`, `Save group (${groupTargets.length})`)}</Button></div></div></td></tr>
        {group.students.map((student, index) => { const key = `${group.key}:${date}:${student.id}`, existing = assessmentFor(group, student.id, date), rowLocked = ['submitted', 'approved'].includes(existing?.status ?? ''); const status = existing?.status ?? 'draft'; const scoreValue = Number(scores[key]); const valid = scores[key] !== '' && scores[key] !== undefined && scoreValue >= 0 && scoreValue <= 20; const rowSaving = submit.isPending && submit.variables?.group.key === group.key && submit.variables?.studentId === student.id; return <tr key={student.id} className="border-t border-slate-100 hover:bg-slate-50/60"><td className="px-4 py-3 text-slate-400">{index + 1}</td><td className="px-4 py-3 font-black text-slate-800">{studentName(student, ar)}{existing?.return_reason && <p className="mt-1 text-[10px] font-bold text-amber-700">{tr('سبب الإعادة:', 'Return reason:')} {existing.return_reason}</p>}</td><td dir="ltr" className="px-4 py-3 text-right font-mono text-slate-500">{student.university_number}</td><td className="px-4 py-3"><input type="number" min="0" max="20" step="0.25" disabled={rowLocked} value={scores[key] ?? ''} onChange={event => setScores(current => ({ ...current, [key]: event.target.value }))} className="w-28 rounded-xl border border-slate-200 px-3 py-2 font-black focus:border-teal-400 focus:outline-none disabled:bg-slate-100" /></td><td className="px-4 py-3"><input disabled={rowLocked} value={notes[key] ?? ''} onChange={event => setNotes(current => ({ ...current, [key]: event.target.value }))} placeholder={tr('تُحفظ وتظهر للمراجع...', 'Saved and shown to reviewer...')} className="w-full rounded-xl border border-slate-200 px-3 py-2 focus:border-teal-400 focus:outline-none disabled:bg-slate-100" /></td><td className="px-4 py-3"><span className={`rounded-lg px-2.5 py-1.5 font-bold ${status === 'returned' ? 'bg-amber-50 text-amber-800' : status === 'approved' ? 'bg-emerald-50 text-emerald-800' : status === 'submitted' ? 'bg-blue-50 text-blue-800' : 'bg-slate-100 text-slate-600'}`}>{ar ? statusText[status]?.ar : statusText[status]?.en}</span></td><td className="px-4 py-3"><Button size="sm" disabled={!isDateValue(date)||!valid||rowLocked||bulkSubmit.isPending} isLoading={rowSaving} onClick={() => submit.mutate({ group, date, studentId: student.id, assessmentId: existing?.id })} className="!min-w-28 !whitespace-nowrap"><Send className="ml-1 h-3.5 w-3.5" />{rowLocked ? tr('تم الإرسال', 'Submitted') : existing?.status === 'returned' ? tr('إعادة الإرسال', 'Resubmit') : tr('حفظ الطالب', 'Save student')}</Button>{saved === key && <p className="mt-1 text-center text-[9px] font-bold text-emerald-700">{tr('تم الحفظ والإرسال', 'Saved and submitted')}</p>}</td></tr>; })}</tbody>; })}</table></div></section>}
    {submit.isError && <p className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{supervisorErrorMessage(submit.error,ar,tr('تعذر حفظ تقييم الطالب. تأكد من العلامة وحالة التقييم.','Unable to save the student assessment. Check the score and assessment status.'))}</p>}
    {bulkSubmit.isError && <p className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{supervisorErrorMessage(bulkSubmit.error,ar,tr('تعذر إكمال الحفظ الجماعي. تم الاحتفاظ بأي تقييمات حُفظت قبل حدوث الخطأ.','Bulk save could not be completed. Assessments saved before the error were retained.'))}</p>}
  </div>;
}
