import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, Award, CalendarDays, CheckCircle2, ClipboardCheck, Clock3, Hospital, Loader2, Save, UserRound, Users } from 'lucide-react';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Button } from '@/components/ui/Button';

type TabKey = 'schedule' | 'attendance' | 'assessments';
type AttendanceStatus = 'present' | 'absent' | 'late' | 'excused';
type Student = { id:number; university_number:string; full_name_ar:string; full_name_en?:string|null; academic_level?:string };
type Assignment = {
  id:number; distribution_version_id:number; rotation_block_id:number|null; training_site_id:number|null; student_subgroup_id:number|null;
  student:Student; student_subgroup?:{id:number;name:string;group?:{id:number;name:string}}|null;
  rotation_block?:{id:number;block_code:string;from_week?:number|null;to_week?:number|null;rotation?:{name?:string;course?:{name_ar?:string;name_en?:string};academic_year?:{code:string}}}|null;
  training_site?:{id:number;name_ar:string;name_en?:string|null}|null;
  department?:{id:number;name_ar:string;name_en?:string|null}|null;
};
type AttendanceRecord = {id:number;student_id:number;status:AttendanceStatus;session?:{rotation_block_id:number|null;session_date:string}|null};
type Assessment = {id:number;student_id:number;score:string|number|null;max_score:string|number;status:string;created_at:string;student?:Student;session?:{session_date:string}|null};
type Workspace = {supervisor:{person_id:number;user_id:number;full_name_ar:string;full_name_en:string};assignments:Assignment[];attendance_records:AttendanceRecord[];assessments:Assessment[]};
type Group = {key:string;assignmentId:number;rotationBlockId:number|null;subgroup:string;group:string;courseAr:string;courseEn:string;period:string;siteAr:string;siteEn:string;departmentAr:string;departmentEn:string;academicYear:string;students:Student[]};

const today = () => new Date().toISOString().slice(0,10);

export function SupervisorPortalPage() {
  const { user, can } = useAuth();
  const { locale } = useI18n();
  const qc = useQueryClient();
  const [params,setParams] = useSearchParams();
  const requestedTab=params.get('tab');
  const activeTab:TabKey=requestedTab==='attendance'||requestedTab==='assessments'?requestedTab:'schedule';
  const roles=(user?.roles??[]).map(role=>String(role).toUpperCase());
  const isSupervisor=roles.includes('CLINICAL_SUPERVISOR');
  const ar=locale==='ar';
  const tr=(arabic:string,english:string)=>ar?arabic:english;

  const workspace=useQuery({queryKey:['supervisor-workspace'],queryFn:()=>apiFetch<Workspace>('/operational/my-supervisor-workspace'),enabled:isSupervisor});
  const groups=useMemo<Group[]>(()=>{
    const map=new Map<string,Group>();
    for(const item of workspace.data?.assignments??[]){
      const key=[item.distribution_version_id,item.rotation_block_id??'none',item.training_site_id??'none',item.student_subgroup_id??'none'].join('-');
      const block=item.rotation_block; const rotation=block?.rotation;
      if(!map.has(key))map.set(key,{key,assignmentId:item.id,rotationBlockId:item.rotation_block_id,subgroup:item.student_subgroup?.name??tr('دون مجموعة فرعية','No subgroup'),group:item.student_subgroup?.group?.name??item.student_subgroup?.name??tr('المجموعة السريرية','Clinical group'),courseAr:rotation?.course?.name_ar??rotation?.name??'المساق السريري',courseEn:rotation?.course?.name_en??rotation?.name??'Clinical course',period:block?.from_week&&block?.to_week?`${tr('الأسبوع','Week')} ${block.from_week}–${block.to_week}`:block?.block_code??tr('الفترة الحالية','Current period'),siteAr:item.training_site?.name_ar??'غير محدد',siteEn:item.training_site?.name_en??item.training_site?.name_ar??'Not specified',departmentAr:item.department?.name_ar??'غير محدد',departmentEn:item.department?.name_en??item.department?.name_ar??'Not specified',academicYear:rotation?.academic_year?.code??'—',students:[]});
      map.get(key)!.students.push(item.student);
    }
    return [...map.values()];
  },[workspace.data,locale]);

  const [selectedGroupKey,setSelectedGroupKey]=useState('');
  const selectedGroup=groups.find(group=>group.key===selectedGroupKey)??groups[0];
  useEffect(()=>{if(groups.length&&!groups.some(group=>group.key===selectedGroupKey))setSelectedGroupKey(groups[0].key)},[groups,selectedGroupKey]);
  const [attendanceDate,setAttendanceDate]=useState(today());
  const [statuses,setStatuses]=useState<Record<number,AttendanceStatus>>({});
  useEffect(()=>{if(!selectedGroup)return;const next:Record<number,AttendanceStatus>={};for(const student of selectedGroup.students){const record=(workspace.data?.attendance_records??[]).find(item=>item.student_id===student.id&&item.session?.rotation_block_id===selectedGroup.rotationBlockId&&String(item.session?.session_date).slice(0,10)===attendanceDate);next[student.id]=record?.status??'present'}setStatuses(next)},[selectedGroup?.key,attendanceDate,workspace.data?.attendance_records]);
  const attendanceMutation=useMutation({mutationFn:()=>apiFetch('/operational/my-supervisor-attendance',{method:'POST',body:{assignment_id:selectedGroup?.assignmentId,session_date:attendanceDate,records:selectedGroup?.students.map(student=>({student_id:student.id,status:statuses[student.id]??'present'}))}}),onSuccess:()=>qc.invalidateQueries({queryKey:['supervisor-workspace']})});

  const [assessmentStudentId,setAssessmentStudentId]=useState(''); const [assessmentDate,setAssessmentDate]=useState(today()); const [score,setScore]=useState(''); const [notes,setNotes]=useState('');
  useEffect(()=>{if(selectedGroup&&!selectedGroup.students.some(student=>String(student.id)===assessmentStudentId))setAssessmentStudentId(String(selectedGroup.students[0]?.id??''))},[selectedGroup?.key,assessmentStudentId]);
  const assessmentMutation=useMutation({mutationFn:()=>apiFetch('/operational/my-supervisor-assessments',{method:'POST',body:{assignment_id:selectedGroup?.assignmentId,student_id:Number(assessmentStudentId),session_date:assessmentDate,score:Number(score),notes:notes||null}}),onSuccess:async()=>{setScore('');setNotes('');await qc.invalidateQueries({queryKey:['supervisor-workspace']})}});

  if(!isSupervisor)return <ErrorState title={tr('بوابة المشرفين السريريين','Clinical supervisors portal')} message={tr('تظهر هذه البوابة فقط للحساب الذي تم تعيين دور مشرف سريري له.','This portal is available only to accounts assigned the Clinical Supervisor role.')} />;
  if(workspace.isLoading)return <LoadingState/>;
  if(workspace.isError||!workspace.data)return <ErrorState title={tr('تعذر تحميل بوابة المشرف','Unable to load supervisor portal')} message={tr('تحقق من ارتباط الحساب بملف الطبيب وصلاحية عرض التوزيع.','Check the account’s doctor profile link and distribution permission.')} onRetry={()=>workspace.refetch()}/>;

  const name=ar?workspace.data.supervisor.full_name_ar:workspace.data.supervisor.full_name_en||workspace.data.supervisor.full_name_ar;
  const tabs:[TabKey,string,typeof Users][]=[['schedule',tr('مجموعاتي ودوامي','My groups & schedule'),Users],['attendance',tr('رصد الحضور','Record attendance'),CalendarDays],['assessments',tr('التقييم السريري','Clinical assessment'),Award]];

  return <div className="space-y-5 pb-20">
    <PageHeader title={`${tr('مرحبًا،','Welcome,')} ${name}`} description={tr('مساحة العمل الشخصية للمشرف السريري، مرتبطة مباشرة بالجدول المنشور وسجلات النظام الرسمية.','Your personal clinical-supervision workspace, linked directly to the published schedule and official records.')}><Link to="/clinical-supervisors/me" className="inline-flex items-center gap-2 rounded-xl border border-teal-200 bg-white px-3 py-2 text-xs font-bold text-teal-700"><UserRound className="h-4 w-4"/>{tr('ملفي السريري','My clinical profile')}</Link></PageHeader>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={Users} label={tr('المجموعات الحالية','Current groups')} value={groups.length}/><Metric icon={UserRound} label={tr('الطلبة المكلف بهم','Assigned students')} value={new Set(workspace.data.assignments.map(item=>item.student.id)).size}/><Metric icon={CalendarDays} label={tr('سجلات الحضور','Attendance records')} value={workspace.data.attendance_records.length}/><Metric icon={ClipboardCheck} label={tr('التقييمات المسجلة','Recorded assessments')} value={workspace.data.assessments.length}/></section>
    <nav className="flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm">{tabs.map(([key,label,Icon])=><button key={key} onClick={()=>setParams({tab:key})} className={`flex min-w-max flex-1 items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-xs font-bold transition ${activeTab===key?'bg-teal-600 text-white shadow-sm':'text-slate-600 hover:bg-teal-50 hover:text-teal-700'}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>
    {!groups.length?<EmptyWorkspace ar={ar}/>:<>
      {activeTab==='schedule'&&<section className="grid gap-4 lg:grid-cols-2">{groups.map(group=><article key={group.key} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-teal-100 bg-teal-50/70 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-black text-slate-900">{ar?group.courseAr:group.courseEn}</h2><p className="mt-1 text-xs font-bold text-teal-700">{group.group} · {group.subgroup}</p></div><span className="rounded-xl bg-white px-2.5 py-1 text-[10px] font-bold text-teal-700">{group.academicYear}</span></div></header><div className="space-y-4 p-4"><div className="grid gap-2 text-xs sm:grid-cols-3"><Info icon={Clock3} label={group.period}/><Info icon={Hospital} label={ar?group.siteAr:group.siteEn}/><Info icon={ClipboardCheck} label={ar?group.departmentAr:group.departmentEn}/></div><div className="border-t border-slate-100 pt-3"><p className="mb-2 text-[11px] font-bold text-slate-500">{tr('الطلبة في المجموعة','Students in group')} ({group.students.length})</p><div className="grid gap-2 sm:grid-cols-2">{group.students.map(student=><div key={student.id} className="rounded-xl bg-slate-50 px-3 py-2"><p className="text-xs font-bold text-slate-800">{ar?student.full_name_ar:student.full_name_en||student.full_name_ar}</p><p className="mt-0.5 text-[10px] text-slate-500">{student.university_number}</p></div>)}</div></div></div></article>)}</section>}
      {activeTab==='attendance'&&<WorkspaceCard title={tr('رصد حضور المجموعة','Record group attendance')} description={tr('يتم الحفظ مباشرة في سجل الحضور الرسمي، ويمكن تعديله بإعادة الحفظ لنفس التاريخ.','Saved directly to the official attendance register; save again on the same date to update it.')}><GroupAndDate groups={groups} selected={selectedGroup?.key??''} date={attendanceDate} onGroup={setSelectedGroupKey} onDate={setAttendanceDate} ar={ar}/><div className="mt-4 divide-y divide-slate-100 rounded-2xl border border-slate-200">{selectedGroup?.students.map(student=><div key={student.id} className="flex flex-col gap-3 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black text-slate-800">{ar?student.full_name_ar:student.full_name_en||student.full_name_ar}</p><p className="text-[10px] text-slate-500">{student.university_number}</p></div><div className="grid grid-cols-4 gap-1">{(['present','absent','late','excused'] as AttendanceStatus[]).map(status=><button key={status} onClick={()=>setStatuses(current=>({...current,[student.id]:status}))} className={`rounded-lg px-2 py-1.5 text-[10px] font-bold ${statuses[student.id]===status?'bg-teal-600 text-white':'bg-slate-100 text-slate-600 hover:bg-teal-50'}`}>{statusLabel(status,ar)}</button>)}</div></div>)}</div><MutationMessage mutation={attendanceMutation} ar={ar} successAr="تم حفظ الحضور في السجل الرسمي." successEn="Attendance was saved to the official register."/><div className="mt-4"><Button disabled={!selectedGroup||attendanceMutation.isPending||!can('attendance.record')} onClick={()=>attendanceMutation.mutate()}>{attendanceMutation.isPending?<Loader2 className="ml-2 h-4 w-4 animate-spin"/>:<Save className="ml-2 h-4 w-4"/>}{tr('حفظ الحضور','Save attendance')}</Button></div></WorkspaceCard>}
      {activeTab==='assessments'&&<WorkspaceCard title={tr('التقييم السريري من 20','Clinical assessment out of 20')} description={tr('يرتبط التقييم بالطالب والطبيب والفترة السريرية، ويُرسل مباشرة للمراجعة.','The assessment is linked to the student, supervisor and clinical period, then submitted directly for review.')}><GroupAndDate groups={groups} selected={selectedGroup?.key??''} date={assessmentDate} onGroup={setSelectedGroupKey} onDate={setAssessmentDate} ar={ar}/><div className="mt-4 grid gap-3 md:grid-cols-[1fr_9rem]"><select className="input" value={assessmentStudentId} onChange={event=>setAssessmentStudentId(event.target.value)}>{selectedGroup?.students.map(student=><option key={student.id} value={student.id}>{ar?student.full_name_ar:student.full_name_en||student.full_name_ar} — {student.university_number}</option>)}</select><label className="relative"><input className="input pl-12" type="number" min="0" max="20" step="0.25" required value={score} onChange={event=>setScore(event.target.value)} placeholder="0"/><span className="absolute left-3 top-3 text-xs font-bold text-slate-400">/ 20</span></label></div><textarea className="input mt-3 min-h-24 resize-y" value={notes} onChange={event=>setNotes(event.target.value)} placeholder={tr('ملاحظات التقييم (اختياري)','Assessment notes (optional)')}/><MutationMessage mutation={assessmentMutation} ar={ar} successAr="تم حفظ التقييم وإرساله للمراجعة." successEn="Assessment saved and submitted for review."/><div className="mt-4"><Button disabled={!selectedGroup||!assessmentStudentId||score===''||assessmentMutation.isPending||!can('assessment.create')} onClick={()=>assessmentMutation.mutate()}>{assessmentMutation.isPending?<Loader2 className="ml-2 h-4 w-4 animate-spin"/>:<Save className="ml-2 h-4 w-4"/>}{tr('حفظ وإرسال التقييم','Save & submit assessment')}</Button></div>{!!workspace.data.assessments.length&&<div className="mt-6 border-t border-slate-100 pt-4"><h3 className="mb-3 text-xs font-black text-slate-700">{tr('آخر التقييمات المسجلة','Recent assessments')}</h3><div className="grid gap-2 md:grid-cols-2">{workspace.data.assessments.slice(0,8).map(item=><div key={item.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p className="text-xs font-bold text-slate-800">{ar?item.student?.full_name_ar:item.student?.full_name_en||item.student?.full_name_ar}</p><p className="text-[10px] text-slate-500">{String(item.session?.session_date??item.created_at).slice(0,10)} · {tr('مرسل للمراجعة','Submitted')}</p></div><span className="rounded-xl bg-teal-50 px-3 py-1 text-sm font-black text-teal-700">{Number(item.score).toFixed(1)}/20</span></div>)}</div></div>}</WorkspaceCard>}
    </>}
  </div>;
}

function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:number}){return <article className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[11px] font-bold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-900">{value}</p></div><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><Icon className="h-5 w-5"/></span></div></article>}
function Info({icon:Icon,label}:{icon:typeof Users;label:string}){return <div className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-slate-600"><Icon className="h-4 w-4 shrink-0 text-teal-600"/><span className="truncate font-bold">{label}</span></div>}
function WorkspaceCard({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="border-b border-slate-100 pb-4"><h2 className="text-sm font-black text-slate-900">{title}</h2><p className="mt-1 text-xs leading-6 text-slate-500">{description}</p></div><div className="pt-4">{children}</div></section>}
function GroupAndDate({groups,selected,date,onGroup,onDate,ar}:{groups:Group[];selected:string;date:string;onGroup:(v:string)=>void;onDate:(v:string)=>void;ar:boolean}){return <div className="grid gap-3 md:grid-cols-[1fr_12rem]"><select className="input" value={selected} onChange={event=>onGroup(event.target.value)}>{groups.map(group=><option key={group.key} value={group.key}>{ar?group.courseAr:group.courseEn} — {group.group} ({group.subgroup})</option>)}</select><input className="input" type="date" value={date} onChange={event=>onDate(event.target.value)}/></div>}
function MutationMessage({mutation,ar,successAr,successEn}:{mutation:{isSuccess:boolean;isError:boolean};ar:boolean;successAr:string;successEn:string}){if(mutation.isSuccess)return <p className="mt-3 flex items-center gap-2 rounded-xl bg-teal-50 p-3 text-xs font-bold text-teal-700"><CheckCircle2 className="h-4 w-4"/>{ar?successAr:successEn}</p>;if(mutation.isError)return <p className="mt-3 flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700"><AlertCircle className="h-4 w-4"/>{ar?'تعذر الحفظ. تحقق من البيانات والصلاحيات ثم حاول مجددًا.':'Unable to save. Check the data and permissions, then try again.'}</p>;return null}
function EmptyWorkspace({ar}:{ar:boolean}){return <section className="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><Users className="mx-auto h-10 w-10 text-slate-300"/><h2 className="mt-3 text-sm font-black text-slate-800">{ar?'لا توجد مجموعات مكلف بها حاليًا':'No current assigned groups'}</h2><p className="mt-2 text-xs text-slate-500">{ar?'تظهر هنا فقط المجموعات المرتبطة بك في جدول منشور وحالي.':'Only groups assigned to you in a current published schedule appear here.'}</p></section>}
function statusLabel(status:AttendanceStatus,ar:boolean){const labels={present:['حاضر','Present'],absent:['غائب','Absent'],late:['متأخر','Late'],excused:['مبرر','Excused']} as const;return labels[status][ar?0:1]}
