import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Award, CalendarDays, ClipboardCheck, UserRound, Users } from 'lucide-react';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { PageHeader } from '@/components/ui/PageHeader';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { groupName, groupSupervisorAssignments, studentName, today, workspaceQueryKey, type Workspace } from './supervisorWorkspace';

export function SupervisorPortalPage(){
 const {user,can}=useAuth();const {locale}=useI18n();const ar=locale==='ar';const tr=(a:string,e:string)=>ar?a:e;
 const isSupervisor=(user?.roles??[]).map(String).map(role=>role.toUpperCase()).includes('CLINICAL_SUPERVISOR');
 const query=useQuery({queryKey:workspaceQueryKey,queryFn:()=>apiFetch<Workspace>('/operational/my-supervisor-workspace'),enabled:isSupervisor&&can('supervisor.workspace.view')});
 if(!isSupervisor)return <ErrorState title={tr('لوحة المشرف السريري','Clinical supervisor dashboard')} message={tr('هذه المساحة مخصصة لحسابات المشرفين السريريين.','This workspace is for clinical supervisor accounts.')}/>;
 if(!can('supervisor.workspace.view'))return <ErrorState title={tr('الصلاحية غير مفعلة','Permission is disabled')}/>;if(query.isLoading)return <LoadingState/>;if(query.isError||!query.data)return <ErrorState onRetry={()=>query.refetch()}/>;
 const groups=groupSupervisorAssignments(query.data.assignments),students=new Set(query.data.assignments.map(item=>item.student.id)).size,attendance=query.data.attendance_records,assessments=query.data.assessments;
 const currentDate=today(),todayAttendance=attendance.filter(item=>String(item.session?.session_date).slice(0,10)===currentDate).length,pending=assessments.filter(item=>item.status==='submitted').length,returned=assessments.filter(item=>item.status==='returned').length;
 return <div className="mx-auto max-w-6xl space-y-5 pb-16"><PageHeader title={tr('لوحة المشرف السريري','Clinical supervisor dashboard')} description={tr('ملخص تكليفاتك السريرية وما يحتاج إلى إجراء.','A summary of your clinical assignments and pending actions.')}><Link to="/clinical-supervisors/me" className="inline-flex items-center gap-2 rounded-xl border border-teal-200 bg-white px-3 py-2 text-xs font-bold text-teal-700"><UserRound className="h-4 w-4"/>{tr('ملفي السريري','My profile')}</Link></PageHeader>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Users} label={tr('المجموعات الحالية','Current groups')} value={groups.length}/><Metric icon={UserRound} label={tr('الطلبة المكلف بهم','Assigned students')} value={students}/><Metric icon={CalendarDays} label={tr('حضور مسجل اليوم','Recorded today')} value={todayAttendance}/><Metric icon={ClipboardCheck} label={tr('تقييمات بانتظار المراجعة','Awaiting review')} value={pending}/></section>
 {(returned>0||!groups.length)&&<div className={`rounded-2xl border px-4 py-3 text-xs font-bold ${returned?'border-amber-200 bg-amber-50 text-amber-900':'border-slate-200 bg-slate-50 text-slate-600'}`}>{returned?tr(`لديك ${returned} تقييم مُعاد يحتاج إلى تعديل وإعادة إرسال.`,`You have ${returned} returned assessments to revise and resubmit.`):tr('لا توجد مجموعات مرتبطة بك في جدول منشور حاليًا.','No groups are assigned to you in a current published schedule.')}</div>}
 <section className="grid gap-3 md:grid-cols-2"><Link to="/supervisor/attendance" className="group rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-teal-300 hover:shadow-md"><div className="flex items-center gap-3"><span className="rounded-2xl bg-teal-50 p-3 text-teal-700"><CalendarDays className="h-6 w-6"/></span><div><h2 className="font-black text-slate-900">{tr('الحضور والغياب','Attendance')}</h2><p className="mt-1 text-xs text-slate-500">{tr('رصد الحضور لكل المجموعات من جدول واحد منظم.','Record attendance for all groups in one organized table.')}</p></div></div></Link><Link to="/supervisor/assessments" className="group rounded-3xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-teal-300 hover:shadow-md"><div className="flex items-center gap-3"><span className="rounded-2xl bg-teal-50 p-3 text-teal-700"><Award className="h-6 w-6"/></span><div><h2 className="font-black text-slate-900">{tr('تقييمات الطلبة','Student assessments')}</h2><p className="mt-1 text-xs text-slate-500">{tr('إدخال علامات الطلبة مصنفة حسب مجموعاتهم.','Enter student scores grouped by their assigned groups.')}</p></div></div></Link></section>
 <section className="rounded-3xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 p-4"><h2 className="text-sm font-black">{tr('ملخص مجموعاتي الحالية','Current group summaries')}</h2></header><div className="divide-y divide-slate-100">{groups.map(group=>{const studentIds=new Set(group.students.map(student=>student.id));const groupAttendance=attendance.filter(item=>studentIds.has(item.student_id)&&item.session?.rotation_block_id===group.rotationBlockId);const groupAssessments=assessments.filter(item=>studentIds.has(item.student_id)&&item.session?.rotation_block_id===group.rotationBlockId);const assessedStudents=new Set(groupAssessments.filter(item=>['submitted','approved'].includes(item.status)).map(item=>item.student_id)).size;return <article key={group.key} className="grid gap-4 p-4 lg:grid-cols-[1fr_auto] lg:items-center"><div><h3 className="text-sm font-black text-slate-800">{groupName(group,ar)}</h3><p className="mt-1 text-[11px] text-slate-500">{ar?group.periodAr:group.periodEn} · {ar?group.siteAr:group.siteEn} · {group.academicYear}</p><div className="mt-3 flex flex-wrap gap-2"><SummaryPill label={tr('الطلبة','Students')} value={group.students.length}/><SummaryPill label={tr('سجلات الحضور','Attendance records')} value={groupAttendance.length}/><SummaryPill label={tr('تم تقييمهم','Assessed')} value={`${assessedStudents}/${group.students.length}`}/>{groupAssessments.some(item=>item.status==='returned')&&<span className="rounded-lg bg-amber-50 px-2.5 py-1.5 text-[10px] font-black text-amber-800">{tr('يوجد تقييم معاد','Returned assessment')}</span>}</div><div className="mt-2 flex flex-wrap gap-1.5">{group.students.slice(0,5).map(student=><span key={student.id} className="rounded-lg bg-slate-50 px-2 py-1 text-[10px] font-bold text-slate-600">{studentName(student,ar)}</span>)}{group.students.length>5&&<span className="rounded-lg bg-teal-50 px-2 py-1 text-[10px] font-bold text-teal-700">+{group.students.length-5}</span>}</div></div><div className="flex gap-2"><Link to={`/supervisor/attendance?group=${group.key}`} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700">{tr('الحضور','Attendance')}</Link><Link to={`/supervisor/assessments?group=${group.key}`} className="rounded-xl bg-teal-600 px-3 py-2 text-xs font-bold text-white">{tr('التقييم','Assessment')}</Link></div></article>})}</div></section></div>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:number}){return <article className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[11px] font-bold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-900">{value}</p></div><span className="rounded-2xl bg-teal-50 p-3 text-teal-700"><Icon className="h-5 w-5"/></span></div></article>}
function SummaryPill({label,value}:{label:string;value:string|number}){return <span className="rounded-lg bg-slate-100 px-2.5 py-1.5 text-[10px] font-bold text-slate-600">{label}: <b className="text-slate-900">{value}</b></span>}
