import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import QRCode from 'qrcode';
import { QrCode } from 'lucide-react';
import { getMySupervisorAssignments } from '@/api/distribution';
import { getQrPayload, getQrSession, getQrSessions, openQrSession, transitionQrSession, type QrSession } from '@/api/clinicalQrAttendance';

const labels:Record<string,string>={check_in_open:'إغلاق تسجيل الدخول',check_in_closed:'فتح تسجيل الخروج',check_out_open:'إنهاء واعتماد الجلسة'};
const action:Record<string,string>={check_in_open:'close_check_in',check_in_closed:'open_check_out',check_out_open:'finalize'};

export function SupervisorQrAttendanceWorkspace(){
 const client=useQueryClient();const [selected,setSelected]=useState<QrSession|null>(null);const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [assignment,setAssignment]=useState('');const [image,setImage]=useState('');const [expires,setExpires]=useState(0);
 const sessions=useQuery({queryKey:['qr-sessions'],queryFn:getQrSessions});const assignments=useQuery({queryKey:['my-supervisor-assignments'],queryFn:getMySupervisorAssignments});
 useEffect(()=>{if(!selected&&sessions.data?.[0])setSelected(sessions.data[0]);},[sessions.data,selected]);
 useEffect(()=>{if(!selected||!['check_in_open','check_out_open'].includes(selected.state))return;let stopped=false;const refresh=async()=>{try{const data=await getQrPayload(selected.id);if(!stopped){setImage(await QRCode.toDataURL(data.token,{margin:1,width:300,color:{dark:'#123743',light:'#ffffff'}}));setExpires(new Date(data.expires_at).getTime());}}catch{setImage('');}};void refresh();const timer=window.setInterval(refresh,15000);return()=>{stopped=true;window.clearInterval(timer)};},[selected?.id,selected?.state]);
 useEffect(()=>{if(!selected||document.hidden)return;const timer=window.setInterval(()=>void getQrSession(selected.id).then(setSelected),5000);return()=>window.clearInterval(timer)},[selected?.id]);
 const open=useMutation({mutationFn:()=>openQrSession(Number(assignment),date),onSuccess:s=>{setSelected(s);void client.invalidateQueries({queryKey:['qr-sessions']})}});const change=useMutation({mutationFn:()=>transitionQrSession(selected!.id,action[selected!.state]),onSuccess:s=>{setSelected(s);void client.invalidateQueries({queryKey:['qr-sessions']})}});
 const left=Math.max(0,Math.ceil((expires-Date.now())/1000));const roster=selected?.roster??[];const stats=useMemo(()=>({in:roster.filter(x=>x.checked_in_at).length,out:roster.filter(x=>x.checked_out_at).length}),[roster]);
 return <div dir="rtl" className="mx-auto max-w-5xl space-y-5 pb-12"><header><h1 className="text-xl font-black">الحضور عبر QR</h1><p className="mt-1 text-sm text-slate-500">افتح الدخول، أغلقه، افتح الخروج، ثم اعتمد الجلسة.</p></header><section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_180px_160px]"><select value={assignment} onChange={e=>setAssignment(e.target.value)} className="h-11 rounded-xl border px-3 text-sm"><option value="">اختر مجموعة مكلفاً بها</option>{assignments.data?.data.map(a=><option key={a.id} value={a.id}>{a.student_subgroup_id?`مجموعة فرعية #${a.student_subgroup_id}`:`تكليف #${a.id}`} — {a.training_site?.name_ar}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-11 rounded-xl border px-3 text-sm"/><button disabled={!assignment||open.isPending} onClick={()=>open.mutate()} className="rounded-xl bg-teal-700 px-4 text-sm font-black text-white disabled:opacity-50">فتح تسجيل الدخول</button></div></section>{selected&&<section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><b>جلسة {selected.session_date}</b><p className="mt-1 text-xs text-slate-500">{selected.training_site?.name_ar} · {selected.state}</p></div><button onClick={()=>change.mutate()} disabled={change.isPending||selected.state==='finalized'} className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{labels[selected.state]??'تم اعتماد الجلسة'}</button></div><div className="grid gap-5 p-5 md:grid-cols-[330px_1fr]"><div className="rounded-2xl bg-slate-50 p-4 text-center">{image?<img src={image} alt="رمز حضور متغير" className="mx-auto w-full max-w-[260px] rounded-xl bg-white p-2"/>:<div className="grid aspect-square place-items-center text-slate-400"><QrCode className="h-12 w-12"/></div>}<p className="mt-3 text-xs font-bold text-teal-800">{selected.state==='check_out_open'?'تسجيل الخروج':'تسجيل الدخول'} · يتغير خلال {left} ث</p></div><div><div className="grid grid-cols-3 gap-2"><Stat title="الطلبة" value={roster.length}/><Stat title="دخول" value={stats.in}/><Stat title="خروج" value={stats.out}/></div><div className="mt-4 max-h-72 overflow-auto divide-y rounded-xl border">{roster.map(r=><div key={r.id} className="flex items-center justify-between gap-3 p-3 text-xs"><div><b>{r.student.full_name_ar}</b><span dir="ltr" className="mr-2 text-slate-400">{r.student.university_number}</span></div><span className={r.checked_out_at?'text-emerald-700':r.checked_in_at?'text-amber-700':'text-slate-400'}>{r.checked_out_at?'اكتمل':r.checked_in_at?'بانتظار الخروج':'لم يسجل'}</span></div>)}</div></div></div></section>}</div>;
}
function Stat({title,value}:{title:string;value:number}){return <div className="rounded-xl bg-teal-50 p-3 text-center"><p className="text-lg font-black text-teal-800">{value}</p><p className="text-[11px] text-teal-700">{title}</p></div>}
