import { basicText as bt, basicLocale } from '@/i18n/basicAttendance';
import { useEffect, useState, type ReactNode } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import QRCode from 'qrcode';
import { apiFetch, apiUrl } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { Button } from '@/components/ui/Button';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { basicQrScanLink } from './basicQrLink';

type Course = { id:number;code:string;name:string;academic_level:string };
type Section = { id:number;course_id:number;course_name:string;course_code:string;number:string;academic_year:string;semester:string;is_active:boolean;students_count:number;lecturers:{id:number;name:string}[];active_session:Session|null };
type Session = { id:number;title:string;state:string;mode:string;opened_at:string;phase_expires_at:string|null;finalized_at:string|null };
type Row = { id:number;student_id:number;name:string;university_number:string;photo_url:string|null;check_in_at:string|null;check_out_at:string|null;is_late:boolean;status:string;source:string;reason:string|null;session_id:number };
type SessionData = {session:Session;section:Section;accepting:boolean;rows:Row[];counts:{total:number;check_in:number;check_out:number;absent:number;late:number;incomplete:number}};
type Report = {section:Section;sessions:Session[];students:{id:number;name:string;university_number:string}[];records:Row[];pagination:{offset:number;total:number;per_page:number}};
const stateLabel = (s:string) => ({check_in:bt('text001'),paused:bt('text002'),check_out:bt('text003'),finalized:bt('text004')}[s]??s);
function statusLabel(r:Row,s:Session){if(r.source==='manual'||s.state==='finalized')return {present:bt('text005'),absent:bt('text006'),incomplete:bt('text007'),excused:bt('text008'),pending:bt('text009')}[r.status]??r.status;return !r.check_in_at?bt('text010'):s.mode==='double'&&!r.check_out_at?bt('text011'):bt('text012');}
const time=(s:string|null)=>s?new Date(s.includes('T')?s:s.replace(' ','T')).toLocaleTimeString(basicLocale(),{hour:'2-digit',minute:'2-digit'}):'—';
const date=(s:string)=>new Date(s.includes('T')?s:s.replace(' ','T')).toLocaleDateString(basicLocale());

export function BasicAttendancePage(){
  const {can,user}=useAuth(); const {t}=useI18n(); const qc=useQueryClient(); const [searchParams,setParams]=useSearchParams();
  const sectionId=Number(searchParams.get('section'))||0;
  const [managing,setManaging]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false); const [search,setSearch]=useState('');
  const [courseForm,setCourseForm]=useState({code:'',name:'',academic_level:'first'});
  const [sectionForm,setSectionForm]=useState({id:0,course_id:0,number:'',academic_year:'',semester:'first',is_active:true,lecturer_ids:[] as number[]});
  const [lecture,setLecture]=useState({title:bt('text013')+new Date().toLocaleDateString(basicLocale()),mode:'single',window_minutes:5,late_after_minutes:2});
  const [rosterPreview,setRosterPreview]=useState<Record<string,unknown>[]>([]); const [reporting,setReporting]=useState(false); const [offset,setOffset]=useState(0);
  const sections=useQuery({queryKey:['basic-sections',user?.id],queryFn:()=>apiFetch<Section[]>('/basic-attendance/sections'),enabled:can('basic_attendance.view')});
  const options=useQuery({queryKey:['basic-options'],queryFn:()=>apiFetch<{courses:Course[];lecturers:{id:number;name:string;email:string}[]}>('/basic-attendance/options'),enabled:can('basic_attendance.manage')&&managing});
  const sessions=useQuery({queryKey:['basic-sessions',sectionId],queryFn:()=>apiFetch<Session[]>(`/basic-attendance/sections/${sectionId}/sessions`),enabled:!!sectionId});
  const roster=useQuery({queryKey:['basic-roster',sectionId],queryFn:()=>apiFetch<{id:number;name:string;university_number:string;email:string}[]>(`/basic-attendance/sections/${sectionId}/roster`),enabled:!!sectionId&&managing});
  const report=useQuery({queryKey:['basic-report',sectionId,offset],queryFn:()=>apiFetch<Report>(`/basic-attendance/sections/${sectionId}/report?offset=${offset}`),enabled:!!sectionId&&reporting});
  const selected=sections.data?.find(s=>s.id===sectionId);
  async function run(action:()=>Promise<unknown>,message=bt('text014')){setBusy(true);setError('');setNotice('');try{await action();setNotice(message);await qc.invalidateQueries({queryKey:['basic-sections']});await qc.invalidateQueries({queryKey:['basic-options']});await qc.invalidateQueries({queryKey:['basic-roster']});await qc.invalidateQueries({queryKey:['basic-sessions']});}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function readFile(file:File){setError('');setRosterPreview([]);try{const x=await import('xlsx');const book=x.read(await file.arrayBuffer(),{type:'array'});const raw=x.utils.sheet_to_json<Record<string,unknown>>(book.Sheets[book.SheetNames[0]],{defval:''});if(!raw.length||raw.length>2000)throw new Error(bt('text015'));const rows=raw.map(r=>({university_number:String(r.university_number??r['الرقم الجامعي']??'').trim(),name:String(r.name??r['الاسم']??'').trim(),email:String(r.email??r['البريد الجامعي']??'').trim(),...(r.photo_url?{photo_url:String(r.photo_url)}:{})}));if(rows.some(r=>!r.university_number||!r.name||!r.email))throw new Error(bt('text016'));setRosterPreview(rows)}catch(e){setError((e as Error).message)}}
  if(!can('basic_attendance.view'))return <ErrorState title={t('state.forbidden.title')} message={t('state.forbidden.message')}/>;
  if(sections.isLoading)return <LoadingState/>;if(sections.isError)return <ErrorState onRetry={()=>sections.refetch()}/>;
  return <div className="mx-auto max-w-6xl space-y-5 pb-8" dir={basicLocale() === 'ar' ? 'rtl' : 'ltr'}><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold text-teal-700">{bt('text017')}</p><h1 className="mt-1 text-xl font-black text-slate-800">{bt('text018')}</h1><p className="mt-2 text-xs leading-6 text-slate-500">{bt('text019')}</p></div>{can('basic_attendance.manage')&&<Button variant="outline" onClick={()=>setManaging(!managing)}>{managing?bt('text020'):bt('text021')}</Button>}</header>
    {error&&<Message error>{error}</Message>}{notice&&<Message>{notice}</Message>}
    {!selected&&<><input className="input" aria-label={bt('text022')} placeholder={bt('text023')} value={search} onChange={e=>setSearch(e.target.value)}/><section className="divide-y divide-slate-100 overflow-hidden rounded-2xl border border-slate-200 bg-white">{(sections.data??[]).filter(s=>`${s.course_name} ${s.course_code} ${s.number}`.includes(search)).map(s=><button key={s.id} className="flex w-full items-center justify-between gap-3 p-4 text-start hover:bg-teal-50/40" onClick={()=>{setParams({section:String(s.id)});setReporting(false);setOffset(0)}}><div><p className="font-bold text-slate-800">{s.course_name} <span className="text-teal-700">{bt('text024')}{s.number}</span></p><p className="mt-1 text-xs leading-6 text-slate-500">{s.course_code} · {s.academic_year} · {s.students_count} {bt('text025')}{s.lecturers.map(l=>l.name).join(bt('text026'))}</p></div><span className="shrink-0 text-xs font-bold text-teal-700">{!s.is_active?bt('text027'):s.active_session?bt('text028'):bt('text029')}</span></button>)}{!sections.data?.length&&<p className="p-8 text-center text-sm text-slate-500">{bt('text030')}</p>}</section></>}
    {managing&&can('basic_attendance.manage')&&<section className="space-y-5 rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><p className="text-xs leading-6 text-slate-500">{bt('text031')}</p>{options.isLoading?<LoadingState/>:options.isError?<ErrorState onRetry={()=>options.refetch()}/>:<>
      <form className="grid gap-3 sm:grid-cols-4" onSubmit={e=>{e.preventDefault();void run(()=>apiFetch('/basic-attendance/courses',{method:'POST',body:courseForm}))}}><Field label={bt('text032')}><input required className="input" value={courseForm.code} onChange={e=>setCourseForm({...courseForm,code:e.target.value})}/></Field><Field label={bt('text033')}><input required className="input" value={courseForm.name} onChange={e=>setCourseForm({...courseForm,name:e.target.value})}/></Field><Field label={bt('text034')}><select className="input" value={courseForm.academic_level} onChange={e=>setCourseForm({...courseForm,academic_level:e.target.value})}><option value="first">{bt('text035')}</option><option value="second">{bt('text036')}</option><option value="third">{bt('text037')}</option></select></Field><Button className="self-end" disabled={busy} type="submit">{bt('text038')}</Button></form>
      <form className="space-y-3 border-t border-slate-100 pt-5" onSubmit={e=>{e.preventDefault();void run(()=>apiFetch(sectionForm.id?`/basic-attendance/sections/${sectionForm.id}`:'/basic-attendance/sections',{method:sectionForm.id?'PUT':'POST',body:sectionForm}))}}><h2 className="font-bold">{sectionForm.id?bt('text039'):bt('text040')}</h2><div className="grid gap-3 sm:grid-cols-4"><Field label={bt('text041')}><select required className="input" value={sectionForm.course_id||''} onChange={e=>setSectionForm({...sectionForm,course_id:Number(e.target.value)})}><option value="">{bt('text042')}</option>{options.data?.courses.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></Field><Field label={bt('text043')}><input required className="input" value={sectionForm.number} onChange={e=>setSectionForm({...sectionForm,number:e.target.value})}/></Field><Field label={bt('text044')}><input required placeholder="2026/2027" className="input" value={sectionForm.academic_year} onChange={e=>setSectionForm({...sectionForm,academic_year:e.target.value})}/></Field><Field label={bt('text045')}><select className="input" value={sectionForm.semester} onChange={e=>setSectionForm({...sectionForm,semester:e.target.value})}><option value="first">{bt('text046')}</option><option value="second">{bt('text047')}</option><option value="summer">{bt('text048')}</option></select></Field></div><fieldset className="grid gap-2 sm:grid-cols-2"><legend className="mb-2 text-xs font-bold">{bt('text049')}</legend>{options.data?.lecturers.map(l=><label key={l.id} className="flex items-center gap-2 rounded-lg bg-slate-50 p-3 text-sm"><input type="checkbox" checked={sectionForm.lecturer_ids.includes(l.id)} onChange={e=>setSectionForm({...sectionForm,lecturer_ids:e.target.checked?[...sectionForm.lecturer_ids,l.id]:sectionForm.lecturer_ids.filter(id=>id!==l.id)})}/>{l.name}</label>)}{!options.data?.lecturers.length&&<p className="text-xs text-amber-700">{bt('text050')}</p>}</fieldset><label className="flex gap-2 text-sm"><input type="checkbox" checked={sectionForm.is_active} onChange={e=>setSectionForm({...sectionForm,is_active:e.target.checked})}/>{bt('text051')}</label><div className="flex gap-2"><Button disabled={busy||!sectionForm.lecturer_ids.length} type="submit">{bt('text052')}</Button>{sectionForm.id>0&&<Button variant="outline" onClick={()=>setSectionForm({id:0,course_id:0,number:'',academic_year:'',semester:'first',is_active:true,lecturer_ids:[]})}>{bt('text053')}</Button>}</div></form></>}
    </section>}
    {selected&&<><div className="flex flex-wrap items-start justify-between gap-3"><div><button className="mb-3 text-sm font-bold text-teal-700" onClick={()=>{setParams({});setReporting(false);setRosterPreview([])}}>{bt('text054')}</button><h2 className="text-lg font-black">{selected.course_name} {bt('text024')}{selected.number}</h2><p className="mt-1 text-xs text-slate-500">{selected.academic_year} · {selected.students_count} {bt('text055')}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setReporting(!reporting)}>{reporting?bt('text056'):bt('text057')}</Button>{can('basic_attendance.export')&&<a className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold" href={apiUrl(`/basic-attendance/sections/${sectionId}/export`)}>{bt('text058')}</a>}{can('basic_attendance.manage')&&<Button variant="outline" onClick={()=>{setManaging(true);setSectionForm({id:selected.id,course_id:selected.course_id,number:selected.number,academic_year:selected.academic_year,semester:selected.semester,is_active:!!selected.is_active,lecturer_ids:selected.lecturers.map(l=>l.id)})}}>{bt('text059')}</Button>}</div></div>
    {managing&&can('basic_attendance.manage')&&<section className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4"><h3 className="font-bold">{bt('text060')}</h3><p className="text-xs leading-6 text-slate-500">{bt('text061')}</p><input type="file" accept=".csv,.xlsx,.xls" aria-label={bt('text062')} onChange={e=>{if(e.target.files?.[0])void readFile(e.target.files[0])}}/>{rosterPreview.length>0&&<div className="space-y-2"><p className="text-sm">{bt('text063')}{rosterPreview.length} {bt('text064')}{String(rosterPreview[0].name)} — {String(rosterPreview[0].university_number)}</p><Button disabled={busy} onClick={()=>void run(async()=>{await apiFetch(`/basic-attendance/sections/${sectionId}/roster`,{method:'POST',body:{rows:rosterPreview}});setRosterPreview([])})}>{bt('text065')}</Button></div>}{roster.isError&&<ErrorState onRetry={()=>roster.refetch()}/>}<div className="max-h-64 overflow-auto"><table className="w-full text-start text-xs"><thead><tr><th className="p-2">{bt('text066')}</th><th>{bt('text067')}</th><th/></tr></thead><tbody>{roster.data?.map(st=><tr key={st.id} className="border-t border-slate-100"><td className="p-2">{st.name}</td><td dir="ltr">{st.university_number}</td><td><button className="text-red-700" onClick={()=>{if(window.confirm(bt('text068')))void run(()=>apiFetch(`/basic-attendance/sections/${sectionId}/roster/${st.id}`,{method:'DELETE'}))}}>{bt('text069')}</button></td></tr>)}</tbody></table></div></section>}
    {reporting?<>{report.isLoading?<LoadingState/>:report.isError?<ErrorState onRetry={()=>report.refetch()}/>:report.data&&<><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-slate-500">{bt('text070')}</p><div className="flex gap-2"><Button variant="outline" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-7))}>{bt('text071')}</Button><Button variant="outline" disabled={offset+7>=report.data.pagination.total} onClick={()=>setOffset(offset+7)}>{bt('text072')}</Button><Button variant="outline" onClick={()=>printReport(report.data!)}>{bt('text073')}</Button></div></div><ReportTable data={report.data}/></>}</>:<>
      {selected.active_session?<Link to={`/basic-attendance/sessions/${selected.active_session.id}`} className="block rounded-2xl border border-teal-200 bg-teal-50 p-4 font-bold text-teal-800">{bt('text074')}{selected.active_session.title} ←</Link>:can('basic_attendance.record')&&selected.is_active&&<form className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4" onSubmit={e=>{e.preventDefault();void run(async()=>{const s=await apiFetch<{id:number}>(`/basic-attendance/sections/${sectionId}/sessions`,{method:'POST',body:lecture});window.location.assign(`/basic-attendance/sessions/${s.id}`)})}}><h3 className="font-bold">{bt('text075')}</h3><Field label={bt('text076')}><input required className="input" value={lecture.title} onChange={e=>setLecture({...lecture,title:e.target.value})}/></Field><div className="grid gap-3 sm:grid-cols-3"><Field label={bt('text077')}><select className="input" value={lecture.mode} onChange={e=>setLecture({...lecture,mode:e.target.value})}><option value="single">{bt('text078')}</option><option value="double">{bt('text079')}</option></select></Field><Field label={bt('text080')}><input className="input" type="number" min={1} max={30} value={lecture.window_minutes} onChange={e=>setLecture({...lecture,window_minutes:Number(e.target.value)})}/></Field><Field label={bt('text081')}><input className="input" type="number" min={0} max={30} value={lecture.late_after_minutes} onChange={e=>setLecture({...lecture,late_after_minutes:Number(e.target.value)})}/></Field></div><Button disabled={busy||!selected.students_count} type="submit">{bt('text082')}</Button></form>}
      <section className="divide-y overflow-hidden rounded-2xl border border-slate-200 bg-white">{sessions.isError?<ErrorState onRetry={()=>sessions.refetch()}/>:sessions.data?.map(s=><Link key={s.id} to={`/basic-attendance/sessions/${s.id}`} className="flex items-center justify-between gap-2 p-4"><div><p className="font-bold">{s.title}</p><p className="mt-1 text-xs text-slate-500">{date(s.opened_at)}</p></div><span className="text-xs text-teal-700">{stateLabel(s.state)} ←</span></Link>)}{sessions.data?.length===0&&<p className="p-6 text-center text-sm text-slate-500">{bt('text083')}</p>}</section></>}
    </>}
    <p className="text-xs leading-6 text-slate-400">{bt('text084')}<a className="font-semibold text-teal-700" href="/lecture-attendance">{window.location.origin}/lecture-attendance</a>{bt('text085')}</p>
  </div>;
}

export function BasicLectureSessionPage(){
  const {sessionId}=useParams();const {can}=useAuth();const {t}=useI18n();const qc=useQueryClient();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [filter,setFilter]=useState('');const [full,setFull]=useState(false);const [editing,setEditing]=useState<Row|null>(null);const [correction,setCorrection]=useState({status:'present',is_late:false,reason:''});const [qrImage,setQrImage]=useState({url:'',image:''});const [tick,setTick]=useState(Date.now());const [auditing,setAuditing]=useState(false);
  const query=useQuery({queryKey:['basic-session',sessionId],queryFn:()=>apiFetch<SessionData>(`/basic-attendance/sessions/${sessionId}`),enabled:can('basic_attendance.view'),refetchInterval:10000});
  const qr=useQuery({queryKey:['basic-qr',sessionId],queryFn:()=>apiFetch<{url:string|null;phase:string;valid_until?:number;server_time?:number}>(`/basic-attendance/sessions/${sessionId}/qr`),enabled:can('basic_attendance.record')&&!!query.data&&query.data.session.state!=='finalized',refetchInterval:5000});
  const audit=useQuery({queryKey:['basic-audit',sessionId],queryFn:()=>apiFetch<{data:{id:number;event:string;actor_name:string|null;details:string;created_at:string}[]}>(`/basic-attendance/sessions/${sessionId}/audit`),enabled:auditing});
  useEffect(()=>{const id=window.setInterval(()=>setTick(Date.now()),500);return()=>window.clearInterval(id)},[]);
  useEffect(()=>{let cancelled=false;setQrImage({url:'',image:''});const url=qr.data?.url;if(url){const link=basicQrScanLink(url,window.location.origin);if(!link){setError(bt('text153'));return()=>{cancelled=true}}void QRCode.toDataURL(link,{width:640,margin:4,errorCorrectionLevel:'M',color:{dark:'#12343b',light:'#ffffff'}}).then(image=>{if(!cancelled)setQrImage({url,image})}).catch(()=>{if(!cancelled)setError(bt('text086'))})}return()=>{cancelled=true}},[qr.data?.url]);
  const seconds=qr.data?.valid_until&&qr.data.server_time?Math.max(0,Math.ceil(qr.data.valid_until-qr.data.server_time-(tick-qr.dataUpdatedAt)/1000)):0;
  useEffect(()=>{if(qr.data?.url&&seconds===0&&!qr.isFetching)void qr.refetch()},[seconds,qr.dataUpdatedAt,qr.isFetching]);
  const visible=!!qr.data?.url&&!qr.isError&&seconds>0&&qrImage.url===qr.data.url&&!!qrImage.image&&!!query.data?.accepting;
  async function action(name:string){if(name==='finalize'&&!window.confirm(bt('text087')))return;setBusy(true);setError('');try{await apiFetch(`/basic-attendance/sessions/${sessionId}/transition`,{method:'POST',body:{action:name}});await qc.invalidateQueries({queryKey:['basic-session',sessionId]});await qc.invalidateQueries({queryKey:['basic-qr',sessionId]});await qc.invalidateQueries({queryKey:['basic-sections']});await qc.invalidateQueries({queryKey:['basic-audit',sessionId]});}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function edit(r:Row){setEditing(r);setCorrection({status:r.status==='pending'?'present':r.status,is_late:!!r.is_late,reason:r.reason??''})}
  if(!can('basic_attendance.view'))return <ErrorState title={t('state.forbidden.title')}/>;if(query.isLoading)return <LoadingState/>;if(query.isError||!query.data)return <ErrorState onRetry={()=>query.refetch()}/>;
  const d=query.data;const state=d.session.state;const rows=d.rows.filter(r=>`${r.name} ${r.university_number} ${statusLabel(r,d.session)}`.includes(filter));
   const qrPanel=<div className="mx-auto flex w-full max-w-xl flex-col items-center rounded-3xl border border-teal-100 bg-white p-4 text-center shadow-[0_18px_44px_-38px_rgba(15,118,110,0.7)] sm:p-6"><h2 className="text-lg font-black text-teal-900">{state==='check_out'?bt('text088'):bt('text089')}</h2>{visible?<img src={qrImage.image} alt={bt('text089')} className="mt-3 aspect-square w-full max-w-[440px] rounded-2xl border border-slate-100 bg-white"/>:<div className="mt-3 flex aspect-square w-full max-w-[440px] items-center justify-center rounded-2xl bg-slate-50 p-6 text-sm leading-7 text-slate-500">{qr.isError?bt('text090'):d.accepting?bt('text091'):bt('text092')}</div>}<p className="mt-3 text-sm font-semibold text-teal-900">{visible?bt('text093', {v0: seconds}):bt('text094')}</p><p className="mt-1 text-xs text-slate-500">{bt('text154', {v0:window.location.host})}</p>{!full&&visible&&<Button className="mt-4" variant="outline" onClick={()=>setFull(true)}>{bt('text095')}</Button>}</div>;
    return <div className="mx-auto max-w-6xl space-y-5 pb-10" dir={basicLocale() === 'ar' ? 'rtl' : 'ltr'}><Link className="inline-flex text-sm font-bold text-teal-700" to={`/basic-attendance/sections/${d.section.id}/lectures`}>{bt('text096')}</Link><header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-5"><div><p className="text-xs font-bold text-teal-700">{d.section.course_name} · {date(d.session.opened_at)}</p><h1 className="mt-1 text-2xl font-black text-slate-900">{d.session.title}</h1><p className="mt-2 text-sm text-slate-500">{bt('text024')}{d.section.number} · {stateLabel(state)}</p></div>{can('basic_attendance.record')&&state!=='finalized'&&<div className="flex flex-wrap gap-2">{['check_in','check_out'].includes(state)&&<Button disabled={busy} onClick={()=>void action('close')}>{bt('text097')}</Button>}{state==='paused'&&d.session.mode==='double'&&<Button disabled={busy} onClick={()=>void action('open_exit')}>{bt('text098')}</Button>}{state==='paused'&&<Button variant={d.session.mode==='double'?'outline':'primary'} disabled={busy} onClick={()=>void action('finalize')}>{bt('text100')}</Button>}{state==='paused'&&d.counts.check_out===0&&<Button variant="outline" disabled={busy} onClick={()=>void action('reopen_entry')}>{bt('text099')}</Button>}</div>}</header>{error&&<Message error>{error}</Message>}
    {state!=='finalized'&&can('basic_attendance.record')&&qrPanel}
     <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[[bt('text101'),d.counts.total],[bt('text102'),d.counts.check_in],...(d.session.mode==='double'?[[bt('text103'),d.counts.check_out]]:[]),[bt('text104'),d.counts.late],...(state==='finalized'?[[bt('text105'),d.counts.absent],[bt('text106'),d.counts.incomplete]]:[])].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white px-4 py-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-black text-slate-900">{value}</p></div>)}</div>
     <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-4 py-4 sm:px-6"><input className="input w-full sm:max-w-sm" aria-label={bt('text107')} placeholder={bt('text108')} value={filter} onChange={e=>setFilter(e.target.value)}/></div>
     <div className="overflow-x-auto"><table className="w-full min-w-[340px] text-start text-xs"><thead className="bg-slate-50 text-slate-600"><tr><th className="sticky start-0 z-10 bg-slate-50 p-3">{bt('text066')}</th><th>{bt('text109')}</th>{d.session.mode==='double'&&<th className="hidden sm:table-cell">{bt('text003')}</th>}<th>{bt('text110')}</th><th className="hidden sm:table-cell">{bt('text111')}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="sticky start-0 w-[46%] bg-white p-2 sm:w-auto sm:p-3"><div className="flex items-center gap-2">{r.photo_url?<img src={r.photo_url} alt="" className="h-9 w-9 rounded-full object-cover"/>:<span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-teal-50 font-bold text-teal-700">{r.name.slice(0,1)}</span>}<div><p className="max-w-[165px] break-words font-bold sm:max-w-none">{r.name}</p><p className="mt-1 text-start font-mono text-[10px] text-slate-500" dir="ltr">{r.university_number}</p>{can('basic_attendance.record')&&<button className="mt-1 text-[10px] font-bold text-teal-700 sm:hidden" onClick={()=>edit(r)}>{bt('text114')}</button>}</div></div></td><td className="px-2">{time(r.check_in_at)}{d.session.mode==='double'&&<p className="mt-1 text-[10px] text-slate-500 sm:hidden">{bt('text003')}: {time(r.check_out_at)}</p>}</td>{d.session.mode==='double'&&<td className="hidden sm:table-cell">{time(r.check_out_at)}</td>}<td><span className={r.status==='absent'?'text-red-700':'text-teal-800'}>{statusLabel(r,d.session)}</span>{!!r.is_late&&<p className="mt-1 text-amber-700">{bt('text112')}</p>}{r.source==='manual'&&<p className="mt-1 text-slate-500" title={r.reason??''}>{bt('text113')}</p>}</td><td className="hidden sm:table-cell">{can('basic_attendance.record')&&<button className="rounded-lg border border-slate-200 px-2 py-1" onClick={()=>edit(r)}>{bt('text114')}</button>}</td></tr>)}</tbody></table></div></section>
    <button className="text-xs font-bold text-teal-700" onClick={()=>setAuditing(!auditing)}>{auditing?bt('text115'):bt('text116')}</button>{auditing&&<section className="max-h-72 space-y-2 overflow-auto rounded-xl border border-slate-200 bg-white p-4">{audit.isError?<ErrorState onRetry={()=>audit.refetch()}/>:audit.data?.data.map(a=><div key={a.id} className="border-b border-slate-100 pb-2 text-xs"><p>{a.event} · {a.actor_name??bt('text117')} · {date(a.created_at)} {time(a.created_at)}</p><pre className="mt-1 whitespace-pre-wrap break-words text-slate-500">{a.details}</pre></div>)}</section>}
    {full&&<div role="dialog" aria-label={bt('text118')} className="fixed inset-0 z-50 flex flex-col items-center justify-center overflow-auto bg-white p-4"><Button variant="outline" className="mb-3" onClick={()=>setFull(false)}>{bt('text119')}</Button><p className="mb-3 text-sm font-bold">{d.section.course_name} {bt('text120')}{d.section.number}</p>{qrPanel}</div>}
    {editing&&<Modal title={bt('text121', {v0: editing.name})} onClose={()=>setEditing(null)}><form className="space-y-3" onSubmit={e=>{e.preventDefault();void(async()=>{setBusy(true);setError('');try{await apiFetch(`/basic-attendance/sessions/${sessionId}/records/${editing.student_id}`,{method:'PUT',body:correction});setEditing(null);await query.refetch();await qc.invalidateQueries({queryKey:['basic-audit',sessionId]})}catch(e){setError((e as Error).message)}finally{setBusy(false)}})()}}><Field label={bt('text110')}><select className="input" value={correction.status} onChange={e=>setCorrection({...correction,status:e.target.value})}><option value="present">{bt('text005')}</option><option value="absent">{bt('text006')}</option><option value="incomplete">{bt('text122')}</option><option value="excused">{bt('text008')}</option></select></Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={correction.is_late} onChange={e=>setCorrection({...correction,is_late:e.target.checked})}/>{bt('text112')}</label><Field label={bt('text123')}><textarea required minLength={5} maxLength={1000} className="input" value={correction.reason} onChange={e=>setCorrection({...correction,reason:e.target.value})}/></Field><p className="text-xs text-slate-500">{bt('text124')}</p>{error&&<Message error>{error}</Message>}<Button type="submit" disabled={busy}>{bt('text125')}</Button></form></Modal>}
  </div>;
}

function ReportTable({data}:{data:Report}){const records=new Map(data.records.map(r=>[`${r.student_id}:${r.session_id}`,r]));return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-start text-xs"><thead className="bg-teal-50/60"><tr><th className="sticky start-0 min-w-44 bg-teal-50 p-3">{bt('text066')}</th>{data.sessions.map(s=><th key={s.id} className="min-w-28 p-3"><p>{s.title}</p><p className="mt-1 font-normal text-slate-500">{date(s.opened_at)} · {stateLabel(s.state)}</p></th>)}</tr></thead><tbody>{data.students.map(st=><tr key={st.id} className="border-t border-slate-100"><td className="sticky start-0 bg-white p-3"><p className="font-bold">{st.name}</p><p className="mt-1 text-start font-mono text-slate-500" dir="ltr">{st.university_number}</p></td>{data.sessions.map(s=>{const r=records.get(`${st.id}:${s.id}`);return <td key={s.id} className="p-3 text-center">{r?<><p className={r.status==='absent'?'text-red-700':'text-teal-800'}>{statusLabel(r,s)}</p>{!!r.is_late&&<span className="text-amber-700">{bt('text112')}</span>}</>:'—'}</td>})}</tr>)}</tbody></table>{!data.students.length&&<p className="p-6 text-sm text-slate-500">{bt('text126')}</p>}</div>}
function printReport(data:Report){const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const w=window.open('','_blank');if(!w)return;const map=new Map(data.records.map(r=>[`${r.student_id}:${r.session_id}`,r]));w.document.write(bt('text127', {v0: esc(data.section.course_name), v1: esc(data.section.number), v2: esc(data.section.academic_year), v3: data.sessions.map(s=>`<th>${esc(s.title)}<br>${esc(date(s.opened_at))}</th>`).join(''), v4: data.students.map(st=>`<tr><td>${esc(st.name)}<br>${esc(st.university_number)}</td>${data.sessions.map(s=>{const r=map.get(`${st.id}:${s.id}`);return `<td>${r?esc(statusLabel(r,s)+(r.is_late?' · '+bt('text112'):'')):'—'}</td>`}).join('')}</tr>`).join('')}));w.document.close();w.focus();w.print();}
function Message({children,error=false}:{children:ReactNode;error?:boolean}){return <div role={error?'alert':'status'} className={`rounded-xl p-3 text-sm leading-6 ${error?'bg-red-50 text-red-700':'bg-teal-50 text-teal-800'}`}>{children}</div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block space-y-1.5"><span className="text-xs font-bold text-slate-600">{label}</span>{children}</label>}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-500/20 p-3"><section role="dialog" aria-label={title} className="max-h-[90dvh] w-full max-w-lg space-y-4 overflow-auto rounded-2xl border border-slate-200 bg-white p-5"><header className="flex justify-between gap-3"><h2 className="font-bold">{title}</h2><button onClick={onClose}>{bt('text128')}</button></header>{children}</section></div>}
