import { basicText as bt, basicLocale } from '@/i18n/basicAttendance';
import { useEffect, useRef, useState } from 'react';
import { apiFetch } from '@/api/client';
import { Button } from '@/components/ui/Button';

type Student={id:number;name:string;university_number:string};
type Attendance={phase:string;time:string;already_recorded:boolean;course_name:string;section_number:string;title:string};
export function PublicLectureAttendancePage(){
  const qr=new URLSearchParams(window.location.search).get('qr');
  const [ticket,setTicket]=useState('');const [claimExpiresAt,setClaimExpiresAt]=useState('');const [preparing,setPreparing]=useState(!!qr);const prepared=useRef(false);
  const [student,setStudent]=useState<Student|null>(null);const [ready,setReady]=useState(false);const [number,setNumber]=useState('');const [challenge,setChallenge]=useState('');const [otp,setOtp]=useState('');const [remember,setRemember]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<Attendance|null>(null);const [notice,setNotice]=useState('');const attempted=useRef(false);
  useEffect(()=>{void apiFetch<{student:Student|null}>('/public/basic-attendance/identity').then(d=>{setStudent(d.student);setReady(true)}).catch(e=>{setError((e as Error).message);setReady(true)})},[]);
  useEffect(()=>{if(!ready||!student||!qr||attempted.current)return;attempted.current=true;setBusy(true);setError('');void apiFetch<Attendance>('/public/basic-attendance/scan',{method:'POST',body:{qr}}).then(setResult).catch(e=>setError((e as Error).message)).finally(()=>setBusy(false))},[ready,student,qr]);
  useEffect(()=>{if(!ready)return;if(student||!qr){setPreparing(false);return}if(prepared.current)return;prepared.current=true;void apiFetch<{scan_ticket:string;claim_expires_at:string}>('/public/basic-attendance/prepare',{method:'POST',body:{qr}}).then(d=>{setTicket(d.scan_ticket);setClaimExpiresAt(d.claim_expires_at)}).catch(e=>setError((e as Error).message)).finally(()=>setPreparing(false))},[ready,student,qr]);
  async function requestOtp(){setBusy(true);setError('');setNotice('');try{const d=await apiFetch<{challenge_token:string;claim_expires_at:string|null}>('/public/basic-attendance/request-otp',{method:'POST',body:{university_number:number,...(ticket?{scan_ticket:ticket}:qr?{qr}:{})}});setChallenge(d.challenge_token);if(d.claim_expires_at)setClaimExpiresAt(d.claim_expires_at);setNotice(bt('text129'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function verify(){setBusy(true);setError('');try{const d=await apiFetch<{student:Student;attendance:Attendance|null;attendance_error:string|null;remembered_days:number|null}>('/public/basic-attendance/verify-otp',{method:'POST',body:{challenge_token:challenge,otp,remember}});attempted.current=true;setStudent(d.student);setResult(d.attendance);setNotice(d.remembered_days?bt('text130'):bt('text131'));if(d.attendance_error)setError(d.attendance_error)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function forget(){setBusy(true);try{await apiFetch('/public/basic-attendance/forget',{method:'POST'});setStudent(null);setNumber('');setTicket('');setClaimExpiresAt('');prepared.current=false;setResult(null);setChallenge('');setOtp('');setNotice('');setError('');attempted.current=false;}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <main className="min-h-dvh bg-slate-50 px-4 py-8" dir={basicLocale() === 'ar' ? 'rtl' : 'ltr'}><section className="mx-auto max-w-md space-y-5 rounded-3xl border border-slate-200 bg-white p-5 sm:p-7"><header><p className="text-xs font-bold text-teal-700">{bt('text132')}</p><h1 className="mt-2 text-xl font-black text-slate-800">{bt('text018')}</h1><p className="mt-2 text-sm leading-7 text-slate-500">{qr?bt('text133'):bt('text134')}</p></header>
    {!ready&&<p className="text-sm text-slate-500">{bt('text135')}</p>}
    {ready&&!student&&<>{qr&&ticket&&claimExpiresAt&&<div role="status" className="rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm leading-6 text-teal-900"><p className="font-bold">{bt('publicScanCaptured',{time:new Date(claimExpiresAt).toLocaleTimeString(basicLocale(),{hour:'2-digit',minute:'2-digit'})})}</p><p className="mt-1 text-xs">{bt('publicScanWaiting')}</p></div>}<form className="space-y-4" onSubmit={e=>{e.preventDefault();void(challenge?verify():requestOtp())}}>{!challenge?<label className="block space-y-2 text-sm font-bold">{bt('text136')}<input aria-label={bt('text136')} required inputMode="numeric" autoComplete="off" className="input text-right" maxLength={20} value={number} onChange={e=>setNumber(e.target.value)}/></label>:<><label className="block space-y-2 text-sm font-bold">{bt('text137')}<input aria-label={bt('text137')} required inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" className="input text-center tracking-[.4em]" value={otp} onChange={e=>setOtp(e.target.value.replace(/[^0-9]/g,''))}/></label><label className="flex items-start gap-3 rounded-xl bg-teal-50 p-3 text-sm leading-7"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="mt-2 h-4 w-4 shrink-0"/><span>{bt('text138')}</span></label></>}<Button className="w-full" type="submit" disabled={busy||preparing||!!qr&&!ticket}>{busy||preparing?bt('text139'):challenge?(qr?bt('text140'):bt('text141')):bt('text142')}</Button>{challenge&&<button type="button" disabled={busy} className="text-xs font-bold text-teal-700" onClick={()=>{setChallenge('');setOtp('');setError('')}}>{bt('text143')}</button>}</form></>}
    {student&&<><div className="rounded-xl bg-teal-50 p-4"><p className="font-bold text-teal-900">{student.name}</p><p className="mt-1 text-right font-mono text-xs text-teal-700" dir="ltr">{student.university_number}</p></div>{busy&&<p className="text-sm">{bt('text144')}</p>}{!qr&&!busy&&<p className="text-sm leading-7 text-slate-600">{bt('text145')}</p>}{result&&<div role="status" className="space-y-2 rounded-xl bg-emerald-50 p-4 text-sm leading-7 text-emerald-800"><p className="font-bold">{result.already_recorded?bt('text146'):result.phase==='check_out'?bt('text147'):bt('text148')}</p><p>{result.course_name} {bt('text024')}{result.section_number}</p><p>{result.title}</p><p>{bt('text149')}{new Date(result.time.includes('T')?result.time:result.time.replace(' ','T')).toLocaleTimeString(basicLocale(),{hour:'2-digit',minute:'2-digit'})}</p></div>}<button disabled={busy} className="text-xs text-slate-500 underline" onClick={()=>void forget()}>{bt('text150')}</button></>}
    {notice&&<p className="text-xs leading-6 text-slate-500">{notice}</p>}{error&&!result&&<div role="alert" className="rounded-xl bg-red-50 p-3 text-sm leading-7 text-red-700">{error}{student&&qr&&<p className="mt-2">{bt('text151')}</p>}</div>}
  </section><p className="mx-auto mt-5 max-w-md text-center text-xs leading-6 text-slate-400">{bt('text152')}</p></main>;
}
