import { useEffect, useState, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDown, ArrowUp, GitBranch, Plus, Save, ShieldCheck, Trash2 } from 'lucide-react';
import { apiFetch, ApiError } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { useI18n } from '@/i18n/I18nContext';
import { Button } from '@/components/ui/Button';

type Role = { code:string; name_key:string };
type Step = { id?:number; step_order?:number; name_ar:string; name_en:string; role_codes:string[] };
type Workflow = { id:number; code:string; name_ar:string; name_en:string; description_ar?:string; description_en?:string; is_active:boolean; prevent_requester_approval:boolean; require_distinct_approvers:boolean; steps:Step[] };
type Payload = { workflows:Workflow[]; roles:Role[] };
const ROLE_NAMES:Record<string,{ar:string;en:string}>={SYS_ADMIN:{ar:'مدير النظام التقني',en:'System Administrator'},DEAN:{ar:'عميد الكلية',en:'Dean'},VICE_DEAN:{ar:'نائب العميد',en:'Vice Dean'},CLINICAL_DIRECTOR:{ar:'مدير الدائرة السريرية',en:'Clinical Director'},ADMIN_ASSISTANT:{ar:'المساعد الإداري',en:'Administrative Assistant'},DEPARTMENT_HEAD:{ar:'رئيس القسم الأكاديمي',en:'Department Head'},RTA:{ar:'مساعد البحث والتدريس',en:'Research and Teaching Assistant'},CLINICAL_SUPERVISOR:{ar:'المشرف السريري',en:'Clinical Supervisor'},ACADEMIC_ADVISOR:{ar:'المرشد الأكاديمي',en:'Academic Advisor'},QUALITY:{ar:'مسؤول الجودة',en:'Quality Officer'}};

export function ApprovalWorkflowsPage() {
  const { locale } = useI18n(); const ar=locale==='ar'; const { can }=useAuth(); const qc=useQueryClient();
  const query=useQuery({queryKey:['approval-workflows'],queryFn:()=>apiFetch<Payload>('/approval-workflows')});
  const [drafts,setDrafts]=useState<Record<string,Workflow>>({}); const [notice,setNotice]=useState<{ok:boolean;text:string}|null>(null);
  useEffect(()=>{if(query.data)setDrafts(Object.fromEntries(query.data.workflows.map(w=>[w.code,structuredClone(w)])));},[query.data]);
  const save=useMutation({mutationFn:(w:Workflow)=>apiFetch<Workflow>(`/approval-workflows/${w.code}`,{method:'PUT',body:{is_active:w.is_active,prevent_requester_approval:w.prevent_requester_approval,require_distinct_approvers:w.require_distinct_approvers,steps:w.steps}}),onSuccess:()=>{setNotice({ok:true,text:ar?'تم حفظ مسار الاعتماد وتطبيقه على الطلبات الجديدة.':'Workflow saved and applied to new requests.'});qc.invalidateQueries({queryKey:['approval-workflows']});},onError:e=>setNotice({ok:false,text:e instanceof ApiError?e.message:(ar?'تعذر حفظ المسار.':'Could not save workflow.')})});
  const update=(code:string,fn:(w:Workflow)=>Workflow)=>setDrafts(d=>({...d,[code]:fn(structuredClone(d[code]))}));
  const move=(code:string,index:number,dir:-1|1)=>update(code,w=>{const target=index+dir;if(target<0||target>=w.steps.length)return w;[w.steps[index],w.steps[target]]=[w.steps[target],w.steps[index]];return w;});
  const roleName=(role:Role)=>ROLE_NAMES[role.code]?.[ar?'ar':'en']??role.code;
  if(query.isLoading)return <p className="p-6 text-sm text-slate-500">{ar?'جارٍ تحميل مسارات الاعتماد...':'Loading approval workflows...'}</p>;
  if(query.isError||!query.data)return <p className="rounded-2xl bg-red-50 p-5 text-red-700">{ar?'تعذر تحميل إعدادات الاعتماد.':'Could not load approval settings.'}</p>;
  return <div className="mx-auto max-w-6xl space-y-5">
    <header className="rounded-3xl bg-gradient-to-l from-teal-800 to-slate-900 p-6 text-white shadow-lg"><div className="flex items-center gap-3"><span className="rounded-2xl bg-white/10 p-3"><GitBranch className="h-6 w-6"/></span><div><h1 className="text-2xl font-black">{ar?'إعداد مسارات الاعتماد':'Approval Workflow Settings'}</h1><p className="mt-1 text-sm text-teal-50">{ar?'حدّد عدد المراحل والجهة المسؤولة عن كل مرحلة دون تعديل برمجي.':'Configure approval stages and responsible roles without code changes.'}</p></div></div></header>
    {notice&&<div className={`rounded-2xl border p-3 text-sm font-bold ${notice.ok?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-red-200 bg-red-50 text-red-700'}`}>{notice.text}</div>}
    <div className="grid gap-4">{query.data.workflows.map(original=>{const w=drafts[original.code]??original;return <section key={w.code} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
      <header className="flex flex-col gap-3 border-b border-slate-100 bg-slate-50/70 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-teal-700"/><h2 className="font-black text-slate-900">{ar?w.name_ar:w.name_en}</h2><span dir="ltr" className="rounded-lg bg-slate-200 px-2 py-1 font-mono text-[10px] text-slate-600">{w.code}</span></div><p className="mt-1 text-xs text-slate-500">{ar?w.description_ar:w.description_en}</p></div>{can('approval_workflows.manage')&&<label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={w.is_active} onChange={e=>update(w.code,x=>({...x,is_active:e.target.checked}))}/>{ar?'المسار مفعّل':'Workflow enabled'}</label>}</header>
      <div className="space-y-4 p-5"><div className="grid gap-3 md:grid-cols-2"><Toggle label={ar?'منع مقدم الطلب من اعتماد طلبه':'Prevent requester self-approval'} checked={w.prevent_requester_approval} disabled={!can('approval_workflows.manage')} onChange={v=>update(w.code,x=>({...x,prevent_requester_approval:v}))}/><Toggle label={ar?'اشتراط أشخاص مختلفين بين المراحل':'Require different approvers across stages'} checked={w.require_distinct_approvers} disabled={!can('approval_workflows.manage')} onChange={v=>update(w.code,x=>({...x,require_distinct_approvers:v}))}/></div>
        <div className="space-y-3">{w.steps.map((step,index)=><div key={index} className="rounded-2xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-black text-teal-800">{ar?`المرحلة ${index+1}`:`Stage ${index+1}`}</span>{can('approval_workflows.manage')&&<div className="flex gap-1"><IconButton title={ar?'تحريك للأعلى':'Move up'} onClick={()=>move(w.code,index,-1)} disabled={index===0}><ArrowUp/></IconButton><IconButton title={ar?'تحريك للأسفل':'Move down'} onClick={()=>move(w.code,index,1)} disabled={index===w.steps.length-1}><ArrowDown/></IconButton><IconButton title={ar?'حذف المرحلة':'Remove stage'} onClick={()=>update(w.code,x=>({...x,steps:x.steps.filter((_,i)=>i!==index)}))} disabled={w.steps.length===1}><Trash2/></IconButton></div>}</div>
          <div className="grid gap-3 md:grid-cols-2"><Field label="اسم المرحلة بالعربية" value={step.name_ar} disabled={!can('approval_workflows.manage')} onChange={v=>update(w.code,x=>{x.steps[index].name_ar=v;return x;})}/><Field label="Stage name in English" value={step.name_en} dir="ltr" disabled={!can('approval_workflows.manage')} onChange={v=>update(w.code,x=>{x.steps[index].name_en=v;return x;})}/></div>
          <p className="mb-2 mt-3 text-xs font-bold text-slate-600">{ar?'الأدوار المخولة في هذه المرحلة':'Roles authorized for this stage'}</p><div className="flex flex-wrap gap-2">{query.data.roles.map(role=>{const active=step.role_codes.includes(role.code);return <button type="button" disabled={!can('approval_workflows.manage')} key={role.code} onClick={()=>update(w.code,x=>{const roles=x.steps[index].role_codes;x.steps[index].role_codes=active?roles.filter(r=>r!==role.code):[...roles,role.code];return x;})} className={`rounded-xl border px-3 py-2 text-xs font-bold transition ${active?'border-teal-600 bg-teal-50 text-teal-800':'border-slate-200 text-slate-500 hover:border-teal-300'} disabled:cursor-default`}>{roleName(role)}</button>})}</div>
        </div>)}</div>
        {can('approval_workflows.manage')&&<div className="flex flex-wrap justify-between gap-2 border-t border-slate-100 pt-4"><Button variant="outline" disabled={w.steps.length>=5} onClick={()=>update(w.code,x=>({...x,steps:[...x.steps,{name_ar:'مرحلة اعتماد جديدة',name_en:'New approval stage',role_codes:[]}]}))}><Plus className="h-4 w-4"/>{ar?'إضافة مرحلة':'Add stage'}</Button><Button isLoading={save.isPending&&save.variables?.code===w.code} disabled={w.steps.some(s=>!s.name_ar.trim()||!s.name_en.trim()||!s.role_codes.length)} onClick={()=>save.mutate(w)}><Save className="h-4 w-4"/>{ar?'حفظ المسار':'Save workflow'}</Button></div>}
      </div></section>})}</div>
  </div>;
}

function Toggle({label,checked,onChange,disabled}:{label:string;checked:boolean;onChange:(v:boolean)=>void;disabled:boolean}){return <label className="flex items-center justify-between rounded-2xl border border-slate-200 p-3 text-xs font-bold text-slate-700"><span>{label}</span><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 accent-teal-700"/></label>}
function Field({label,value,onChange,disabled,dir}:{label:string;value:string;onChange:(v:string)=>void;disabled:boolean;dir?:'ltr'|'rtl'}){return <label className="space-y-1"><span className="text-[11px] font-bold text-slate-500">{label}</span><input dir={dir} value={value} disabled={disabled} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-teal-500 disabled:bg-slate-50"/></label>}
function IconButton({title,onClick,disabled,children}:{title:string;onClick:()=>void;disabled:boolean;children:ReactNode}){return <button type="button" title={title} disabled={disabled} onClick={onClick} className="rounded-lg border border-slate-200 p-1.5 text-slate-500 hover:bg-slate-100 disabled:opacity-30 [&_svg]:h-3.5 [&_svg]:w-3.5">{children}</button>}
