import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import { Download, Eye, FileText, KeyRound, LockKeyhole, ShieldCheck } from 'lucide-react';
import { apiFetch, apiUrl, ApiError } from '@/api/client';
import logo from '@/assets/hebron.png';

type VaultFile={id:number;original_name:string;mime_type:string;file_size:number};
type Vault={title:string;description?:string|null;files:VaultFile[]};
type PublicState={unlocked:boolean;session_minutes?:number;vault?:Vault};

export function ProtectedFinancialDocumentPage(){
  const {token}=useParams();const qc=useQueryClient();const [password,setPassword]=useState('');const [error,setError]=useState('');
  const query=useQuery({queryKey:['protected-financial-document',token],queryFn:()=>apiFetch<PublicState>(`/public/confidential-financial-vaults/${token}`),enabled:Boolean(token),retry:false});
  const unlock=useMutation({mutationFn:()=>apiFetch<PublicState>(`/public/confidential-financial-vaults/${token}/unlock`,{method:'POST',body:{password}}),onSuccess:data=>{setPassword('');setError('');qc.setQueryData(['protected-financial-document',token],data)},onError:value=>setError(value instanceof ApiError&&value.status===429?'تم تجاوز عدد المحاولات المسموح. انتظر دقيقة ثم حاول مجدداً.':value instanceof ApiError?value.message:'تعذر التحقق من كلمة المرور.')});

  if(query.isLoading)return <div dir="rtl" className="flex min-h-screen items-center justify-center bg-slate-50 text-sm font-bold text-slate-600">جارٍ فتح الصفحة الآمنة…</div>;
  if(query.isError)return <div dir="rtl" className="flex min-h-screen items-center justify-center bg-slate-50 p-5"><div className="max-w-md rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm"><LockKeyhole className="mx-auto h-9 w-9 text-slate-400"/><h1 className="mt-4 text-lg font-black">الرابط غير متاح</h1><p className="mt-2 text-sm leading-7 text-slate-500">تم تعطيل الوصول إلى هذا المستند أو أن الرابط غير صحيح.</p></div></div>;
  const state=query.data;

  return <div dir="rtl" lang="ar" className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-4xl items-center gap-4 px-4 py-4"><img src={logo} alt="جامعة الخليل" className="h-14 w-14 object-contain"/><div><p className="text-[10px] font-black text-teal-700">جامعة الخليل · كلية الطب</p><h1 className="mt-1 text-lg font-black text-slate-900">بوابة المستند المالي المحمي</h1></div></div></header>{!state?.unlocked||!state.vault?<LockedForm password={password} setPassword={setPassword} error={error} submit={()=>unlock.mutate()} busy={unlock.isPending}/>:<UnlockedVault vault={state.vault} token={token??''} sessionMinutes={state.session_minutes}/>}</div>;
}

function LockedForm({password,setPassword,error,submit,busy}:{password:string;setPassword:(value:string)=>void;error:string;submit:()=>void;busy:boolean}){return <main className="mx-auto max-w-md px-4 py-12"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-teal-50"><LockKeyhole className="h-7 w-7 text-teal-700"/></span><h2 className="mt-5 text-center text-lg font-black text-slate-900">هذا المستند محمي</h2><p className="mt-2 text-center text-sm leading-7 text-slate-500">أدخل كلمة المرور التي حصلت عليها من الجهة المخولة لعرض الملفات.</p><form onSubmit={(e:FormEvent)=>{e.preventDefault();submit()}} className="mt-6 space-y-3"><label><span className="mb-1.5 block text-xs font-black text-slate-700">كلمة المرور</span><div className="relative"><KeyRound className="absolute start-3 top-3.5 h-4 w-4 text-slate-400"/><input type="password" required autoFocus autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="h-12 w-full rounded-xl border border-slate-200 bg-white ps-10 pe-3 text-sm font-bold outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100"/></div></label>{error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-xs font-bold leading-6 text-rose-700">{error}</p>}<button type="submit" disabled={busy} className="h-11 w-full rounded-xl bg-teal-700 text-sm font-black text-white hover:bg-teal-800 disabled:opacity-60">{busy?'جارٍ التحقق…':'فتح المستند'}</button></form><p className="mt-5 flex items-start gap-2 rounded-xl bg-slate-50 p-3 text-[10px] font-bold leading-5 text-slate-600"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-teal-700"/>رمز QR لا يحتوي على كلمة المرور، ولا يمكن عرض اسم الملف أو محتواه قبل التحقق.</p></section></main>}

function UnlockedVault({vault,token,sessionMinutes}:{vault:Vault;token:string;sessionMinutes?:number}){return <main className="mx-auto max-w-4xl space-y-4 px-4 py-7"><section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-700"/><div><h2 className="text-sm font-black text-emerald-900">تم التحقق من كلمة المرور</h2><p className="mt-1 text-xs leading-6 text-emerald-800">الجلسة مؤقتة لمدة {sessionMinutes??30} دقيقة. لا تترك الجهاز مفتوحاً بعد الانتهاء.</p></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-slate-900">{vault.title}</h2>{vault.description&&<p className="mt-2 text-sm leading-7 text-slate-600">{vault.description}</p>}</section><section><h2 className="mb-3 text-sm font-black text-slate-900">الملفات المحمية ({vault.files.length})</h2><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{vault.files.length===0?<p className="p-8 text-center text-sm font-bold text-slate-500">لا توجد ملفات متاحة حالياً.</p>:<div className="divide-y divide-slate-100">{vault.files.map(file=>{const previewable=file.mime_type==='application/pdf'||file.mime_type.startsWith('image/');const url=apiUrl(`/public/confidential-financial-vaults/${token}/files/${file.id}`);return <div key={file.id} className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center"><div className="flex min-w-0 items-center gap-3"><span className="rounded-xl bg-slate-100 p-2.5"><FileText className="h-5 w-5 text-slate-500"/></span><div className="min-w-0"><p className="truncate text-sm font-black text-slate-800">{file.original_name}</p><p className="mt-1 text-[10px] text-slate-400">{formatBytes(file.file_size)}</p></div></div><div className="flex gap-2">{previewable&&<a href={url} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center rounded-lg border border-slate-200 px-3 text-xs font-bold text-slate-700 hover:bg-slate-50"><Eye className="me-1.5 h-4 w-4"/>عرض</a>}<a href={`${url}?download=1`} className="inline-flex h-9 items-center rounded-lg bg-teal-700 px-3 text-xs font-bold text-white hover:bg-teal-800"><Download className="me-1.5 h-4 w-4"/>تنزيل</a></div></div>})}</div>}</div></section></main>}
function formatBytes(value:number){if(value<1024)return `${value} بايت`;if(value<1024*1024)return `${Math.round(value/1024)} ك.ب`;return `${(value/1024/1024).toFixed(1)} م.ب`}
