import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import { CheckCircle2, ClipboardCheck, LockKeyhole, Send } from 'lucide-react';
import { apiFetch, ApiError } from '@/api/client';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Button } from '@/components/ui/Button';
import { useI18n } from '@/i18n/I18nContext';

type Question = { id:number; question_text:string; question_type:string; options?:string|null; is_required:boolean; axis?:string|null };
type Survey = { public_id:string; title:string; target_group:string; purpose?:string; is_anonymous:boolean; response_policy:string; requires_student_number?:boolean; closes_at?:string; questions:Question[] };
const inputClass = 'mt-3 min-h-12 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-100';

export function PublicQualitySurveyPage(){
 const {locale}=useI18n();const ar=locale==='ar';const tr=(a:string,e:string)=>ar?a:e;
 const {publicId}=useParams();const [answers,setAnswers]=useState<Record<number,string>>({});const [identifier,setIdentifier]=useState('');const [identifierError,setIdentifierError]=useState(false);const [eligible,setEligible]=useState<boolean|null>(null);const [done,setDone]=useState(false);const [missing,setMissing]=useState<number|null>(null);const formRef=useRef<HTMLFormElement>(null);
 const tokenKey=`cdms-survey-device-${publicId}`;let deviceToken=localStorage.getItem(tokenKey);if(!deviceToken){deviceToken=crypto.randomUUID();localStorage.setItem(tokenKey,deviceToken)}
 const query=useQuery({queryKey:['public-quality-survey',publicId],queryFn:()=>apiFetch<Survey>(`/public/quality-surveys/${publicId}`),enabled:Boolean(publicId),retry:false});
 const check=useMutation({mutationFn:()=>apiFetch<{eligible:boolean}>(`/public/quality-surveys/${publicId}/eligibility`,{method:'POST',body:{respondent_identifier:null,respondent_token:deviceToken}}),onSuccess:r=>setEligible(r.eligible)});
 const submit=useMutation({mutationFn:()=>apiFetch(`/public/quality-surveys/${publicId}/submit`,{method:'POST',body:{respondent_identifier:identifier.trim()||null,respondent_token:deviceToken,answers:Object.entries(answers).map(([question_id,value])=>({question_id:Number(question_id),value}))}}),onSuccess:()=>setDone(true)});
 useEffect(()=>{if(!query.data)return;if(query.data.response_policy!=='one_per_device')setEligible(true);else if(eligible===null&&!check.isPending)check.mutate()},[query.data?.response_policy]);
 const grouped=useMemo(()=>{const map=new Map<string,Question[]>();for(const q of query.data?.questions||[]){const key=q.axis?.trim()||tr('الأسئلة','Questions');map.set(key,[...(map.get(key)||[]),q])}return [...map.entries()]},[query.data,locale]);
 if(query.isLoading||check.isPending)return <LoadingState/>;
 if(query.isError||!query.data)return <Centered><ErrorState title={tr('الاستبيان غير متاح','Survey unavailable')} message={(query.error as ApiError)?.message||tr('تعذر فتح الاستبيان.','The survey could not be opened.')}/></Centered>;
 const survey=query.data;
 if(done)return <Status title={tr('تم استلام إجابتك','Your response was received')} text={tr('شكرًا لمساهمتك في تحسين جودة التعليم والتدريب.','Thank you for helping improve the quality of education and training.')}/>;
 if(eligible===false)return <Status title={tr('تم الرد مسبقًا','Already submitted')} text={tr('هذا الاستبيان مقيد برد واحد، وقد تم تسجيل ردك سابقًا.','This survey allows one response, and yours has already been recorded.')}/>;
 if(survey.response_policy==='one_per_device'&&check.isError)return <Centered><ErrorState title={tr('تعذر التحقق من الرد السابق','Unable to verify previous response')} onRetry={()=>check.mutate()}/></Centered>;
 if(eligible!==true)return <LoadingState/>;
 const needsIdentifier=survey.requires_student_number||survey.response_policy==='one_per_identifier'||!survey.is_anonymous;
 const answered=survey.questions.filter(q=>Boolean(answers[q.id]?.trim())).length;
 const progress=survey.questions.length?Math.round(answered/survey.questions.length*100):0;
 const submitForm=(event:FormEvent)=>{event.preventDefault();if(needsIdentifier&&!identifier.trim()){setIdentifierError(true);formRef.current?.querySelector<HTMLInputElement>('#survey-identifier')?.focus();return}const first=survey.questions.find(q=>q.is_required&&!answers[q.id]?.trim());if(first){setMissing(first.id);document.getElementById(`survey-question-${first.id}`)?.scrollIntoView?.({behavior:'smooth',block:'center'});return}setMissing(null);submit.mutate()};
 return <main dir={ar?'rtl':'ltr'} className="min-h-screen bg-[#f3f7f6] px-3 pb-24 pt-4 text-slate-900 sm:px-5 sm:py-8">
  <form ref={formRef} noValidate onSubmit={submitForm} className="mx-auto w-full max-w-2xl space-y-3.5 sm:space-y-4">
   <header className="overflow-hidden rounded-[1.4rem] border border-slate-200 bg-white shadow-sm"><div className="h-1.5 bg-teal-700"/><div className="p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-2 text-xs font-black text-teal-800"><span className="inline-flex items-center gap-2"><ClipboardCheck className="h-4 w-4"/>{tr('استبيان الكلية','College survey')}</span><span className="rounded-full bg-teal-50 px-2.5 py-1 text-[11px]">{survey.target_group}</span></div><h1 className="mt-3 break-words text-xl font-black leading-8 sm:text-2xl">{survey.title}</h1>{survey.purpose&&<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{survey.purpose}</p>}{survey.closes_at&&<p className="mt-3 text-xs font-semibold text-slate-500">{tr('آخر موعد: ','Closes: ')}{new Date(survey.closes_at).toLocaleDateString(ar?'ar-PS':'en-GB')}</p>}</div></header>
   <section aria-label={tr('تقدم الإجابة','Response progress')} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><div className="flex items-center justify-between text-xs"><b>{tr('تقدم الإجابة','Your progress')}</b><span className="font-black text-teal-800">{answered} / {survey.questions.length}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600 transition-[width]" style={{width:`${progress}%`}}/></div></section>
   {needsIdentifier&&<section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><label htmlFor="survey-identifier" className="block text-sm font-black">{survey.requires_student_number?tr('الرقم الجامعي','University number'):tr('الرقم أو المعرّف','Number or identifier')} <span aria-hidden="true" className="text-red-600">*</span></label><input id="survey-identifier" required aria-invalid={identifierError} inputMode={survey.requires_student_number?'numeric':'text'} autoComplete="off" value={identifier} onChange={e=>{setIdentifier(e.target.value);setIdentifierError(false)}} className={`${inputClass} ${identifierError?'border-red-400':''}`} placeholder={survey.requires_student_number?tr('اكتب رقمك الجامعي','Enter your university number'):tr('اكتب الرقم أو المعرّف','Enter number or identifier')} dir="ltr"/>{identifierError&&<p role="alert" className="mt-2 text-xs font-bold text-red-700">{tr('هذا الحقل مطلوب.','This field is required.')}</p>}<p className="mt-2 flex items-start gap-2 text-[11px] leading-5 text-slate-500"><LockKeyhole className="mt-0.5 h-3.5 w-3.5 shrink-0"/>{survey.requires_student_number?tr('يُستخدم الرقم لتسجيل المشاركة ومنع التكرار؛ لا نرسل رمزًا بالبريد ولا نتحقق من هوية مُدخل الرقم.','The number records participation and prevents duplicates. No email code or identity verification is used.'):survey.is_anonymous?tr('يُستخدم المعرّف لمنع تكرار الرد، ولا يظهر بجانب إجاباتك.','The identifier prevents duplicate submissions and is not shown with your answers.'):tr('سيظهر هذا المعرّف مع إجابتك.','This identifier will be shown with your response.')}</p></section>}
   {grouped.map(([axis,questions])=><section key={axis} aria-label={axis} className="space-y-3"><h2 className="px-1 pt-2 text-sm font-black text-teal-900">{axis}</h2>{questions.map(q=>{const index=survey.questions.findIndex(item=>item.id===q.id)+1;return <fieldset id={`survey-question-${q.id}`} key={q.id} className={`rounded-2xl border bg-white p-4 shadow-sm transition-colors sm:p-5 ${missing===q.id?'border-red-400 ring-2 ring-red-100':'border-slate-200'}`}><legend className="sr-only">{q.question_text}</legend><div className="mb-3 flex items-start gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-teal-50 text-xs font-black text-teal-800">{index}</span><div className="min-w-0"><p className="text-sm font-bold leading-6">{q.question_text}{q.is_required&&<span className="ms-1 text-red-600" aria-label={tr('مطلوب','Required')}>*</span>}</p>{!q.is_required&&<p className="text-[11px] text-slate-400">{tr('اختياري','Optional')}</p>}</div></div><Answer q={q} value={answers[q.id]||''} ar={ar} set={value=>{setAnswers(current=>({...current,[q.id]:value}));if(missing===q.id)setMissing(null)}}/>{missing===q.id&&<p role="alert" className="mt-2 text-xs font-bold text-red-700">{tr('هذا السؤال مطلوب.','This question is required.')}</p>}</fieldset>})}</section>)}
   {submit.isError&&<p role="alert" className="rounded-xl border border-red-100 bg-red-50 p-3 text-sm font-bold text-red-700">{(submit.error as ApiError).message}</p>}
   <div className="fixed inset-x-0 bottom-0 z-20 border-t border-slate-200 bg-white/95 px-3 py-3 shadow-[0_-8px_30px_rgba(15,23,42,0.08)] backdrop-blur sm:static sm:rounded-2xl sm:border sm:p-4 sm:shadow-sm"><div className="mx-auto flex max-w-2xl items-center gap-3"><div className="hidden min-w-0 flex-1 text-xs text-slate-500 sm:block">{tr('راجع إجاباتك قبل الإرسال.','Review your answers before submitting.')}</div><Button type="submit" className="h-12 w-full text-sm sm:w-auto sm:min-w-44" isLoading={submit.isPending}><Send className="me-2 h-4 w-4"/>{tr('إرسال الإجابات','Submit responses')}</Button></div></div>
  </form>
 </main>;
}

function Answer({q,value,set,ar}:{q:Question;value:string;set:(v:string)=>void;ar:boolean}){
 const choices=(q.options||'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean);
 if(q.question_type==='rating')return <div className="grid grid-cols-5 gap-2" role="radiogroup" aria-label={q.question_text}>{[1,2,3,4,5].map(n=><label key={n} className={`grid min-h-12 cursor-pointer place-items-center rounded-xl border text-sm font-black transition ${value===String(n)?'border-teal-700 bg-teal-700 text-white':'border-slate-200 bg-slate-50 text-slate-700 hover:border-teal-300'}`}><input required={q.is_required} className="sr-only" type="radio" name={`q-${q.id}`} value={n} checked={value===String(n)} onChange={e=>set(e.target.value)}/>{n}</label>)}</div>;
 if(q.question_type==='multiple_choice'){const selected=value?value.split('\n'):[];return <div className="grid gap-2">{choices.map(c=><label key={c} className={`flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border px-3 py-2.5 text-sm leading-5 ${selected.includes(c)?'border-teal-500 bg-teal-50 font-bold text-teal-900':'border-slate-200 hover:border-teal-300'}`}><input type="checkbox" className="h-4 w-4 shrink-0 accent-teal-700" checked={selected.includes(c)} onChange={e=>set(e.target.checked?[...selected,c].join('\n'):selected.filter(x=>x!==c).join('\n'))}/>{c}</label>)}</div>}
 if(q.question_type==='single_choice')return <div className="grid gap-2">{choices.map(c=><label key={c} className={`flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border px-3 py-2.5 text-sm leading-5 ${value===c?'border-teal-500 bg-teal-50 font-bold text-teal-900':'border-slate-200 hover:border-teal-300'}`}><input required={q.is_required} type="radio" className="h-4 w-4 shrink-0 accent-teal-700" name={`q-${q.id}`} value={c} checked={value===c} onChange={e=>set(e.target.value)}/>{c}</label>)}</div>;
 if(q.question_type==='number')return <input aria-label={q.question_text} required={q.is_required} type="number" inputMode="decimal" value={value} onChange={e=>set(e.target.value)} className={inputClass}/>;
 if(q.question_type==='short_text')return <input aria-label={q.question_text} required={q.is_required} type="text" value={value} onChange={e=>set(e.target.value)} className={inputClass} placeholder={ar?'اكتب إجابتك':'Your answer'}/>;
 return <textarea aria-label={q.question_text} required={q.is_required} rows={4} value={value} onChange={e=>set(e.target.value)} className={inputClass} placeholder={ar?'اكتب إجابتك':'Your answer'}/>;
}
function Centered({children}:{children:React.ReactNode}){return <div className="mx-auto mt-20 max-w-xl px-4">{children}</div>}
function Status({title,text}:{title:string;text:string}){return <main className="grid min-h-screen place-items-center bg-[#f3f7f6] px-4"><section className="w-full max-w-xl rounded-3xl border border-emerald-100 bg-white p-8 text-center shadow-sm sm:p-10"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-600"/><h1 className="mt-5 text-2xl font-black">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></section></main>}
