import { useMemo, useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import { CheckCircle2, ClipboardCheck } from 'lucide-react';
import { apiFetch, ApiError } from '@/api/client';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Button } from '@/components/ui/Button';

type Question={id:number;question_number:number;question_text:string;question_type:string;options?:string|null;is_required:boolean;axis?:string|null};
type Survey={public_id:string;title:string;target_group:string;purpose?:string;is_anonymous:boolean;response_policy:string;closes_at?:string;questions:Question[]};

export function PublicQualitySurveyPage(){
 const{publicId}=useParams();const[answers,setAnswers]=useState<Record<number,string>>({});const[identifier,setIdentifier]=useState('');const[done,setDone]=useState(false);
 const query=useQuery({queryKey:['public-quality-survey',publicId],queryFn:()=>apiFetch<Survey>(`/public/quality-surveys/${publicId}`),enabled:Boolean(publicId),retry:false});
 const tokenKey=`cdms-survey-device-${publicId}`;let deviceToken=localStorage.getItem(tokenKey);if(!deviceToken){deviceToken=crypto.randomUUID();localStorage.setItem(tokenKey,deviceToken)}
 const submit=useMutation({mutationFn:()=>apiFetch(`/public/quality-surveys/${publicId}/submit`,{method:'POST',body:{respondent_identifier:identifier||null,respondent_token:deviceToken,answers:Object.entries(answers).map(([question_id,value])=>({question_id:Number(question_id),value}))}}),onSuccess:()=>setDone(true)});
 const grouped=useMemo(()=>{const map=new Map<string,Question[]>();for(const q of query.data?.questions||[]){const key=q.axis||'الأسئلة';map.set(key,[...(map.get(key)||[]),q]);}return [...map.entries()];},[query.data]);
 if(query.isLoading)return <LoadingState/>;if(query.isError||!query.data)return <div className="mx-auto mt-20 max-w-xl px-4"><ErrorState title="الاستبيان غير متاح" message={(query.error as ApiError)?.message||'تعذر فتح الاستبيان.'}/></div>;
 if(done)return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-16"><section className="mx-auto max-w-xl rounded-3xl border border-emerald-100 bg-white p-10 text-center shadow-sm"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-600"/><h1 className="mt-5 text-2xl font-black">تم استلام إجابتك</h1><p className="mt-2 text-sm text-slate-500">شكرًا لمساهمتك في تحسين جودة التعليم والتدريب.</p></section></main>;
 const survey=query.data;return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900"><form onSubmit={(e:FormEvent)=>{e.preventDefault();submit.mutate();}} className="mx-auto max-w-3xl space-y-5"><header className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="h-2 bg-teal-600"/><div className="p-6 sm:p-8"><div className="flex items-center gap-3 text-teal-700"><ClipboardCheck className="h-6 w-6"/><span className="text-xs font-black">استبيان جودة</span></div><h1 className="mt-4 text-2xl font-black sm:text-3xl">{survey.title}</h1>{survey.purpose&&<p className="mt-3 leading-7 text-slate-600">{survey.purpose}</p>}<div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-500"><span className="rounded-lg bg-slate-100 px-3 py-2">الفئة: {survey.target_group}</span>{survey.closes_at&&<span className="rounded-lg bg-slate-100 px-3 py-2">آخر موعد: {survey.closes_at}</span>}</div></div></header>
 {(!survey.is_anonymous||survey.response_policy==='one_per_identifier')&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><label className="text-sm font-black">الاسم أو الرقم التعريفي</label><input required value={identifier} onChange={e=>setIdentifier(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-teal-500"/>{survey.is_anonymous&&<p className="mt-2 text-xs text-slate-400">يُستخدم المعرّف لمنع تكرار الرد فقط، ويُحفظ مشفرًا ولا يظهر مع الإجابات.</p>}</section>}
 {grouped.map(([axis,questions])=><section key={axis} className="space-y-3"><h2 className="px-1 text-sm font-black text-teal-800">{axis}</h2>{questions.map((q,index)=><article key={q.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="block text-sm font-bold"><span className="ml-2 text-teal-700">{index+1}.</span>{q.question_text}{q.is_required&&<span className="mr-1 text-red-500">*</span>}</label><Answer q={q} value={answers[q.id]||''} set={value=>setAnswers({...answers,[q.id]:value})}/></article>)}</section>)}
 {submit.isError&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{(submit.error as ApiError)?.message||'تعذر إرسال الإجابة.'}</p>}<Button type="submit" isLoading={submit.isPending} className="h-12 w-full text-base">إرسال الإجابات</Button></form></main>;
}

function Answer({q,value,set}:{q:Question;value:string;set:(v:string)=>void}){const choices=(q.options||'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean);if(q.question_type==='rating')return <div className="mt-4 flex flex-wrap gap-2">{[1,2,3,4,5].map(n=><label key={n} className={`flex h-11 w-11 cursor-pointer items-center justify-center rounded-xl border font-black ${value===String(n)?'border-teal-600 bg-teal-600 text-white':'border-slate-200'}`}><input required={q.is_required} className="sr-only" type="radio" name={`q-${q.id}`} value={n} checked={value===String(n)} onChange={e=>set(e.target.value)}/>{n}</label>)}</div>;if(q.question_type==='multiple_choice'){const selected=value?value.split('\n'):[];return <div className="mt-3 grid gap-2">{choices.map(choice=><label key={choice} className="flex cursor-pointer gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox" checked={selected.includes(choice)} onChange={e=>set(e.target.checked?[...selected,choice].join('\n'):selected.filter(x=>x!==choice).join('\n'))}/>{choice}</label>)}</div>}if(q.question_type==='single_choice')return <div className="mt-3 grid gap-2">{choices.map(choice=><label key={choice} className="flex cursor-pointer gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input required={q.is_required} type="radio" name={`q-${q.id}`} value={choice} checked={value===choice} onChange={e=>set(e.target.value)}/>{choice}</label>)}</div>;if(q.question_type==='number')return <input required={q.is_required} type="number" value={value} onChange={e=>set(e.target.value)} className="mt-3 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-teal-500"/>;return <textarea required={q.is_required} rows={q.question_type==='long_text'?5:2} value={value} onChange={e=>set(e.target.value)} className="mt-3 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-teal-500"/>}
