import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import { CheckCircle2, ClipboardCheck, ShieldCheck } from 'lucide-react';
import { apiFetch, ApiError } from '@/api/client';
import { LoadingState } from '@/components/ui/LoadingState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Button } from '@/components/ui/Button';
import { useI18n } from '@/i18n/I18nContext';

type Question={id:number;question_text:string;question_type:string;options?:string|null;is_required:boolean;axis?:string|null};
type Survey={public_id:string;title:string;target_group:string;purpose?:string;is_anonymous:boolean;response_policy:string;closes_at?:string;questions:Question[]};

export function PublicQualitySurveyPage(){
 const{locale}=useI18n();const ar=locale==='ar';const tr=(arabic:string,english:string)=>ar?arabic:english;
 const{publicId}=useParams();const[answers,setAnswers]=useState<Record<number,string>>({});const[identifier,setIdentifier]=useState('');const[eligible,setEligible]=useState<boolean|null>(null);const[done,setDone]=useState(false);
 const tokenKey=`cdms-survey-device-${publicId}`;let deviceToken=localStorage.getItem(tokenKey);if(!deviceToken){deviceToken=crypto.randomUUID();localStorage.setItem(tokenKey,deviceToken)}
 const query=useQuery({queryKey:['public-quality-survey',publicId],queryFn:()=>apiFetch<Survey>(`/public/quality-surveys/${publicId}`),enabled:Boolean(publicId),retry:false});
 const check=useMutation({mutationFn:(idValue?:string)=>apiFetch<{eligible:boolean;message?:string}>(`/public/quality-surveys/${publicId}/eligibility`,{method:'POST',body:{respondent_identifier:idValue||null,respondent_token:deviceToken}}),onSuccess:r=>setEligible(r.eligible)});
 const submit=useMutation({mutationFn:()=>apiFetch(`/public/quality-surveys/${publicId}/submit`,{method:'POST',body:{respondent_identifier:identifier||null,respondent_token:deviceToken,answers:Object.entries(answers).map(([question_id,value])=>({question_id:Number(question_id),value}))}}),onSuccess:()=>setDone(true)});
 useEffect(()=>{if(!query.data)return;if(query.data.response_policy==='multiple')setEligible(true);else if(query.data.response_policy==='one_per_device'&&!check.isPending&&eligible===null)check.mutate(undefined)},[query.data?.response_policy]);
 const grouped=useMemo(()=>{const map=new Map<string,Question[]>();for(const q of query.data?.questions||[]){const key=q.axis||tr('الأسئلة','Questions');map.set(key,[...(map.get(key)||[]),q])}return [...map.entries()]},[query.data,locale]);
 if(query.isLoading||check.isPending)return <LoadingState/>;if(query.isError||!query.data)return <Centered><ErrorState title={tr('الاستبيان غير متاح','Survey unavailable')} message={(query.error as ApiError)?.message||tr('تعذر فتح الاستبيان.','The survey could not be opened.')}/></Centered>;
 const survey=query.data;if(done)return <Status title={tr('تم استلام إجابتك','Your response was received')} text={tr('شكرًا لمساهمتك في تحسين جودة التعليم والتدريب.','Thank you for helping improve the quality of education and training.')}/>;if(eligible===false)return <Status title={tr('تم الرد مسبقًا','Already submitted')} text={tr('هذا الاستبيان مقيد برد واحد، وقد تم تسجيل ردك سابقًا.','This survey allows one response, and yours has already been recorded.')}/>;
 if(survey.response_policy==='one_per_identifier'&&eligible!==true)return <main className="min-h-screen bg-slate-50 px-4 py-16"><form onSubmit={(e:FormEvent)=>{e.preventDefault();check.mutate(identifier)}} className="mx-auto max-w-lg rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><ShieldCheck className="h-10 w-10 text-teal-600"/><h1 className="mt-4 text-xl font-black">{tr('التحقق قبل فتح الاستبيان','Verify before opening the survey')}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{tr('أدخل رقمك أو معرّفك للتحقق من عدم إرسال رد سابق. لن تظهر الأسئلة قبل نجاح التحقق.','Enter your number or identifier to verify that no previous response was submitted. Questions appear after verification.')}</p><input autoFocus required value={identifier} onChange={e=>setIdentifier(e.target.value)} className="mt-5 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-teal-500" placeholder={tr('الرقم أو المعرّف','Number or identifier')}/>{survey.is_anonymous&&<p className="mt-2 text-xs text-slate-400">{tr('يُحفظ المعرّف كبصمة مشفرة لمنع التكرار، ولا يظهر مع إجاباتك.','The identifier is stored as an encrypted fingerprint to prevent duplicates and is not shown with your answers.')}</p>}{check.isError&&<p className="mt-3 text-sm font-bold text-red-600">{(check.error as ApiError).message}</p>}<Button type="submit" className="mt-5 w-full" isLoading={check.isPending}>{tr('متابعة إلى الاستبيان','Continue to survey')}</Button></form></main>;
 if(eligible!==true)return <LoadingState/>;
 return <main className="min-h-screen bg-slate-50 px-4 py-8"><form onSubmit={(e:FormEvent)=>{e.preventDefault();submit.mutate()}} className="mx-auto max-w-3xl space-y-5"><header className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="h-2 bg-teal-600"/><div className="p-7"><div className="flex items-center gap-2 text-teal-700"><ClipboardCheck className="h-6 w-6"/><b>{tr('استبيان جودة','Quality Survey')}</b></div><h1 className="mt-4 text-2xl font-black">{survey.title}</h1>{survey.purpose&&<p className="mt-3 leading-7 text-slate-600">{survey.purpose}</p>}</div></header>{!survey.is_anonymous&&survey.response_policy!=='one_per_identifier'&&<input required value={identifier} onChange={e=>setIdentifier(e.target.value)} className="w-full rounded-xl border bg-white p-4" placeholder={tr('الاسم أو الرقم التعريفي','Name or identifier')}/>} {grouped.map(([axis,questions])=><section key={axis} className="space-y-3"><h2 className="text-sm font-black text-teal-800">{axis}</h2>{questions.map((q,i)=><article key={q.id} className="rounded-2xl border bg-white p-5 shadow-sm"><label className="text-sm font-bold"><span className="me-2 text-teal-700">{i+1}.</span>{q.question_text}{q.is_required&&<span className="text-red-500"> *</span>}</label><Answer q={q} value={answers[q.id]||''} set={v=>setAnswers({...answers,[q.id]:v})}/></article>)}</section>)}{submit.isError&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{(submit.error as ApiError).message}</p>}<Button type="submit" className="h-12 w-full" isLoading={submit.isPending}>{tr('إرسال الإجابات','Submit responses')}</Button></form></main>;
}
function Centered({children}:{children:React.ReactNode}){return <div className="mx-auto mt-20 max-w-xl px-4">{children}</div>}
function Status({title,text}:{title:string;text:string}){return <main className="min-h-screen bg-slate-50 px-4 py-16"><section className="mx-auto max-w-xl rounded-3xl border border-emerald-100 bg-white p-10 text-center shadow-sm"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-600"/><h1 className="mt-5 text-2xl font-black">{title}</h1><p className="mt-2 text-sm text-slate-500">{text}</p></section></main>}
function Answer({q,value,set}:{q:Question;value:string;set:(v:string)=>void}){const choices=(q.options||'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean);if(q.question_type==='rating')return <div className="mt-4 flex gap-2">{[1,2,3,4,5].map(n=><label key={n} className={`flex h-11 w-11 cursor-pointer items-center justify-center rounded-xl border font-black ${value===String(n)?'bg-teal-600 text-white':''}`}><input required={q.is_required} className="sr-only" type="radio" name={`q-${q.id}`} value={n} checked={value===String(n)} onChange={e=>set(e.target.value)}/>{n}</label>)}</div>;if(q.question_type==='multiple_choice'){const selected=value?value.split('\n'):[];return <div className="mt-3 grid gap-2">{choices.map(c=><label key={c} className="flex gap-3 rounded-xl border p-3"><input type="checkbox" checked={selected.includes(c)} onChange={e=>set(e.target.checked?[...selected,c].join('\n'):selected.filter(x=>x!==c).join('\n'))}/>{c}</label>)}</div>}if(q.question_type==='single_choice')return <div className="mt-3 grid gap-2">{choices.map(c=><label key={c} className="flex gap-3 rounded-xl border p-3"><input required={q.is_required} type="radio" name={`q-${q.id}`} value={c} checked={value===c} onChange={e=>set(e.target.value)}/>{c}</label>)}</div>;if(q.question_type==='number')return <input required={q.is_required} type="number" value={value} onChange={e=>set(e.target.value)} className="mt-3 w-full rounded-xl border p-3"/>;return <textarea required={q.is_required} rows={q.question_type==='long_text'?5:2} value={value} onChange={e=>set(e.target.value)} className="mt-3 w-full rounded-xl border p-3"/>}
