import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { BookOpenCheck, CheckCircle2, FileSignature, KeyRound, Loader2, Mail, ShieldCheck } from 'lucide-react';
import { apiFetch, apiUrl } from '@/api/client';
import hebronLogo from '@/assets/hebron.png';

type Meta = { public_id:string; status:string; deadline:string; academic_year?:string; title_ar:string; title_en:string; version_label:string };

export function PublicStudentPolicyPage() {
  const { publicId = '' } = useParams(); const [meta,setMeta]=useState<Meta|null>(null); const [stage,setStage]=useState<'identity'|'otp'|'document'|'done'>('identity');
  const [number,setNumber]=useState(''); const [challenge,setChallenge]=useState(''); const [otp,setOtp]=useState(''); const [token,setToken]=useState(''); const [studentName,setStudentName]=useState(''); const [typedName,setTypedName]=useState(''); const [opened,setOpened]=useState(false); const [understood,setUnderstood]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  useEffect(()=>{apiFetch<Meta>(`/public/student-policies/${publicId}`).then(setMeta).catch((e:Error)=>setMessage(e.message));},[publicId]);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'تعذر إتمام الطلب.');}finally{setBusy(false)}};
  const requestOtp=()=>run(async()=>{const d=await apiFetch<{challenge_token:string}>(`/public/student-policies/${publicId}/request-otp`,{method:'POST',body:{university_number:number}});setChallenge(d.challenge_token);setStage('otp');setMessage('إذا كانت بياناتك مشمولة فسيصل الرمز إلى بريدك الجامعي.');});
  const verify=()=>run(async()=>{const d=await apiFetch<any>(`/public/student-policies/${publicId}/verify-otp`,{method:'POST',body:{challenge_token:challenge,otp}});setToken(d.access_token);setStudentName(d.student.name);setTypedName(d.student.name);if(d.acknowledged)setStage('done');else{setOpened(d.opened);setStage('document')}});
  const openDocument=()=>{const tab=window.open('','_blank');void run(async()=>{await apiFetch(`/public/student-policies/${publicId}/document-opened`,{method:'POST',body:{access_token:token}});const response=await fetch(apiUrl(`/public/student-policies/${publicId}/document`),{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('تعذر فتح الوثيقة الرسمية.');const url=URL.createObjectURL(await response.blob());if(tab)tab.location.href=url;else window.open(url,'_blank');setOpened(true);setTimeout(()=>URL.revokeObjectURL(url),60000);});};
  const acknowledge=()=>run(async()=>{await apiFetch(`/public/student-policies/${publicId}/acknowledge`,{method:'POST',body:{access_token:token,typed_name:typedName,paper_signature_understood:understood}});setStage('done');});
  if(!meta)return <div className="flex min-h-screen items-center justify-center bg-slate-50">{message||<Loader2 className="h-7 w-7 animate-spin text-teal-700"/>}</div>;
  return <main dir="rtl" className="min-h-screen bg-gradient-to-b from-teal-50/70 to-slate-50 px-4 py-6 sm:py-10"><div className="mx-auto max-w-xl">
    <header className="mb-5 flex items-center gap-3"><img src={hebronLogo} className="h-12 w-12 object-contain" alt="جامعة الخليل"/><div><p className="text-sm font-black text-teal-800">كلية الطب</p><p className="text-xs text-slate-500">بوابة السياسات والتعهدات الطلابية</p></div></header>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="h-1.5 bg-teal-700"/><div className="p-5 sm:p-8"><div className="mb-6 flex gap-3"><div className="rounded-2xl bg-teal-50 p-3"><BookOpenCheck className="h-6 w-6 text-teal-700"/></div><div><h1 className="text-xl font-black text-slate-900">{meta.title_ar}</h1><p className="mt-1 text-sm text-slate-500">{meta.title_en}</p><p className="mt-1 text-xs font-bold text-teal-700">الإصدار {meta.version_label} · آخر موعد {meta.deadline}</p></div></div>
      <div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-7 text-amber-950"><FileSignature className="ml-2 inline h-5 w-5"/><b>تنبيه مهم:</b> إقرار القراءة الإلكتروني لا يغني عن التوقيع الورقي. بعد القراءة يجب طباعة الوثيقة وتوقيعها وتسليمها للكلية.</div>
      {meta.status!=='published'?<div className="rounded-2xl bg-slate-100 p-6 text-center font-bold text-slate-700">هذه الحملة غير متاحة لاستقبال الإقرارات حالياً.</div>:
      stage==='identity'?<form onSubmit={e=>{e.preventDefault();requestOtp()}} className="space-y-4"><div><label className="mb-1.5 block text-sm font-bold">الرقم الجامعي</label><input inputMode="numeric" pattern="[0-9]+" required value={number} onChange={e=>setNumber(e.target.value)} className="w-full rounded-xl border border-slate-300 px-4 py-3 text-base" placeholder="أدخل رقمك الجامعي"/></div><button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-teal-700 py-3 font-bold text-white"><Mail className="h-5 w-5"/>{busy?'جارٍ الإرسال...':'إرسال رمز التحقق'}</button></form>:
      stage==='otp'?<form onSubmit={e=>{e.preventDefault();verify()}} className="space-y-4"><p className="text-sm text-slate-600">أدخل رمز التحقق المرسل إلى بريدك الجامعي.</p><input autoFocus inputMode="numeric" maxLength={6} required value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} className="w-full rounded-xl border px-4 py-3 text-center text-2xl font-black tracking-[.4em]"/><button disabled={busy||otp.length!==6} className="flex w-full items-center justify-center gap-2 rounded-xl bg-teal-700 py-3 font-bold text-white"><KeyRound className="h-5 w-5"/>تحقق ومتابعة</button><button type="button" onClick={()=>setStage('identity')} className="w-full text-sm font-bold text-slate-500">تعديل الرقم الجامعي</button></form>:
      stage==='document'?<div className="space-y-4"><div className="rounded-xl bg-slate-50 p-3 text-sm">الطالب: <b>{studentName}</b></div><button type="button" onClick={openDocument} disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl border-2 border-teal-700 py-3 font-bold text-teal-800"><BookOpenCheck className="h-5 w-5"/>فتح النسخة الرسمية وقراءتها</button><label className={`flex gap-3 rounded-xl border p-4 text-sm leading-6 ${opened?'cursor-pointer':'opacity-50'}`}><input type="checkbox" disabled={!opened} checked={understood} onChange={e=>setUnderstood(e.target.checked)} className="mt-1 h-4 w-4"/><span>أقر بأنني فتحت وقرأت النسخة الرسمية، وأفهم أن هذا الإقرار لا يستبدل توقيعي الورقي وتسليم النسخة للكلية.</span></label><div><label className="mb-1 block text-sm font-bold">اكتب اسمك كما يظهر في سجل الطالب</label><input disabled={!opened} value={typedName} onChange={e=>setTypedName(e.target.value)} className="w-full rounded-xl border px-4 py-3"/></div><button onClick={acknowledge} disabled={busy||!opened||!understood||!typedName.trim()} className="w-full rounded-xl bg-teal-700 py-3 font-bold text-white disabled:bg-slate-300">تسجيل إقرار القراءة</button></div>:
      <div className="text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-600"/><h2 className="mt-3 text-xl font-black">تم تسجيل إقرار القراءة</h2><p className="mt-2 text-sm leading-7 text-slate-600">الخطوة المتبقية: اطبع الوثيقة، وقّعها بخط اليد، ثم سلّم النسخة إلى الكلية ليتم توثيق استلامها في ملفك.</p><div className="mt-5 rounded-xl bg-teal-50 p-4 text-sm font-bold text-teal-900"><ShieldCheck className="ml-2 inline h-5 w-5"/>تم ربط الإقرار بهذه النسخة والإصدار بشكل آمن.</div></div>}
      {message&&<p className="mt-4 rounded-xl bg-slate-100 p-3 text-sm text-slate-700">{message}</p>}
    </div></section><p className="mt-5 text-center text-xs text-slate-400">الدائرة السريرية · كلية الطب · جامعة الخليل</p>
  </div></main>;
}
