import { useCallback, useState } from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle2, ShieldCheck } from 'lucide-react';
import { apiFetch } from '@/api/client';
import { clinicalAttendanceIdentity, scanClinicalQr } from '@/api/clinicalQrAttendance';
import { LiveQrScanner } from '@/components/clinical/LiveQrScanner';

export function PublicClinicalAttendancePage(){
 const [number,setNumber]=useState('');const [challenge,setChallenge]=useState('');const [otp,setOtp]=useState('');const [token,setToken]=useState('');const [student,setStudent]=useState<{name:string;university_number:string}|null>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const request=async()=>{setLoading(true);setError('');try{const res=await apiFetch<{otp_required:boolean;challenge_token?:string;access_token?:string}>('/public/clinical-attendance/request-otp',{method:'POST',body:{university_number:number}});if(res.access_token){setToken(res.access_token);const identity=await clinicalAttendanceIdentity(res.access_token);setStudent(identity.student);}else setChallenge(res.challenge_token??'');setMessage('تم إرسال رمز التحقق إلى بريدك الجامعي.');}catch(e){setError(e instanceof Error?e.message:'تعذر إرسال الرمز.');}finally{setLoading(false)}};
 const verify=async()=>{setLoading(true);setError('');try{const res=await apiFetch<{access_token:string}>('/public/clinical-attendance/verify-otp',{method:'POST',body:{challenge_token:challenge,otp}});setToken(res.access_token);const identity=await clinicalAttendanceIdentity(res.access_token);setStudent(identity.student);setMessage('تم التحقق بنجاح. يمكنك فتح الكاميرا الآن.');}catch(e){setError(e instanceof Error?e.message:'رمز التحقق غير صحيح.');}finally{setLoading(false)}};
 const decoded=useCallback(async(qr:string)=>{setError('');try{const result=await scanClinicalQr(qr,token||undefined);setMessage(`تم تسجيل ${result.operation==='check_in'?'الدخول':'الخروج'} بنجاح الساعة ${new Date(result.recorded_at).toLocaleTimeString('ar-PS',{hour:'2-digit',minute:'2-digit'})}.`);}catch(e){setError(e instanceof Error?e.message:'تعذر تسجيل الحضور. انتظر الرمز التالي ثم أعد المسح.');}},[token]);
 return <main dir="rtl" className="min-h-screen bg-slate-50 p-4 text-slate-900"><div className="mx-auto max-w-md space-y-5 py-5"><Link to="/portal/clinical-schedule" className="text-xs font-bold text-teal-700">← العودة للجدول السريري</Link><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-teal-50 text-teal-700"><ShieldCheck/></span><div><h1 className="font-black">تسجيل الحضور السريري</h1><p className="mt-1 text-xs text-slate-500">امسح رمز المشرف بالكاميرا فقط.</p></div></div>{!student?<div className="space-y-3">{!challenge?<><label className="block text-xs font-bold">الرقم الجامعي<input dir="ltr" value={number} onChange={e=>setNumber(e.target.value.replace(/\D/g,''))} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 px-3 text-right outline-none focus:border-teal-500" placeholder="مثال: 22130000"/></label><button disabled={loading||!number} onClick={request} className="h-11 w-full rounded-xl bg-teal-700 text-sm font-black text-white disabled:opacity-50">إرسال رمز التحقق</button></>:<><label className="block text-xs font-bold">رمز التحقق من البريد الجامعي<input dir="ltr" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 px-3 text-center tracking-[0.45em] outline-none focus:border-teal-500" inputMode="numeric"/></label><button disabled={loading||otp.length!==6} onClick={verify} className="h-11 w-full rounded-xl bg-teal-700 text-sm font-black text-white disabled:opacity-50">تحقق وافتح الماسح</button></>}</div>:<><div className="mb-4 rounded-2xl bg-teal-50 p-3 text-xs text-teal-900"><b>{student.name}</b><span dir="ltr" className="mr-2">{student.university_number}</span></div><LiveQrScanner onDecoded={decoded} onError={setError}/></>}{message&&<p className="mt-4 flex gap-2 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-800"><CheckCircle2 className="h-4 w-4 shrink-0"/>{message}</p>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}</section><p className="px-3 text-center text-[11px] leading-5 text-slate-500">لا تلتقط صورة للرمز ولا تشاركه. الرمز يتغير تلقائياً وتُعتمد ساعة النظام.</p></div></main>;
}
