import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ChevronDown, CircleHelp } from 'lucide-react';
import { useI18n } from '@/i18n/I18nContext';

export function QualitySectionGuide({titleAr,titleEn,stepsAr,stepsEn}:{titleAr:string;titleEn:string;stepsAr:string[];stepsEn:string[]}){
 const{locale}=useI18n();const ar=locale==='ar';const[open,setOpen]=useState(false);const steps=ar?stepsAr:stepsEn;
 return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex h-12 items-center justify-between gap-2 px-3 sm:h-auto sm:px-4 sm:py-3"><Link to="/quality" className="inline-flex h-8 items-center gap-1.5 rounded-lg px-2 text-xs font-black text-slate-500 hover:bg-slate-50 hover:text-teal-700 sm:h-9 sm:border sm:border-slate-200 sm:px-3"><ArrowRight className="h-4 w-4"/><span className="sm:hidden">{ar?'رجوع':'Back'}</span><span className="hidden sm:inline">{ar?'الرجوع لمركز الجودة':'Back to quality center'}</span></Link><button type="button" onClick={()=>setOpen(v=>!v)} className="inline-flex h-8 items-center gap-1.5 rounded-lg px-2 text-xs font-black text-teal-700 hover:bg-teal-50 sm:h-9 sm:bg-teal-50 sm:px-3"><CircleHelp className="h-4 w-4"/><span className="sm:hidden">{ar?'مساعدة':'Help'}</span><span className="hidden sm:inline">{ar?'كيف تعمل هذه الشاشة؟':'How does this screen work?'}</span><ChevronDown className={`h-3.5 w-3.5 transition ${open?'rotate-180':''}`}/></button></div>{open&&<div className="border-t bg-slate-50/70 p-3 sm:px-4 sm:py-4"><h2 className="text-xs font-black text-slate-800 sm:text-sm">{ar?titleAr:titleEn}</h2><ol className="mt-2 grid gap-1.5 sm:mt-3 sm:gap-2 md:grid-cols-2">{steps.map((step,index)=><li key={step} className="flex gap-2 rounded-lg bg-white p-2 text-[11px] leading-5 text-slate-600 ring-1 ring-slate-100 sm:rounded-xl sm:p-3 sm:text-xs"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-teal-100 text-[10px] font-black text-teal-700">{index+1}</span>{step}</li>)}</ol></div>}</section>;
}
